.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_80086DE0, 0x180

glabel func_80086DE0
    /* 3B3C0 80086DE0 27BDFFD0 */  addiu      $sp, $sp, -0x30
    /* 3B3C4 80086DE4 AFBF001C */  sw         $ra, 0x1C($sp)
    /* 3B3C8 80086DE8 15C00059 */  bnez       $t6, .L80086F50
    /* 3B3CC 80086DEC AFA40030 */   sw        $a0, 0x30($sp)
    /* 3B3D0 80086DF0 0C01F49E */  jal        func_8007D278
    /* 3B3D4 80086DF4 00000000 */   nop
    /* 3B3D8 80086DF8 3C048019 */  lui        $a0, %hi(D_8018AC98)
    /* 3B3DC 80086DFC 3C058019 */  lui        $a1, %hi(D_8018ACB0)
    /* 3B3E0 80086E00 24A5ACB0 */  addiu      $a1, $a1, %lo(D_8018ACB0)
    /* 3B3E4 80086E04 2484AC98 */  addiu      $a0, $a0, %lo(D_8018AC98)
    /* 3B3E8 80086E08 0C01EF36 */  jal        func_8007BCD8
    /* 3B3EC 80086E0C 24060005 */   addiu     $a2, $zero, 0x5
    /* 3B3F0 80086E10 3C018019 */  lui        $at, %hi(D_8018ACC8)
    /* 3B3F4 80086E14 240F000D */  addiu      $t7, $zero, 0xD
    /* 3B3F8 80086E18 A42FACC8 */  sh         $t7, %lo(D_8018ACC8)($at)
    /* 3B3FC 80086E1C A020ACCA */  sb         $zero, %lo(D_8018ACCA)($at)
    /* 3B400 80086E20 AC20ACCC */  sw         $zero, %lo(D_8018ACCC)($at)
    /* 3B404 80086E24 3C018019 */  lui        $at, %hi(D_8018ACE0)
    /* 3B408 80086E28 2418000E */  addiu      $t8, $zero, 0xE
    /* 3B40C 80086E2C 3C058019 */  lui        $a1, %hi(D_8018AC98)
    /* 3B410 80086E30 3C068019 */  lui        $a2, %hi(D_8018ACC8)
    /* 3B414 80086E34 A438ACE0 */  sh         $t8, %lo(D_8018ACE0)($at)
    /* 3B418 80086E38 A020ACE2 */  sb         $zero, %lo(D_8018ACE2)($at)
    /* 3B41C 80086E3C AC20ACE4 */  sw         $zero, %lo(D_8018ACE4)($at)
    /* 3B420 80086E40 24C6ACC8 */  addiu      $a2, $a2, %lo(D_8018ACC8)
    /* 3B424 80086E44 24A5AC98 */  addiu      $a1, $a1, %lo(D_8018AC98)
    /* 3B428 80086E48 0C01F3E6 */  jal        func_8007CF98
    /* 3B42C 80086E4C 24040007 */   addiu     $a0, $zero, 0x7
    /* 3B430 80086E50 3C058019 */  lui        $a1, %hi(D_8018AC98)
    /* 3B434 80086E54 3C068019 */  lui        $a2, %hi(D_8018ACE0)
    /* 3B438 80086E58 24C6ACE0 */  addiu      $a2, $a2, %lo(D_8018ACE0)
    /* 3B43C 80086E5C 24A5AC98 */  addiu      $a1, $a1, %lo(D_8018AC98)
    /* 3B440 80086E60 0C01F3E6 */  jal        func_8007CF98
    /* 3B444 80086E64 24040003 */   addiu     $a0, $zero, 0x3
    /* 3B448 80086E68 2419FFFF */  addiu      $t9, $zero, -0x1
    /* 3B44C 80086E6C AFB90028 */  sw         $t9, 0x28($sp)
    /* 3B450 80086E70 0C021C4E */  jal        func_80087138
    /* 3B454 80086E74 00002025 */   or        $a0, $zero, $zero
    /* 3B458 80086E78 AFA20024 */  sw         $v0, 0x24($sp)
    /* 3B45C 80086E7C 8FA80024 */  lw         $t0, 0x24($sp)
    /* 3B460 80086E80 8FA90030 */  lw         $t1, 0x30($sp)
    /* 3B464 80086E84 0109082A */  slt        $at, $t0, $t1
    /* 3B468 80086E88 10200005 */  beqz       $at, .L80086EA0
    /* 3B46C 80086E8C 00000000 */   nop
    /* 3B470 80086E90 AFA80028 */  sw         $t0, 0x28($sp)
    /* 3B474 80086E94 00002025 */  or         $a0, $zero, $zero
    /* 3B478 80086E98 0C01F402 */  jal        func_8007D008
    /* 3B47C 80086E9C 01202825 */   or        $a1, $t1, $zero
  .L80086EA0:
    /* 3B480 80086EA0 0C01F1DA */  jal        func_8007C768
    /* 3B484 80086EA4 00000000 */   nop
    /* 3B488 80086EA8 3C018009 */  lui        $at, %hi(D_800955C0)
    /* 3B48C 80086EAC 3C0C8019 */  lui        $t4, %hi(D_8018AC98)
    /* 3B490 80086EB0 3C0B8019 */  lui        $t3, %hi(D_80189AE8)
    /* 3B494 80086EB4 258CAC98 */  addiu      $t4, $t4, %lo(D_8018AC98)
    /* 3B498 80086EB8 240A0001 */  addiu      $t2, $zero, 0x1
    /* 3B49C 80086EBC 256B9AE8 */  addiu      $t3, $t3, %lo(D_80189AE8)
    /* 3B4A0 80086EC0 AC2A55C0 */  sw         $t2, %lo(D_800955C0)($at)
    /* 3B4A4 80086EC4 AC2B55C4 */  sw         $t3, %lo(D_800955C4)($at)
    /* 3B4A8 80086EC8 AC2C55C8 */  sw         $t4, %lo(D_800955C8)($at)
    /* 3B4AC 80086ECC AC2C55CC */  sw         $t4, %lo(D_800955CC)($at)
    /* 3B4B0 80086ED0 3C0D8019 */  lui        $t5, %hi(D_80189C98)
    /* 3B4B4 80086ED4 8FAF0030 */  lw         $t7, 0x30($sp)
    /* 3B4B8 80086ED8 3C018009 */  lui        $at, %hi(D_800955D0)
    /* 3B4BC 80086EDC 25AD9C98 */  addiu      $t5, $t5, %lo(D_80189C98)
    /* 3B4C0 80086EE0 25AE1000 */  addiu      $t6, $t5, 0x1000
    /* 3B4C4 80086EE4 3C068008 */  lui        $a2, %hi(func_80086F60)
    /* 3B4C8 80086EE8 3C078009 */  lui        $a3, %hi(D_800955C0)
    /* 3B4CC 80086EEC AFA2002C */  sw         $v0, 0x2C($sp)
    /* 3B4D0 80086EF0 AC2055D0 */  sw         $zero, %lo(D_800955D0)($at)
    /* 3B4D4 80086EF4 AC2055D4 */  sw         $zero, %lo(D_800955D4)($at)
    /* 3B4D8 80086EF8 AC2055D8 */  sw         $zero, %lo(D_800955D8)($at)
    /* 3B4DC 80086EFC 24E755C0 */  addiu      $a3, $a3, %lo(D_800955C0)
    /* 3B4E0 80086F00 24C66F60 */  addiu      $a2, $a2, %lo(func_80086F60)
    /* 3B4E4 80086F04 AFAE0010 */  sw         $t6, 0x10($sp)
    /* 3B4E8 80086F08 01602025 */  or         $a0, $t3, $zero
    /* 3B4EC 80086F0C 00002825 */  or         $a1, $zero, $zero
    /* 3B4F0 80086F10 0C01EF42 */  jal        func_8007BD08
    /* 3B4F4 80086F14 AFAF0014 */   sw        $t7, 0x14($sp)
    /* 3B4F8 80086F18 0C021C56 */  jal        func_80087158
    /* 3B4FC 80086F1C 00000000 */   nop
    /* 3B500 80086F20 3C048019 */  lui        $a0, %hi(D_80189AE8)
    /* 3B504 80086F24 0C01F43A */  jal        func_8007D0E8
    /* 3B508 80086F28 24849AE8 */   addiu     $a0, $a0, %lo(D_80189AE8)
    /* 3B50C 80086F2C 0C01F1E2 */  jal        func_8007C788
    /* 3B510 80086F30 8FA4002C */   lw        $a0, 0x2C($sp)
    /* 3B514 80086F34 8FB80028 */  lw         $t8, 0x28($sp)
    /* 3B518 80086F38 2401FFFF */  addiu      $at, $zero, -0x1
    /* 3B51C 80086F3C 13010004 */  beq        $t8, $at, .L80086F50
    /* 3B520 80086F40 00000000 */   nop
    /* 3B524 80086F44 00002025 */  or         $a0, $zero, $zero
    /* 3B528 80086F48 0C01F402 */  jal        func_8007D008
    /* 3B52C 80086F4C 03002825 */   or        $a1, $t8, $zero
  .L80086F50:
    /* 3B530 80086F50 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 3B534 80086F54 27BD0030 */  addiu      $sp, $sp, 0x30
    /* 3B538 80086F58 03E00008 */  jr         $ra
    /* 3B53C 80086F5C 00000000 */   nop
endlabel func_80086DE0
