.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_8007CD08, 0x138

glabel func_8007CD08
    /* 312E8 8007CD08 27BDFFD8 */  addiu      $sp, $sp, -0x28
    /* 312EC 8007CD0C AFBF001C */  sw         $ra, 0x1C($sp)
    /* 312F0 8007CD10 AFA40028 */  sw         $a0, 0x28($sp)
    /* 312F4 8007CD14 AFA5002C */  sw         $a1, 0x2C($sp)
    /* 312F8 8007CD18 AFA60030 */  sw         $a2, 0x30($sp)
    /* 312FC 8007CD1C AFB10018 */  sw         $s1, 0x18($sp)
    /* 31300 8007CD20 0C01F1DA */  jal        func_8007C768
    /* 31304 8007CD24 AFB00014 */   sw        $s0, 0x14($sp)
    /* 31308 8007CD28 8FAE0028 */  lw         $t6, 0x28($sp)
    /* 3130C 8007CD2C 00408025 */  or         $s0, $v0, $zero
    /* 31310 8007CD30 8DCF0008 */  lw         $t7, 0x8($t6)
    /* 31314 8007CD34 15E00012 */  bnez       $t7, .L8007CD80
    /* 31318 8007CD38 00000000 */   nop
  .L8007CD3C:
    /* 3131C 8007CD3C 8FB80030 */  lw         $t8, 0x30($sp)
    /* 31320 8007CD40 17000005 */  bnez       $t8, .L8007CD58
    /* 31324 8007CD44 00000000 */   nop
    /* 31328 8007CD48 0C01F1E2 */  jal        func_8007C788
    /* 3132C 8007CD4C 02002025 */   or        $a0, $s0, $zero
    /* 31330 8007CD50 10000036 */  b          .L8007CE2C
    /* 31334 8007CD54 2402FFFF */   addiu     $v0, $zero, -0x1
  .L8007CD58:
    /* 31338 8007CD58 3C088009 */  lui        $t0, %hi(D_800952B0)
    /* 3133C 8007CD5C 8D0852B0 */  lw         $t0, %lo(D_800952B0)($t0)
    /* 31340 8007CD60 24190008 */  addiu      $t9, $zero, 0x8
    /* 31344 8007CD64 A5190010 */  sh         $t9, 0x10($t0)
    /* 31348 8007CD68 0C01F121 */  jal        func_8007C484
    /* 3134C 8007CD6C 8FA40028 */   lw        $a0, 0x28($sp)
    /* 31350 8007CD70 8FA90028 */  lw         $t1, 0x28($sp)
    /* 31354 8007CD74 8D2A0008 */  lw         $t2, 0x8($t1)
    /* 31358 8007CD78 1140FFF0 */  beqz       $t2, .L8007CD3C
    /* 3135C 8007CD7C 00000000 */   nop
  .L8007CD80:
    /* 31360 8007CD80 8FAB002C */  lw         $t3, 0x2C($sp)
    /* 31364 8007CD84 11600008 */  beqz       $t3, .L8007CDA8
    /* 31368 8007CD88 00000000 */   nop
    /* 3136C 8007CD8C 8FAC0028 */  lw         $t4, 0x28($sp)
    /* 31370 8007CD90 8D8E000C */  lw         $t6, 0xC($t4)
    /* 31374 8007CD94 8D8D0014 */  lw         $t5, 0x14($t4)
    /* 31378 8007CD98 000E7880 */  sll        $t7, $t6, 2
    /* 3137C 8007CD9C 01AFC021 */  addu       $t8, $t5, $t7
    /* 31380 8007CDA0 8F190000 */  lw         $t9, 0x0($t8)
    /* 31384 8007CDA4 AD790000 */  sw         $t9, 0x0($t3)
  .L8007CDA8:
    /* 31388 8007CDA8 8FA80028 */  lw         $t0, 0x28($sp)
    /* 3138C 8007CDAC 8D09000C */  lw         $t1, 0xC($t0)
    /* 31390 8007CDB0 8D0C0010 */  lw         $t4, 0x10($t0)
    /* 31394 8007CDB4 252A0001 */  addiu      $t2, $t1, 0x1
    /* 31398 8007CDB8 014C001A */  div        $zero, $t2, $t4
    /* 3139C 8007CDBC 00007010 */  mfhi       $t6
    /* 313A0 8007CDC0 AD0E000C */  sw         $t6, 0xC($t0)
    /* 313A4 8007CDC4 8FAD0028 */  lw         $t5, 0x28($sp)
    /* 313A8 8007CDC8 15800002 */  bnez       $t4, .L8007CDD4
    /* 313AC 8007CDCC 00000000 */   nop
    /* 313B0 8007CDD0 0007000D */  break      7
  .L8007CDD4:
    /* 313B4 8007CDD4 2401FFFF */  addiu      $at, $zero, -0x1
    /* 313B8 8007CDD8 15810004 */  bne        $t4, $at, .L8007CDEC
    /* 313BC 8007CDDC 3C018000 */   lui       $at, (0x80000000 >> 16)
    /* 313C0 8007CDE0 15410002 */  bne        $t2, $at, .L8007CDEC
    /* 313C4 8007CDE4 00000000 */   nop
    /* 313C8 8007CDE8 0006000D */  break      6
  .L8007CDEC:
    /* 313CC 8007CDEC 8DAF0008 */  lw         $t7, 0x8($t5)
    /* 313D0 8007CDF0 25F8FFFF */  addiu      $t8, $t7, -0x1
    /* 313D4 8007CDF4 ADB80008 */  sw         $t8, 0x8($t5)
    /* 313D8 8007CDF8 8FB90028 */  lw         $t9, 0x28($sp)
    /* 313DC 8007CDFC 8F2B0004 */  lw         $t3, 0x4($t9)
    /* 313E0 8007CE00 8D690000 */  lw         $t1, 0x0($t3)
    /* 313E4 8007CE04 11200006 */  beqz       $t1, .L8007CE20
    /* 313E8 8007CE08 00000000 */   nop
    /* 313EC 8007CE0C 0C01F173 */  jal        func_8007C5CC
    /* 313F0 8007CE10 27240004 */   addiu     $a0, $t9, 0x4
    /* 313F4 8007CE14 00408825 */  or         $s1, $v0, $zero
    /* 313F8 8007CE18 0C01F43A */  jal        func_8007D0E8
    /* 313FC 8007CE1C 02202025 */   or        $a0, $s1, $zero
  .L8007CE20:
    /* 31400 8007CE20 0C01F1E2 */  jal        func_8007C788
    /* 31404 8007CE24 02002025 */   or        $a0, $s0, $zero
    /* 31408 8007CE28 00001025 */  or         $v0, $zero, $zero
  .L8007CE2C:
    /* 3140C 8007CE2C 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 31410 8007CE30 8FB00014 */  lw         $s0, 0x14($sp)
    /* 31414 8007CE34 8FB10018 */  lw         $s1, 0x18($sp)
    /* 31418 8007CE38 03E00008 */  jr         $ra
    /* 3141C 8007CE3C 27BD0028 */   addiu     $sp, $sp, 0x28
endlabel func_8007CD08
    /* 31420 8007CE40 00000000 */  nop
    /* 31424 8007CE44 00000000 */  nop
