.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_8005AC70, 0x244

glabel func_8005AC70
    /* F250 8005AC70 27BDEF98 */  addiu      $sp, $sp, -0x1068
    /* F254 8005AC74 00801021 */  addu       $v0, $a0, $zero
    /* F258 8005AC78 AFB21048 */  sw         $s2, 0x1048($sp)
    /* F25C 8005AC7C 00A09021 */  addu       $s2, $a1, $zero
    /* F260 8005AC80 AFB7105C */  sw         $s7, 0x105C($sp)
    /* F264 8005AC84 00C0B821 */  addu       $s7, $a2, $zero
    /* F268 8005AC88 27A41028 */  addiu      $a0, $sp, 0x1028
    /* F26C 8005AC8C 00402821 */  addu       $a1, $v0, $zero
    /* F270 8005AC90 00E03021 */  addu       $a2, $a3, $zero
    /* F274 8005AC94 AFBF1060 */  sw         $ra, 0x1060($sp)
    /* F278 8005AC98 AFB61058 */  sw         $s6, 0x1058($sp)
    /* F27C 8005AC9C AFB51054 */  sw         $s5, 0x1054($sp)
    /* F280 8005ACA0 AFB41050 */  sw         $s4, 0x1050($sp)
    /* F284 8005ACA4 AFB3104C */  sw         $s3, 0x104C($sp)
    /* F288 8005ACA8 AFB11044 */  sw         $s1, 0x1044($sp)
    /* F28C 8005ACAC 0C016A99 */  jal        func_8005AA64
    /* F290 8005ACB0 AFB01040 */   sw        $s0, 0x1040($sp)
    /* F294 8005ACB4 24030FED */  addiu      $v1, $zero, 0xFED
    /* F298 8005ACB8 27A20FFD */  addiu      $v0, $sp, 0xFFD
  .L8005ACBC:
    /* F29C 8005ACBC A0400000 */  sb         $zero, 0x0($v0)
    /* F2A0 8005ACC0 2463FFFF */  addiu      $v1, $v1, -0x1
    /* F2A4 8005ACC4 0461FFFD */  bgez       $v1, .L8005ACBC
    /* F2A8 8005ACC8 2442FFFF */   addiu     $v0, $v0, -0x1
    /* F2AC 8005ACCC 0000A021 */  addu       $s4, $zero, $zero
    /* F2B0 8005ACD0 24100FEE */  addiu      $s0, $zero, 0xFEE
    /* F2B4 8005ACD4 1AE0006A */  blez       $s7, .L8005AE80
    /* F2B8 8005ACD8 02809821 */   addu      $s3, $s4, $zero
    /* F2BC 8005ACDC 3C028019 */  lui        $v0, %hi(D_80190000)
    /* F2C0 8005ACE0 24560000 */  addiu      $s6, $v0, %lo(D_80190000)
    /* F2C4 8005ACE4 27B50010 */  addiu      $s5, $sp, 0x10
    /* F2C8 8005ACE8 0014A043 */  sra        $s4, $s4, 1
  .L8005ACEC:
    /* F2CC 8005ACEC 32820100 */  andi       $v0, $s4, 0x100
    /* F2D0 8005ACF0 14400012 */  bnez       $v0, .L8005AD3C
    /* F2D4 8005ACF4 32820001 */   andi      $v0, $s4, 0x1
    /* F2D8 8005ACF8 8FA21034 */  lw         $v0, 0x1034($sp)
    /* F2DC 8005ACFC 8FA31038 */  lw         $v1, 0x1038($sp)
    /* F2E0 8005AD00 0043102B */  sltu       $v0, $v0, $v1
    /* F2E4 8005AD04 14400003 */  bnez       $v0, .L8005AD14
    /* F2E8 8005AD08 00000000 */   nop
    /* F2EC 8005AD0C 0C016AA6 */  jal        func_8005AA98
    /* F2F0 8005AD10 27A41028 */   addiu     $a0, $sp, 0x1028
  .L8005AD14:
    /* F2F4 8005AD14 8FA21030 */  lw         $v0, 0x1030($sp)
    /* F2F8 8005AD18 8FA31034 */  lw         $v1, 0x1034($sp)
    /* F2FC 8005AD1C 00021280 */  sll        $v0, $v0, 10
    /* F300 8005AD20 00621021 */  addu       $v0, $v1, $v0
    /* F304 8005AD24 00561021 */  addu       $v0, $v0, $s6
    /* F308 8005AD28 90420000 */  lbu        $v0, 0x0($v0)
    /* F30C 8005AD2C 24630001 */  addiu      $v1, $v1, 0x1
    /* F310 8005AD30 AFA31034 */  sw         $v1, 0x1034($sp)
    /* F314 8005AD34 3454FF00 */  ori        $s4, $v0, 0xFF00
    /* F318 8005AD38 32820001 */  andi       $v0, $s4, 0x1
  .L8005AD3C:
    /* F31C 8005AD3C 10400019 */  beqz       $v0, .L8005ADA4
    /* F320 8005AD40 00000000 */   nop
    /* F324 8005AD44 8FA21034 */  lw         $v0, 0x1034($sp)
    /* F328 8005AD48 8FA31038 */  lw         $v1, 0x1038($sp)
    /* F32C 8005AD4C 0043102B */  sltu       $v0, $v0, $v1
    /* F330 8005AD50 14400004 */  bnez       $v0, .L8005AD64
    /* F334 8005AD54 02B02021 */   addu      $a0, $s5, $s0
    /* F338 8005AD58 0C016AA6 */  jal        func_8005AA98
    /* F33C 8005AD5C 27A41028 */   addiu     $a0, $sp, 0x1028
    /* F340 8005AD60 02B02021 */  addu       $a0, $s5, $s0
  .L8005AD64:
    /* F344 8005AD64 26100001 */  addiu      $s0, $s0, 0x1
    /* F348 8005AD68 32100FFF */  andi       $s0, $s0, 0xFFF
    /* F34C 8005AD6C 26730001 */  addiu      $s3, $s3, 0x1
    /* F350 8005AD70 8FA21030 */  lw         $v0, 0x1030($sp)
    /* F354 8005AD74 8FA31034 */  lw         $v1, 0x1034($sp)
    /* F358 8005AD78 00021280 */  sll        $v0, $v0, 10
    /* F35C 8005AD7C 00621021 */  addu       $v0, $v1, $v0
    /* F360 8005AD80 00561021 */  addu       $v0, $v0, $s6
    /* F364 8005AD84 90420000 */  lbu        $v0, 0x0($v0)
    /* F368 8005AD88 24630001 */  addiu      $v1, $v1, 0x1
    /* F36C 8005AD8C AFA31034 */  sw         $v1, 0x1034($sp)
    /* F370 8005AD90 00401821 */  addu       $v1, $v0, $zero
    /* F374 8005AD94 A0830000 */  sb         $v1, 0x0($a0)
    /* F378 8005AD98 A2430000 */  sb         $v1, 0x0($s2)
    /* F37C 8005AD9C 08016B9D */  j          func_8005AE74
    /* F380 8005ADA0 26520001 */   addiu     $s2, $s2, 0x1
  .L8005ADA4:
    /* F384 8005ADA4 8FA21034 */  lw         $v0, 0x1034($sp)
    /* F388 8005ADA8 8FA31038 */  lw         $v1, 0x1038($sp)
    /* F38C 8005ADAC 0043102B */  sltu       $v0, $v0, $v1
    /* F390 8005ADB0 14400003 */  bnez       $v0, .L8005ADC0
    /* F394 8005ADB4 00000000 */   nop
    /* F398 8005ADB8 0C016AA6 */  jal        func_8005AA98
    /* F39C 8005ADBC 27A41028 */   addiu     $a0, $sp, 0x1028
  .L8005ADC0:
    /* F3A0 8005ADC0 8FA21030 */  lw         $v0, 0x1030($sp)
    /* F3A4 8005ADC4 8FA31034 */  lw         $v1, 0x1034($sp)
    /* F3A8 8005ADC8 00021280 */  sll        $v0, $v0, 10
    /* F3AC 8005ADCC 00621021 */  addu       $v0, $v1, $v0
    /* F3B0 8005ADD0 00561021 */  addu       $v0, $v0, $s6
    /* F3B4 8005ADD4 90440000 */  lbu        $a0, 0x0($v0)
    /* F3B8 8005ADD8 8FA21038 */  lw         $v0, 0x1038($sp)
    /* F3BC 8005ADDC 24630001 */  addiu      $v1, $v1, 0x1
    /* F3C0 8005ADE0 AFA31034 */  sw         $v1, 0x1034($sp)
    /* F3C4 8005ADE4 0062182B */  sltu       $v1, $v1, $v0
    /* F3C8 8005ADE8 14600003 */  bnez       $v1, .L8005ADF8
    /* F3CC 8005ADEC 00808821 */   addu      $s1, $a0, $zero
    /* F3D0 8005ADF0 0C016AA6 */  jal        func_8005AA98
    /* F3D4 8005ADF4 27A41028 */   addiu     $a0, $sp, 0x1028
  .L8005ADF8:
    /* F3D8 8005ADF8 00002821 */  addu       $a1, $zero, $zero
    /* F3DC 8005ADFC 8FA21030 */  lw         $v0, 0x1030($sp)
    /* F3E0 8005AE00 8FA31034 */  lw         $v1, 0x1034($sp)
    /* F3E4 8005AE04 00021280 */  sll        $v0, $v0, 10
    /* F3E8 8005AE08 00621021 */  addu       $v0, $v1, $v0
    /* F3EC 8005AE0C 00561021 */  addu       $v0, $v0, $s6
    /* F3F0 8005AE10 90420000 */  lbu        $v0, 0x0($v0)
    /* F3F4 8005AE14 24630001 */  addiu      $v1, $v1, 0x1
    /* F3F8 8005AE18 00402021 */  addu       $a0, $v0, $zero
    /* F3FC 8005AE1C 308200F0 */  andi       $v0, $a0, 0xF0
    /* F400 8005AE20 00021100 */  sll        $v0, $v0, 4
    /* F404 8005AE24 02228825 */  or         $s1, $s1, $v0
    /* F408 8005AE28 3082000F */  andi       $v0, $a0, 0xF
    /* F40C 8005AE2C 24440002 */  addiu      $a0, $v0, 0x2
    /* F410 8005AE30 0085102A */  slt        $v0, $a0, $a1
    /* F414 8005AE34 1440000F */  bnez       $v0, func_8005AE74
    /* F418 8005AE38 AFA31034 */   sw        $v1, 0x1034($sp)
  .L8005AE3C:
    /* F41C 8005AE3C 02B01021 */  addu       $v0, $s5, $s0
    /* F420 8005AE40 26100001 */  addiu      $s0, $s0, 0x1
    /* F424 8005AE44 32100FFF */  andi       $s0, $s0, 0xFFF
    /* F428 8005AE48 26730001 */  addiu      $s3, $s3, 0x1
    /* F42C 8005AE4C 02251821 */  addu       $v1, $s1, $a1
    /* F430 8005AE50 30630FFF */  andi       $v1, $v1, 0xFFF
    /* F434 8005AE54 02A31821 */  addu       $v1, $s5, $v1
    /* F438 8005AE58 90630000 */  lbu        $v1, 0x0($v1)
    /* F43C 8005AE5C 24A50001 */  addiu      $a1, $a1, 0x1
    /* F440 8005AE60 A0430000 */  sb         $v1, 0x0($v0)
    /* F444 8005AE64 A2430000 */  sb         $v1, 0x0($s2)
    /* F448 8005AE68 0085102A */  slt        $v0, $a0, $a1
    /* F44C 8005AE6C 1040FFF3 */  beqz       $v0, .L8005AE3C
    /* F450 8005AE70 26520001 */   addiu     $s2, $s2, 0x1
  alabel func_8005AE74
    /* F454 8005AE74 0277102A */  slt        $v0, $s3, $s7
    /* F458 8005AE78 1440FF9C */  bnez       $v0, .L8005ACEC
    /* F45C 8005AE7C 0014A043 */   sra       $s4, $s4, 1
  .L8005AE80:
    /* F460 8005AE80 0C016ACA */  jal        func_8005AB28
    /* F464 8005AE84 00000000 */   nop
    /* F468 8005AE88 8FBF1060 */  lw         $ra, 0x1060($sp)
    /* F46C 8005AE8C 8FB7105C */  lw         $s7, 0x105C($sp)
    /* F470 8005AE90 8FB61058 */  lw         $s6, 0x1058($sp)
    /* F474 8005AE94 8FB51054 */  lw         $s5, 0x1054($sp)
    /* F478 8005AE98 8FB41050 */  lw         $s4, 0x1050($sp)
    /* F47C 8005AE9C 8FB3104C */  lw         $s3, 0x104C($sp)
    /* F480 8005AEA0 8FB21048 */  lw         $s2, 0x1048($sp)
    /* F484 8005AEA4 8FB11044 */  lw         $s1, 0x1044($sp)
    /* F488 8005AEA8 8FB01040 */  lw         $s0, 0x1040($sp)
    /* F48C 8005AEAC 03E00008 */  jr         $ra
    /* F490 8005AEB0 27BD1068 */   addiu     $sp, $sp, 0x1068
endlabel func_8005AC70

nonmatching func_8005AEB4, 0x110

glabel func_8005AEB4
    /* F494 8005AEB4 00004021 */  addu       $t0, $zero, $zero
    /* F498 8005AEB8 3C028018 */  lui        $v0, %hi(D_8017CE08)
    /* F49C 8005AEBC 2449CE08 */  addiu      $t1, $v0, %lo(D_8017CE08)
    /* F4A0 8005AEC0 24070001 */  addiu      $a3, $zero, 0x1
    /* F4A4 8005AEC4 3C028018 */  lui        $v0, %hi(D_8017DA58)
    /* F4A8 8005AEC8 2446DA58 */  addiu      $a2, $v0, %lo(D_8017DA58)
    /* F4AC 8005AECC 3C028018 */  lui        $v0, %hi(D_8017D2F8)
    /* F4B0 8005AED0 2445D2F8 */  addiu      $a1, $v0, %lo(D_8017D2F8)
    /* F4B4 8005AED4 00081400 */  sll        $v0, $t0, 16
  .L8005AED8:
    /* F4B8 8005AED8 00021403 */  sra        $v0, $v0, 16
    /* F4BC 8005AEDC 00022040 */  sll        $a0, $v0, 1
    /* F4C0 8005AEE0 00891821 */  addu       $v1, $a0, $t1
    /* F4C4 8005AEE4 00862021 */  addu       $a0, $a0, $a2
    /* F4C8 8005AEE8 A4670000 */  sh         $a3, 0x0($v1)
    /* F4CC 8005AEEC 25030273 */  addiu      $v1, $t0, 0x273
    /* F4D0 8005AEF0 24420273 */  addiu      $v0, $v0, 0x273
    /* F4D4 8005AEF4 00021040 */  sll        $v0, $v0, 1
    /* F4D8 8005AEF8 00451021 */  addu       $v0, $v0, $a1
    /* F4DC 8005AEFC A4830000 */  sh         $v1, 0x0($a0)
    /* F4E0 8005AF00 A4480000 */  sh         $t0, 0x0($v0)
    /* F4E4 8005AF04 25020001 */  addiu      $v0, $t0, 0x1
    /* F4E8 8005AF08 00404021 */  addu       $t0, $v0, $zero
    /* F4EC 8005AF0C 00021400 */  sll        $v0, $v0, 16
    /* F4F0 8005AF10 00021403 */  sra        $v0, $v0, 16
    /* F4F4 8005AF14 2842013A */  slti       $v0, $v0, 0x13A
    /* F4F8 8005AF18 1440FFEF */  bnez       $v0, .L8005AED8
    /* F4FC 8005AF1C 00081400 */   sll       $v0, $t0, 16
    /* F500 8005AF20 00004021 */  addu       $t0, $zero, $zero
    /* F504 8005AF24 2409013A */  addiu      $t1, $zero, 0x13A
    /* F508 8005AF28 3C028018 */  lui        $v0, %hi(D_8017CE08)
    /* F50C 8005AF2C 244ACE08 */  addiu      $t2, $v0, %lo(D_8017CE08)
    /* F510 8005AF30 3C028018 */  lui        $v0, %hi(D_8017DA58)
    /* F514 8005AF34 244CDA58 */  addiu      $t4, $v0, %lo(D_8017DA58)
    /* F518 8005AF38 3C028018 */  lui        $v0, %hi(D_8017D2F8)
    /* F51C 8005AF3C 244BD2F8 */  addiu      $t3, $v0, %lo(D_8017D2F8)
  .L8005AF40:
    /* F520 8005AF40 00093400 */  sll        $a2, $t1, 16
    /* F524 8005AF44 000633C3 */  sra        $a2, $a2, 15
    /* F528 8005AF48 00081400 */  sll        $v0, $t0, 16
    /* F52C 8005AF4C 00021403 */  sra        $v0, $v0, 16
    /* F530 8005AF50 00023840 */  sll        $a3, $v0, 1
    /* F534 8005AF54 00EA1821 */  addu       $v1, $a3, $t2
    /* F538 8005AF58 24420001 */  addiu      $v0, $v0, 0x1
    /* F53C 8005AF5C 00021040 */  sll        $v0, $v0, 1
    /* F540 8005AF60 004A2021 */  addu       $a0, $v0, $t2
    /* F544 8005AF64 00CA2821 */  addu       $a1, $a2, $t2
    /* F548 8005AF68 00CC3021 */  addu       $a2, $a2, $t4
    /* F54C 8005AF6C 004B1021 */  addu       $v0, $v0, $t3
    /* F550 8005AF70 94630000 */  lhu        $v1, 0x0($v1)
    /* F554 8005AF74 94840000 */  lhu        $a0, 0x0($a0)
    /* F558 8005AF78 00EB3821 */  addu       $a3, $a3, $t3
    /* F55C 8005AF7C 00641821 */  addu       $v1, $v1, $a0
    /* F560 8005AF80 A4A30000 */  sh         $v1, 0x0($a1)
    /* F564 8005AF84 A4C80000 */  sh         $t0, 0x0($a2)
    /* F568 8005AF88 A4490000 */  sh         $t1, 0x0($v0)
    /* F56C 8005AF8C 25220001 */  addiu      $v0, $t1, 0x1
    /* F570 8005AF90 A4E90000 */  sh         $t1, 0x0($a3)
    /* F574 8005AF94 00404821 */  addu       $t1, $v0, $zero
    /* F578 8005AF98 00021400 */  sll        $v0, $v0, 16
    /* F57C 8005AF9C 00021403 */  sra        $v0, $v0, 16
    /* F580 8005AFA0 28420273 */  slti       $v0, $v0, 0x273
    /* F584 8005AFA4 1440FFE6 */  bnez       $v0, .L8005AF40
    /* F588 8005AFA8 25080002 */   addiu     $t0, $t0, 0x2
    /* F58C 8005AFAC 3C028018 */  lui        $v0, %hi(D_8017D2EE)
    /* F590 8005AFB0 3403FFFF */  ori        $v1, $zero, 0xFFFF
    /* F594 8005AFB4 A443D2EE */  sh         $v1, %lo(D_8017D2EE)($v0)
    /* F598 8005AFB8 3C028018 */  lui        $v0, %hi(D_8017D7DC)
    /* F59C 8005AFBC 03E00008 */  jr         $ra
    /* F5A0 8005AFC0 A440D7DC */   sh        $zero, %lo(D_8017D7DC)($v0)
endlabel func_8005AEB4
