.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_80090C38, 0xBC

glabel func_80090C38
    /* 45218 80090C38 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* 4521C 80090C3C AFB10014 */  sw         $s1, 0x14($sp)
    /* 45220 80090C40 00808821 */  addu       $s1, $a0, $zero
    /* 45224 80090C44 AFBF001C */  sw         $ra, 0x1C($sp)
    /* 45228 80090C48 AFB20018 */  sw         $s2, 0x18($sp)
    /* 4522C 80090C4C AFB00010 */  sw         $s0, 0x10($sp)
    /* 45230 80090C50 8E300014 */  lw         $s0, 0x14($s1)
    /* 45234 80090C54 16000004 */  bnez       $s0, .L80090C68
    /* 45238 80090C58 00009021 */   addu      $s2, $zero, $zero
    /* 4523C 80090C5C 8E300004 */  lw         $s0, 0x4($s1)
    /* 45240 80090C60 12000009 */  beqz       $s0, .L80090C88
    /* 45244 80090C64 00000000 */   nop
  .L80090C68:
    /* 45248 80090C68 ACB00000 */  sw         $s0, 0x0($a1)
    /* 4524C 80090C6C 0C01F686 */  jal        func_8007DA18
    /* 45250 80090C70 02002021 */   addu      $a0, $s0, $zero
    /* 45254 80090C74 02002021 */  addu       $a0, $s0, $zero
    /* 45258 80090C78 0C01F692 */  jal        func_8007DA48
    /* 4525C 80090C7C 2625000C */   addiu     $a1, $s1, 0xC
    /* 45260 80090C80 08024336 */  j          func_80090CD8
    /* 45264 80090C84 02401021 */   addu      $v0, $s2, $zero
  .L80090C88:
    /* 45268 80090C88 8E30000C */  lw         $s0, 0xC($s1)
    /* 4526C 80090C8C 12000012 */  beqz       $s0, func_80090CD8
    /* 45270 80090C90 02401021 */   addu      $v0, $s2, $zero
  .L80090C94:
    /* 45274 80090C94 8E020008 */  lw         $v0, 0x8($s0)
    /* 45278 80090C98 84430016 */  lh         $v1, 0x16($v0)
    /* 4527C 80090C9C 00061400 */  sll        $v0, $a2, 16
    /* 45280 80090CA0 00021403 */  sra        $v0, $v0, 16
    /* 45284 80090CA4 0043102A */  slt        $v0, $v0, $v1
    /* 45288 80090CA8 14400008 */  bnez       $v0, .L80090CCC
    /* 4528C 80090CAC 00000000 */   nop
    /* 45290 80090CB0 8E0200D8 */  lw         $v0, 0xD8($s0)
    /* 45294 80090CB4 14400005 */  bnez       $v0, .L80090CCC
    /* 45298 80090CB8 00000000 */   nop
    /* 4529C 80090CBC ACB00000 */  sw         $s0, 0x0($a1)
    /* 452A0 80090CC0 8E020008 */  lw         $v0, 0x8($s0)
    /* 452A4 80090CC4 24120001 */  addiu      $s2, $zero, 0x1
    /* 452A8 80090CC8 94460016 */  lhu        $a2, 0x16($v0)
  .L80090CCC:
    /* 452AC 80090CCC 8E100000 */  lw         $s0, 0x0($s0)
    /* 452B0 80090CD0 1600FFF0 */  bnez       $s0, .L80090C94
    /* 452B4 80090CD4 02401021 */   addu      $v0, $s2, $zero
  alabel func_80090CD8
    /* 452B8 80090CD8 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 452BC 80090CDC 8FB20018 */  lw         $s2, 0x18($sp)
    /* 452C0 80090CE0 8FB10014 */  lw         $s1, 0x14($sp)
    /* 452C4 80090CE4 8FB00010 */  lw         $s0, 0x10($sp)
    /* 452C8 80090CE8 27BD0020 */  addiu      $sp, $sp, 0x20
    /* 452CC 80090CEC 03E00008 */  jr         $ra
    /* 452D0 80090CF0 00000000 */   nop
endlabel func_80090C38

nonmatching func_80090CF4, 0x4

glabel func_80090CF4
    /* 452D4 80090CF4 1080867F */  beqz       $a0, lbl_800726F4
endlabel func_80090CF4
