.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_8008CF18, 0x188

glabel func_8008CF18
    /* 414F8 8008CF18 27BDFFD0 */  addiu      $sp, $sp, -0x30
    /* 414FC 8008CF1C 3C0E8009 */  lui        $t6, %hi(D_80096480)
    /* 41500 8008CF20 8DCE6480 */  lw         $t6, %lo(D_80096480)($t6)
    /* 41504 8008CF24 AFBF001C */  sw         $ra, 0x1C($sp)
    /* 41508 8008CF28 AFA40030 */  sw         $a0, 0x30($sp)
    /* 4150C 8008CF2C AFA50034 */  sw         $a1, 0x34($sp)
    /* 41510 8008CF30 AFA60038 */  sw         $a2, 0x38($sp)
    /* 41514 8008CF34 15C00056 */  bnez       $t6, .L8008D090
    /* 41518 8008CF38 AFA7003C */   sw        $a3, 0x3C($sp)
    /* 4151C 8008CF3C 8FA40034 */  lw         $a0, 0x34($sp)
    /* 41520 8008CF40 8FA50038 */  lw         $a1, 0x38($sp)
    /* 41524 8008CF44 0C01EF36 */  jal        func_8007BCD8
    /* 41528 8008CF48 8FA6003C */   lw        $a2, 0x3C($sp)
    /* 4152C 8008CF4C 3C048019 */  lui        $a0, %hi(D_8018C1E8)
    /* 41530 8008CF50 3C058019 */  lui        $a1, %hi(D_8018C200)
    /* 41534 8008CF54 24A5C200 */  addiu      $a1, $a1, %lo(D_8018C200)
    /* 41538 8008CF58 2484C1E8 */  addiu      $a0, $a0, %lo(D_8018C1E8)
    /* 4153C 8008CF5C 0C01EF36 */  jal        func_8007BCD8
    /* 41540 8008CF60 24060001 */   addiu     $a2, $zero, 0x1
    /* 41544 8008CF64 3C0F8009 */  lui        $t7, %hi(D_800964B0)
    /* 41548 8008CF68 8DEF64B0 */  lw         $t7, %lo(D_800964B0)($t7)
    /* 4154C 8008CF6C 15E00003 */  bnez       $t7, .L8008CF7C
    /* 41550 8008CF70 00000000 */   nop
    /* 41554 8008CF74 0C023916 */  jal        func_8008E458
    /* 41558 8008CF78 00000000 */   nop
  .L8008CF7C:
    /* 4155C 8008CF7C 3C058019 */  lui        $a1, %hi(D_8018C1E8)
    /* 41560 8008CF80 3C062222 */  lui        $a2, (0x22222222 >> 16)
    /* 41564 8008CF84 34C62222 */  ori        $a2, $a2, (0x22222222 & 0xFFFF)
    /* 41568 8008CF88 24A5C1E8 */  addiu      $a1, $a1, %lo(D_8018C1E8)
    /* 4156C 8008CF8C 0C01F3E6 */  jal        func_8007CF98
    /* 41570 8008CF90 24040008 */   addiu     $a0, $zero, 0x8
    /* 41574 8008CF94 2418FFFF */  addiu      $t8, $zero, -0x1
    /* 41578 8008CF98 AFB80028 */  sw         $t8, 0x28($sp)
    /* 4157C 8008CF9C 0C021C4E */  jal        func_80087138
    /* 41580 8008CFA0 00002025 */   or        $a0, $zero, $zero
    /* 41584 8008CFA4 AFA20024 */  sw         $v0, 0x24($sp)
    /* 41588 8008CFA8 8FB90024 */  lw         $t9, 0x24($sp)
    /* 4158C 8008CFAC 8FA80030 */  lw         $t0, 0x30($sp)
    /* 41590 8008CFB0 0328082A */  slt        $at, $t9, $t0
    /* 41594 8008CFB4 10200005 */  beqz       $at, .L8008CFCC
    /* 41598 8008CFB8 00000000 */   nop
    /* 4159C 8008CFBC AFB90028 */  sw         $t9, 0x28($sp)
    /* 415A0 8008CFC0 00002025 */  or         $a0, $zero, $zero
    /* 415A4 8008CFC4 0C01F402 */  jal        func_8007D008
    /* 415A8 8008CFC8 01002825 */   or        $a1, $t0, $zero
  .L8008CFCC:
    /* 415AC 8008CFCC 0C01F1DA */  jal        func_8007C768
    /* 415B0 8008CFD0 00000000 */   nop
    /* 415B4 8008CFD4 3C018009 */  lui        $at, %hi(D_80096480)
    /* 415B8 8008CFD8 8FAB0034 */  lw         $t3, 0x34($sp)
    /* 415BC 8008CFDC 3C0A8019 */  lui        $t2, %hi(D_8018B038)
    /* 415C0 8008CFE0 3C0C8019 */  lui        $t4, %hi(D_8018C1E8)
    /* 415C4 8008CFE4 24090001 */  addiu      $t1, $zero, 0x1
    /* 415C8 8008CFE8 254AB038 */  addiu      $t2, $t2, %lo(D_8018B038)
    /* 415CC 8008CFEC 258CC1E8 */  addiu      $t4, $t4, %lo(D_8018C1E8)
    /* 415D0 8008CFF0 AC296480 */  sw         $t1, %lo(D_80096480)($at)
    /* 415D4 8008CFF4 AC2A6484 */  sw         $t2, %lo(D_80096484)($at)
    /* 415D8 8008CFF8 AC2C648C */  sw         $t4, %lo(D_8009648C)($at)
    /* 415DC 8008CFFC 3C188019 */  lui        $t8, %hi(D_8018B1E8)
    /* 415E0 8008D000 AC2B6488 */  sw         $t3, %lo(D_80096488)($at)
    /* 415E4 8008D004 8FA80030 */  lw         $t0, 0x30($sp)
    /* 415E8 8008D008 3C018009 */  lui        $at, %hi(D_80096490)
    /* 415EC 8008D00C 3C0D8019 */  lui        $t5, %hi(D_8018D310)
    /* 415F0 8008D010 3C0E8009 */  lui        $t6, %hi(func_8008D0A8)
    /* 415F4 8008D014 3C0F8009 */  lui        $t7, %hi(func_8008D188)
    /* 415F8 8008D018 2718B1E8 */  addiu      $t8, $t8, %lo(D_8018B1E8)
    /* 415FC 8008D01C 25ADD310 */  addiu      $t5, $t5, %lo(D_8018D310)
    /* 41600 8008D020 25CED0A8 */  addiu      $t6, $t6, %lo(func_8008D0A8)
    /* 41604 8008D024 25EFD188 */  addiu      $t7, $t7, %lo(func_8008D188)
    /* 41608 8008D028 27191000 */  addiu      $t9, $t8, 0x1000
    /* 4160C 8008D02C 3C068009 */  lui        $a2, %hi(func_8008DE28)
    /* 41610 8008D030 3C078009 */  lui        $a3, %hi(D_80096480)
    /* 41614 8008D034 AFA2002C */  sw         $v0, 0x2C($sp)
    /* 41618 8008D038 AC2D6490 */  sw         $t5, %lo(D_80096490)($at)
    /* 4161C 8008D03C AC2E6494 */  sw         $t6, %lo(D_80096494)($at)
    /* 41620 8008D040 AC2F6498 */  sw         $t7, %lo(D_80096498)($at)
    /* 41624 8008D044 24E76480 */  addiu      $a3, $a3, %lo(D_80096480)
    /* 41628 8008D048 24C6DE28 */  addiu      $a2, $a2, %lo(func_8008DE28)
    /* 4162C 8008D04C AFB90010 */  sw         $t9, 0x10($sp)
    /* 41630 8008D050 01402025 */  or         $a0, $t2, $zero
    /* 41634 8008D054 00002825 */  or         $a1, $zero, $zero
    /* 41638 8008D058 0C01EF42 */  jal        func_8007BD08
    /* 4163C 8008D05C AFA80014 */   sw        $t0, 0x14($sp)
    /* 41640 8008D060 3C048019 */  lui        $a0, %hi(D_8018B038)
    /* 41644 8008D064 0C01F43A */  jal        func_8007D0E8
    /* 41648 8008D068 2484B038 */   addiu     $a0, $a0, %lo(D_8018B038)
    /* 4164C 8008D06C 0C01F1E2 */  jal        func_8007C788
    /* 41650 8008D070 8FA4002C */   lw        $a0, 0x2C($sp)
    /* 41654 8008D074 8FA90028 */  lw         $t1, 0x28($sp)
    /* 41658 8008D078 2401FFFF */  addiu      $at, $zero, -0x1
    /* 4165C 8008D07C 11210004 */  beq        $t1, $at, .L8008D090
    /* 41660 8008D080 00000000 */   nop
    /* 41664 8008D084 00002025 */  or         $a0, $zero, $zero
    /* 41668 8008D088 0C01F402 */  jal        func_8007D008
    /* 4166C 8008D08C 01202825 */   or        $a1, $t1, $zero
  .L8008D090:
    /* 41670 8008D090 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 41674 8008D094 27BD0030 */  addiu      $sp, $sp, 0x30
    /* 41678 8008D098 03E00008 */  jr         $ra
    /* 4167C 8008D09C 00000000 */   nop
endlabel func_8008CF18
    /* 41680 8008D0A0 00000000 */  nop
    /* 41684 8008D0A4 00000000 */  nop
