.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_8005E544, 0x60

glabel func_8005E544
    /* 12B24 8005E544 27BDFFD8 */  addiu      $sp, $sp, -0x28
    /* 12B28 8005E548 AFB00020 */  sw         $s0, 0x20($sp)
    /* 12B2C 8005E54C 00808021 */  addu       $s0, $a0, $zero
    /* 12B30 8005E550 44867000 */  mtc1       $a2, $fa1
    /* 12B34 8005E554 00E03021 */  addu       $a2, $a3, $zero
    /* 12B38 8005E558 27A70038 */  addiu      $a3, $sp, 0x38
    /* 12B3C 8005E55C 8FA20038 */  lw         $v0, 0x38($sp)
    /* 12B40 8005E560 44856000 */  mtc1       $a1, $fa0
    /* 12B44 8005E564 27A20018 */  addiu      $v0, $sp, 0x18
    /* 12B48 8005E568 AFBF0024 */  sw         $ra, 0x24($sp)
    /* 12B4C 8005E56C AFA00018 */  sw         $zero, 0x18($sp)
    /* 12B50 8005E570 0C017917 */  jal        func_8005E45C
    /* 12B54 8005E574 AFA20010 */   sw        $v0, 0x10($sp)
    /* 12B58 8005E578 10400006 */  beqz       $v0, .L8005E594
    /* 12B5C 8005E57C 24070040 */   addiu     $a3, $zero, 0x40
    /* 12B60 8005E580 8FA60038 */  lw         $a2, 0x38($sp)
    /* 12B64 8005E584 3C053F80 */  lui        $a1, (0x3F800000 >> 16)
    /* 12B68 8005E588 02002021 */  addu       $a0, $s0, $zero
    /* 12B6C 8005E58C 0C017338 */  jal        func_8005CCE0
    /* 12B70 8005E590 AFA00010 */   sw        $zero, 0x10($sp)
  .L8005E594:
    /* 12B74 8005E594 8FBF0024 */  lw         $ra, 0x24($sp)
    /* 12B78 8005E598 8FB00020 */  lw         $s0, 0x20($sp)
    /* 12B7C 8005E59C 03E00008 */  jr         $ra
    /* 12B80 8005E5A0 27BD0028 */   addiu     $sp, $sp, 0x28
endlabel func_8005E544
