.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_8005B224, 0x5B4

glabel func_8005B224
    /* F804 8005B224 27BDEF60 */  addiu      $sp, $sp, -0x10A0
    /* F808 8005B228 00801821 */  addu       $v1, $a0, $zero
    /* F80C 8005B22C AFBE1098 */  sw         $fp, 0x1098($sp)
    /* F810 8005B230 00A0F021 */  addu       $fp, $a1, $zero
    /* F814 8005B234 27A41050 */  addiu      $a0, $sp, 0x1050
    /* F818 8005B238 3C028018 */  lui        $v0, %hi(D_8017DF44)
    /* F81C 8005B23C 00602821 */  addu       $a1, $v1, $zero
    /* F820 8005B240 AFA610A8 */  sw         $a2, 0x10A8($sp)
    /* F824 8005B244 2406FFFF */  addiu      $a2, $zero, -0x1
    /* F828 8005B248 AFBF109C */  sw         $ra, 0x109C($sp)
    /* F82C 8005B24C AFB71094 */  sw         $s7, 0x1094($sp)
    /* F830 8005B250 AFB61090 */  sw         $s6, 0x1090($sp)
    /* F834 8005B254 AFB5108C */  sw         $s5, 0x108C($sp)
    /* F838 8005B258 AFB41088 */  sw         $s4, 0x1088($sp)
    /* F83C 8005B25C AFB31084 */  sw         $s3, 0x1084($sp)
    /* F840 8005B260 AFB21080 */  sw         $s2, 0x1080($sp)
    /* F844 8005B264 AFB1107C */  sw         $s1, 0x107C($sp)
    /* F848 8005B268 AFB01078 */  sw         $s0, 0x1078($sp)
    /* F84C 8005B26C 0C016A99 */  jal        func_8005AA64
    /* F850 8005B270 AC44DF44 */   sw        $a0, %lo(D_8017DF44)($v0)
    /* F854 8005B274 0C016BAD */  jal        func_8005AEB4
    /* F858 8005B278 00000000 */   nop
    /* F85C 8005B27C 00001821 */  addu       $v1, $zero, $zero
    /* F860 8005B280 27A40010 */  addiu      $a0, $sp, 0x10
    /* F864 8005B284 3C028018 */  lui        $v0, %hi(D_8017DF3E)
    /* F868 8005B288 A440DF3E */  sh         $zero, %lo(D_8017DF3E)($v0)
    /* F86C 8005B28C 3C028018 */  lui        $v0, %hi(D_8017DF40)
    /* F870 8005B290 A040DF40 */  sb         $zero, %lo(D_8017DF40)($v0)
    /* F874 8005B294 3C028018 */  lui        $v0, %hi(D_8017DF4C)
    /* F878 8005B298 AC40DF4C */  sw         $zero, %lo(D_8017DF4C)($v0)
    /* F87C 8005B29C 00031400 */  sll        $v0, $v1, 16
  .L8005B2A0:
    /* F880 8005B2A0 00021403 */  sra        $v0, $v0, 16
    /* F884 8005B2A4 00821021 */  addu       $v0, $a0, $v0
    /* F888 8005B2A8 A0400000 */  sb         $zero, 0x0($v0)
    /* F88C 8005B2AC 24620001 */  addiu      $v0, $v1, 0x1
    /* F890 8005B2B0 00401821 */  addu       $v1, $v0, $zero
    /* F894 8005B2B4 00021400 */  sll        $v0, $v0, 16
    /* F898 8005B2B8 00021403 */  sra        $v0, $v0, 16
    /* F89C 8005B2BC 28420FC4 */  slti       $v0, $v0, 0xFC4
    /* F8A0 8005B2C0 1440FFF7 */  bnez       $v0, .L8005B2A0
    /* F8A4 8005B2C4 00031400 */   sll       $v0, $v1, 16
    /* F8A8 8005B2C8 24150FC4 */  addiu      $s5, $zero, 0xFC4
    /* F8AC 8005B2CC 8FAD10A8 */  lw         $t5, 0x10A8($sp)
    /* F8B0 8005B2D0 11A00133 */  beqz       $t5, .L8005B7A0
    /* F8B4 8005B2D4 0000B021 */   addu      $s6, $zero, $zero
    /* F8B8 8005B2D8 3C178018 */  lui        $s7, %hi(D_8017DF4C)
    /* F8BC 8005B2DC 3C0C8018 */  lui        $t4, %hi(D_8017DF48)
    /* F8C0 8005B2E0 3C0D8018 */  lui        $t5, %hi(D_8017DA58)
  .L8005B2E4:
    /* F8C4 8005B2E4 25ADDA58 */  addiu      $t5, $t5, %lo(D_8017DA58)
    /* F8C8 8005B2E8 95B104E4 */  lhu        $s1, 0x4E4($t5)
    /* F8CC 8005B2EC 2E220273 */  sltiu      $v0, $s1, 0x273
    /* F8D0 8005B2F0 1040002C */  beqz       $v0, .L8005B3A4
    /* F8D4 8005B2F4 24120020 */   addiu     $s2, $zero, 0x20
  .L8005B2F8:
    /* F8D8 8005B2F8 8EE2DF4C */  lw         $v0, %lo(D_8017DF4C)($s7)
    /* F8DC 8005B2FC 14400019 */  bnez       $v0, .L8005B364
    /* F8E0 8005B300 3C0D8018 */   lui       $t5, %hi(D_8017DA58)
    /* F8E4 8005B304 3C0D8018 */  lui        $t5, %hi(D_8017DF44)
    /* F8E8 8005B308 8DB0DF44 */  lw         $s0, %lo(D_8017DF44)($t5)
    /* F8EC 8005B30C 8E02000C */  lw         $v0, 0xC($s0)
    /* F8F0 8005B310 8E030010 */  lw         $v1, 0x10($s0)
    /* F8F4 8005B314 0043102B */  sltu       $v0, $v0, $v1
    /* F8F8 8005B318 14400006 */  bnez       $v0, .L8005B334
    /* F8FC 8005B31C 3C0D8019 */   lui       $t5, %hi(D_80190000)
    /* F900 8005B320 02002021 */  addu       $a0, $s0, $zero
    /* F904 8005B324 0C016AA6 */  jal        func_8005AA98
    /* F908 8005B328 AFAC1070 */   sw        $t4, 0x1070($sp)
    /* F90C 8005B32C 8FAC1070 */  lw         $t4, 0x1070($sp)
    /* F910 8005B330 3C0D8019 */  lui        $t5, %hi(D_80190000)
  .L8005B334:
    /* F914 8005B334 25AD0000 */  addiu      $t5, $t5, %lo(D_80190000)
    /* F918 8005B338 8E020008 */  lw         $v0, 0x8($s0)
    /* F91C 8005B33C 8E03000C */  lw         $v1, 0xC($s0)
    /* F920 8005B340 00021280 */  sll        $v0, $v0, 10
    /* F924 8005B344 00431021 */  addu       $v0, $v0, $v1
    /* F928 8005B348 004D1021 */  addu       $v0, $v0, $t5
    /* F92C 8005B34C 8C420000 */  lw         $v0, 0x0($v0)
    /* F930 8005B350 24630004 */  addiu      $v1, $v1, 0x4
    /* F934 8005B354 AE03000C */  sw         $v1, 0xC($s0)
    /* F938 8005B358 AEF2DF4C */  sw         $s2, %lo(D_8017DF4C)($s7)
    /* F93C 8005B35C AD82DF48 */  sw         $v0, %lo(D_8017DF48)($t4)
    /* F940 8005B360 3C0D8018 */  lui        $t5, %hi(D_8017DA58)
  .L8005B364:
    /* F944 8005B364 8D83DF48 */  lw         $v1, %lo(D_8017DF48)($t4)
    /* F948 8005B368 25ADDA58 */  addiu      $t5, $t5, %lo(D_8017DA58)
    /* F94C 8005B36C 000317C2 */  srl        $v0, $v1, 31
    /* F950 8005B370 02228821 */  addu       $s1, $s1, $v0
    /* F954 8005B374 3222FFFF */  andi       $v0, $s1, 0xFFFF
    /* F958 8005B378 00021040 */  sll        $v0, $v0, 1
    /* F95C 8005B37C 004D1021 */  addu       $v0, $v0, $t5
    /* F960 8005B380 94510000 */  lhu        $s1, 0x0($v0)
    /* F964 8005B384 8EE2DF4C */  lw         $v0, %lo(D_8017DF4C)($s7)
    /* F968 8005B388 00031840 */  sll        $v1, $v1, 1
    /* F96C 8005B38C AD83DF48 */  sw         $v1, %lo(D_8017DF48)($t4)
    /* F970 8005B390 2442FFFF */  addiu      $v0, $v0, -0x1
    /* F974 8005B394 AEE2DF4C */  sw         $v0, %lo(D_8017DF4C)($s7)
    /* F978 8005B398 2E220273 */  sltiu      $v0, $s1, 0x273
    /* F97C 8005B39C 1440FFD6 */  bnez       $v0, .L8005B2F8
    /* F980 8005B3A0 00000000 */   nop
  .L8005B3A4:
    /* F984 8005B3A4 2630FD8D */  addiu      $s0, $s1, -0x273
    /* F988 8005B3A8 3C028018 */  lui        $v0, %hi(D_8017CE08)
    /* F98C 8005B3AC 2452CE08 */  addiu      $s2, $v0, %lo(D_8017CE08)
    /* F990 8005B3B0 964304E4 */  lhu        $v1, 0x4E4($s2)
    /* F994 8005B3B4 34028000 */  ori        $v0, $zero, 0x8000
    /* F998 8005B3B8 14620004 */  bne        $v1, $v0, .L8005B3CC
    /* F99C 8005B3BC 02008821 */   addu      $s1, $s0, $zero
    /* F9A0 8005B3C0 0C016BF1 */  jal        func_8005AFC4
    /* F9A4 8005B3C4 AFAC1070 */   sw        $t4, 0x1070($sp)
    /* F9A8 8005B3C8 8FAC1070 */  lw         $t4, 0x1070($sp)
  .L8005B3CC:
    /* F9AC 8005B3CC 3C038018 */  lui        $v1, %hi(D_8017D2F8)
    /* F9B0 8005B3D0 2463D2F8 */  addiu      $v1, $v1, %lo(D_8017D2F8)
    /* F9B4 8005B3D4 00101400 */  sll        $v0, $s0, 16
    /* F9B8 8005B3D8 000213C3 */  sra        $v0, $v0, 15
    /* F9BC 8005B3DC 00431021 */  addu       $v0, $v0, $v1
    /* F9C0 8005B3E0 944604E6 */  lhu        $a2, 0x4E6($v0)
    /* F9C4 8005B3E4 02405021 */  addu       $t2, $s2, $zero
    /* F9C8 8005B3E8 00604821 */  addu       $t1, $v1, $zero
  .L8005B3EC:
    /* F9CC 8005B3EC 00061400 */  sll        $v0, $a2, 16
    /* F9D0 8005B3F0 000213C3 */  sra        $v0, $v0, 15
    /* F9D4 8005B3F4 004A1021 */  addu       $v0, $v0, $t2
    /* F9D8 8005B3F8 94430000 */  lhu        $v1, 0x0($v0)
    /* F9DC 8005B3FC 24630001 */  addiu      $v1, $v1, 0x1
    /* F9E0 8005B400 00605821 */  addu       $t3, $v1, $zero
    /* F9E4 8005B404 A4430000 */  sh         $v1, 0x0($v0)
    /* F9E8 8005B408 00031C00 */  sll        $v1, $v1, 16
    /* F9EC 8005B40C 24C20001 */  addiu      $v0, $a2, 0x1
    /* F9F0 8005B410 00021400 */  sll        $v0, $v0, 16
    /* F9F4 8005B414 000213C3 */  sra        $v0, $v0, 15
    /* F9F8 8005B418 004A1021 */  addu       $v0, $v0, $t2
    /* F9FC 8005B41C 94420000 */  lhu        $v0, 0x0($v0)
    /* FA00 8005B420 00032C03 */  sra        $a1, $v1, 16
    /* FA04 8005B424 0045102A */  slt        $v0, $v0, $a1
    /* FA08 8005B428 1040003C */  beqz       $v0, .L8005B51C
    /* FA0C 8005B42C 24C20002 */   addiu     $v0, $a2, 0x2
    /* FA10 8005B430 00021C00 */  sll        $v1, $v0, 16
    /* FA14 8005B434 00031BC3 */  sra        $v1, $v1, 15
    /* FA18 8005B438 006A1821 */  addu       $v1, $v1, $t2
    /* FA1C 8005B43C 94630000 */  lhu        $v1, 0x0($v1)
    /* FA20 8005B440 0065182A */  slt        $v1, $v1, $a1
    /* FA24 8005B444 1060000B */  beqz       $v1, .L8005B474
    /* FA28 8005B448 00402021 */   addu      $a0, $v0, $zero
    /* FA2C 8005B44C 3C028018 */  lui        $v0, %hi(D_8017CE08)
    /* FA30 8005B450 2447CE08 */  addiu      $a3, $v0, %lo(D_8017CE08)
  .L8005B454:
    /* FA34 8005B454 24820001 */  addiu      $v0, $a0, 0x1
    /* FA38 8005B458 00021C00 */  sll        $v1, $v0, 16
    /* FA3C 8005B45C 00031BC3 */  sra        $v1, $v1, 15
    /* FA40 8005B460 00671821 */  addu       $v1, $v1, $a3
    /* FA44 8005B464 94630000 */  lhu        $v1, 0x0($v1)
    /* FA48 8005B468 0065182A */  slt        $v1, $v1, $a1
    /* FA4C 8005B46C 1460FFF9 */  bnez       $v1, .L8005B454
    /* FA50 8005B470 00402021 */   addu      $a0, $v0, $zero
  .L8005B474:
    /* FA54 8005B474 2488FFFF */  addiu      $t0, $a0, -0x1
    /* FA58 8005B478 00062C00 */  sll        $a1, $a2, 16
    /* FA5C 8005B47C 00052BC3 */  sra        $a1, $a1, 15
    /* FA60 8005B480 00081400 */  sll        $v0, $t0, 16
    /* FA64 8005B484 00023BC3 */  sra        $a3, $v0, 15
    /* FA68 8005B488 00EA1821 */  addu       $v1, $a3, $t2
    /* FA6C 8005B48C 00AA1021 */  addu       $v0, $a1, $t2
    /* FA70 8005B490 3C0D8018 */  lui        $t5, %hi(D_8017DA58)
    /* FA74 8005B494 25ADDA58 */  addiu      $t5, $t5, %lo(D_8017DA58)
    /* FA78 8005B498 00AD2821 */  addu       $a1, $a1, $t5
    /* FA7C 8005B49C 94640000 */  lhu        $a0, 0x0($v1)
    /* FA80 8005B4A0 A4440000 */  sh         $a0, 0x0($v0)
    /* FA84 8005B4A4 A46B0000 */  sh         $t3, 0x0($v1)
    /* FA88 8005B4A8 84A30000 */  lh         $v1, 0x0($a1)
    /* FA8C 8005B4AC 94A40000 */  lhu        $a0, 0x0($a1)
    /* FA90 8005B4B0 00031040 */  sll        $v0, $v1, 1
    /* FA94 8005B4B4 00491021 */  addu       $v0, $v0, $t1
    /* FA98 8005B4B8 A4480000 */  sh         $t0, 0x0($v0)
    /* FA9C 8005B4BC 28620273 */  slti       $v0, $v1, 0x273
    /* FAA0 8005B4C0 10400004 */  beqz       $v0, .L8005B4D4
    /* FAA4 8005B4C4 24620001 */   addiu     $v0, $v1, 0x1
    /* FAA8 8005B4C8 00021040 */  sll        $v0, $v0, 1
    /* FAAC 8005B4CC 00491021 */  addu       $v0, $v0, $t1
    /* FAB0 8005B4D0 A4480000 */  sh         $t0, 0x0($v0)
  .L8005B4D4:
    /* FAB4 8005B4D4 3C0D8018 */  lui        $t5, %hi(D_8017DA58)
    /* FAB8 8005B4D8 25ADDA58 */  addiu      $t5, $t5, %lo(D_8017DA58)
    /* FABC 8005B4DC 00ED1021 */  addu       $v0, $a3, $t5
    /* FAC0 8005B4E0 94470000 */  lhu        $a3, 0x0($v0)
    /* FAC4 8005B4E4 A4440000 */  sh         $a0, 0x0($v0)
    /* FAC8 8005B4E8 00071400 */  sll        $v0, $a3, 16
    /* FACC 8005B4EC 00021C03 */  sra        $v1, $v0, 16
    /* FAD0 8005B4F0 00031040 */  sll        $v0, $v1, 1
    /* FAD4 8005B4F4 00491021 */  addu       $v0, $v0, $t1
    /* FAD8 8005B4F8 A4460000 */  sh         $a2, 0x0($v0)
    /* FADC 8005B4FC 28620273 */  slti       $v0, $v1, 0x273
    /* FAE0 8005B500 10400004 */  beqz       $v0, .L8005B514
    /* FAE4 8005B504 24620001 */   addiu     $v0, $v1, 0x1
    /* FAE8 8005B508 00021040 */  sll        $v0, $v0, 1
    /* FAEC 8005B50C 00491021 */  addu       $v0, $v0, $t1
    /* FAF0 8005B510 A4460000 */  sh         $a2, 0x0($v0)
  .L8005B514:
    /* FAF4 8005B514 A4A70000 */  sh         $a3, 0x0($a1)
    /* FAF8 8005B518 01003021 */  addu       $a2, $t0, $zero
  .L8005B51C:
    /* FAFC 8005B51C 00061400 */  sll        $v0, $a2, 16
    /* FB00 8005B520 000213C3 */  sra        $v0, $v0, 15
    /* FB04 8005B524 00491021 */  addu       $v0, $v0, $t1
    /* FB08 8005B528 84420000 */  lh         $v0, 0x0($v0)
    /* FB0C 8005B52C 1440FFAF */  bnez       $v0, .L8005B3EC
    /* FB10 8005B530 00403021 */   addu      $a2, $v0, $zero
    /* FB14 8005B534 00111400 */  sll        $v0, $s1, 16
    /* FB18 8005B538 00021403 */  sra        $v0, $v0, 16
    /* FB1C 8005B53C 00409821 */  addu       $s3, $v0, $zero
    /* FB20 8005B540 28420100 */  slti       $v0, $v0, 0x100
    /* FB24 8005B544 10400008 */  beqz       $v0, .L8005B568
    /* FB28 8005B548 26A20001 */   addiu     $v0, $s5, 0x1
    /* FB2C 8005B54C A3D30000 */  sb         $s3, 0x0($fp)
    /* FB30 8005B550 27DE0001 */  addiu      $fp, $fp, 0x1
    /* FB34 8005B554 02BD1821 */  addu       $v1, $s5, $sp
    /* FB38 8005B558 30550FFF */  andi       $s5, $v0, 0xFFF
    /* FB3C 8005B55C 26D60001 */  addiu      $s6, $s6, 0x1
    /* FB40 8005B560 08016DE4 */  j          func_8005B790
    /* FB44 8005B564 A0730010 */   sb        $s3, 0x10($v1)
  .L8005B568:
    /* FB48 8005B568 8D84DF48 */  lw         $a0, %lo(D_8017DF48)($t4)
    /* FB4C 8005B56C 8EE3DF4C */  lw         $v1, %lo(D_8017DF4C)($s7)
    /* FB50 8005B570 28620008 */  slti       $v0, $v1, 0x8
    /* FB54 8005B574 10400023 */  beqz       $v0, .L8005B604
    /* FB58 8005B578 00049602 */   srl       $s2, $a0, 24
    /* FB5C 8005B57C 24020008 */  addiu      $v0, $zero, 0x8
    /* FB60 8005B580 00438823 */  subu       $s1, $v0, $v1
    /* FB64 8005B584 2403FFFF */  addiu      $v1, $zero, -0x1
    /* FB68 8005B588 3C0D8018 */  lui        $t5, %hi(D_8017DF44)
    /* FB6C 8005B58C 8DB0DF44 */  lw         $s0, %lo(D_8017DF44)($t5)
    /* FB70 8005B590 02231806 */  srlv       $v1, $v1, $s1
    /* FB74 8005B594 8E02000C */  lw         $v0, 0xC($s0)
    /* FB78 8005B598 8E040010 */  lw         $a0, 0x10($s0)
    /* FB7C 8005B59C 0044102B */  sltu       $v0, $v0, $a0
    /* FB80 8005B5A0 14400005 */  bnez       $v0, .L8005B5B8
    /* FB84 8005B5A4 0003A027 */   nor       $s4, $zero, $v1
    /* FB88 8005B5A8 02002021 */  addu       $a0, $s0, $zero
    /* FB8C 8005B5AC 0C016AA6 */  jal        func_8005AA98
    /* FB90 8005B5B0 AFAC1070 */   sw        $t4, 0x1070($sp)
    /* FB94 8005B5B4 8FAC1070 */  lw         $t4, 0x1070($sp)
  .L8005B5B8:
    /* FB98 8005B5B8 3C0D8019 */  lui        $t5, %hi(D_80190000)
    /* FB9C 8005B5BC 25AD0000 */  addiu      $t5, $t5, %lo(D_80190000)
    /* FBA0 8005B5C0 8E020008 */  lw         $v0, 0x8($s0)
    /* FBA4 8005B5C4 8E03000C */  lw         $v1, 0xC($s0)
    /* FBA8 8005B5C8 00021280 */  sll        $v0, $v0, 10
    /* FBAC 8005B5CC 00431021 */  addu       $v0, $v0, $v1
    /* FBB0 8005B5D0 004D1021 */  addu       $v0, $v0, $t5
    /* FBB4 8005B5D4 8C440000 */  lw         $a0, 0x0($v0)
    /* FBB8 8005B5D8 24630004 */  addiu      $v1, $v1, 0x4
    /* FBBC 8005B5DC AE03000C */  sw         $v1, 0xC($s0)
    /* FBC0 8005B5E0 24030020 */  addiu      $v1, $zero, 0x20
    /* FBC4 8005B5E4 00711823 */  subu       $v1, $v1, $s1
    /* FBC8 8005B5E8 AEE3DF4C */  sw         $v1, %lo(D_8017DF4C)($s7)
    /* FBCC 8005B5EC 00941024 */  and        $v0, $a0, $s4
    /* FBD0 8005B5F0 00621006 */  srlv       $v0, $v0, $v1
    /* FBD4 8005B5F4 02429025 */  or         $s2, $s2, $v0
    /* FBD8 8005B5F8 02242004 */  sllv       $a0, $a0, $s1
    /* FBDC 8005B5FC 08016D85 */  j          func_8005B614
    /* FBE0 8005B600 AD84DF48 */   sw        $a0, %lo(D_8017DF48)($t4)
  .L8005B604:
    /* FBE4 8005B604 2462FFF8 */  addiu      $v0, $v1, -0x8
    /* FBE8 8005B608 AEE2DF4C */  sw         $v0, %lo(D_8017DF4C)($s7)
    /* FBEC 8005B60C 00041200 */  sll        $v0, $a0, 8
    /* FBF0 8005B610 AD82DF48 */  sw         $v0, %lo(D_8017DF48)($t4)
  alabel func_8005B614
    /* FBF4 8005B614 3C038009 */  lui        $v1, %hi(D_800925D0)
    /* FBF8 8005B618 246325D0 */  addiu      $v1, $v1, %lo(D_800925D0)
    /* FBFC 8005B61C 3244FFFF */  andi       $a0, $s2, 0xFFFF
    /* FC00 8005B620 00831821 */  addu       $v1, $a0, $v1
    /* FC04 8005B624 3C028009 */  lui        $v0, %hi(D_800926D0)
    /* FC08 8005B628 244226D0 */  addiu      $v0, $v0, %lo(D_800926D0)
    /* FC0C 8005B62C 00822021 */  addu       $a0, $a0, $v0
    /* FC10 8005B630 90620000 */  lbu        $v0, 0x0($v1)
    /* FC14 8005B634 90910000 */  lbu        $s1, 0x0($a0)
    /* FC18 8005B638 0002A180 */  sll        $s4, $v0, 6
    /* FC1C 8005B63C 2623FFFD */  addiu      $v1, $s1, -0x3
    /* FC20 8005B640 00608821 */  addu       $s1, $v1, $zero
    /* FC24 8005B644 3063FFFF */  andi       $v1, $v1, 0xFFFF
    /* FC28 8005B648 3402FFFF */  ori        $v0, $zero, 0xFFFF
    /* FC2C 8005B64C 5062002F */  beql       $v1, $v0, .L8005B70C
    /* FC30 8005B650 3242003F */   andi      $v0, $s2, 0x3F
    /* FC34 8005B654 24070020 */  addiu      $a3, $zero, 0x20
    /* FC38 8005B658 00403021 */  addu       $a2, $v0, $zero
  .L8005B65C:
    /* FC3C 8005B65C 8EE2DF4C */  lw         $v0, %lo(D_8017DF4C)($s7)
    /* FC40 8005B660 1440001D */  bnez       $v0, .L8005B6D8
    /* FC44 8005B664 2625FFFF */   addiu     $a1, $s1, -0x1
    /* FC48 8005B668 3C0D8018 */  lui        $t5, %hi(D_8017DF44)
    /* FC4C 8005B66C 8DB0DF44 */  lw         $s0, %lo(D_8017DF44)($t5)
    /* FC50 8005B670 8E02000C */  lw         $v0, 0xC($s0)
    /* FC54 8005B674 8E030010 */  lw         $v1, 0x10($s0)
    /* FC58 8005B678 0043102B */  sltu       $v0, $v0, $v1
    /* FC5C 8005B67C 1440000A */  bnez       $v0, .L8005B6A8
    /* FC60 8005B680 3C0D8019 */   lui       $t5, %hi(D_80190000)
    /* FC64 8005B684 02002021 */  addu       $a0, $s0, $zero
    /* FC68 8005B688 AFA61068 */  sw         $a2, 0x1068($sp)
    /* FC6C 8005B68C AFA7106C */  sw         $a3, 0x106C($sp)
    /* FC70 8005B690 0C016AA6 */  jal        func_8005AA98
    /* FC74 8005B694 AFAC1070 */   sw        $t4, 0x1070($sp)
    /* FC78 8005B698 8FAC1070 */  lw         $t4, 0x1070($sp)
    /* FC7C 8005B69C 8FA7106C */  lw         $a3, 0x106C($sp)
    /* FC80 8005B6A0 8FA61068 */  lw         $a2, 0x1068($sp)
    /* FC84 8005B6A4 3C0D8019 */  lui        $t5, %hi(D_80190000)
  .L8005B6A8:
    /* FC88 8005B6A8 25AD0000 */  addiu      $t5, $t5, %lo(D_80190000)
    /* FC8C 8005B6AC 8E020008 */  lw         $v0, 0x8($s0)
    /* FC90 8005B6B0 8E03000C */  lw         $v1, 0xC($s0)
    /* FC94 8005B6B4 00021280 */  sll        $v0, $v0, 10
    /* FC98 8005B6B8 00431021 */  addu       $v0, $v0, $v1
    /* FC9C 8005B6BC 004D1021 */  addu       $v0, $v0, $t5
    /* FCA0 8005B6C0 8C420000 */  lw         $v0, 0x0($v0)
    /* FCA4 8005B6C4 24630004 */  addiu      $v1, $v1, 0x4
    /* FCA8 8005B6C8 AE03000C */  sw         $v1, 0xC($s0)
    /* FCAC 8005B6CC AEE7DF4C */  sw         $a3, %lo(D_8017DF4C)($s7)
    /* FCB0 8005B6D0 AD82DF48 */  sw         $v0, %lo(D_8017DF48)($t4)
    /* FCB4 8005B6D4 2625FFFF */  addiu      $a1, $s1, -0x1
  .L8005B6D8:
    /* FCB8 8005B6D8 00A08821 */  addu       $s1, $a1, $zero
    /* FCBC 8005B6DC 00121040 */  sll        $v0, $s2, 1
    /* FCC0 8005B6E0 8D83DF48 */  lw         $v1, %lo(D_8017DF48)($t4)
    /* FCC4 8005B6E4 30A5FFFF */  andi       $a1, $a1, 0xFFFF
    /* FCC8 8005B6E8 000327C2 */  srl        $a0, $v1, 31
    /* FCCC 8005B6EC 00829025 */  or         $s2, $a0, $v0
    /* FCD0 8005B6F0 8EE2DF4C */  lw         $v0, %lo(D_8017DF4C)($s7)
    /* FCD4 8005B6F4 00031840 */  sll        $v1, $v1, 1
    /* FCD8 8005B6F8 AD83DF48 */  sw         $v1, %lo(D_8017DF48)($t4)
    /* FCDC 8005B6FC 2442FFFF */  addiu      $v0, $v0, -0x1
    /* FCE0 8005B700 14A6FFD6 */  bne        $a1, $a2, .L8005B65C
    /* FCE4 8005B704 AEE2DF4C */   sw        $v0, %lo(D_8017DF4C)($s7)
    /* FCE8 8005B708 3242003F */  andi       $v0, $s2, 0x3F
  .L8005B70C:
    /* FCEC 8005B70C 00541027 */  nor        $v0, $v0, $s4
    /* FCF0 8005B710 00551021 */  addu       $v0, $v0, $s5
    /* FCF4 8005B714 30430FFF */  andi       $v1, $v0, 0xFFF
    /* FCF8 8005B718 2662FF03 */  addiu      $v0, $s3, -0xFD
    /* FCFC 8005B71C 00021400 */  sll        $v0, $v0, 16
    /* FD00 8005B720 00021403 */  sra        $v0, $v0, 16
    /* FD04 8005B724 1840001A */  blez       $v0, func_8005B790
    /* FD08 8005B728 00002821 */   addu      $a1, $zero, $zero
    /* FD0C 8005B72C 00603821 */  addu       $a3, $v1, $zero
    /* FD10 8005B730 27A40010 */  addiu      $a0, $sp, 0x10
    /* FD14 8005B734 00403021 */  addu       $a2, $v0, $zero
  .L8005B738:
    /* FD18 8005B738 8FAD10A8 */  lw         $t5, 0x10A8($sp)
    /* FD1C 8005B73C 02CD102B */  sltu       $v0, $s6, $t5
    /* FD20 8005B740 10400017 */  beqz       $v0, .L8005B7A0
    /* FD24 8005B744 26A20001 */   addiu     $v0, $s5, 0x1
    /* FD28 8005B748 02A41821 */  addu       $v1, $s5, $a0
    /* FD2C 8005B74C 30550FFF */  andi       $s5, $v0, 0xFFF
    /* FD30 8005B750 26D60001 */  addiu      $s6, $s6, 0x1
    /* FD34 8005B754 00051400 */  sll        $v0, $a1, 16
    /* FD38 8005B758 00021403 */  sra        $v0, $v0, 16
    /* FD3C 8005B75C 00E21021 */  addu       $v0, $a3, $v0
    /* FD40 8005B760 30420FFF */  andi       $v0, $v0, 0xFFF
    /* FD44 8005B764 00821021 */  addu       $v0, $a0, $v0
    /* FD48 8005B768 90530000 */  lbu        $s3, 0x0($v0)
    /* FD4C 8005B76C 24A20001 */  addiu      $v0, $a1, 0x1
    /* FD50 8005B770 00402821 */  addu       $a1, $v0, $zero
    /* FD54 8005B774 00021400 */  sll        $v0, $v0, 16
    /* FD58 8005B778 00021403 */  sra        $v0, $v0, 16
    /* FD5C 8005B77C 0046102A */  slt        $v0, $v0, $a2
    /* FD60 8005B780 A3D30000 */  sb         $s3, 0x0($fp)
    /* FD64 8005B784 27DE0001 */  addiu      $fp, $fp, 0x1
    /* FD68 8005B788 1440FFEB */  bnez       $v0, .L8005B738
    /* FD6C 8005B78C A0730000 */   sb        $s3, 0x0($v1)
  alabel func_8005B790
    /* FD70 8005B790 8FAD10A8 */  lw         $t5, 0x10A8($sp)
    /* FD74 8005B794 02CD102B */  sltu       $v0, $s6, $t5
    /* FD78 8005B798 1440FED2 */  bnez       $v0, .L8005B2E4
    /* FD7C 8005B79C 3C0D8018 */   lui       $t5, %hi(D_8017DA58)
  .L8005B7A0:
    /* FD80 8005B7A0 0C016ACA */  jal        func_8005AB28
    /* FD84 8005B7A4 00000000 */   nop
    /* FD88 8005B7A8 8FBF109C */  lw         $ra, 0x109C($sp)
    /* FD8C 8005B7AC 8FBE1098 */  lw         $fp, 0x1098($sp)
    /* FD90 8005B7B0 8FB71094 */  lw         $s7, 0x1094($sp)
    /* FD94 8005B7B4 8FB61090 */  lw         $s6, 0x1090($sp)
    /* FD98 8005B7B8 8FB5108C */  lw         $s5, 0x108C($sp)
    /* FD9C 8005B7BC 8FB41088 */  lw         $s4, 0x1088($sp)
    /* FDA0 8005B7C0 8FB31084 */  lw         $s3, 0x1084($sp)
    /* FDA4 8005B7C4 8FB21080 */  lw         $s2, 0x1080($sp)
    /* FDA8 8005B7C8 8FB1107C */  lw         $s1, 0x107C($sp)
    /* FDAC 8005B7CC 8FB01078 */  lw         $s0, 0x1078($sp)
    /* FDB0 8005B7D0 03E00008 */  jr         $ra
    /* FDB4 8005B7D4 27BD10A0 */   addiu     $sp, $sp, 0x10A0
endlabel func_8005B224
