.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_80087318, 0x68

glabel func_80087318
    /* 3B8F8 80087318 27BDFFD8 */  addiu      $sp, $sp, -0x28
    /* 3B8FC 8008731C AFBF001C */  sw         $ra, 0x1C($sp)
    /* 3B900 80087320 AFA40028 */  sw         $a0, 0x28($sp)
    /* 3B904 80087324 0C01F1DA */  jal        func_8007C768
    /* 3B908 80087328 AFB00018 */   sw        $s0, 0x18($sp)
    /* 3B90C 8008732C 3C0F8009 */  lui        $t7, %hi(D_80095644)
    /* 3B910 80087330 8DEF5644 */  lw         $t7, %lo(D_80095644)($t7)
    /* 3B914 80087334 8FAE0028 */  lw         $t6, 0x28($sp)
    /* 3B918 80087338 3C198009 */  lui        $t9, %hi(D_80095644)
    /* 3B91C 8008733C 24180001 */  addiu      $t8, $zero, 0x1
    /* 3B920 80087340 ADEE0008 */  sw         $t6, 0x8($t7)
    /* 3B924 80087344 8F395644 */  lw         $t9, %lo(D_80095644)($t9)
    /* 3B928 80087348 3C088009 */  lui        $t0, %hi(D_80095644)
    /* 3B92C 8008734C 00408025 */  or         $s0, $v0, $zero
    /* 3B930 80087350 A7380000 */  sh         $t8, 0x0($t9)
    /* 3B934 80087354 8D085644 */  lw         $t0, %lo(D_80095644)($t0)
    /* 3B938 80087358 02002025 */  or         $a0, $s0, $zero
    /* 3B93C 8008735C 8D090008 */  lw         $t1, 0x8($t0)
    /* 3B940 80087360 8D2A0004 */  lw         $t2, 0x4($t1)
    /* 3B944 80087364 0C01F1E2 */  jal        func_8007C788
    /* 3B948 80087368 AD0A000C */   sw        $t2, 0xC($t0)
    /* 3B94C 8008736C 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 3B950 80087370 8FB00018 */  lw         $s0, 0x18($sp)
    /* 3B954 80087374 27BD0028 */  addiu      $sp, $sp, 0x28
    /* 3B958 80087378 03E00008 */  jr         $ra
    /* 3B95C 8008737C 00000000 */   nop
endlabel func_80087318
    /* 3B960 80087380 00000000 */  nop
    /* 3B964 80087384 00000000 */  nop
