.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_80061EA4, 0x24

glabel func_80061EA4
    /* 16484 80061EA4 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* 16488 80061EA8 00003821 */  addu       $a3, $zero, $zero
    /* 1648C 80061EAC AFBF0018 */  sw         $ra, 0x18($sp)
    /* 16490 80061EB0 AFA00010 */  sw         $zero, 0x10($sp)
    /* 16494 80061EB4 0C01873C */  jal        func_80061CF0
    /* 16498 80061EB8 AFA00014 */   sw        $zero, 0x14($sp)
    /* 1649C 80061EBC 8FBF0018 */  lw         $ra, 0x18($sp)
    /* 164A0 80061EC0 03E00008 */  jr         $ra
    /* 164A4 80061EC4 27BD0020 */   addiu     $sp, $sp, 0x20
endlabel func_80061EA4
