.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_8005F5B0, 0x104

glabel func_8005F5B0
    /* 13B90 8005F5B0 27BDFFD0 */  addiu      $sp, $sp, -0x30
    /* 13B94 8005F5B4 44854000 */  mtc1       $a1, $ft2
    /* 13B98 8005F5B8 44862000 */  mtc1       $a2, $ft0
    /* 13B9C 8005F5BC 44873000 */  mtc1       $a3, $ft1
    /* 13BA0 8005F5C0 46044000 */  add.s      $fv0, $ft2, $ft0
    /* 13BA4 8005F5C4 C7AA0040 */  lwc1       $ft3, 0x40($sp)
    /* 13BA8 8005F5C8 3C018005 */  lui        $at, %hi(D_8004BF48)
    /* 13BAC 8005F5CC C422BF48 */  lwc1       $fv1, %lo(D_8004BF48)($at)
    /* 13BB0 8005F5D0 46060000 */  add.s      $fv0, $fv0, $ft1
    /* 13BB4 8005F5D4 F7B40028 */  sdc1       $fs0, 0x28($sp)
    /* 13BB8 8005F5D8 C7B40044 */  lwc1       $fs0, 0x44($sp)
    /* 13BBC 8005F5DC 460A0000 */  add.s      $fv0, $fv0, $ft3
    /* 13BC0 8005F5E0 AFB20020 */  sw         $s2, 0x20($sp)
    /* 13BC4 8005F5E4 8FB20048 */  lw         $s2, 0x48($sp)
    /* 13BC8 8005F5E8 46020082 */  mul.s      $fv1, $fv0, $fv1
    /* 13BCC 8005F5EC 3C018005 */  lui        $at, %hi(D_8004BF4C)
    /* 13BD0 8005F5F0 C420BF4C */  lwc1       $fv0, %lo(D_8004BF4C)($at)
    /* 13BD4 8005F5F4 AFBF0024 */  sw         $ra, 0x24($sp)
    /* 13BD8 8005F5F8 AFB1001C */  sw         $s1, 0x1C($sp)
    /* 13BDC 8005F5FC 4602003C */  c.lt.s     $fv0, $fv1
    /* 13BE0 8005F600 00000000 */  nop
    /* 13BE4 8005F604 45000005 */  bc1f       .L8005F61C
    /* 13BE8 8005F608 AFB00018 */   sw        $s0, 0x18($sp)
    /* 13BEC 8005F60C 46024203 */  div.s      $ft2, $ft2, $fv1
    /* 13BF0 8005F610 46022103 */  div.s      $ft0, $ft0, $fv1
    /* 13BF4 8005F614 46023183 */  div.s      $ft1, $ft1, $fv1
    /* 13BF8 8005F618 46025283 */  div.s      $ft3, $ft3, $fv1
  .L8005F61C:
    /* 13BFC 8005F61C 3C018005 */  lui        $at, %hi(D_8004BF50)
    /* 13C00 8005F620 C420BF50 */  lwc1       $fv0, %lo(D_8004BF50)($at)
    /* 13C04 8005F624 46004082 */  mul.s      $fv1, $ft2, $fv0
    /* 13C08 8005F628 00000000 */  nop
    /* 13C0C 8005F62C 46002102 */  mul.s      $ft0, $ft0, $fv0
    /* 13C10 8005F630 00000000 */  nop
    /* 13C14 8005F634 46003182 */  mul.s      $ft1, $ft1, $fv0
    /* 13C18 8005F638 00008821 */  addu       $s1, $zero, $zero
    /* 13C1C 8005F63C 3C038018 */  lui        $v1, %hi(D_80181588)
    /* 13C20 8005F640 24621588 */  addiu      $v0, $v1, %lo(D_80181588)
    /* 13C24 8005F644 46005002 */  mul.s      $fv0, $ft3, $fv0
    /* 13C28 8005F648 00408021 */  addu       $s0, $v0, $zero
    /* 13C2C 8005F64C 4600130D */  trunc.w.s  $fa0, $fv1
    /* 13C30 8005F650 E46C1588 */  swc1       $fa0, %lo(D_80181588)($v1)
    /* 13C34 8005F654 4600230D */  trunc.w.s  $fa0, $ft0
    /* 13C38 8005F658 E60C0004 */  swc1       $fa0, 0x4($s0)
    /* 13C3C 8005F65C 4600330D */  trunc.w.s  $fa0, $ft1
    /* 13C40 8005F660 E60C0008 */  swc1       $fa0, 0x8($s0)
    /* 13C44 8005F664 4600030D */  trunc.w.s  $fa0, $fv0
    /* 13C48 8005F668 E60C000C */  swc1       $fa0, 0xC($s0)
    /* 13C4C 8005F66C AFA00010 */  sw         $zero, 0x10($sp)
  .L8005F670:
    /* 13C50 8005F670 8E040010 */  lw         $a0, 0x10($s0)
    /* 13C54 8005F674 8E060000 */  lw         $a2, 0x0($s0)
    /* 13C58 8005F678 26100004 */  addiu      $s0, $s0, 0x4
    /* 13C5C 8005F67C 26310001 */  addiu      $s1, $s1, 0x1
    /* 13C60 8005F680 4405A000 */  mfc1       $a1, $fs0
    /* 13C64 8005F684 0C017364 */  jal        func_8005CD90
    /* 13C68 8005F688 02403821 */   addu      $a3, $s2, $zero
    /* 13C6C 8005F68C 2A220004 */  slti       $v0, $s1, 0x4
    /* 13C70 8005F690 5440FFF7 */  bnel       $v0, $zero, .L8005F670
    /* 13C74 8005F694 AFA00010 */   sw        $zero, 0x10($sp)
    /* 13C78 8005F698 8FBF0024 */  lw         $ra, 0x24($sp)
    /* 13C7C 8005F69C 8FB20020 */  lw         $s2, 0x20($sp)
    /* 13C80 8005F6A0 8FB1001C */  lw         $s1, 0x1C($sp)
    /* 13C84 8005F6A4 8FB00018 */  lw         $s0, 0x18($sp)
    /* 13C88 8005F6A8 D7B40028 */  ldc1       $fs0, 0x28($sp)
    /* 13C8C 8005F6AC 03E00008 */  jr         $ra
    /* 13C90 8005F6B0 27BD0030 */   addiu     $sp, $sp, 0x30
endlabel func_8005F5B0

nonmatching func_8005F6B4, 0x4

glabel func_8005F6B4
    /* 13C94 8005F6B4 80807C83 */  lb         $zero, 0x7C83($a0)
endlabel func_8005F6B4
