.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_8007B4C0, 0x3C

glabel func_8007B4C0
    /* 2FAA0 8007B4C0 27BDFFA8 */  addiu      $sp, $sp, -0x58
    /* 2FAA4 8007B4C4 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 2FAA8 8007B4C8 AFA40058 */  sw         $a0, 0x58($sp)
    /* 2FAAC 8007B4CC 44056000 */  mfc1       $a1, $fa0
    /* 2FAB0 8007B4D0 44067000 */  mfc1       $a2, $fa1
    /* 2FAB4 8007B4D4 44078000 */  mfc1       $a3, $ft4
    /* 2FAB8 8007B4D8 0C01ECDA */  jal        func_8007B368
    /* 2FABC 8007B4DC 27A40018 */   addiu     $a0, $sp, 0x18
    /* 2FAC0 8007B4E0 27A40018 */  addiu      $a0, $sp, 0x18
    /* 2FAC4 8007B4E4 0C01E9D6 */  jal        func_8007A758
    /* 2FAC8 8007B4E8 8FA50058 */   lw        $a1, 0x58($sp)
    /* 2FACC 8007B4EC 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 2FAD0 8007B4F0 27BD0058 */  addiu      $sp, $sp, 0x58
    /* 2FAD4 8007B4F4 03E00008 */  jr         $ra
    /* 2FAD8 8007B4F8 00000000 */   nop
endlabel func_8007B4C0
    /* 2FADC 8007B4FC 00000000 */  nop
    /* 2FAE0 8007B500 00000000 */  nop
    /* 2FAE4 8007B504 00000000 */  nop
