.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */


glabel func_80082F30
    /* 37510 80082F30 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 37514 80082F34 AFA5001C */  sw         $a1, 0x1C($sp)
    /* 37518 80082F38 AFA60020 */  sw         $a2, 0x20($sp)
    /* 3751C 80082F3C AFBF0014 */  sw         $ra, 0x14($sp)
    /* 37520 80082F40 3C068008 */  lui        $a2, %hi(func_80084188)
    /* 37524 80082F44 3C058008 */  lui        $a1, %hi(func_800841B8)
    /* 37528 80082F48 24A541B8 */  addiu      $a1, $a1, %lo(func_800841B8)
    /* 3752C 80082F4C 24C64188 */  addiu      $a2, $a2, %lo(func_80084188)
    /* 37530 80082F50 AFA40018 */  sw         $a0, 0x18($sp)
    /* 37534 80082F54 0C0213BE */  jal        func_80084EF8
    /* 37538 80082F58 24070006 */   addiu     $a3, $zero, 0x6
    /* 3753C 80082F5C 8FA40018 */  lw         $a0, 0x18($sp)
    /* 37540 80082F60 AC800014 */  sw         $zero, 0x14($a0)
    /* 37544 80082F64 8FAE0020 */  lw         $t6, 0x20($sp)
    /* 37548 80082F68 AC8E0018 */  sw         $t6, 0x18($a0)
    /* 3754C 80082F6C 8FAF001C */  lw         $t7, 0x1C($sp)
    /* 37550 80082F70 AC8F001C */  sw         $t7, 0x1C($a0)
    /* 37554 80082F74 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 37558 80082F78 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 3755C 80082F7C 03E00008 */  jr         $ra
    /* 37560 80082F80 00000000 */   nop
endlabel func_80082F30
