.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_80086C20, 0x24

glabel func_80086C20
    /* 3B200 80086C20 27BDFFF8 */  addiu      $sp, $sp, -0x8
    /* 3B204 80086C24 308F001C */  andi       $t7, $a0, 0x1C
    /* 3B208 80086C28 11E00003 */  beqz       $t7, .L80086C38
    /* 3B20C 80086C2C 00000000 */   nop
    /* 3B210 80086C30 10000002 */  b          .L80086C3C
    /* 3B214 80086C34 24020001 */   addiu     $v0, $zero, 0x1
  .L80086C38:
    /* 3B218 80086C38 00001025 */  or         $v0, $zero, $zero
  .L80086C3C:
    /* 3B21C 80086C3C 03E00008 */  jr         $ra
    /* 3B220 80086C40 27BD0008 */   addiu     $sp, $sp, 0x8
endlabel func_80086C20
    /* 3B224 80086C44 00000000 */  nop

nonmatching func_80086C48, 0xC

glabel func_80086C48
    /* 3B228 80086C48 3C0EA404 */  lui        $t6, %hi(D_A4040010)
    /* 3B22C 80086C4C 03E00008 */  jr         $ra
    /* 3B230 80086C50 ADC40010 */   sw        $a0, %lo(D_A4040010)($t6)
endlabel func_80086C48
    /* 3B234 80086C54 00000000 */  nop

nonmatching func_80086C58, 0x8

glabel func_80086C58
    /* 3B238 80086C58 3C0EA404 */  lui        $t6, %hi(D_A4040010)
    /* 3B23C 80086C5C 8DC50010 */  lw         $a1, %lo(D_A4040010)($t6)
endlabel func_80086C58
