.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */


glabel func_80082818
    /* 36DF8 80082818 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 36DFC 8008281C AFBF0014 */  sw         $ra, 0x14($sp)
    /* 36E00 80082820 AFA40018 */  sw         $a0, 0x18($sp)
    /* 36E04 80082824 AFA5001C */  sw         $a1, 0x1C($sp)
    /* 36E08 80082828 0C01F686 */  jal        func_8007DA18
    /* 36E0C 8008282C 00A02025 */   or        $a0, $a1, $zero
    /* 36E10 80082830 8FA50018 */  lw         $a1, 0x18($sp)
    /* 36E14 80082834 8FA4001C */  lw         $a0, 0x1C($sp)
    /* 36E18 80082838 0C01F692 */  jal        func_8007DA48
    /* 36E1C 8008283C 24A50014 */   addiu     $a1, $a1, 0x14
    /* 36E20 80082840 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 36E24 80082844 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 36E28 80082848 03E00008 */  jr         $ra
    /* 36E2C 8008284C 00000000 */   nop
endlabel func_80082818
