.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_8008E4A8, 0x8

glabel func_8008E4A8
    /* 42A88 8008E4A8 3C0E8009 */  lui        $t6, %hi(D_800964B0)
    /* 42A8C 8008E4AC 8DCE64B0 */  lw         $t6, %lo(D_800964B0)($t6)
endlabel func_8008E4A8
