.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_8007ABD8, 0x60

glabel func_8007ABD8
    /* 2F1B8 8007ABD8 27BDFF98 */  addiu      $sp, $sp, -0x68
    /* 2F1BC 8007ABDC AFA5006C */  sw         $a1, 0x6C($sp)
    /* 2F1C0 8007ABE0 00802825 */  or         $a1, $a0, $zero
    /* 2F1C4 8007ABE4 AFBF0024 */  sw         $ra, 0x24($sp)
    /* 2F1C8 8007ABE8 AFA40068 */  sw         $a0, 0x68($sp)
    /* 2F1CC 8007ABEC AFA60070 */  sw         $a2, 0x70($sp)
    /* 2F1D0 8007ABF0 AFA70074 */  sw         $a3, 0x74($sp)
    /* 2F1D4 8007ABF4 0C01EA44 */  jal        func_8007A910
    /* 2F1D8 8007ABF8 27A40028 */   addiu     $a0, $sp, 0x28
    /* 2F1DC 8007ABFC 8FAE0078 */  lw         $t6, 0x78($sp)
    /* 2F1E0 8007AC00 8FAF007C */  lw         $t7, 0x7C($sp)
    /* 2F1E4 8007AC04 8FB80080 */  lw         $t8, 0x80($sp)
    /* 2F1E8 8007AC08 27A40028 */  addiu      $a0, $sp, 0x28
    /* 2F1EC 8007AC0C 8FA5006C */  lw         $a1, 0x6C($sp)
    /* 2F1F0 8007AC10 8FA60070 */  lw         $a2, 0x70($sp)
    /* 2F1F4 8007AC14 8FA70074 */  lw         $a3, 0x74($sp)
    /* 2F1F8 8007AC18 AFAE0010 */  sw         $t6, 0x10($sp)
    /* 2F1FC 8007AC1C AFAF0014 */  sw         $t7, 0x14($sp)
    /* 2F200 8007AC20 0C01EA72 */  jal        func_8007A9C8
    /* 2F204 8007AC24 AFB80018 */   sw        $t8, 0x18($sp)
    /* 2F208 8007AC28 8FBF0024 */  lw         $ra, 0x24($sp)
    /* 2F20C 8007AC2C 27BD0068 */  addiu      $sp, $sp, 0x68
    /* 2F210 8007AC30 03E00008 */  jr         $ra
    /* 2F214 8007AC34 00000000 */   nop
endlabel func_8007ABD8
