.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */


glabel func_8007B7D8
    /* 2FDB8 8007B7D8 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 2FDBC 8007B7DC AFBF0014 */  sw         $ra, 0x14($sp)
    /* 2FDC0 8007B7E0 AFA5001C */  sw         $a1, 0x1C($sp)
    /* 2FDC4 8007B7E4 AFA60020 */  sw         $a2, 0x20($sp)
    /* 2FDC8 8007B7E8 AFA70024 */  sw         $a3, 0x24($sp)
    /* 2FDCC 8007B7EC 0C01EA16 */  jal        func_8007A858
    /* 2FDD0 8007B7F0 AFA40018 */   sw        $a0, 0x18($sp)
    /* 2FDD4 8007B7F4 8FA40018 */  lw         $a0, 0x18($sp)
    /* 2FDD8 8007B7F8 C7A4001C */  lwc1       $ft0, 0x1C($sp)
    /* 2FDDC 8007B7FC E4840030 */  swc1       $ft0, 0x30($a0)
    /* 2FDE0 8007B800 C7A60020 */  lwc1       $ft1, 0x20($sp)
    /* 2FDE4 8007B804 E4860034 */  swc1       $ft1, 0x34($a0)
    /* 2FDE8 8007B808 C7A80024 */  lwc1       $ft2, 0x24($sp)
    /* 2FDEC 8007B80C E4880038 */  swc1       $ft2, 0x38($a0)
    /* 2FDF0 8007B810 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 2FDF4 8007B814 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 2FDF8 8007B818 03E00008 */  jr         $ra
    /* 2FDFC 8007B81C 00000000 */   nop
endlabel func_8007B7D8
