.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_80087D28, 0x50

glabel func_80087D28
    /* 3C308 80087D28 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 3C30C 80087D2C AFBF0014 */  sw         $ra, 0x14($sp)
    /* 3C310 80087D30 240E0001 */  addiu      $t6, $zero, 0x1
    /* 3C314 80087D34 3C018009 */  lui        $at, %hi(D_80096370)
    /* 3C318 80087D38 3C048019 */  lui        $a0, %hi(D_8018AD10)
    /* 3C31C 80087D3C 3C058019 */  lui        $a1, %hi(D_8018AD08)
    /* 3C320 80087D40 AC2E6370 */  sw         $t6, %lo(D_80096370)($at)
    /* 3C324 80087D44 24A5AD08 */  addiu      $a1, $a1, %lo(D_8018AD08)
    /* 3C328 80087D48 2484AD10 */  addiu      $a0, $a0, %lo(D_8018AD10)
    /* 3C32C 80087D4C 0C01EF36 */  jal        func_8007BCD8
    /* 3C330 80087D50 24060001 */   addiu     $a2, $zero, 0x1
    /* 3C334 80087D54 3C048019 */  lui        $a0, %hi(D_8018AD10)
    /* 3C338 80087D58 2484AD10 */  addiu      $a0, $a0, %lo(D_8018AD10)
    /* 3C33C 80087D5C 00002825 */  or         $a1, $zero, $zero
    /* 3C340 80087D60 0C01F392 */  jal        func_8007CE48
    /* 3C344 80087D64 00003025 */   or        $a2, $zero, $zero
    /* 3C348 80087D68 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 3C34C 80087D6C 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 3C350 80087D70 03E00008 */  jr         $ra
    /* 3C354 80087D74 00000000 */   nop
endlabel func_80087D28

nonmatching func_80087D78, 0x8

glabel func_80087D78
    /* 3C358 80087D78 3C0E8009 */  lui        $t6, %hi(D_80096370)
    /* 3C35C 80087D7C 8DCE6370 */  lw         $t6, %lo(D_80096370)($t6)
endlabel func_80087D78
