.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_80082850, 0x60

glabel func_80082850
    /* 36E30 80082850 27BDFFD8 */  addiu      $sp, $sp, -0x28
    /* 36E34 80082854 AFBF0024 */  sw         $ra, 0x24($sp)
    /* 36E38 80082858 AFB20020 */  sw         $s2, 0x20($sp)
    /* 36E3C 8008285C AFB1001C */  sw         $s1, 0x1C($sp)
    /* 36E40 80082860 AFB00018 */  sw         $s0, 0x18($sp)
    /* 36E44 80082864 8C900014 */  lw         $s0, 0x14($a0)
    /* 36E48 80082868 00808825 */  or         $s1, $a0, $zero
    /* 36E4C 8008286C 24920004 */  addiu      $s2, $a0, 0x4
    /* 36E50 80082870 5200000A */  beql       $s0, $zero, .L8008289C
    /* 36E54 80082874 8FBF0024 */   lw        $ra, 0x24($sp)
  .L80082878:
    /* 36E58 80082878 0C01F686 */  jal        func_8007DA18
    /* 36E5C 8008287C 02002025 */   or        $a0, $s0, $zero
    /* 36E60 80082880 02002025 */  or         $a0, $s0, $zero
    /* 36E64 80082884 0C01F692 */  jal        func_8007DA48
    /* 36E68 80082888 02402825 */   or        $a1, $s2, $zero
    /* 36E6C 8008288C 8E300014 */  lw         $s0, 0x14($s1)
    /* 36E70 80082890 1600FFF9 */  bnez       $s0, .L80082878
    /* 36E74 80082894 00000000 */   nop
    /* 36E78 80082898 8FBF0024 */  lw         $ra, 0x24($sp)
  .L8008289C:
    /* 36E7C 8008289C 8FB00018 */  lw         $s0, 0x18($sp)
    /* 36E80 800828A0 8FB1001C */  lw         $s1, 0x1C($sp)
    /* 36E84 800828A4 8FB20020 */  lw         $s2, 0x20($sp)
    /* 36E88 800828A8 03E00008 */  jr         $ra
    /* 36E8C 800828AC 27BD0028 */   addiu     $sp, $sp, 0x28
endlabel func_80082850

nonmatching func_800828B0, 0x18

glabel func_800828B0
    /* 36E90 800828B0 3C028009 */  lui        $v0, %hi(D_800952D0)
    /* 36E94 800828B4 8C4252D0 */  lw         $v0, %lo(D_800952D0)($v0)
    /* 36E98 800828B8 8C4E002C */  lw         $t6, 0x2C($v0)
    /* 36E9C 800828BC AC8E0000 */  sw         $t6, 0x0($a0)
    /* 36EA0 800828C0 03E00008 */  jr         $ra
    /* 36EA4 800828C4 AC44002C */   sw        $a0, 0x2C($v0)
endlabel func_800828B0

nonmatching func_800828C8, 0x30

glabel func_800828C8
    /* 36EA8 800828C8 3C028009 */  lui        $v0, %hi(D_800952D0)
    /* 36EAC 800828CC 8C4252D0 */  lw         $v0, %lo(D_800952D0)($v0)
    /* 36EB0 800828D0 00001825 */  or         $v1, $zero, $zero
    /* 36EB4 800828D4 8C44002C */  lw         $a0, 0x2C($v0)
    /* 36EB8 800828D8 10800005 */  beqz       $a0, .L800828F0
    /* 36EBC 800828DC 00000000 */   nop
    /* 36EC0 800828E0 8C8E0000 */  lw         $t6, 0x0($a0)
    /* 36EC4 800828E4 00801825 */  or         $v1, $a0, $zero
    /* 36EC8 800828E8 AC4E002C */  sw         $t6, 0x2C($v0)
    /* 36ECC 800828EC AC800000 */  sw         $zero, 0x0($a0)
  .L800828F0:
    /* 36ED0 800828F0 03E00008 */  jr         $ra
    /* 36ED4 800828F4 00601025 */   or        $v0, $v1, $zero
endlabel func_800828C8

nonmatching func_800828F8, 0x8

glabel func_800828F8
    /* 36ED8 800828F8 03E00008 */  jr         $ra
    /* 36EDC 800828FC 00000000 */   nop
endlabel func_800828F8
