.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_8007B568, 0x3C

glabel func_8007B568
    /* 2FB48 8007B568 27BDFFA8 */  addiu      $sp, $sp, -0x58
    /* 2FB4C 8007B56C AFBF0014 */  sw         $ra, 0x14($sp)
    /* 2FB50 8007B570 AFA40058 */  sw         $a0, 0x58($sp)
    /* 2FB54 8007B574 44056000 */  mfc1       $a1, $fa0
    /* 2FB58 8007B578 44067000 */  mfc1       $a2, $fa1
    /* 2FB5C 8007B57C 44078000 */  mfc1       $a3, $ft4
    /* 2FB60 8007B580 0C01ED42 */  jal        func_8007B508
    /* 2FB64 8007B584 27A40018 */   addiu     $a0, $sp, 0x18
    /* 2FB68 8007B588 27A40018 */  addiu      $a0, $sp, 0x18
    /* 2FB6C 8007B58C 0C01E9D6 */  jal        func_8007A758
    /* 2FB70 8007B590 8FA50058 */   lw        $a1, 0x58($sp)
    /* 2FB74 8007B594 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 2FB78 8007B598 27BD0058 */  addiu      $sp, $sp, 0x58
    /* 2FB7C 8007B59C 03E00008 */  jr         $ra
    /* 2FB80 8007B5A0 00000000 */   nop
endlabel func_8007B568
    /* 2FB84 8007B5A4 00000000 */  nop

nonmatching func_8007B5A8, 0x1C0

glabel func_8007B5A8
    /* 2FB88 8007B5A8 E7AC0000 */  swc1       $fa0, 0x0($sp)
    /* 2FB8C 8007B5AC 8FA20000 */  lw         $v0, 0x0($sp)
    /* 2FB90 8007B5B0 C7A40000 */  lwc1       $ft0, 0x0($sp)
    /* 2FB94 8007B5B4 00021D83 */  sra        $v1, $v0, 22
    /* 2FB98 8007B5B8 306E01FF */  andi       $t6, $v1, 0x1FF
    /* 2FB9C 8007B5BC 29C100FF */  slti       $at, $t6, 0xFF
    /* 2FBA0 8007B5C0 10200019 */  beqz       $at, .L8007B628
    /* 2FBA4 8007B5C4 01C01825 */   or        $v1, $t6, $zero
    /* 2FBA8 8007B5C8 29C100E6 */  slti       $at, $t6, 0xE6
    /* 2FBAC 8007B5CC 14200014 */  bnez       $at, .L8007B620
    /* 2FBB0 8007B5D0 460020A1 */   cvt.d.s   $fv1, $ft0
    /* 2FBB4 8007B5D4 46221302 */  mul.d      $fa0, $fv1, $fv1
    /* 2FBB8 8007B5D8 3C038005 */  lui        $v1, %hi(D_8004C898)
    /* 2FBBC 8007B5DC 2463C898 */  addiu      $v1, $v1, %lo(D_8004C898)
    /* 2FBC0 8007B5E0 D4660020 */  ldc1       $ft1, 0x20($v1)
    /* 2FBC4 8007B5E4 D46A0018 */  ldc1       $ft3, 0x18($v1)
    /* 2FBC8 8007B5E8 D4640010 */  ldc1       $ft0, 0x10($v1)
    /* 2FBCC 8007B5EC 462C3202 */  mul.d      $ft2, $ft1, $fa0
    /* 2FBD0 8007B5F0 462A4400 */  add.d      $ft4, $ft2, $ft3
    /* 2FBD4 8007B5F4 D46A0008 */  ldc1       $ft3, 0x8($v1)
    /* 2FBD8 8007B5F8 462C8482 */  mul.d      $ft5, $ft4, $fa0
    /* 2FBDC 8007B5FC 46249180 */  add.d      $ft1, $ft5, $ft0
    /* 2FBE0 8007B600 462C3202 */  mul.d      $ft2, $ft1, $fa0
    /* 2FBE4 8007B604 46285380 */  add.d      $fa1, $ft3, $ft2
    /* 2FBE8 8007B608 462C1402 */  mul.d      $ft4, $fv1, $fa0
    /* 2FBEC 8007B60C 00000000 */  nop
    /* 2FBF0 8007B610 462E8482 */  mul.d      $ft5, $ft4, $fa1
    /* 2FBF4 8007B614 46229100 */  add.d      $ft0, $ft5, $fv1
    /* 2FBF8 8007B618 03E00008 */  jr         $ra
    /* 2FBFC 8007B61C 46202020 */   cvt.s.d   $fv0, $ft0
  .L8007B620:
    /* 2FC00 8007B620 03E00008 */  jr         $ra
    /* 2FC04 8007B624 C7A00000 */   lwc1      $fv0, 0x0($sp)
  .L8007B628:
    /* 2FC08 8007B628 28610136 */  slti       $at, $v1, 0x136
    /* 2FC0C 8007B62C 10200044 */  beqz       $at, .L8007B740
    /* 2FC10 8007B630 C7A40000 */   lwc1      $ft0, 0x0($sp)
    /* 2FC14 8007B634 C7A60000 */  lwc1       $ft1, 0x0($sp)
    /* 2FC18 8007B638 3C018005 */  lui        $at, %hi(D_8004C8C0)
    /* 2FC1C 8007B63C D42AC8C0 */  ldc1       $ft3, %lo(D_8004C8C0)($at)
    /* 2FC20 8007B640 460030A1 */  cvt.d.s    $fv1, $ft1
    /* 2FC24 8007B644 44804800 */  mtc1       $zero, $ft2f
    /* 2FC28 8007B648 462A1002 */  mul.d      $fv0, $fv1, $ft3
    /* 2FC2C 8007B64C 44804000 */  mtc1       $zero, $ft2
    /* 2FC30 8007B650 3C013FE0 */  lui        $at, (0x3FE00000 >> 16)
    /* 2FC34 8007B654 4620403E */  c.le.d     $ft2, $fv0
    /* 2FC38 8007B658 00000000 */  nop
    /* 2FC3C 8007B65C 4502000B */  bc1fl      .L8007B68C
    /* 2FC40 8007B660 44813800 */   mtc1      $at, $ft1f
    /* 2FC44 8007B664 3C013FE0 */  lui        $at, (0x3FE00000 >> 16)
    /* 2FC48 8007B668 44818800 */  mtc1       $at, $ft4f
    /* 2FC4C 8007B66C 44808000 */  mtc1       $zero, $ft4
    /* 2FC50 8007B670 00000000 */  nop
    /* 2FC54 8007B674 46300480 */  add.d      $ft5, $fv0, $ft4
    /* 2FC58 8007B678 4620910D */  trunc.w.d  $ft0, $ft5
    /* 2FC5C 8007B67C 44022000 */  mfc1       $v0, $ft0
    /* 2FC60 8007B680 10000009 */  b          .L8007B6A8
    /* 2FC64 8007B684 44828000 */   mtc1      $v0, $ft4
    /* 2FC68 8007B688 44813800 */  mtc1       $at, $ft1f
  .L8007B68C:
    /* 2FC6C 8007B68C 44803000 */  mtc1       $zero, $ft1
    /* 2FC70 8007B690 00000000 */  nop
    /* 2FC74 8007B694 46260281 */  sub.d      $ft3, $fv0, $ft1
    /* 2FC78 8007B698 4620520D */  trunc.w.d  $ft2, $ft3
    /* 2FC7C 8007B69C 44024000 */  mfc1       $v0, $ft2
    /* 2FC80 8007B6A0 00000000 */  nop
    /* 2FC84 8007B6A4 44828000 */  mtc1       $v0, $ft4
  .L8007B6A8:
    /* 2FC88 8007B6A8 3C018005 */  lui        $at, %hi(D_8004C8C8)
    /* 2FC8C 8007B6AC D432C8C8 */  ldc1       $ft5, %lo(D_8004C8C8)($at)
    /* 2FC90 8007B6B0 46808021 */  cvt.d.w    $fv0, $ft4
    /* 2FC94 8007B6B4 3C018005 */  lui        $at, %hi(D_8004C8D0)
    /* 2FC98 8007B6B8 D426C8D0 */  ldc1       $ft1, %lo(D_8004C8D0)($at)
    /* 2FC9C 8007B6BC 3C038005 */  lui        $v1, %hi(D_8004C898)
    /* 2FCA0 8007B6C0 2463C898 */  addiu      $v1, $v1, %lo(D_8004C898)
    /* 2FCA4 8007B6C4 46320102 */  mul.d      $ft0, $fv0, $ft5
    /* 2FCA8 8007B6C8 D4680020 */  ldc1       $ft2, 0x20($v1)
    /* 2FCAC 8007B6CC D4720018 */  ldc1       $ft5, 0x18($v1)
    /* 2FCB0 8007B6D0 30590001 */  andi       $t9, $v0, 0x1
    /* 2FCB4 8007B6D4 46260282 */  mul.d      $ft3, $fv0, $ft1
    /* 2FCB8 8007B6D8 46241081 */  sub.d      $fv1, $fv1, $ft0
    /* 2FCBC 8007B6DC 462A1081 */  sub.d      $fv1, $fv1, $ft3
    /* 2FCC0 8007B6E0 D46A0010 */  ldc1       $ft3, 0x10($v1)
    /* 2FCC4 8007B6E4 46221302 */  mul.d      $fa0, $fv1, $fv1
    /* 2FCC8 8007B6E8 00000000 */  nop
    /* 2FCCC 8007B6EC 462C4402 */  mul.d      $ft4, $ft2, $fa0
    /* 2FCD0 8007B6F0 46328100 */  add.d      $ft0, $ft4, $ft5
    /* 2FCD4 8007B6F4 D4720008 */  ldc1       $ft5, 0x8($v1)
    /* 2FCD8 8007B6F8 462C2182 */  mul.d      $ft1, $ft0, $fa0
    /* 2FCDC 8007B6FC 462A3200 */  add.d      $ft2, $ft1, $ft3
    /* 2FCE0 8007B700 462C4402 */  mul.d      $ft4, $ft2, $fa0
    /* 2FCE4 8007B704 17200007 */  bnez       $t9, .L8007B724
    /* 2FCE8 8007B708 46309380 */   add.d     $fa1, $ft5, $ft4
    /* 2FCEC 8007B70C 462C1102 */  mul.d      $ft0, $fv1, $fa0
    /* 2FCF0 8007B710 00000000 */  nop
    /* 2FCF4 8007B714 462E2182 */  mul.d      $ft1, $ft0, $fa1
    /* 2FCF8 8007B718 46223280 */  add.d      $ft3, $ft1, $fv1
    /* 2FCFC 8007B71C 03E00008 */  jr         $ra
    /* 2FD00 8007B720 46205020 */   cvt.s.d   $fv0, $ft3
  .L8007B724:
    /* 2FD04 8007B724 462C1202 */  mul.d      $ft2, $fv1, $fa0
    /* 2FD08 8007B728 00000000 */  nop
    /* 2FD0C 8007B72C 462E4482 */  mul.d      $ft5, $ft2, $fa1
    /* 2FD10 8007B730 46229400 */  add.d      $ft4, $ft5, $fv1
    /* 2FD14 8007B734 46208020 */  cvt.s.d    $fv0, $ft4
    /* 2FD18 8007B738 03E00008 */  jr         $ra
    /* 2FD1C 8007B73C 46000007 */   neg.s     $fv0, $fv0
  .L8007B740:
    /* 2FD20 8007B740 46042032 */  c.eq.s     $ft0, $ft0
    /* 2FD24 8007B744 3C018005 */  lui        $at, %hi(D_8004C8D8)
    /* 2FD28 8007B748 45010004 */  bc1t       .L8007B75C
    /* 2FD2C 8007B74C 00000000 */   nop
    /* 2FD30 8007B750 3C018005 */  lui        $at, %hi(D_8004C848)
    /* 2FD34 8007B754 03E00008 */  jr         $ra
    /* 2FD38 8007B758 C420C848 */   lwc1      $fv0, %lo(D_8004C848)($at)
  .L8007B75C:
    /* 2FD3C 8007B75C C420C8D8 */  lwc1       $fv0, %lo(D_8004C8D8)($at)
    /* 2FD40 8007B760 03E00008 */  jr         $ra
    /* 2FD44 8007B764 00000000 */   nop
endlabel func_8007B5A8

nonmatching func_8007B768, 0x70

glabel func_8007B768
    /* 2FD48 8007B768 308EFFFF */  andi       $t6, $a0, 0xFFFF
    /* 2FD4C 8007B76C 000E7902 */  srl        $t7, $t6, 4
    /* 2FD50 8007B770 31F8FFFF */  andi       $t8, $t7, 0xFFFF
    /* 2FD54 8007B774 33190400 */  andi       $t9, $t8, 0x400
    /* 2FD58 8007B778 AFA40000 */  sw         $a0, 0x0($sp)
    /* 2FD5C 8007B77C 13200008 */  beqz       $t9, .L8007B7A0
    /* 2FD60 8007B780 03001025 */   or        $v0, $t8, $zero
    /* 2FD64 8007B784 330803FF */  andi       $t0, $t8, 0x3FF
    /* 2FD68 8007B788 00084840 */  sll        $t1, $t0, 1
    /* 2FD6C 8007B78C 00095023 */  negu       $t2, $t1
    /* 2FD70 8007B790 3C038009 */  lui        $v1, %hi(D_8009525E)
    /* 2FD74 8007B794 006A1821 */  addu       $v1, $v1, $t2
    /* 2FD78 8007B798 10000006 */  b          .L8007B7B4
    /* 2FD7C 8007B79C 8463525E */   lh        $v1, %lo(D_8009525E)($v1)
  .L8007B7A0:
    /* 2FD80 8007B7A0 304B03FF */  andi       $t3, $v0, 0x3FF
    /* 2FD84 8007B7A4 000B6040 */  sll        $t4, $t3, 1
    /* 2FD88 8007B7A8 3C038009 */  lui        $v1, %hi(D_80094A60)
    /* 2FD8C 8007B7AC 006C1821 */  addu       $v1, $v1, $t4
    /* 2FD90 8007B7B0 84634A60 */  lh         $v1, %lo(D_80094A60)($v1)
  .L8007B7B4:
    /* 2FD94 8007B7B4 304D0800 */  andi       $t5, $v0, 0x800
    /* 2FD98 8007B7B8 11A00005 */  beqz       $t5, .L8007B7D0
    /* 2FD9C 8007B7BC 00601025 */   or        $v0, $v1, $zero
    /* 2FDA0 8007B7C0 00031023 */  negu       $v0, $v1
    /* 2FDA4 8007B7C4 00027400 */  sll        $t6, $v0, 16
    /* 2FDA8 8007B7C8 03E00008 */  jr         $ra
    /* 2FDAC 8007B7CC 000E1403 */   sra       $v0, $t6, 16
  .L8007B7D0:
    /* 2FDB0 8007B7D0 03E00008 */  jr         $ra
    /* 2FDB4 8007B7D4 00000000 */   nop
endlabel func_8007B768
