.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_8004D138, 0x90

glabel func_8004D138
    /* 1718 8004D138 27BDFFA8 */  addiu      $sp, $sp, -0x58
    /* 171C 8004D13C AFB3004C */  sw         $s3, 0x4C($sp)
    /* 1720 8004D140 00809821 */  addu       $s3, $a0, $zero
    /* 1724 8004D144 AFB10044 */  sw         $s1, 0x44($sp)
    /* 1728 8004D148 00A08821 */  addu       $s1, $a1, $zero
    /* 172C 8004D14C AFB20048 */  sw         $s2, 0x48($sp)
    /* 1730 8004D150 00C09021 */  addu       $s2, $a2, $zero
    /* 1734 8004D154 02202021 */  addu       $a0, $s1, $zero
    /* 1738 8004D158 02402821 */  addu       $a1, $s2, $zero
    /* 173C 8004D15C AFBF0050 */  sw         $ra, 0x50($sp)
    /* 1740 8004D160 0C01EF0A */  jal        func_8007BC28
    /* 1744 8004D164 AFB00040 */   sw        $s0, 0x40($sp)
    /* 1748 8004D168 27A40020 */  addiu      $a0, $sp, 0x20
    /* 174C 8004D16C 00002821 */  addu       $a1, $zero, $zero
    /* 1750 8004D170 00A03021 */  addu       $a2, $a1, $zero
    /* 1754 8004D174 3C108017 */  lui        $s0, %hi(D_8016DF70)
    /* 1758 8004D178 2610DF70 */  addiu      $s0, $s0, %lo(D_8016DF70)
    /* 175C 8004D17C 02603821 */  addu       $a3, $s3, $zero
    /* 1760 8004D180 AFB10010 */  sw         $s1, 0x10($sp)
    /* 1764 8004D184 AFB20014 */  sw         $s2, 0x14($sp)
    /* 1768 8004D188 0C023946 */  jal        func_8008E518
    /* 176C 8004D18C AFB00018 */   sw        $s0, 0x18($sp)
    /* 1770 8004D190 02002021 */  addu       $a0, $s0, $zero
    /* 1774 8004D194 27A50038 */  addiu      $a1, $sp, 0x38
    /* 1778 8004D198 0C01F342 */  jal        func_8007CD08
    /* 177C 8004D19C 24060001 */   addiu     $a2, $zero, 0x1
    /* 1780 8004D1A0 02202021 */  addu       $a0, $s1, $zero
    /* 1784 8004D1A4 0C01EEA6 */  jal        func_8007BA98
    /* 1788 8004D1A8 02402821 */   addu      $a1, $s2, $zero
    /* 178C 8004D1AC 8FBF0050 */  lw         $ra, 0x50($sp)
    /* 1790 8004D1B0 8FB3004C */  lw         $s3, 0x4C($sp)
    /* 1794 8004D1B4 8FB20048 */  lw         $s2, 0x48($sp)
    /* 1798 8004D1B8 8FB10044 */  lw         $s1, 0x44($sp)
    /* 179C 8004D1BC 8FB00040 */  lw         $s0, 0x40($sp)
    /* 17A0 8004D1C0 03E00008 */  jr         $ra
    /* 17A4 8004D1C4 27BD0058 */   addiu     $sp, $sp, 0x58
endlabel func_8004D138
