.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_8008B088, 0x1B4

glabel func_8008B088
    /* 3F668 8008B088 27BDFFB8 */  addiu      $sp, $sp, -0x48
    /* 3F66C 8008B08C AFBF0014 */  sw         $ra, 0x14($sp)
    /* 3F670 8008B090 AFA40048 */  sw         $a0, 0x48($sp)
    /* 3F674 8008B094 AFA5004C */  sw         $a1, 0x4C($sp)
    /* 3F678 8008B098 AFA60050 */  sw         $a2, 0x50($sp)
    /* 3F67C 8008B09C AFA70054 */  sw         $a3, 0x54($sp)
    /* 3F680 8008B0A0 AFA0001C */  sw         $zero, 0x1C($sp)
    /* 3F684 8008B0A4 0C02269A */  jal        func_80089A68
    /* 3F688 8008B0A8 8FA40048 */   lw        $a0, 0x48($sp)
    /* 3F68C 8008B0AC 24010002 */  addiu      $at, $zero, 0x2
    /* 3F690 8008B0B0 14410003 */  bne        $v0, $at, .L8008B0C0
    /* 3F694 8008B0B4 00000000 */   nop
    /* 3F698 8008B0B8 1000005C */  b          .L8008B22C
    /* 3F69C 8008B0BC 24020002 */   addiu     $v0, $zero, 0x2
  .L8008B0C0:
    /* 3F6A0 8008B0C0 8FAE0048 */  lw         $t6, 0x48($sp)
    /* 3F6A4 8008B0C4 AFA00044 */  sw         $zero, 0x44($sp)
    /* 3F6A8 8008B0C8 8DCF0050 */  lw         $t7, 0x50($t6)
    /* 3F6AC 8008B0CC 19E00053 */  blez       $t7, .L8008B21C
    /* 3F6B0 8008B0D0 00000000 */   nop
  .L8008B0D4:
    /* 3F6B4 8008B0D4 8FB80048 */  lw         $t8, 0x48($sp)
    /* 3F6B8 8008B0D8 8FA80044 */  lw         $t0, 0x44($sp)
    /* 3F6BC 8008B0DC 27A70020 */  addiu      $a3, $sp, 0x20
    /* 3F6C0 8008B0E0 8F19005C */  lw         $t9, 0x5C($t8)
    /* 3F6C4 8008B0E4 8F040004 */  lw         $a0, 0x4($t8)
    /* 3F6C8 8008B0E8 8F050008 */  lw         $a1, 0x8($t8)
    /* 3F6CC 8008B0EC 0C0227BE */  jal        func_80089EF8
    /* 3F6D0 8008B0F0 03283021 */   addu      $a2, $t9, $t0
    /* 3F6D4 8008B0F4 AFA2001C */  sw         $v0, 0x1C($sp)
    /* 3F6D8 8008B0F8 8FA9001C */  lw         $t1, 0x1C($sp)
    /* 3F6DC 8008B0FC 11200003 */  beqz       $t1, .L8008B10C
    /* 3F6E0 8008B100 00000000 */   nop
    /* 3F6E4 8008B104 10000049 */  b          .L8008B22C
    /* 3F6E8 8008B108 01201025 */   or        $v0, $t1, $zero
  .L8008B10C:
    /* 3F6EC 8008B10C 97AA0024 */  lhu        $t2, 0x24($sp)
    /* 3F6F0 8008B110 97AB004E */  lhu        $t3, 0x4E($sp)
    /* 3F6F4 8008B114 154B0039 */  bne        $t2, $t3, .L8008B1FC
    /* 3F6F8 8008B118 00000000 */   nop
    /* 3F6FC 8008B11C 8FAC0020 */  lw         $t4, 0x20($sp)
    /* 3F700 8008B120 8FAD0050 */  lw         $t5, 0x50($sp)
    /* 3F704 8008B124 158D0035 */  bne        $t4, $t5, .L8008B1FC
    /* 3F708 8008B128 00000000 */   nop
    /* 3F70C 8008B12C 8FAE0054 */  lw         $t6, 0x54($sp)
    /* 3F710 8008B130 AFA00018 */  sw         $zero, 0x18($sp)
    /* 3F714 8008B134 11C00012 */  beqz       $t6, .L8008B180
    /* 3F718 8008B138 00000000 */   nop
    /* 3F71C 8008B13C AFA00040 */  sw         $zero, 0x40($sp)
  .L8008B140:
    /* 3F720 8008B140 8FB80040 */  lw         $t8, 0x40($sp)
    /* 3F724 8008B144 8FAF0054 */  lw         $t7, 0x54($sp)
    /* 3F728 8008B148 03B84821 */  addu       $t1, $sp, $t8
    /* 3F72C 8008B14C 01F8C821 */  addu       $t9, $t7, $t8
    /* 3F730 8008B150 93280000 */  lbu        $t0, 0x0($t9)
    /* 3F734 8008B154 91290030 */  lbu        $t1, 0x30($t1)
    /* 3F738 8008B158 11090004 */  beq        $t0, $t1, .L8008B16C
    /* 3F73C 8008B15C 00000000 */   nop
    /* 3F740 8008B160 240A0001 */  addiu      $t2, $zero, 0x1
    /* 3F744 8008B164 10000006 */  b          .L8008B180
    /* 3F748 8008B168 AFAA0018 */   sw        $t2, 0x18($sp)
  .L8008B16C:
    /* 3F74C 8008B16C 8FAB0040 */  lw         $t3, 0x40($sp)
    /* 3F750 8008B170 256C0001 */  addiu      $t4, $t3, 0x1
    /* 3F754 8008B174 29810010 */  slti       $at, $t4, 0x10
    /* 3F758 8008B178 1420FFF1 */  bnez       $at, .L8008B140
    /* 3F75C 8008B17C AFAC0040 */   sw        $t4, 0x40($sp)
  .L8008B180:
    /* 3F760 8008B180 8FAD0058 */  lw         $t5, 0x58($sp)
    /* 3F764 8008B184 11A00015 */  beqz       $t5, .L8008B1DC
    /* 3F768 8008B188 00000000 */   nop
    /* 3F76C 8008B18C 8FAE0018 */  lw         $t6, 0x18($sp)
    /* 3F770 8008B190 15C00012 */  bnez       $t6, .L8008B1DC
    /* 3F774 8008B194 00000000 */   nop
    /* 3F778 8008B198 AFA00040 */  sw         $zero, 0x40($sp)
  .L8008B19C:
    /* 3F77C 8008B19C 8FB90040 */  lw         $t9, 0x40($sp)
    /* 3F780 8008B1A0 8FAF0058 */  lw         $t7, 0x58($sp)
    /* 3F784 8008B1A4 03B94821 */  addu       $t1, $sp, $t9
    /* 3F788 8008B1A8 01F9C021 */  addu       $t8, $t7, $t9
    /* 3F78C 8008B1AC 93080000 */  lbu        $t0, 0x0($t8)
    /* 3F790 8008B1B0 9129002C */  lbu        $t1, 0x2C($t1)
    /* 3F794 8008B1B4 11090004 */  beq        $t0, $t1, .L8008B1C8
    /* 3F798 8008B1B8 00000000 */   nop
    /* 3F79C 8008B1BC 240A0001 */  addiu      $t2, $zero, 0x1
    /* 3F7A0 8008B1C0 10000006 */  b          .L8008B1DC
    /* 3F7A4 8008B1C4 AFAA0018 */   sw        $t2, 0x18($sp)
  .L8008B1C8:
    /* 3F7A8 8008B1C8 8FAB0040 */  lw         $t3, 0x40($sp)
    /* 3F7AC 8008B1CC 256C0001 */  addiu      $t4, $t3, 0x1
    /* 3F7B0 8008B1D0 29810004 */  slti       $at, $t4, 0x4
    /* 3F7B4 8008B1D4 1420FFF1 */  bnez       $at, .L8008B19C
    /* 3F7B8 8008B1D8 AFAC0040 */   sw        $t4, 0x40($sp)
  .L8008B1DC:
    /* 3F7BC 8008B1DC 8FAD0018 */  lw         $t5, 0x18($sp)
    /* 3F7C0 8008B1E0 15A00006 */  bnez       $t5, .L8008B1FC
    /* 3F7C4 8008B1E4 00000000 */   nop
    /* 3F7C8 8008B1E8 8FAE0044 */  lw         $t6, 0x44($sp)
    /* 3F7CC 8008B1EC 8FAF005C */  lw         $t7, 0x5C($sp)
    /* 3F7D0 8008B1F0 ADEE0000 */  sw         $t6, 0x0($t7)
    /* 3F7D4 8008B1F4 1000000D */  b          .L8008B22C
    /* 3F7D8 8008B1F8 8FA2001C */   lw        $v0, 0x1C($sp)
  .L8008B1FC:
    /* 3F7DC 8008B1FC 8FB80044 */  lw         $t8, 0x44($sp)
    /* 3F7E0 8008B200 8FA80048 */  lw         $t0, 0x48($sp)
    /* 3F7E4 8008B204 27190001 */  addiu      $t9, $t8, 0x1
    /* 3F7E8 8008B208 AFB90044 */  sw         $t9, 0x44($sp)
    /* 3F7EC 8008B20C 8D090050 */  lw         $t1, 0x50($t0)
    /* 3F7F0 8008B210 0329082A */  slt        $at, $t9, $t1
    /* 3F7F4 8008B214 1420FFAF */  bnez       $at, .L8008B0D4
    /* 3F7F8 8008B218 00000000 */   nop
  .L8008B21C:
    /* 3F7FC 8008B21C 8FAB005C */  lw         $t3, 0x5C($sp)
    /* 3F800 8008B220 240AFFFF */  addiu      $t2, $zero, -0x1
    /* 3F804 8008B224 24020005 */  addiu      $v0, $zero, 0x5
    /* 3F808 8008B228 AD6A0000 */  sw         $t2, 0x0($t3)
  .L8008B22C:
    /* 3F80C 8008B22C 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 3F810 8008B230 27BD0048 */  addiu      $sp, $sp, 0x48
    /* 3F814 8008B234 03E00008 */  jr         $ra
    /* 3F818 8008B238 00000000 */   nop
endlabel func_8008B088
    /* 3F81C 8008B23C 00000000 */  nop
    /* 3F820 8008B240 00000000 */  nop
    /* 3F824 8008B244 00000000 */  nop
