.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_800865F8, 0x98

glabel func_800865F8
    /* 3ABD8 800865F8 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* 3ABDC 800865FC 00054400 */  sll        $t0, $a1, 16
    /* 3ABE0 80086600 00087403 */  sra        $t6, $t0, 16
    /* 3ABE4 80086604 AFB10018 */  sw         $s1, 0x18($sp)
    /* 3ABE8 80086608 000E8880 */  sll        $s1, $t6, 2
    /* 3ABEC 8008660C AFBF001C */  sw         $ra, 0x1C($sp)
    /* 3ABF0 80086610 AFB00014 */  sw         $s0, 0x14($sp)
    /* 3ABF4 80086614 AFA50024 */  sw         $a1, 0x24($sp)
    /* 3ABF8 80086618 022E8821 */  addu       $s1, $s1, $t6
    /* 3ABFC 8008661C 8C8F0034 */  lw         $t7, 0x34($a0)
    /* 3AC00 80086620 00118880 */  sll        $s1, $s1, 2
    /* 3AC04 80086624 022E8823 */  subu       $s1, $s1, $t6
    /* 3AC08 80086628 00808025 */  or         $s0, $a0, $zero
    /* 3AC0C 8008662C 00118880 */  sll        $s1, $s1, 2
    /* 3AC10 80086630 00C02825 */  or         $a1, $a2, $zero
    /* 3AC14 80086634 01F12021 */  addu       $a0, $t7, $s1
    /* 3AC18 80086638 24840020 */  addiu      $a0, $a0, 0x20
    /* 3AC1C 8008663C 0C020C7E */  jal        func_800831F8
    /* 3AC20 80086640 00E03025 */   or        $a2, $a3, $zero
    /* 3AC24 80086644 8E180034 */  lw         $t8, 0x34($s0)
    /* 3AC28 80086648 24050001 */  addiu      $a1, $zero, 0x1
    /* 3AC2C 8008664C 03113021 */  addu       $a2, $t8, $s1
    /* 3AC30 80086650 0C021717 */  jal        func_80085C5C
    /* 3AC34 80086654 24C40020 */   addiu     $a0, $a2, 0x20
    /* 3AC38 80086658 8E190034 */  lw         $t9, 0x34($s0)
    /* 3AC3C 8008665C 8E040030 */  lw         $a0, 0x30($s0)
    /* 3AC40 80086660 24050002 */  addiu      $a1, $zero, 0x2
    /* 3AC44 80086664 03313021 */  addu       $a2, $t9, $s1
    /* 3AC48 80086668 0C0213C6 */  jal        func_80084F18
    /* 3AC4C 8008666C 24C60020 */   addiu     $a2, $a2, 0x20
    /* 3AC50 80086670 8E0A0034 */  lw         $t2, 0x34($s0)
    /* 3AC54 80086674 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 3AC58 80086678 8FB00014 */  lw         $s0, 0x14($sp)
    /* 3AC5C 8008667C 01511021 */  addu       $v0, $t2, $s1
    /* 3AC60 80086680 8FB10018 */  lw         $s1, 0x18($sp)
    /* 3AC64 80086684 27BD0020 */  addiu      $sp, $sp, 0x20
    /* 3AC68 80086688 03E00008 */  jr         $ra
    /* 3AC6C 8008668C 24420020 */   addiu     $v0, $v0, 0x20
endlabel func_800865F8
    /* 3AC70 80086690 00000000 */  nop
    /* 3AC74 80086694 00000000 */  nop

nonmatching func_80086698, 0x50

glabel func_80086698
    /* 3AC78 80086698 3C013F80 */  lui        $at, (0x3F800000 >> 16)
    /* 3AC7C 8008669C 44811000 */  mtc1       $at, $fv1
    /* 3AC80 800866A0 04800004 */  bltz       $a0, .L800866B4
    /* 3AC84 800866A4 3C018005 */   lui       $at, %hi(D_8004CFAC)
    /* 3AC88 800866A8 3C018005 */  lui        $at, %hi(D_8004CFA8)
    /* 3AC8C 800866AC 10000003 */  b          .L800866BC
    /* 3AC90 800866B0 C420CFA8 */   lwc1      $fv0, %lo(D_8004CFA8)($at)
  .L800866B4:
    /* 3AC94 800866B4 C420CFAC */  lwc1       $fv0, %lo(D_8004CFAC)($at)
    /* 3AC98 800866B8 00042023 */  negu       $a0, $a0
  .L800866BC:
    /* 3AC9C 800866BC 10800008 */  beqz       $a0, .L800866E0
  .L800866C0:
    /* 3ACA0 800866C0 308E0001 */   andi      $t6, $a0, 0x1
    /* 3ACA4 800866C4 11C00003 */  beqz       $t6, .L800866D4
    /* 3ACA8 800866C8 00047843 */   sra       $t7, $a0, 1
    /* 3ACAC 800866CC 46001082 */  mul.s      $fv1, $fv1, $fv0
    /* 3ACB0 800866D0 00000000 */  nop
  .L800866D4:
    /* 3ACB4 800866D4 46000002 */  mul.s      $fv0, $fv0, $fv0
    /* 3ACB8 800866D8 15E0FFF9 */  bnez       $t7, .L800866C0
    /* 3ACBC 800866DC 01E02025 */   or        $a0, $t7, $zero
  .L800866E0:
    /* 3ACC0 800866E0 03E00008 */  jr         $ra
    /* 3ACC4 800866E4 46001006 */   mov.s     $fv0, $fv1
endlabel func_80086698

nonmatching func_800866E8, 0xC

glabel func_800866E8
    /* 3ACC8 800866E8 3C0E8009 */  lui        $t6, %hi(D_80095288)
    /* 3ACCC 800866EC 8DCE5288 */  lw         $t6, %lo(D_80095288)($t6)
    /* 3ACD0 800866F0 44844000 */  mtc1       $a0, $ft2
endlabel func_800866E8
