.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_80087F54, 0xEC

glabel func_80087F54
    /* 3C534 80087F54 27BDFFF0 */  addiu      $sp, $sp, -0x10
    /* 3C538 80087F58 3C0E8019 */  lui        $t6, %hi(D_8018AD28)
    /* 3C53C 80087F5C 25CEAD28 */  addiu      $t6, $t6, %lo(D_8018AD28)
    /* 3C540 80087F60 AFAE000C */  sw         $t6, 0xC($sp)
    /* 3C544 80087F64 AFA00000 */  sw         $zero, 0x0($sp)
  .L80087F68:
    /* 3C548 80087F68 8FAF0000 */  lw         $t7, 0x0($sp)
    /* 3C54C 80087F6C 8FB90000 */  lw         $t9, 0x0($sp)
    /* 3C550 80087F70 3C018019 */  lui        $at, %hi(D_8018AD28)
    /* 3C554 80087F74 000FC080 */  sll        $t8, $t7, 2
    /* 3C558 80087F78 00380821 */  addu       $at, $at, $t8
    /* 3C55C 80087F7C AC20AD28 */  sw         $zero, %lo(D_8018AD28)($at)
    /* 3C560 80087F80 27280001 */  addiu      $t0, $t9, 0x1
    /* 3C564 80087F84 29010010 */  slti       $at, $t0, 0x10
    /* 3C568 80087F88 1420FFF7 */  bnez       $at, .L80087F68
    /* 3C56C 80087F8C AFA80000 */   sw        $t0, 0x0($sp)
    /* 3C570 80087F90 3C198019 */  lui        $t9, %hi(D_8018AD69)
    /* 3C574 80087F94 9339AD69 */  lbu        $t9, %lo(D_8018AD69)($t9)
    /* 3C578 80087F98 24090001 */  addiu      $t1, $zero, 0x1
    /* 3C57C 80087F9C 3C018019 */  lui        $at, %hi(D_8018AD64)
    /* 3C580 80087FA0 240A00FF */  addiu      $t2, $zero, 0xFF
    /* 3C584 80087FA4 240B0001 */  addiu      $t3, $zero, 0x1
    /* 3C588 80087FA8 240C0004 */  addiu      $t4, $zero, 0x4
    /* 3C58C 80087FAC 240D0001 */  addiu      $t5, $zero, 0x1
    /* 3C590 80087FB0 340EFFFF */  ori        $t6, $zero, 0xFFFF
    /* 3C594 80087FB4 240FFFFF */  addiu      $t7, $zero, -0x1
    /* 3C598 80087FB8 2418FFFF */  addiu      $t8, $zero, -0x1
    /* 3C59C 80087FBC AC29AD64 */  sw         $t1, %lo(D_8018AD64)($at)
    /* 3C5A0 80087FC0 A3AA0004 */  sb         $t2, 0x4($sp)
    /* 3C5A4 80087FC4 A3AB0005 */  sb         $t3, 0x5($sp)
    /* 3C5A8 80087FC8 A3AC0006 */  sb         $t4, 0x6($sp)
    /* 3C5AC 80087FCC A3AD0007 */  sb         $t5, 0x7($sp)
    /* 3C5B0 80087FD0 A7AE0008 */  sh         $t6, 0x8($sp)
    /* 3C5B4 80087FD4 A3AF000A */  sb         $t7, 0xA($sp)
    /* 3C5B8 80087FD8 A3B8000B */  sb         $t8, 0xB($sp)
    /* 3C5BC 80087FDC 1B200013 */  blez       $t9, .L8008802C
    /* 3C5C0 80087FE0 AFA00000 */   sw        $zero, 0x0($sp)
  .L80087FE4:
    /* 3C5C4 80087FE4 27A90004 */  addiu      $t1, $sp, 0x4
    /* 3C5C8 80087FE8 8D210000 */  lw         $at, 0x0($t1)
    /* 3C5CC 80087FEC 8FA8000C */  lw         $t0, 0xC($sp)
    /* 3C5D0 80087FF0 3C188019 */  lui        $t8, %hi(D_8018AD69)
    /* 3C5D4 80087FF4 A9010000 */  swl        $at, 0x0($t0)
    /* 3C5D8 80087FF8 B9010003 */  swr        $at, 0x3($t0)
    /* 3C5DC 80087FFC 8D2B0004 */  lw         $t3, 0x4($t1)
    /* 3C5E0 80088000 A90B0004 */  swl        $t3, 0x4($t0)
    /* 3C5E4 80088004 B90B0007 */  swr        $t3, 0x7($t0)
    /* 3C5E8 80088008 8FAE0000 */  lw         $t6, 0x0($sp)
    /* 3C5EC 8008800C 9318AD69 */  lbu        $t8, %lo(D_8018AD69)($t8)
    /* 3C5F0 80088010 8FAC000C */  lw         $t4, 0xC($sp)
    /* 3C5F4 80088014 25CF0001 */  addiu      $t7, $t6, 0x1
    /* 3C5F8 80088018 01F8082A */  slt        $at, $t7, $t8
    /* 3C5FC 8008801C 258D0008 */  addiu      $t5, $t4, 0x8
    /* 3C600 80088020 AFAF0000 */  sw         $t7, 0x0($sp)
    /* 3C604 80088024 1420FFEF */  bnez       $at, .L80087FE4
    /* 3C608 80088028 AFAD000C */   sw        $t5, 0xC($sp)
  .L8008802C:
    /* 3C60C 8008802C 8FAA000C */  lw         $t2, 0xC($sp)
    /* 3C610 80088030 241900FE */  addiu      $t9, $zero, 0xFE
    /* 3C614 80088034 27BD0010 */  addiu      $sp, $sp, 0x10
    /* 3C618 80088038 03E00008 */  jr         $ra
    /* 3C61C 8008803C A1590000 */   sb        $t9, 0x0($t2)
endlabel func_80087F54
    /* 3C620 80088040 00000000 */  nop
    /* 3C624 80088044 00000000 */  nop
