.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_8007573C, 0x100

glabel func_8007573C
    /* 29D1C 8007573C 27BDFFD0 */  addiu      $sp, $sp, -0x30
    /* 29D20 80075740 3C04B1FF */  lui        $a0, (0xB1FFFFF4 >> 16)
    /* 29D24 80075744 3484FFF4 */  ori        $a0, $a0, (0xB1FFFFF4 & 0xFFFF)
    /* 29D28 80075748 AFBF002C */  sw         $ra, 0x2C($sp)
    /* 29D2C 8007574C AFB40028 */  sw         $s4, 0x28($sp)
    /* 29D30 80075750 AFB30024 */  sw         $s3, 0x24($sp)
    /* 29D34 80075754 AFB20020 */  sw         $s2, 0x20($sp)
    /* 29D38 80075758 AFB1001C */  sw         $s1, 0x1C($sp)
    /* 29D3C 8007575C 0C01D3D0 */  jal        func_80074F40
    /* 29D40 80075760 AFB00018 */   sw        $s0, 0x18($sp)
    /* 29D44 80075764 3C03B1FF */  lui        $v1, (0xB1FFFFFC >> 16)
    /* 29D48 80075768 3463FFFC */  ori        $v1, $v1, (0xB1FFFFFC & 0xFFFF)
    /* 29D4C 8007576C 3C04B1FF */  lui        $a0, (0xB1FFFFF8 >> 16)
    /* 29D50 80075770 3484FFF8 */  ori        $a0, $a0, (0xB1FFFFF8 & 0xFFFF)
    /* 29D54 80075774 0C01D3D0 */  jal        func_80074F40
    /* 29D58 80075778 0043A024 */   and       $s4, $v0, $v1
    /* 29D5C 8007577C 3C0301FF */  lui        $v1, (0x1FFFFFC >> 16)
    /* 29D60 80075780 3463FFFC */  ori        $v1, $v1, (0x1FFFFFC & 0xFFFF)
    /* 29D64 80075784 3C04B1FF */  lui        $a0, (0xB1FFFFFC >> 16)
    /* 29D68 80075788 3484FFFC */  ori        $a0, $a0, (0xB1FFFFFC & 0xFFFF)
    /* 29D6C 8007578C 00002821 */  addu       $a1, $zero, $zero
    /* 29D70 80075790 0C01D3C2 */  jal        func_80074F08
    /* 29D74 80075794 00438824 */   and       $s1, $v0, $v1
    /* 29D78 80075798 3C04B000 */  lui        $a0, (0xB0000010 >> 16)
  alabel func_8007579C
    /* 29D7C 8007579C 0C01D3D0 */  jal        func_80074F40
    /* 29D80 800757A0 34840010 */   ori       $a0, $a0, (0xB0000010 & 0xFFFF)
    /* 29D84 800757A4 14400005 */  bnez       $v0, .L800757BC
    /* 29D88 800757A8 00111882 */   srl       $v1, $s1, 2
    /* 29D8C 800757AC 0C01D3DF */  jal        func_80074F7C
    /* 29D90 800757B0 240401F4 */   addiu     $a0, $zero, 0x1F4
    /* 29D94 800757B4 0801D5E7 */  j          func_8007579C
    /* 29D98 800757B8 3C04B000 */   lui       $a0, (0xB0000000 >> 16)
  .L800757BC:
    /* 29D9C 800757BC 10600010 */  beqz       $v1, .L80075800
    /* 29DA0 800757C0 00008021 */   addu      $s0, $zero, $zero
    /* 29DA4 800757C4 3C02B07F */  lui        $v0, (0xB07FFFFF >> 16)
    /* 29DA8 800757C8 3442FFFF */  ori        $v0, $v0, (0xB07FFFFF & 0xFFFF)
    /* 29DAC 800757CC 00609821 */  addu       $s3, $v1, $zero
    /* 29DB0 800757D0 02829024 */  and        $s2, $s4, $v0
    /* 29DB4 800757D4 02808821 */  addu       $s1, $s4, $zero
  .L800757D8:
    /* 29DB8 800757D8 0C01D3D0 */  jal        func_80074F40
    /* 29DBC 800757DC 02202021 */   addu      $a0, $s1, $zero
    /* 29DC0 800757E0 02402021 */  addu       $a0, $s2, $zero
    /* 29DC4 800757E4 0C01D3C2 */  jal        func_80074F08
    /* 29DC8 800757E8 00402821 */   addu      $a1, $v0, $zero
    /* 29DCC 800757EC 26520004 */  addiu      $s2, $s2, 0x4
    /* 29DD0 800757F0 26100001 */  addiu      $s0, $s0, 0x1
    /* 29DD4 800757F4 0213102B */  sltu       $v0, $s0, $s3
    /* 29DD8 800757F8 1440FFF7 */  bnez       $v0, .L800757D8
    /* 29DDC 800757FC 26310004 */   addiu     $s1, $s1, 0x4
  .L80075800:
    /* 29DE0 80075800 0C01D3DF */  jal        func_80074F7C
    /* 29DE4 80075804 240407D0 */   addiu     $a0, $zero, 0x7D0
    /* 29DE8 80075808 3C04B1FF */  lui        $a0, (0xB1FFFFF4 >> 16)
    /* 29DEC 8007580C 3484FFF4 */  ori        $a0, $a0, (0xB1FFFFF4 & 0xFFFF)
    /* 29DF0 80075810 0C01D3C2 */  jal        func_80074F08
    /* 29DF4 80075814 00002821 */   addu      $a1, $zero, $zero
    /* 29DF8 80075818 8FBF002C */  lw         $ra, 0x2C($sp)
    /* 29DFC 8007581C 8FB40028 */  lw         $s4, 0x28($sp)
    /* 29E00 80075820 8FB30024 */  lw         $s3, 0x24($sp)
    /* 29E04 80075824 8FB20020 */  lw         $s2, 0x20($sp)
    /* 29E08 80075828 8FB1001C */  lw         $s1, 0x1C($sp)
    /* 29E0C 8007582C 8FB00018 */  lw         $s0, 0x18($sp)
    /* 29E10 80075830 27BD0030 */  addiu      $sp, $sp, 0x30
    /* 29E14 80075834 03E00008 */  jr         $ra
    /* 29E18 80075838 00000000 */   nop
endlabel func_8007573C
