.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */


glabel func_8008EE18
    /* 433F8 8008EE18 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 433FC 8008EE1C AFBF0014 */  sw         $ra, 0x14($sp)
    /* 43400 8008EE20 0C023BA6 */  jal        func_8008EE98
    /* 43404 8008EE24 AFA60020 */   sw        $a2, 0x20($sp)
    /* 43408 8008EE28 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 4340C 8008EE2C 8FAE0020 */  lw         $t6, 0x20($sp)
    /* 43410 8008EE30 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 43414 8008EE34 03E00008 */  jr         $ra
    /* 43418 8008EE38 004E1021 */   addu      $v0, $v0, $t6
endlabel func_8008EE18
