.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_8005B7D8, 0x8C

glabel func_8005B7D8
    /* FDB8 8005B7D8 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* FDBC 8005B7DC 00802821 */  addu       $a1, $a0, $zero
    /* FDC0 8005B7E0 3C028018 */  lui        $v0, %hi(D_8017DF44)
    /* FDC4 8005B7E4 3C048018 */  lui        $a0, %hi(D_8017EF98)
    /* FDC8 8005B7E8 2484EF98 */  addiu      $a0, $a0, %lo(D_8017EF98)
    /* FDCC 8005B7EC 2406FFFF */  addiu      $a2, $zero, -0x1
    /* FDD0 8005B7F0 AFBF0010 */  sw         $ra, 0x10($sp)
    /* FDD4 8005B7F4 0C016A99 */  jal        func_8005AA64
    /* FDD8 8005B7F8 AC44DF44 */   sw        $a0, %lo(D_8017DF44)($v0)
    /* FDDC 8005B7FC 0C016BAD */  jal        func_8005AEB4
    /* FDE0 8005B800 00000000 */   nop
    /* FDE4 8005B804 24040FC3 */  addiu      $a0, $zero, 0xFC3
    /* FDE8 8005B808 3C028018 */  lui        $v0, %hi(D_8017DF58)
    /* FDEC 8005B80C 2442DF58 */  addiu      $v0, $v0, %lo(D_8017DF58)
    /* FDF0 8005B810 00441821 */  addu       $v1, $v0, $a0
    /* FDF4 8005B814 3C028018 */  lui        $v0, %hi(D_8017DF3E)
    /* FDF8 8005B818 A440DF3E */  sh         $zero, %lo(D_8017DF3E)($v0)
    /* FDFC 8005B81C 3C028018 */  lui        $v0, %hi(D_8017DF40)
    /* FE00 8005B820 A040DF40 */  sb         $zero, %lo(D_8017DF40)($v0)
    /* FE04 8005B824 3C028018 */  lui        $v0, %hi(D_8017DF4C)
    /* FE08 8005B828 AC40DF4C */  sw         $zero, %lo(D_8017DF4C)($v0)
  .L8005B82C:
    /* FE0C 8005B82C A0600000 */  sb         $zero, 0x0($v1)
    /* FE10 8005B830 2484FFFF */  addiu      $a0, $a0, -0x1
    /* FE14 8005B834 0481FFFD */  bgez       $a0, .L8005B82C
    /* FE18 8005B838 2463FFFF */   addiu     $v1, $v1, -0x1
    /* FE1C 8005B83C 3C038018 */  lui        $v1, %hi(D_8017DF56)
    /* FE20 8005B840 8FBF0010 */  lw         $ra, 0x10($sp)
    /* FE24 8005B844 24020FC4 */  addiu      $v0, $zero, 0xFC4
    /* FE28 8005B848 A462DF56 */  sh         $v0, %lo(D_8017DF56)($v1)
    /* FE2C 8005B84C 3C028018 */  lui        $v0, %hi(D_8017DF52)
    /* FE30 8005B850 A440DF52 */  sh         $zero, %lo(D_8017DF52)($v0)
    /* FE34 8005B854 3C028018 */  lui        $v0, %hi(D_8017DF54)
    /* FE38 8005B858 A440DF54 */  sh         $zero, %lo(D_8017DF54)($v0)
    /* FE3C 8005B85C 03E00008 */  jr         $ra
    /* FE40 8005B860 27BD0018 */   addiu     $sp, $sp, 0x18
endlabel func_8005B7D8

nonmatching func_8005B864, 0x10

glabel func_8005B864
    /* FE44 8005B864 3C028018 */  lui        $v0, %hi(D_8017DF54)
    /* FE48 8005B868 3C038018 */  lui        $v1, %hi(D_8017DF52)
    /* FE4C 8005B86C 8444DF54 */  lh         $a0, %lo(D_8017DF54)($v0)
    /* FE50 8005B870 8462DF52 */  lh         $v0, %lo(D_8017DF52)($v1)
endlabel func_8005B864
