.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_8007AA68, 0x168

glabel func_8007AA68
    /* 2F048 8007AA68 27BDFF98 */  addiu      $sp, $sp, -0x68
    /* 2F04C 8007AA6C 44800000 */  mtc1       $zero, $fv0
    /* 2F050 8007AA70 27A3001C */  addiu      $v1, $sp, 0x1C
    /* 2F054 8007AA74 27AB005C */  addiu      $t3, $sp, 0x5C
    /* 2F058 8007AA78 00803825 */  or         $a3, $a0, $zero
    /* 2F05C 8007AA7C 00A04025 */  or         $t0, $a1, $zero
    /* 2F060 8007AA80 240A0010 */  addiu      $t2, $zero, 0x10
  .L8007AA84:
    /* 2F064 8007AA84 00002025 */  or         $a0, $zero, $zero
    /* 2F068 8007AA88 00602825 */  or         $a1, $v1, $zero
    /* 2F06C 8007AA8C 01004825 */  or         $t1, $t0, $zero
    /* 2F070 8007AA90 E4A00000 */  swc1       $fv0, 0x0($a1)
    /* 2F074 8007AA94 C52C0000 */  lwc1       $fa0, 0x0($t1)
    /* 2F078 8007AA98 C4EE0000 */  lwc1       $fa1, 0x0($a3)
    /* 2F07C 8007AA9C 24840004 */  addiu      $a0, $a0, 0x4
    /* 2F080 8007AAA0 C4B00000 */  lwc1       $ft4, 0x0($a1)
    /* 2F084 8007AAA4 460C7482 */  mul.s      $ft5, $fa1, $fa0
    /* 2F088 8007AAA8 508A0020 */  beql       $a0, $t2, .L8007AB2C
    /* 2F08C 8007AAAC 46128380 */   add.s     $fa1, $ft4, $ft5
    /* 2F090 8007AAB0 46128380 */  add.s      $fa1, $ft4, $ft5
  .L8007AAB4:
    /* 2F094 8007AAB4 24840004 */  addiu      $a0, $a0, 0x4
    /* 2F098 8007AAB8 24A50004 */  addiu      $a1, $a1, 0x4
    /* 2F09C 8007AABC 25290004 */  addiu      $t1, $t1, 0x4
    /* 2F0A0 8007AAC0 E4AEFFFC */  swc1       $fa1, -0x4($a1)
    /* 2F0A4 8007AAC4 C4EE0004 */  lwc1       $fa1, 0x4($a3)
    /* 2F0A8 8007AAC8 C52C000C */  lwc1       $fa0, 0xC($t1)
    /* 2F0AC 8007AACC C4AAFFFC */  lwc1       $ft3, -0x4($a1)
    /* 2F0B0 8007AAD0 460C7302 */  mul.s      $fa0, $fa1, $fa0
    /* 2F0B4 8007AAD4 460C5300 */  add.s      $fa0, $ft3, $fa0
    /* 2F0B8 8007AAD8 E4ACFFFC */  swc1       $fa0, -0x4($a1)
    /* 2F0BC 8007AADC C4EC0008 */  lwc1       $fa0, 0x8($a3)
    /* 2F0C0 8007AAE0 C52A001C */  lwc1       $ft3, 0x1C($t1)
    /* 2F0C4 8007AAE4 C4AEFFFC */  lwc1       $fa1, -0x4($a1)
    /* 2F0C8 8007AAE8 460A6282 */  mul.s      $ft3, $fa0, $ft3
    /* 2F0CC 8007AAEC 460A7280 */  add.s      $ft3, $fa1, $ft3
    /* 2F0D0 8007AAF0 E4AAFFFC */  swc1       $ft3, -0x4($a1)
    /* 2F0D4 8007AAF4 C4EA000C */  lwc1       $ft3, 0xC($a3)
    /* 2F0D8 8007AAF8 C52E002C */  lwc1       $fa1, 0x2C($t1)
    /* 2F0DC 8007AAFC C4ACFFFC */  lwc1       $fa0, -0x4($a1)
    /* 2F0E0 8007AB00 E4A00000 */  swc1       $fv0, 0x0($a1)
    /* 2F0E4 8007AB04 460E5382 */  mul.s      $fa1, $ft3, $fa1
    /* 2F0E8 8007AB08 C4B00000 */  lwc1       $ft4, 0x0($a1)
    /* 2F0EC 8007AB0C 460E6380 */  add.s      $fa1, $fa0, $fa1
    /* 2F0F0 8007AB10 E4AEFFFC */  swc1       $fa1, -0x4($a1)
    /* 2F0F4 8007AB14 C4EE0000 */  lwc1       $fa1, 0x0($a3)
    /* 2F0F8 8007AB18 C52C0000 */  lwc1       $fa0, 0x0($t1)
    /* 2F0FC 8007AB1C 460C7482 */  mul.s      $ft5, $fa1, $fa0
    /* 2F100 8007AB20 548AFFE4 */  bnel       $a0, $t2, .L8007AAB4
    /* 2F104 8007AB24 46128380 */   add.s     $fa1, $ft4, $ft5
    /* 2F108 8007AB28 46128380 */  add.s      $fa1, $ft4, $ft5
  .L8007AB2C:
    /* 2F10C 8007AB2C 24A50004 */  addiu      $a1, $a1, 0x4
    /* 2F110 8007AB30 25290004 */  addiu      $t1, $t1, 0x4
    /* 2F114 8007AB34 E4AEFFFC */  swc1       $fa1, -0x4($a1)
    /* 2F118 8007AB38 C52C000C */  lwc1       $fa0, 0xC($t1)
    /* 2F11C 8007AB3C C4EE0004 */  lwc1       $fa1, 0x4($a3)
    /* 2F120 8007AB40 C4AAFFFC */  lwc1       $ft3, -0x4($a1)
    /* 2F124 8007AB44 460C7302 */  mul.s      $fa0, $fa1, $fa0
    /* 2F128 8007AB48 460C5300 */  add.s      $fa0, $ft3, $fa0
    /* 2F12C 8007AB4C E4ACFFFC */  swc1       $fa0, -0x4($a1)
    /* 2F130 8007AB50 C52A001C */  lwc1       $ft3, 0x1C($t1)
    /* 2F134 8007AB54 C4EC0008 */  lwc1       $fa0, 0x8($a3)
    /* 2F138 8007AB58 C4AEFFFC */  lwc1       $fa1, -0x4($a1)
    /* 2F13C 8007AB5C 460A6282 */  mul.s      $ft3, $fa0, $ft3
    /* 2F140 8007AB60 460A7280 */  add.s      $ft3, $fa1, $ft3
    /* 2F144 8007AB64 E4AAFFFC */  swc1       $ft3, -0x4($a1)
    /* 2F148 8007AB68 C52E002C */  lwc1       $fa1, 0x2C($t1)
    /* 2F14C 8007AB6C C4EA000C */  lwc1       $ft3, 0xC($a3)
    /* 2F150 8007AB70 C4ACFFFC */  lwc1       $fa0, -0x4($a1)
    /* 2F154 8007AB74 460E5382 */  mul.s      $fa1, $ft3, $fa1
    /* 2F158 8007AB78 460E6380 */  add.s      $fa1, $fa0, $fa1
    /* 2F15C 8007AB7C E4AEFFFC */  swc1       $fa1, -0x4($a1)
    /* 2F160 8007AB80 24630010 */  addiu      $v1, $v1, 0x10
    /* 2F164 8007AB84 006B082B */  sltu       $at, $v1, $t3
    /* 2F168 8007AB88 1420FFBE */  bnez       $at, .L8007AA84
    /* 2F16C 8007AB8C 24E70010 */   addiu     $a3, $a3, 0x10
    /* 2F170 8007AB90 00C01825 */  or         $v1, $a2, $zero
    /* 2F174 8007AB94 27A4001C */  addiu      $a0, $sp, 0x1C
    /* 2F178 8007AB98 27A2005C */  addiu      $v0, $sp, 0x5C
  .L8007AB9C:
    /* 2F17C 8007AB9C C4860000 */  lwc1       $ft1, 0x0($a0)
    /* 2F180 8007ABA0 24840010 */  addiu      $a0, $a0, 0x10
    /* 2F184 8007ABA4 24630010 */  addiu      $v1, $v1, 0x10
    /* 2F188 8007ABA8 E466FFF0 */  swc1       $ft1, -0x10($v1)
    /* 2F18C 8007ABAC C488FFF4 */  lwc1       $ft2, -0xC($a0)
    /* 2F190 8007ABB0 E468FFF4 */  swc1       $ft2, -0xC($v1)
    /* 2F194 8007ABB4 C490FFF8 */  lwc1       $ft4, -0x8($a0)
    /* 2F198 8007ABB8 E470FFF8 */  swc1       $ft4, -0x8($v1)
    /* 2F19C 8007ABBC C48AFFFC */  lwc1       $ft3, -0x4($a0)
    /* 2F1A0 8007ABC0 1482FFF6 */  bne        $a0, $v0, .L8007AB9C
    /* 2F1A4 8007ABC4 E46AFFFC */   swc1      $ft3, -0x4($v1)
    /* 2F1A8 8007ABC8 03E00008 */  jr         $ra
    /* 2F1AC 8007ABCC 27BD0068 */   addiu     $sp, $sp, 0x68
endlabel func_8007AA68
    /* 2F1B0 8007ABD0 00000000 */  nop
    /* 2F1B4 8007ABD4 00000000 */  nop
