.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_8008E2B8, 0x58

glabel func_8008E2B8
    /* 42898 8008E2B8 27BDFFD8 */  addiu      $sp, $sp, -0x28
    /* 4289C 8008E2BC AFBF001C */  sw         $ra, 0x1C($sp)
    /* 428A0 8008E2C0 AFA40028 */  sw         $a0, 0x28($sp)
    /* 428A4 8008E2C4 0C01F1DA */  jal        func_8007C768
    /* 428A8 8008E2C8 AFB00018 */   sw        $s0, 0x18($sp)
    /* 428AC 8008E2CC 8FAF0028 */  lw         $t7, 0x28($sp)
    /* 428B0 8008E2D0 3C0E8009 */  lui        $t6, %hi(D_80095290)
    /* 428B4 8008E2D4 8DCE5290 */  lw         $t6, %lo(D_80095290)($t6)
    /* 428B8 8008E2D8 2401FBFE */  addiu      $at, $zero, -0x402
    /* 428BC 8008E2DC 01E1C024 */  and        $t8, $t7, $at
    /* 428C0 8008E2E0 0300C827 */  not        $t9, $t8
    /* 428C4 8008E2E4 00408025 */  or         $s0, $v0, $zero
    /* 428C8 8008E2E8 3C018009 */  lui        $at, %hi(D_80095290)
    /* 428CC 8008E2EC 01D94024 */  and        $t0, $t6, $t9
    /* 428D0 8008E2F0 AC285290 */  sw         $t0, %lo(D_80095290)($at)
    /* 428D4 8008E2F4 0C01F1E2 */  jal        func_8007C788
    /* 428D8 8008E2F8 02002025 */   or        $a0, $s0, $zero
    /* 428DC 8008E2FC 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 428E0 8008E300 8FB00018 */  lw         $s0, 0x18($sp)
    /* 428E4 8008E304 27BD0028 */  addiu      $sp, $sp, 0x28
    /* 428E8 8008E308 03E00008 */  jr         $ra
    /* 428EC 8008E30C 00000000 */   nop
endlabel func_8008E2B8
    /* 428F0 8008E310 00000000 */  nop
    /* 428F4 8008E314 00000000 */  nop
