.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_8007D240, 0x38

glabel func_8007D240
    /* 31820 8007D240 27BDFFF8 */  addiu      $sp, $sp, -0x8
    /* 31824 8007D244 10E0000A */  beqz       $a3, .L8007D270
    /* 31828 8007D248 00000000 */   nop
  .L8007D24C:
    /* 3182C 8007D24C 14E50004 */  bne        $a3, $a1, .L8007D260
    /* 31830 8007D250 00000000 */   nop
    /* 31834 8007D254 8CAE0000 */  lw         $t6, 0x0($a1)
    /* 31838 8007D258 10000005 */  b          .L8007D270
    /* 3183C 8007D25C ACCE0000 */   sw        $t6, 0x0($a2)
  .L8007D260:
    /* 31840 8007D260 00E03025 */  or         $a2, $a3, $zero
    /* 31844 8007D264 8CC70000 */  lw         $a3, 0x0($a2)
    /* 31848 8007D268 14E0FFF8 */  bnez       $a3, .L8007D24C
    /* 3184C 8007D26C 00000000 */   nop
  .L8007D270:
    /* 31850 8007D270 03E00008 */  jr         $ra
    /* 31854 8007D274 27BD0008 */   addiu     $sp, $sp, 0x8
endlabel func_8007D240

nonmatching func_8007D278, 0x8C

glabel func_8007D278
    /* 31858 8007D278 3C018019 */  lui        $at, %hi(D_80189A8C)
    /* 3185C 8007D27C 240E0000 */  addiu      $t6, $zero, 0x0
    /* 31860 8007D280 240F0000 */  addiu      $t7, $zero, 0x0
    /* 31864 8007D284 AC2F9A8C */  sw         $t7, %lo(D_80189A8C)($at)
    /* 31868 8007D288 AC2E9A88 */  sw         $t6, %lo(D_80189A88)($at)
    /* 3186C 8007D28C 3C018019 */  lui        $at, %hi(D_80189A90)
    /* 31870 8007D290 3C188009 */  lui        $t8, %hi(D_800952C0)
    /* 31874 8007D294 8F1852C0 */  lw         $t8, %lo(D_800952C0)($t8)
    /* 31878 8007D298 AC209A90 */  sw         $zero, %lo(D_80189A90)($at)
    /* 3187C 8007D29C 3C018019 */  lui        $at, %hi(D_80189A94)
    /* 31880 8007D2A0 AC209A94 */  sw         $zero, %lo(D_80189A94)($at)
    /* 31884 8007D2A4 3C198009 */  lui        $t9, %hi(D_800952C0)
    /* 31888 8007D2A8 AF180004 */  sw         $t8, 0x4($t8)
    /* 3188C 8007D2AC 8F3952C0 */  lw         $t9, %lo(D_800952C0)($t9)
    /* 31890 8007D2B0 3C098009 */  lui        $t1, %hi(D_800952C0)
    /* 31894 8007D2B4 240A0000 */  addiu      $t2, $zero, 0x0
    /* 31898 8007D2B8 8F280004 */  lw         $t0, 0x4($t9)
    /* 3189C 8007D2BC 240B0000 */  addiu      $t3, $zero, 0x0
    /* 318A0 8007D2C0 3C0C8009 */  lui        $t4, %hi(D_800952C0)
    /* 318A4 8007D2C4 AF280000 */  sw         $t0, 0x0($t9)
    /* 318A8 8007D2C8 8D2952C0 */  lw         $t1, %lo(D_800952C0)($t1)
    /* 318AC 8007D2CC 3C0D8009 */  lui        $t5, %hi(D_800952C0)
    /* 318B0 8007D2D0 3C188009 */  lui        $t8, %hi(D_800952C0)
    /* 318B4 8007D2D4 AD2A0010 */  sw         $t2, 0x10($t1)
    /* 318B8 8007D2D8 AD2B0014 */  sw         $t3, 0x14($t1)
    /* 318BC 8007D2DC 8D8C52C0 */  lw         $t4, %lo(D_800952C0)($t4)
    /* 318C0 8007D2E0 8D8E0010 */  lw         $t6, 0x10($t4)
    /* 318C4 8007D2E4 8D8F0014 */  lw         $t7, 0x14($t4)
    /* 318C8 8007D2E8 AD8E0008 */  sw         $t6, 0x8($t4)
    /* 318CC 8007D2EC AD8F000C */  sw         $t7, 0xC($t4)
    /* 318D0 8007D2F0 8DAD52C0 */  lw         $t5, %lo(D_800952C0)($t5)
    /* 318D4 8007D2F4 ADA00018 */  sw         $zero, 0x18($t5)
    /* 318D8 8007D2F8 8F1852C0 */  lw         $t8, %lo(D_800952C0)($t8)
    /* 318DC 8007D2FC 03E00008 */  jr         $ra
    /* 318E0 8007D300 AF00001C */   sw        $zero, 0x1C($t8)
endlabel func_8007D278

nonmatching func_8007D304, 0x8

glabel func_8007D304
    /* 318E4 8007D304 3C0E8009 */  lui        $t6, %hi(D_800952C0)
    /* 318E8 8007D308 8DCE52C0 */  lw         $t6, %lo(D_800952C0)($t6)
endlabel func_8007D304
