.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_8005AB80, 0xF0

glabel func_8005AB80
    /* F160 8005AB80 27BDFFB8 */  addiu      $sp, $sp, -0x48
    /* F164 8005AB84 00801021 */  addu       $v0, $a0, $zero
    /* F168 8005AB88 00A01821 */  addu       $v1, $a1, $zero
    /* F16C 8005AB8C AFB00030 */  sw         $s0, 0x30($sp)
    /* F170 8005AB90 00C08021 */  addu       $s0, $a2, $zero
    /* F174 8005AB94 27A40010 */  addiu      $a0, $sp, 0x10
    /* F178 8005AB98 00402821 */  addu       $a1, $v0, $zero
    /* F17C 8005AB9C 00603021 */  addu       $a2, $v1, $zero
    /* F180 8005ABA0 AFBF0044 */  sw         $ra, 0x44($sp)
    /* F184 8005ABA4 AFB40040 */  sw         $s4, 0x40($sp)
    /* F188 8005ABA8 AFB3003C */  sw         $s3, 0x3C($sp)
    /* F18C 8005ABAC AFB20038 */  sw         $s2, 0x38($sp)
    /* F190 8005ABB0 0C016A99 */  jal        func_8005AA64
    /* F194 8005ABB4 AFB10034 */   sw        $s1, 0x34($sp)
    /* F198 8005ABB8 8FA20024 */  lw         $v0, 0x24($sp)
    /* F19C 8005ABBC 10400024 */  beqz       $v0, .L8005AC50
    /* F1A0 8005ABC0 3C118018 */   lui       $s1, %hi(D_8017CDF8)
    /* F1A4 8005ABC4 3C148017 */  lui        $s4, %hi(D_8016DF70)
    /* F1A8 8005ABC8 24130001 */  addiu      $s3, $zero, 0x1
    /* F1AC 8005ABCC 3C028019 */  lui        $v0, %hi(D_80190000)
    /* F1B0 8005ABD0 24520000 */  addiu      $s2, $v0, %lo(D_80190000)
  .L8005ABD4:
    /* F1B4 8005ABD4 8E22CDF8 */  lw         $v0, %lo(D_8017CDF8)($s1)
    /* F1B8 8005ABD8 10400007 */  beqz       $v0, .L8005ABF8
    /* F1BC 8005ABDC 2684DF70 */   addiu     $a0, $s4, %lo(D_8016DF70)
    /* F1C0 8005ABE0 27A50028 */  addiu      $a1, $sp, 0x28
    /* F1C4 8005ABE4 0C01F342 */  jal        func_8007CD08
    /* F1C8 8005ABE8 24060001 */   addiu     $a2, $zero, 0x1
    /* F1CC 8005ABEC 8E22CDF8 */  lw         $v0, %lo(D_8017CDF8)($s1)
    /* F1D0 8005ABF0 2442FFFF */  addiu      $v0, $v0, -0x1
    /* F1D4 8005ABF4 AE22CDF8 */  sw         $v0, %lo(D_8017CDF8)($s1)
  .L8005ABF8:
    /* F1D8 8005ABF8 8FA20018 */  lw         $v0, 0x18($sp)
    /* F1DC 8005ABFC 8FA30024 */  lw         $v1, 0x24($sp)
    /* F1E0 8005AC00 8FA40014 */  lw         $a0, 0x14($sp)
    /* F1E4 8005AC04 AFA0001C */  sw         $zero, 0x1C($sp)
    /* F1E8 8005AC08 02621023 */  subu       $v0, $s3, $v0
    /* F1EC 8005AC0C AFA20018 */  sw         $v0, 0x18($sp)
    /* F1F0 8005AC10 14800003 */  bnez       $a0, .L8005AC20
    /* F1F4 8005AC14 AFA30020 */   sw        $v1, 0x20($sp)
    /* F1F8 8005AC18 08016B0A */  j          func_8005AC28
    /* F1FC 8005AC1C AFA00024 */   sw        $zero, 0x24($sp)
  .L8005AC20:
    /* F200 8005AC20 0C016A5E */  jal        func_8005A978
    /* F204 8005AC24 27A40010 */   addiu     $a0, $sp, 0x10
  alabel func_8005AC28
    /* F208 8005AC28 02002021 */  addu       $a0, $s0, $zero
    /* F20C 8005AC2C 8FA50018 */  lw         $a1, 0x18($sp)
    /* F210 8005AC30 8FA60020 */  lw         $a2, 0x20($sp)
    /* F214 8005AC34 00052A80 */  sll        $a1, $a1, 10
    /* F218 8005AC38 0C01866C */  jal        func_800619B0
    /* F21C 8005AC3C 00B22821 */   addu      $a1, $a1, $s2
    /* F220 8005AC40 8FA20020 */  lw         $v0, 0x20($sp)
    /* F224 8005AC44 8FA30024 */  lw         $v1, 0x24($sp)
    /* F228 8005AC48 1460FFE2 */  bnez       $v1, .L8005ABD4
    /* F22C 8005AC4C 02028021 */   addu      $s0, $s0, $v0
  .L8005AC50:
    /* F230 8005AC50 8FBF0044 */  lw         $ra, 0x44($sp)
    /* F234 8005AC54 8FB40040 */  lw         $s4, 0x40($sp)
    /* F238 8005AC58 8FB3003C */  lw         $s3, 0x3C($sp)
    /* F23C 8005AC5C 8FB20038 */  lw         $s2, 0x38($sp)
    /* F240 8005AC60 8FB10034 */  lw         $s1, 0x34($sp)
    /* F244 8005AC64 8FB00030 */  lw         $s0, 0x30($sp)
    /* F248 8005AC68 03E00008 */  jr         $ra
    /* F24C 8005AC6C 27BD0048 */   addiu     $sp, $sp, 0x48
endlabel func_8005AB80
