.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_8007C9E8, 0x28C

glabel func_8007C9E8
    /* 30FC8 8007C9E8 27BDFFC8 */  addiu      $sp, $sp, -0x38
    /* 30FCC 8007C9EC AFBF001C */  sw         $ra, 0x1C($sp)
    /* 30FD0 8007C9F0 240E0001 */  addiu      $t6, $zero, 0x1
    /* 30FD4 8007C9F4 3C018019 */  lui        $at, %hi(D_80189828)
    /* 30FD8 8007C9F8 AFB00018 */  sw         $s0, 0x18($sp)
    /* 30FDC 8007C9FC AFA00030 */  sw         $zero, 0x30($sp)
    /* 30FE0 8007CA00 0C01F31E */  jal        func_8007CC78
    /* 30FE4 8007CA04 AC2E9828 */   sw        $t6, %lo(D_80189828)($at)
    /* 30FE8 8007CA08 00408025 */  or         $s0, $v0, $zero
    /* 30FEC 8007CA0C 3C012000 */  lui        $at, (0x20000000 >> 16)
    /* 30FF0 8007CA10 0C01F326 */  jal        func_8007CC98
    /* 30FF4 8007CA14 02012025 */   or        $a0, $s0, $at
    /* 30FF8 8007CA18 3C040100 */  lui        $a0, (0x1000800 >> 16)
    /* 30FFC 8007CA1C 0C01F322 */  jal        func_8007CC88
    /* 31000 8007CA20 34840800 */   ori       $a0, $a0, (0x1000800 & 0xFFFF)
    /* 31004 8007CA24 3C041FC0 */  lui        $a0, (0x1FC007FC >> 16)
    /* 31008 8007CA28 348407FC */  ori        $a0, $a0, (0x1FC007FC & 0xFFFF)
    /* 3100C 8007CA2C 0C021EBE */  jal        func_80087AF8
    /* 31010 8007CA30 27A50034 */   addiu     $a1, $sp, 0x34
    /* 31014 8007CA34 10400007 */  beqz       $v0, .L8007CA54
    /* 31018 8007CA38 00000000 */   nop
  .L8007CA3C:
    /* 3101C 8007CA3C 3C041FC0 */  lui        $a0, (0x1FC007FC >> 16)
    /* 31020 8007CA40 348407FC */  ori        $a0, $a0, (0x1FC007FC & 0xFFFF)
    /* 31024 8007CA44 0C021EBE */  jal        func_80087AF8
    /* 31028 8007CA48 27A50034 */   addiu     $a1, $sp, 0x34
    /* 3102C 8007CA4C 1440FFFB */  bnez       $v0, .L8007CA3C
    /* 31030 8007CA50 00000000 */   nop
  .L8007CA54:
    /* 31034 8007CA54 8FA50034 */  lw         $a1, 0x34($sp)
    /* 31038 8007CA58 3C041FC0 */  lui        $a0, (0x1FC007FC >> 16)
    /* 3103C 8007CA5C 348407FC */  ori        $a0, $a0, (0x1FC007FC & 0xFFFF)
    /* 31040 8007CA60 34AF0008 */  ori        $t7, $a1, 0x8
    /* 31044 8007CA64 0C021EDE */  jal        func_80087B78
    /* 31048 8007CA68 01E02825 */   or        $a1, $t7, $zero
    /* 3104C 8007CA6C 10400009 */  beqz       $v0, .L8007CA94
    /* 31050 8007CA70 00000000 */   nop
  .L8007CA74:
    /* 31054 8007CA74 8FA50034 */  lw         $a1, 0x34($sp)
    /* 31058 8007CA78 3C041FC0 */  lui        $a0, (0x1FC007FC >> 16)
    /* 3105C 8007CA7C 348407FC */  ori        $a0, $a0, (0x1FC007FC & 0xFFFF)
    /* 31060 8007CA80 34B80008 */  ori        $t8, $a1, 0x8
    /* 31064 8007CA84 0C021EDE */  jal        func_80087B78
    /* 31068 8007CA88 03002825 */   or        $a1, $t8, $zero
    /* 3106C 8007CA8C 1440FFF9 */  bnez       $v0, .L8007CA74
    /* 31070 8007CA90 00000000 */   nop
  .L8007CA94:
    /* 31074 8007CA94 3C088008 */  lui        $t0, %hi(func_8007BE58)
    /* 31078 8007CA98 2508BE58 */  addiu      $t0, $t0, %lo(func_8007BE58)
    /* 3107C 8007CA9C 8D010000 */  lw         $at, 0x0($t0)
    /* 31080 8007CAA0 3C198000 */  lui        $t9, %hi(D_80000000)
    /* 31084 8007CAA4 3C0D8008 */  lui        $t5, %hi(func_8007BE58)
    /* 31088 8007CAA8 AF210000 */  sw         $at, %lo(D_80000000)($t9)
    /* 3108C 8007CAAC 8D0B0004 */  lw         $t3, 0x4($t0)
    /* 31090 8007CAB0 25ADBE58 */  addiu      $t5, $t5, %lo(func_8007BE58)
    /* 31094 8007CAB4 3C0C8000 */  lui        $t4, (0x80000080 >> 16)
    /* 31098 8007CAB8 AF2B0004 */  sw         $t3, %lo(D_80000004)($t9)
    /* 3109C 8007CABC 8D010008 */  lw         $at, 0x8($t0)
    /* 310A0 8007CAC0 358C0080 */  ori        $t4, $t4, (0x80000080 & 0xFFFF)
    /* 310A4 8007CAC4 3C098008 */  lui        $t1, %hi(func_8007BE58)
    /* 310A8 8007CAC8 AF210008 */  sw         $at, %lo(D_80000008)($t9)
    /* 310AC 8007CACC 8D0B000C */  lw         $t3, 0xC($t0)
    /* 310B0 8007CAD0 2529BE58 */  addiu      $t1, $t1, %lo(func_8007BE58)
    /* 310B4 8007CAD4 3C0A8000 */  lui        $t2, (0x80000100 >> 16)
    /* 310B8 8007CAD8 AF2B000C */  sw         $t3, %lo(D_8000000C)($t9)
    /* 310BC 8007CADC 8DA10000 */  lw         $at, 0x0($t5)
    /* 310C0 8007CAE0 354A0100 */  ori        $t2, $t2, (0x80000100 & 0xFFFF)
    /* 310C4 8007CAE4 3C0E8008 */  lui        $t6, %hi(func_8007BE58)
    /* 310C8 8007CAE8 AD810000 */  sw         $at, 0x0($t4)
    /* 310CC 8007CAEC 8DB80004 */  lw         $t8, 0x4($t5)
    /* 310D0 8007CAF0 25CEBE58 */  addiu      $t6, $t6, %lo(func_8007BE58)
    /* 310D4 8007CAF4 3C0F8000 */  lui        $t7, (0x80000180 >> 16)
    /* 310D8 8007CAF8 AD980004 */  sw         $t8, 0x4($t4)
    /* 310DC 8007CAFC 8DA10008 */  lw         $at, 0x8($t5)
    /* 310E0 8007CB00 35EF0180 */  ori        $t7, $t7, (0x80000180 & 0xFFFF)
    /* 310E4 8007CB04 3C048000 */  lui        $a0, (0x80000000 >> 16)
    /* 310E8 8007CB08 AD810008 */  sw         $at, 0x8($t4)
    /* 310EC 8007CB0C 8DB8000C */  lw         $t8, 0xC($t5)
    /* 310F0 8007CB10 24050190 */  addiu      $a1, $zero, 0x190
    /* 310F4 8007CB14 AD98000C */  sw         $t8, 0xC($t4)
    /* 310F8 8007CB18 8D210000 */  lw         $at, 0x0($t1)
    /* 310FC 8007CB1C AD410000 */  sw         $at, 0x0($t2)
    /* 31100 8007CB20 8D2B0004 */  lw         $t3, 0x4($t1)
    /* 31104 8007CB24 AD4B0004 */  sw         $t3, 0x4($t2)
    /* 31108 8007CB28 8D210008 */  lw         $at, 0x8($t1)
    /* 3110C 8007CB2C AD410008 */  sw         $at, 0x8($t2)
    /* 31110 8007CB30 8D2B000C */  lw         $t3, 0xC($t1)
    /* 31114 8007CB34 AD4B000C */  sw         $t3, 0xC($t2)
    /* 31118 8007CB38 8DC10000 */  lw         $at, 0x0($t6)
    /* 3111C 8007CB3C ADE10000 */  sw         $at, 0x0($t7)
    /* 31120 8007CB40 8DD80004 */  lw         $t8, 0x4($t6)
    /* 31124 8007CB44 ADF80004 */  sw         $t8, 0x4($t7)
    /* 31128 8007CB48 8DC10008 */  lw         $at, 0x8($t6)
    /* 3112C 8007CB4C ADE10008 */  sw         $at, 0x8($t7)
    /* 31130 8007CB50 8DD8000C */  lw         $t8, 0xC($t6)
    /* 31134 8007CB54 0C01EF0A */  jal        func_8007BC28
    /* 31138 8007CB58 ADF8000C */   sw        $t8, 0xC($t7)
    /* 3113C 8007CB5C 3C048000 */  lui        $a0, (0x80000000 >> 16)
    /* 31140 8007CB60 0C01EED2 */  jal        func_8007BB48
    /* 31144 8007CB64 24050190 */   addiu     $a1, $zero, 0x190
    /* 31148 8007CB68 0C01F32A */  jal        func_8007CCA8
    /* 3114C 8007CB6C 00000000 */   nop
    /* 31150 8007CB70 24040004 */  addiu      $a0, $zero, 0x4
    /* 31154 8007CB74 0C0233AE */  jal        func_8008CEB8
    /* 31158 8007CB78 27A50030 */   addiu     $a1, $sp, 0x30
    /* 3115C 8007CB7C 8FA80030 */  lw         $t0, 0x30($sp)
    /* 31160 8007CB80 2401FFF0 */  addiu      $at, $zero, -0x10
    /* 31164 8007CB84 0101C824 */  and        $t9, $t0, $at
    /* 31168 8007CB88 13200006 */  beqz       $t9, .L8007CBA4
    /* 3116C 8007CB8C AFB90030 */   sw        $t9, 0x30($sp)
    /* 31170 8007CB90 3C018009 */  lui        $at, %hi(D_80095280)
    /* 31174 8007CB94 03205825 */  or         $t3, $t9, $zero
    /* 31178 8007CB98 240A0000 */  addiu      $t2, $zero, 0x0
    /* 3117C 8007CB9C AC2A5280 */  sw         $t2, %lo(D_80095280)($at)
    /* 31180 8007CBA0 AC2B5284 */  sw         $t3, %lo(D_80095284)($at)
  .L8007CBA4:
    /* 31184 8007CBA4 3C048009 */  lui        $a0, %hi(D_80095280)
    /* 31188 8007CBA8 3C058009 */  lui        $a1, %hi(D_80095284)
    /* 3118C 8007CBAC 8CA55284 */  lw         $a1, %lo(D_80095284)($a1)
    /* 31190 8007CBB0 8C845280 */  lw         $a0, %lo(D_80095280)($a0)
    /* 31194 8007CBB4 24060000 */  addiu      $a2, $zero, 0x0
    /* 31198 8007CBB8 0C023B30 */  jal        func_8008ECC0
    /* 3119C 8007CBBC 24070003 */   addiu     $a3, $zero, 0x3
    /* 311A0 8007CBC0 AFA20020 */  sw         $v0, 0x20($sp)
    /* 311A4 8007CBC4 AFA30024 */  sw         $v1, 0x24($sp)
    /* 311A8 8007CBC8 8FA50024 */  lw         $a1, 0x24($sp)
    /* 311AC 8007CBCC 8FA40020 */  lw         $a0, 0x20($sp)
    /* 311B0 8007CBD0 24060000 */  addiu      $a2, $zero, 0x0
    /* 311B4 8007CBD4 0C023AF0 */  jal        func_8008EBC0
    /* 311B8 8007CBD8 24070004 */   addiu     $a3, $zero, 0x4
    /* 311BC 8007CBDC 3C098000 */  lui        $t1, %hi(D_8000030C)
    /* 311C0 8007CBE0 8D29030C */  lw         $t1, %lo(D_8000030C)($t1)
    /* 311C4 8007CBE4 3C018009 */  lui        $at, %hi(D_80095280)
    /* 311C8 8007CBE8 AC225280 */  sw         $v0, %lo(D_80095280)($at)
    /* 311CC 8007CBEC 15200005 */  bnez       $t1, .L8007CC04
    /* 311D0 8007CBF0 AC235284 */   sw        $v1, %lo(D_80095284)($at)
    /* 311D4 8007CBF4 3C048000 */  lui        $a0, %hi(D_8000031C)
    /* 311D8 8007CBF8 2484031C */  addiu      $a0, $a0, %lo(D_8000031C)
    /* 311DC 8007CBFC 0C023AAE */  jal        func_8008EAB8
    /* 311E0 8007CC00 24050040 */   addiu     $a1, $zero, 0x40
  .L8007CC04:
    /* 311E4 8007CC04 3C0D8000 */  lui        $t5, %hi(D_80000300)
    /* 311E8 8007CC08 8DAD0300 */  lw         $t5, %lo(D_80000300)($t5)
    /* 311EC 8007CC0C 15A00006 */  bnez       $t5, .L8007CC28
    /* 311F0 8007CC10 00000000 */   nop
    /* 311F4 8007CC14 3C0C02F5 */  lui        $t4, (0x2F5B2D2 >> 16)
    /* 311F8 8007CC18 358CB2D2 */  ori        $t4, $t4, (0x2F5B2D2 & 0xFFFF)
    /* 311FC 8007CC1C 3C018009 */  lui        $at, %hi(D_80095288)
    /* 31200 8007CC20 1000000F */  b          .L8007CC60
    /* 31204 8007CC24 AC2C5288 */   sw        $t4, %lo(D_80095288)($at)
  .L8007CC28:
    /* 31208 8007CC28 3C0F8000 */  lui        $t7, %hi(D_80000300)
    /* 3120C 8007CC2C 8DEF0300 */  lw         $t7, %lo(D_80000300)($t7)
    /* 31210 8007CC30 24010002 */  addiu      $at, $zero, 0x2
    /* 31214 8007CC34 15E10006 */  bne        $t7, $at, .L8007CC50
    /* 31218 8007CC38 00000000 */   nop
    /* 3121C 8007CC3C 3C0E02E6 */  lui        $t6, (0x2E6025C >> 16)
    /* 31220 8007CC40 35CE025C */  ori        $t6, $t6, (0x2E6025C & 0xFFFF)
    /* 31224 8007CC44 3C018009 */  lui        $at, %hi(D_80095288)
    /* 31228 8007CC48 10000005 */  b          .L8007CC60
    /* 3122C 8007CC4C AC2E5288 */   sw        $t6, %lo(D_80095288)($at)
  .L8007CC50:
    /* 31230 8007CC50 3C1802E6 */  lui        $t8, (0x2E6D354 >> 16)
    /* 31234 8007CC54 3718D354 */  ori        $t8, $t8, (0x2E6D354 & 0xFFFF)
    /* 31238 8007CC58 3C018009 */  lui        $at, %hi(D_80095288)
    /* 3123C 8007CC5C AC385288 */  sw         $t8, %lo(D_80095288)($at)
  .L8007CC60:
    /* 31240 8007CC60 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 31244 8007CC64 8FB00018 */  lw         $s0, 0x18($sp)
    /* 31248 8007CC68 27BD0038 */  addiu      $sp, $sp, 0x38
    /* 3124C 8007CC6C 03E00008 */  jr         $ra
    /* 31250 8007CC70 00000000 */   nop
endlabel func_8007C9E8
    /* 31254 8007CC74 00000000 */  nop

/* Handwritten function */
nonmatching func_8007CC78, 0xC

glabel func_8007CC78
    /* 31258 8007CC78 40026000 */  mfc0       $v0, $12 /* handwritten instruction */
    /* 3125C 8007CC7C 03E00008 */  jr         $ra
    /* 31260 8007CC80 00000000 */   nop
endlabel func_8007CC78
    /* 31264 8007CC84 00000000 */  nop

nonmatching func_8007CC88, 0x10

glabel func_8007CC88
    /* 31268 8007CC88 4442F800 */  cfc1       $v0, $31
    /* 3126C 8007CC8C 44C4F800 */  ctc1       $a0, $31
    /* 31270 8007CC90 03E00008 */  jr         $ra
    /* 31274 8007CC94 00000000 */   nop
endlabel func_8007CC88

/* Handwritten function */
nonmatching func_8007CC98, 0x10

glabel func_8007CC98
    /* 31278 8007CC98 40846000 */  mtc0       $a0, $12 /* handwritten instruction */
    /* 3127C 8007CC9C 00000000 */  nop
    /* 31280 8007CCA0 03E00008 */  jr         $ra
    /* 31284 8007CCA4 00000000 */   nop
endlabel func_8007CC98

/* Handwritten function */
nonmatching func_8007CCA8, 0x58

glabel func_8007CCA8
    /* 31288 8007CCA8 40085000 */  mfc0       $t0, $10 /* handwritten instruction */
    /* 3128C 8007CCAC 2409001F */  addiu      $t1, $zero, 0x1F
    /* 31290 8007CCB0 40890000 */  mtc0       $t1, $0 /* handwritten instruction */
    /* 31294 8007CCB4 40802800 */  mtc0       $zero, $5 /* handwritten instruction */
    /* 31298 8007CCB8 240A0017 */  addiu      $t2, $zero, 0x17
    /* 3129C 8007CCBC 3C09C000 */  lui        $t1, (0xC0000000 >> 16)
    /* 312A0 8007CCC0 40895000 */  mtc0       $t1, $10 /* handwritten instruction */
    /* 312A4 8007CCC4 3C098000 */  lui        $t1, (0x80000000 >> 16)
    /* 312A8 8007CCC8 00095982 */  srl        $t3, $t1, 6
    /* 312AC 8007CCCC 016A5825 */  or         $t3, $t3, $t2
    /* 312B0 8007CCD0 408B1000 */  mtc0       $t3, $2 /* handwritten instruction */
    /* 312B4 8007CCD4 24090001 */  addiu      $t1, $zero, 0x1
    /* 312B8 8007CCD8 40891800 */  mtc0       $t1, $3 /* handwritten instruction */
    /* 312BC 8007CCDC 00000000 */  nop
    /* 312C0 8007CCE0 42000002 */  tlbwi /* handwritten instruction */
    /* 312C4 8007CCE4 00000000 */  nop
    /* 312C8 8007CCE8 00000000 */  nop
    /* 312CC 8007CCEC 00000000 */  nop
    /* 312D0 8007CCF0 00000000 */  nop
    /* 312D4 8007CCF4 40885000 */  mtc0       $t0, $10 /* handwritten instruction */
    /* 312D8 8007CCF8 03E00008 */  jr         $ra
    /* 312DC 8007CCFC 00000000 */   nop
endlabel func_8007CCA8
    /* 312E0 8007CD00 00000000 */  nop
    /* 312E4 8007CD04 00000000 */  nop
