.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_80063B14, 0x80

glabel func_80063B14
    /* 180F4 80063B14 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* 180F8 80063B18 AFB10014 */  sw         $s1, 0x14($sp)
    /* 180FC 80063B1C 00808821 */  addu       $s1, $a0, $zero
    /* 18100 80063B20 AFBF0018 */  sw         $ra, 0x18($sp)
    /* 18104 80063B24 0222102B */  sltu       $v0, $s1, $v0
    /* 18108 80063B28 10400014 */  beqz       $v0, .L80063B7C
    /* 1810C 80063B2C AFB00010 */   sw        $s0, 0x10($sp)
    /* 18110 80063B30 3C028009 */  lui        $v0, %hi(D_80092D38)
    /* 18114 80063B34 8C432D38 */  lw         $v1, %lo(D_80092D38)($v0)
    /* 18118 80063B38 00111100 */  sll        $v0, $s1, 4
    /* 1811C 80063B3C 00431021 */  addu       $v0, $v0, $v1
    /* 18120 80063B40 8C440008 */  lw         $a0, 0x8($v0)
    /* 18124 80063B44 0C018DCC */  jal        func_80063730
    /* 18128 80063B48 00000000 */   nop
    /* 1812C 80063B4C 3050FFFF */  andi       $s0, $v0, 0xFFFF
    /* 18130 80063B50 1200000B */  beqz       $s0, .L80063B80
    /* 18134 80063B54 00001021 */   addu      $v0, $zero, $zero
    /* 18138 80063B58 0C018E6C */  jal        func_800639B0
    /* 1813C 80063B5C 02002021 */   addu      $a0, $s0, $zero
    /* 18140 80063B60 02202021 */  addu       $a0, $s1, $zero
    /* 18144 80063B64 0C018E8F */  jal        func_80063A3C
    /* 18148 80063B68 00402821 */   addu      $a1, $v0, $zero
    /* 1814C 80063B6C 14400004 */  bnez       $v0, .L80063B80
    /* 18150 80063B70 02001021 */   addu      $v0, $s0, $zero
    /* 18154 80063B74 0C018E1E */  jal        func_80063878
    /* 18158 80063B78 02002021 */   addu      $a0, $s0, $zero
  .L80063B7C:
    /* 1815C 80063B7C 00001021 */  addu       $v0, $zero, $zero
  .L80063B80:
    /* 18160 80063B80 8FBF0018 */  lw         $ra, 0x18($sp)
    /* 18164 80063B84 8FB10014 */  lw         $s1, 0x14($sp)
    /* 18168 80063B88 8FB00010 */  lw         $s0, 0x10($sp)
    /* 1816C 80063B8C 03E00008 */  jr         $ra
    /* 18170 80063B90 27BD0020 */   addiu     $sp, $sp, 0x20
endlabel func_80063B14

nonmatching func_80063B94, 0x8

glabel func_80063B94
    /* 18174 80063B94 3C028018 */  lui        $v0, %hi(D_801823E0)
    /* 18178 80063B98 8C4223E0 */  lw         $v0, %lo(D_801823E0)($v0)
endlabel func_80063B94
