.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_8004E094, 0x64

glabel func_8004E094
    /* 2674 8004E094 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* 2678 8004E098 AFBF001C */  sw         $ra, 0x1C($sp)
    /* 267C 8004E09C 0C01F27A */  jal        func_8007C9E8
    /* 2680 8004E0A0 AFB00018 */   sw        $s0, 0x18($sp)
    /* 2684 8004E0A4 3C108017 */  lui        $s0, %hi(D_8016DC10)
    /* 2688 8004E0A8 2610DC10 */  addiu      $s0, $s0, %lo(D_8016DC10)
    /* 268C 8004E0AC 02002021 */  addu       $a0, $s0, $zero
    /* 2690 8004E0B0 3C028018 */  lui        $v0, %hi(D_801786B8)
    /* 2694 8004E0B4 AC4086B8 */  sw         $zero, %lo(D_801786B8)($v0)
    /* 2698 8004E0B8 3C028017 */  lui        $v0, %hi(D_8016DBD0)
    /* 269C 8004E0BC 2442DBD0 */  addiu      $v0, $v0, %lo(D_8016DBD0)
    /* 26A0 8004E0C0 AFA20010 */  sw         $v0, 0x10($sp)
    /* 26A4 8004E0C4 2402000A */  addiu      $v0, $zero, 0xA
    /* 26A8 8004E0C8 3C068005 */  lui        $a2, %hi(func_8004E0F8)
    /* 26AC 8004E0CC 24050001 */  addiu      $a1, $zero, 0x1
    /* 26B0 8004E0D0 24C6E0F8 */  addiu      $a2, $a2, %lo(func_8004E0F8)
    /* 26B4 8004E0D4 00003821 */  addu       $a3, $zero, $zero
    /* 26B8 8004E0D8 0C01EF42 */  jal        func_8007BD08
    /* 26BC 8004E0DC AFA20014 */   sw        $v0, 0x14($sp)
    /* 26C0 8004E0E0 0C01F43A */  jal        func_8007D0E8
    /* 26C4 8004E0E4 02002021 */   addu      $a0, $s0, $zero
    /* 26C8 8004E0E8 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 26CC 8004E0EC 8FB00018 */  lw         $s0, 0x18($sp)
    /* 26D0 8004E0F0 03E00008 */  jr         $ra
    /* 26D4 8004E0F4 27BD0020 */   addiu     $sp, $sp, 0x20
endlabel func_8004E094
