.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_80082F84, 0x88

glabel func_80082F84
    /* 37564 80082F84 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* 37568 80082F88 AFA50024 */  sw         $a1, 0x24($sp)
    /* 3756C 80082F8C AFBF001C */  sw         $ra, 0x1C($sp)
    /* 37570 80082F90 3C058008 */  lui        $a1, %hi(func_80085154)
    /* 37574 80082F94 3C068008 */  lui        $a2, %hi(func_80085068)
    /* 37578 80082F98 24C65068 */  addiu      $a2, $a2, %lo(func_80085068)
    /* 3757C 80082F9C 24A55154 */  addiu      $a1, $a1, %lo(func_80085154)
    /* 37580 80082FA0 AFA40020 */  sw         $a0, 0x20($sp)
    /* 37584 80082FA4 0C0213BE */  jal        func_80084EF8
    /* 37588 80082FA8 24070001 */   addiu     $a3, $zero, 0x1
    /* 3758C 80082FAC 240E0020 */  addiu      $t6, $zero, 0x20
    /* 37590 80082FB0 AFAE0010 */  sw         $t6, 0x10($sp)
    /* 37594 80082FB4 00002025 */  or         $a0, $zero, $zero
    /* 37598 80082FB8 00002825 */  or         $a1, $zero, $zero
    /* 3759C 80082FBC 8FA60024 */  lw         $a2, 0x24($sp)
    /* 375A0 80082FC0 0C01FF52 */  jal        func_8007FD48
    /* 375A4 80082FC4 24070001 */   addiu     $a3, $zero, 0x1
    /* 375A8 80082FC8 8FA80020 */  lw         $t0, 0x20($sp)
    /* 375AC 80082FCC 3C013F80 */  lui        $at, (0x3F800000 >> 16)
    /* 375B0 80082FD0 44802000 */  mtc1       $zero, $ft0
    /* 375B4 80082FD4 44813000 */  mtc1       $at, $ft1
    /* 375B8 80082FD8 240F0001 */  addiu      $t7, $zero, 0x1
    /* 375BC 80082FDC AD020014 */  sw         $v0, 0x14($t0)
    /* 375C0 80082FE0 AD0F0024 */  sw         $t7, 0x24($t0)
    /* 375C4 80082FE4 AD000030 */  sw         $zero, 0x30($t0)
    /* 375C8 80082FE8 AD00001C */  sw         $zero, 0x1C($t0)
    /* 375CC 80082FEC AD000028 */  sw         $zero, 0x28($t0)
    /* 375D0 80082FF0 AD00002C */  sw         $zero, 0x2C($t0)
    /* 375D4 80082FF4 E5040020 */  swc1       $ft0, 0x20($t0)
    /* 375D8 80082FF8 E5060018 */  swc1       $ft1, 0x18($t0)
    /* 375DC 80082FFC 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 375E0 80083000 27BD0020 */  addiu      $sp, $sp, 0x20
    /* 375E4 80083004 03E00008 */  jr         $ra
    /* 375E8 80083008 00000000 */   nop
endlabel func_80082F84
