.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_80075EC8, 0xC8

glabel func_80075EC8
    /* 2A4A8 80075EC8 27BDFFD0 */  addiu      $sp, $sp, -0x30
    /* 2A4AC 80075ECC AFB50024 */  sw         $s5, 0x24($sp)
    /* 2A4B0 80075ED0 0080A821 */  addu       $s5, $a0, $zero
    /* 2A4B4 80075ED4 AFB3001C */  sw         $s3, 0x1C($sp)
    /* 2A4B8 80075ED8 00A09821 */  addu       $s3, $a1, $zero
    /* 2A4BC 80075EDC AFB10014 */  sw         $s1, 0x14($sp)
    /* 2A4C0 80075EE0 00C08821 */  addu       $s1, $a2, $zero
    /* 2A4C4 80075EE4 AFBF002C */  sw         $ra, 0x2C($sp)
    /* 2A4C8 80075EE8 AFB60028 */  sw         $s6, 0x28($sp)
    /* 2A4CC 80075EEC AFB40020 */  sw         $s4, 0x20($sp)
    /* 2A4D0 80075EF0 AFB20018 */  sw         $s2, 0x18($sp)
    /* 2A4D4 80075EF4 0C01D3A8 */  jal        func_80074EA0
    /* 2A4D8 80075EF8 AFB00010 */   sw        $s0, 0x10($sp)
    /* 2A4DC 80075EFC 00009021 */  addu       $s2, $zero, $zero
    /* 2A4E0 80075F00 12200015 */  beqz       $s1, .L80075F58
    /* 2A4E4 80075F04 0040A021 */   addu      $s4, $v0, $zero
    /* 2A4E8 80075F08 34168000 */  ori        $s6, $zero, 0x8000
  .L80075F0C:
    /* 2A4EC 80075F0C 02D1102B */  sltu       $v0, $s6, $s1
    /* 2A4F0 80075F10 10400002 */  beqz       $v0, .L80075F1C
    /* 2A4F4 80075F14 02208021 */   addu      $s0, $s1, $zero
    /* 2A4F8 80075F18 34108000 */  ori        $s0, $zero, 0x8000
  .L80075F1C:
    /* 2A4FC 80075F1C 3C04B1FF */  lui        $a0, (0xB1FF0000 >> 16)
    /* 2A500 80075F20 02602821 */  addu       $a1, $s3, $zero
    /* 2A504 80075F24 0C01D4D8 */  jal        func_80075360
    /* 2A508 80075F28 02003021 */   addu      $a2, $s0, $zero
    /* 2A50C 80075F2C 24040606 */  addiu      $a0, $zero, 0x606
    /* 2A510 80075F30 02A02821 */  addu       $a1, $s5, $zero
    /* 2A514 80075F34 02003021 */  addu       $a2, $s0, $zero
    /* 2A518 80075F38 0C01D6DE */  jal        func_80075B78
    /* 2A51C 80075F3C 00003821 */   addu      $a3, $zero, $zero
    /* 2A520 80075F40 10400005 */  beqz       $v0, .L80075F58
    /* 2A524 80075F44 00000000 */   nop
    /* 2A528 80075F48 02629821 */  addu       $s3, $s3, $v0
    /* 2A52C 80075F4C 02228823 */  subu       $s1, $s1, $v0
    /* 2A530 80075F50 1620FFEE */  bnez       $s1, .L80075F0C
    /* 2A534 80075F54 02429021 */   addu      $s2, $s2, $v0
  .L80075F58:
    /* 2A538 80075F58 0C01D3B6 */  jal        func_80074ED8
    /* 2A53C 80075F5C 02802021 */   addu      $a0, $s4, $zero
    /* 2A540 80075F60 02401021 */  addu       $v0, $s2, $zero
    /* 2A544 80075F64 8FBF002C */  lw         $ra, 0x2C($sp)
    /* 2A548 80075F68 8FB60028 */  lw         $s6, 0x28($sp)
    /* 2A54C 80075F6C 8FB50024 */  lw         $s5, 0x24($sp)
    /* 2A550 80075F70 8FB40020 */  lw         $s4, 0x20($sp)
    /* 2A554 80075F74 8FB3001C */  lw         $s3, 0x1C($sp)
    /* 2A558 80075F78 8FB20018 */  lw         $s2, 0x18($sp)
    /* 2A55C 80075F7C 8FB10014 */  lw         $s1, 0x14($sp)
    /* 2A560 80075F80 8FB00010 */  lw         $s0, 0x10($sp)
    /* 2A564 80075F84 27BD0030 */  addiu      $sp, $sp, 0x30
    /* 2A568 80075F88 03E00008 */  jr         $ra
    /* 2A56C 80075F8C 00000000 */   nop
endlabel func_80075EC8
