.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_80061EE8, 0x24

glabel func_80061EE8
    /* 164C8 80061EE8 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* 164CC 80061EEC 8FA20030 */  lw         $v0, 0x30($sp)
    /* 164D0 80061EF0 AFBF0018 */  sw         $ra, 0x18($sp)
    /* 164D4 80061EF4 AFA00014 */  sw         $zero, 0x14($sp)
    /* 164D8 80061EF8 0C01873C */  jal        func_80061CF0
    /* 164DC 80061EFC AFA20010 */   sw        $v0, 0x10($sp)
    /* 164E0 80061F00 8FBF0018 */  lw         $ra, 0x18($sp)
    /* 164E4 80061F04 03E00008 */  jr         $ra
    /* 164E8 80061F08 27BD0020 */   addiu     $sp, $sp, 0x20
endlabel func_80061EE8
