.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_8004D1C8, 0x168

glabel func_8004D1C8
    /* 17A8 8004D1C8 27BDFFA0 */  addiu      $sp, $sp, -0x60
    /* 17AC 8004D1CC AFB3004C */  sw         $s3, 0x4C($sp)
    /* 17B0 8004D1D0 00809821 */  addu       $s3, $a0, $zero
    /* 17B4 8004D1D4 AFB20048 */  sw         $s2, 0x48($sp)
    /* 17B8 8004D1D8 00C09021 */  addu       $s2, $a2, $zero
    /* 17BC 8004D1DC AFB10044 */  sw         $s1, 0x44($sp)
    /* 17C0 8004D1E0 00A08821 */  addu       $s1, $a1, $zero
    /* 17C4 8004D1E4 AFB40050 */  sw         $s4, 0x50($sp)
    /* 17C8 8004D1E8 3274003F */  andi       $s4, $s3, 0x3F
    /* 17CC 8004D1EC AFBF0058 */  sw         $ra, 0x58($sp)
    /* 17D0 8004D1F0 AFB50054 */  sw         $s5, 0x54($sp)
    /* 17D4 8004D1F4 12800034 */  beqz       $s4, .L8004D2C8
    /* 17D8 8004D1F8 AFB00040 */   sw        $s0, 0x40($sp)
    /* 17DC 8004D1FC 3C028017 */  lui        $v0, %hi(D_8016DBD0)
    /* 17E0 8004D200 2455DBD0 */  addiu      $s5, $v0, %lo(D_8016DBD0)
    /* 17E4 8004D204 02A02021 */  addu       $a0, $s5, $zero
    /* 17E8 8004D208 0C01EEA6 */  jal        func_8007BA98
    /* 17EC 8004D20C 24050040 */   addiu     $a1, $zero, 0x40
    /* 17F0 8004D210 27A40020 */  addiu      $a0, $sp, 0x20
    /* 17F4 8004D214 00002821 */  addu       $a1, $zero, $zero
    /* 17F8 8004D218 00A03021 */  addu       $a2, $a1, $zero
    /* 17FC 8004D21C 2407FFC0 */  addiu      $a3, $zero, -0x40
    /* 1800 8004D220 02673824 */  and        $a3, $s3, $a3
    /* 1804 8004D224 24020040 */  addiu      $v0, $zero, 0x40
    /* 1808 8004D228 3C108017 */  lui        $s0, %hi(D_8016DF70)
    /* 180C 8004D22C 2610DF70 */  addiu      $s0, $s0, %lo(D_8016DF70)
    /* 1810 8004D230 AFB50010 */  sw         $s5, 0x10($sp)
    /* 1814 8004D234 AFA20014 */  sw         $v0, 0x14($sp)
    /* 1818 8004D238 0C023946 */  jal        func_8008E518
    /* 181C 8004D23C AFB00018 */   sw        $s0, 0x18($sp)
    /* 1820 8004D240 02002021 */  addu       $a0, $s0, $zero
    /* 1824 8004D244 27A50038 */  addiu      $a1, $sp, 0x38
    /* 1828 8004D248 0C01F342 */  jal        func_8007CD08
    /* 182C 8004D24C 24060001 */   addiu     $a2, $zero, 0x1
    /* 1830 8004D250 02542821 */  addu       $a1, $s2, $s4
    /* 1834 8004D254 28A20041 */  slti       $v0, $a1, 0x41
    /* 1838 8004D258 1040000D */  beqz       $v0, .L8004D290
    /* 183C 8004D25C 02801821 */   addu      $v1, $s4, $zero
    /* 1840 8004D260 0065102A */  slt        $v0, $v1, $a1
    /* 1844 8004D264 10400029 */  beqz       $v0, func_8004D30C
    /* 1848 8004D268 02A02021 */   addu      $a0, $s5, $zero
  .L8004D26C:
    /* 184C 8004D26C 00641021 */  addu       $v0, $v1, $a0
    /* 1850 8004D270 90420000 */  lbu        $v0, 0x0($v0)
    /* 1854 8004D274 24630001 */  addiu      $v1, $v1, 0x1
    /* 1858 8004D278 A2220000 */  sb         $v0, 0x0($s1)
    /* 185C 8004D27C 0065102A */  slt        $v0, $v1, $a1
    /* 1860 8004D280 1440FFFA */  bnez       $v0, .L8004D26C
    /* 1864 8004D284 26310001 */   addiu     $s1, $s1, 0x1
    /* 1868 8004D288 080134C3 */  j          func_8004D30C
    /* 186C 8004D28C 00000000 */   nop
  .L8004D290:
    /* 1870 8004D290 28620040 */  slti       $v0, $v1, 0x40
    /* 1874 8004D294 1040000A */  beqz       $v0, .L8004D2C0
    /* 1878 8004D298 02A02021 */   addu      $a0, $s5, $zero
  .L8004D29C:
    /* 187C 8004D29C 2652FFFF */  addiu      $s2, $s2, -0x1
    /* 1880 8004D2A0 26730001 */  addiu      $s3, $s3, 0x1
    /* 1884 8004D2A4 00641021 */  addu       $v0, $v1, $a0
    /* 1888 8004D2A8 90420000 */  lbu        $v0, 0x0($v0)
    /* 188C 8004D2AC 24630001 */  addiu      $v1, $v1, 0x1
    /* 1890 8004D2B0 A2220000 */  sb         $v0, 0x0($s1)
    /* 1894 8004D2B4 28620040 */  slti       $v0, $v1, 0x40
    /* 1898 8004D2B8 1440FFF8 */  bnez       $v0, .L8004D29C
    /* 189C 8004D2BC 26310001 */   addiu     $s1, $s1, 0x1
  .L8004D2C0:
    /* 18A0 8004D2C0 0C01EF2A */  jal        func_8007BCA8
    /* 18A4 8004D2C4 00000000 */   nop
  .L8004D2C8:
    /* 18A8 8004D2C8 02202021 */  addu       $a0, $s1, $zero
    /* 18AC 8004D2CC 0C01EEA6 */  jal        func_8007BA98
    /* 18B0 8004D2D0 02402821 */   addu      $a1, $s2, $zero
    /* 18B4 8004D2D4 27A40020 */  addiu      $a0, $sp, 0x20
    /* 18B8 8004D2D8 00002821 */  addu       $a1, $zero, $zero
    /* 18BC 8004D2DC 00A03021 */  addu       $a2, $a1, $zero
    /* 18C0 8004D2E0 02603821 */  addu       $a3, $s3, $zero
    /* 18C4 8004D2E4 3C108017 */  lui        $s0, %hi(D_8016DF70)
    /* 18C8 8004D2E8 2610DF70 */  addiu      $s0, $s0, %lo(D_8016DF70)
    /* 18CC 8004D2EC AFB10010 */  sw         $s1, 0x10($sp)
    /* 18D0 8004D2F0 AFB20014 */  sw         $s2, 0x14($sp)
    /* 18D4 8004D2F4 0C023946 */  jal        func_8008E518
    /* 18D8 8004D2F8 AFB00018 */   sw        $s0, 0x18($sp)
    /* 18DC 8004D2FC 02002021 */  addu       $a0, $s0, $zero
    /* 18E0 8004D300 27A50038 */  addiu      $a1, $sp, 0x38
    /* 18E4 8004D304 0C01F342 */  jal        func_8007CD08
    /* 18E8 8004D308 24060001 */   addiu     $a2, $zero, 0x1
  alabel func_8004D30C
    /* 18EC 8004D30C 8FBF0058 */  lw         $ra, 0x58($sp)
    /* 18F0 8004D310 8FB50054 */  lw         $s5, 0x54($sp)
    /* 18F4 8004D314 8FB40050 */  lw         $s4, 0x50($sp)
    /* 18F8 8004D318 8FB3004C */  lw         $s3, 0x4C($sp)
    /* 18FC 8004D31C 8FB20048 */  lw         $s2, 0x48($sp)
    /* 1900 8004D320 8FB10044 */  lw         $s1, 0x44($sp)
    /* 1904 8004D324 8FB00040 */  lw         $s0, 0x40($sp)
    /* 1908 8004D328 03E00008 */  jr         $ra
    /* 190C 8004D32C 27BD0060 */   addiu     $sp, $sp, 0x60
endlabel func_8004D1C8

nonmatching func_8004D330, 0x14

glabel func_8004D330
    /* 1910 8004D330 3C028009 */  lui        $v0, %hi(D_80090CF8)
    /* 1914 8004D334 8C430CF8 */  lw         $v1, %lo(D_80090CF8)($v0)
    /* 1918 8004D338 3C028009 */  lui        $v0, %hi(D_80090D10)
    /* 191C 8004D33C 03E00008 */  jr         $ra
    /* 1920 8004D340 AC430D10 */   sw        $v1, %lo(D_80090D10)($v0)
endlabel func_8004D330

nonmatching func_8004D344, 0x14

glabel func_8004D344
    /* 1924 8004D344 3C028009 */  lui        $v0, %hi(D_80090D10)
    /* 1928 8004D348 8C430D10 */  lw         $v1, %lo(D_80090D10)($v0)
    /* 192C 8004D34C 3C028009 */  lui        $v0, %hi(D_80090CF8)
    /* 1930 8004D350 03E00008 */  jr         $ra
    /* 1934 8004D354 AC430CF8 */   sw        $v1, %lo(D_80090CF8)($v0)
endlabel func_8004D344

nonmatching func_8004D358, 0x28

glabel func_8004D358
    /* 1938 8004D358 3C028009 */  lui        $v0, %hi(D_80090CFC)
    /* 193C 8004D35C 8C420CFC */  lw         $v0, %lo(D_80090CFC)($v0)
    /* 1940 8004D360 10400003 */  beqz       $v0, .L8004D370
    /* 1944 8004D364 3C038009 */   lui       $v1, %hi(D_80090CF8)
    /* 1948 8004D368 03E00008 */  jr         $ra
    /* 194C 8004D36C AC620CF8 */   sw        $v0, %lo(D_80090CF8)($v1)
  .L8004D370:
    /* 1950 8004D370 3C02801A */  lui        $v0, %hi(D_801A3000)
    /* 1954 8004D374 24423000 */  addiu      $v0, $v0, %lo(D_801A3000)
    /* 1958 8004D378 03E00008 */  jr         $ra
    /* 195C 8004D37C AC620CF8 */   sw        $v0, %lo(D_80090CF8)($v1)
endlabel func_8004D358

nonmatching func_8004D380, 0x28

glabel func_8004D380
    /* 1960 8004D380 3C028009 */  lui        $v0, %hi(D_80090D08)
    /* 1964 8004D384 8C420D08 */  lw         $v0, %lo(D_80090D08)($v0)
    /* 1968 8004D388 14400005 */  bnez       $v0, .L8004D3A0
    /* 196C 8004D38C 00000000 */   nop
    /* 1970 8004D390 3C028009 */  lui        $v0, %hi(D_80090CF8)
    /* 1974 8004D394 8C420CF8 */  lw         $v0, %lo(D_80090CF8)($v0)
    /* 1978 8004D398 03E00008 */  jr         $ra
    /* 197C 8004D39C 00000000 */   nop
  .L8004D3A0:
    /* 1980 8004D3A0 03E00008 */  jr         $ra
    /* 1984 8004D3A4 00000000 */   nop
endlabel func_8004D380

nonmatching func_8004D3A8, 0x78

glabel func_8004D3A8
    /* 1988 8004D3A8 00001821 */  addu       $v1, $zero, $zero
    /* 198C 8004D3AC 3C068009 */  lui        $a2, %hi(D_80090D00)
    /* 1990 8004D3B0 3C028009 */  lui        $v0, %hi(D_80090D04)
    /* 1994 8004D3B4 ACC40D00 */  sw         $a0, %lo(D_80090D00)($a2)
    /* 1998 8004D3B8 18A00009 */  blez       $a1, .L8004D3E0
    /* 199C 8004D3BC AC450D04 */   sw        $a1, %lo(D_80090D04)($v0)
    /* 19A0 8004D3C0 00C02021 */  addu       $a0, $a2, $zero
  .L8004D3C4:
    /* 19A4 8004D3C4 8C820D00 */  lw         $v0, %lo(D_80090D00)($a0)
    /* 19A8 8004D3C8 00431021 */  addu       $v0, $v0, $v1
    /* 19AC 8004D3CC 24630001 */  addiu      $v1, $v1, 0x1
    /* 19B0 8004D3D0 A0400000 */  sb         $zero, 0x0($v0)
    /* 19B4 8004D3D4 0065102A */  slt        $v0, $v1, $a1
    /* 19B8 8004D3D8 1440FFFA */  bnez       $v0, .L8004D3C4
    /* 19BC 8004D3DC 00000000 */   nop
  .L8004D3E0:
    /* 19C0 8004D3E0 3C038009 */  lui        $v1, %hi(D_80090D00)
    /* 19C4 8004D3E4 8C620D00 */  lw         $v0, %lo(D_80090D00)($v1)
    /* 19C8 8004D3E8 3042000F */  andi       $v0, $v0, 0xF
    /* 19CC 8004D3EC 1040000A */  beqz       $v0, .L8004D418
    /* 19D0 8004D3F0 00602821 */   addu      $a1, $v1, $zero
    /* 19D4 8004D3F4 3C048009 */  lui        $a0, %hi(D_80090D04)
  .L8004D3F8:
    /* 19D8 8004D3F8 8CA20D00 */  lw         $v0, %lo(D_80090D00)($a1)
    /* 19DC 8004D3FC 8C830D04 */  lw         $v1, %lo(D_80090D04)($a0)
    /* 19E0 8004D400 24420001 */  addiu      $v0, $v0, 0x1
    /* 19E4 8004D404 2463FFFF */  addiu      $v1, $v1, -0x1
    /* 19E8 8004D408 ACA20D00 */  sw         $v0, %lo(D_80090D00)($a1)
    /* 19EC 8004D40C 3042000F */  andi       $v0, $v0, 0xF
    /* 19F0 8004D410 1440FFF9 */  bnez       $v0, .L8004D3F8
    /* 19F4 8004D414 AC830D04 */   sw        $v1, %lo(D_80090D04)($a0)
  .L8004D418:
    /* 19F8 8004D418 03E00008 */  jr         $ra
    /* 19FC 8004D41C 00000000 */   nop
endlabel func_8004D3A8

nonmatching func_8004D420, 0x14

glabel func_8004D420
    /* 1A00 8004D420 3C028009 */  lui        $v0, %hi(D_80090D00)
    /* 1A04 8004D424 AC400D00 */  sw         $zero, %lo(D_80090D00)($v0)
    /* 1A08 8004D428 3C028009 */  lui        $v0, %hi(D_80090D04)
    /* 1A0C 8004D42C 03E00008 */  jr         $ra
    /* 1A10 8004D430 AC400D04 */   sw        $zero, %lo(D_80090D04)($v0)
endlabel func_8004D420

nonmatching func_8004D434, 0x74

glabel func_8004D434
    /* 1A14 8004D434 2484000F */  addiu      $a0, $a0, 0xF
    /* 1A18 8004D438 2402FFF0 */  addiu      $v0, $zero, -0x10
    /* 1A1C 8004D43C 3C078009 */  lui        $a3, %hi(D_80090D08)
    /* 1A20 8004D440 8CE30D08 */  lw         $v1, %lo(D_80090D08)($a3)
    /* 1A24 8004D444 1060000C */  beqz       $v1, .L8004D478
    /* 1A28 8004D448 00822024 */   and       $a0, $a0, $v0
    /* 1A2C 8004D44C 3C068009 */  lui        $a2, %hi(D_80090D0C)
    /* 1A30 8004D450 8CC50D0C */  lw         $a1, %lo(D_80090D0C)($a2)
    /* 1A34 8004D454 00A4102A */  slt        $v0, $a1, $a0
    /* 1A38 8004D458 54400008 */  bnel       $v0, $zero, .L8004D47C
    /* 1A3C 8004D45C 3C058009 */   lui       $a1, %hi(D_80090CF8)
    /* 1A40 8004D460 00601021 */  addu       $v0, $v1, $zero
    /* 1A44 8004D464 00441821 */  addu       $v1, $v0, $a0
    /* 1A48 8004D468 ACE30D08 */  sw         $v1, %lo(D_80090D08)($a3)
    /* 1A4C 8004D46C 00A41823 */  subu       $v1, $a1, $a0
    /* 1A50 8004D470 03E00008 */  jr         $ra
    /* 1A54 8004D474 ACC30D0C */   sw        $v1, %lo(D_80090D0C)($a2)
  .L8004D478:
    /* 1A58 8004D478 3C058009 */  lui        $a1, %hi(D_80090CF8)
  .L8004D47C:
    /* 1A5C 8004D47C 8CA30CF8 */  lw         $v1, %lo(D_80090CF8)($a1)
    /* 1A60 8004D480 3C02803E */  lui        $v0, %hi(D_803DA400)
    /* 1A64 8004D484 2442A400 */  addiu      $v0, $v0, %lo(D_803DA400)
    /* 1A68 8004D488 00642021 */  addu       $a0, $v1, $a0
    /* 1A6C 8004D48C 0044102A */  slt        $v0, $v0, $a0
    /* 1A70 8004D490 14400003 */  bnez       $v0, .L8004D4A0
    /* 1A74 8004D494 00601021 */   addu      $v0, $v1, $zero
    /* 1A78 8004D498 03E00008 */  jr         $ra
    /* 1A7C 8004D49C ACA40CF8 */   sw        $a0, %lo(D_80090CF8)($a1)
  .L8004D4A0:
    /* 1A80 8004D4A0 03E00008 */  jr         $ra
    /* 1A84 8004D4A4 00001021 */   addu      $v0, $zero, $zero
endlabel func_8004D434

nonmatching func_8004D4A8, 0x8

glabel func_8004D4A8
    /* 1A88 8004D4A8 3C088009 */  lui        $t0, %hi(D_80090D00)
    /* 1A8C 8004D4AC 8D050D00 */  lw         $a1, %lo(D_80090D00)($t0)
endlabel func_8004D4A8
