.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_8005FC3C, 0x7C

glabel func_8005FC3C
    /* 1421C 8005FC3C 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 14220 8005FC40 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 14224 8005FC44 0C018F89 */  jal        func_80063E24
    /* 14228 8005FC48 AFB00010 */   sw        $s0, 0x10($sp)
    /* 1422C 8005FC4C 3C038018 */  lui        $v1, %hi(D_80181E48)
    /* 14230 8005FC50 8C621E48 */  lw         $v0, %lo(D_80181E48)($v1)
    /* 14234 8005FC54 14400014 */  bnez       $v0, .L8005FCA8
    /* 14238 8005FC58 24020001 */   addiu     $v0, $zero, 0x1
    /* 1423C 8005FC5C AC621E48 */  sw         $v0, %lo(D_80181E48)($v1)
    /* 14240 8005FC60 3C028017 */  lui        $v0, %hi(D_80173D08)
    /* 14244 8005FC64 8C433D08 */  lw         $v1, %lo(D_80173D08)($v0)
    /* 14248 8005FC68 3C028018 */  lui        $v0, %hi(D_80181E4C)
    /* 1424C 8005FC6C 0C01886C */  jal        func_800621B0
    /* 14250 8005FC70 AC431E4C */   sw        $v1, %lo(D_80181E4C)($v0)
    /* 14254 8005FC74 2450FFFF */  addiu      $s0, $v0, -0x1
    /* 14258 8005FC78 0600000A */  bltz       $s0, .L8005FCA4
    /* 1425C 8005FC7C 3C028009 */   lui       $v0, %hi(D_80091E54)
    /* 14260 8005FC80 02002021 */  addu       $a0, $s0, $zero
  .L8005FC84:
    /* 14264 8005FC84 0C018870 */  jal        func_800621C0
    /* 14268 8005FC88 00002821 */   addu      $a1, $zero, $zero
    /* 1426C 8005FC8C 0C018833 */  jal        func_800620CC
    /* 14270 8005FC90 00402021 */   addu      $a0, $v0, $zero
    /* 14274 8005FC94 2610FFFF */  addiu      $s0, $s0, -0x1
    /* 14278 8005FC98 0603FFFA */  bgezl      $s0, .L8005FC84
    /* 1427C 8005FC9C 02002021 */   addu      $a0, $s0, $zero
    /* 14280 8005FCA0 3C028009 */  lui        $v0, %hi(D_80091E54)
  .L8005FCA4:
    /* 14284 8005FCA4 AC401E54 */  sw         $zero, %lo(D_80091E54)($v0)
  .L8005FCA8:
    /* 14288 8005FCA8 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 1428C 8005FCAC 8FB00010 */  lw         $s0, 0x10($sp)
    /* 14290 8005FCB0 03E00008 */  jr         $ra
    /* 14294 8005FCB4 27BD0018 */   addiu     $sp, $sp, 0x18
endlabel func_8005FC3C

nonmatching func_8005FCB8, 0x8

glabel func_8005FCB8
    /* 14298 8005FCB8 3C028009 */  lui        $v0, %hi(D_80092B80)
    /* 1429C 8005FCBC 8C422B80 */  lw         $v0, %lo(D_80092B80)($v0)
endlabel func_8005FCB8
