.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_800502B8, 0x1C

glabel func_800502B8
    /* 4898 800502B8 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 489C 800502BC AFBF0010 */  sw         $ra, 0x10($sp)
    /* 48A0 800502C0 0C016DF6 */  jal        func_8005B7D8
    /* 48A4 800502C4 00000000 */   nop
    /* 48A8 800502C8 8FBF0010 */  lw         $ra, 0x10($sp)
    /* 48AC 800502CC 03E00008 */  jr         $ra
    /* 48B0 800502D0 27BD0018 */   addiu     $sp, $sp, 0x18
endlabel func_800502B8
