.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_80075C30, 0x4C

glabel func_80075C30
    /* 2A210 80075C30 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 2A214 80075C34 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 2A218 80075C38 0C01D3A8 */  jal        func_80074EA0
    /* 2A21C 80075C3C AFB00010 */   sw        $s0, 0x10($sp)
    /* 2A220 80075C40 24040101 */  addiu      $a0, $zero, 0x101
    /* 2A224 80075C44 00408021 */  addu       $s0, $v0, $zero
    /* 2A228 80075C48 00002821 */  addu       $a1, $zero, $zero
    /* 2A22C 80075C4C 00003021 */  addu       $a2, $zero, $zero
    /* 2A230 80075C50 0C01D6DE */  jal        func_80075B78
    /* 2A234 80075C54 00003821 */   addu      $a3, $zero, $zero
    /* 2A238 80075C58 02002021 */  addu       $a0, $s0, $zero
    /* 2A23C 80075C5C 0C01D3B6 */  jal        func_80074ED8
    /* 2A240 80075C60 00408021 */   addu      $s0, $v0, $zero
    /* 2A244 80075C64 02001021 */  addu       $v0, $s0, $zero
    /* 2A248 80075C68 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 2A24C 80075C6C 8FB00010 */  lw         $s0, 0x10($sp)
    /* 2A250 80075C70 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 2A254 80075C74 03E00008 */  jr         $ra
    /* 2A258 80075C78 00000000 */   nop
endlabel func_80075C30
