.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_8008FFA0, 0x7C

glabel func_8008FFA0
    /* 44580 8008FFA0 27BDFFF8 */  addiu      $sp, $sp, -0x8
    /* 44584 8008FFA4 14C00002 */  bnez       $a2, .L8008FFB0
    /* 44588 8008FFA8 00000000 */   nop
    /* 4458C 8008FFAC 0007000D */  break      7
  .L8008FFB0:
    /* 44590 8008FFB0 2401FFFF */  addiu      $at, $zero, -0x1
    /* 44594 8008FFB4 14C10004 */  bne        $a2, $at, .L8008FFC8
    /* 44598 8008FFB8 3C018000 */   lui       $at, (0x80000000 >> 16)
    /* 4459C 8008FFBC 14A10002 */  bne        $a1, $at, .L8008FFC8
    /* 445A0 8008FFC0 00000000 */   nop
    /* 445A4 8008FFC4 0006000D */  break      6
  .L8008FFC8:
    /* 445A8 8008FFC8 00C20019 */  multu      $a2, $v0
    /* 445AC 8008FFCC AFA20000 */  sw         $v0, 0x0($sp)
    /* 445B0 8008FFD0 27AF0000 */  addiu      $t7, $sp, 0x0
    /* 445B4 8008FFD4 00007012 */  mflo       $t6
    /* 445B8 8008FFD8 00AE1823 */  subu       $v1, $a1, $t6
    /* 445BC 8008FFDC 04410008 */  bgez       $v0, .L80090000
    /* 445C0 8008FFE0 AFA30004 */   sw        $v1, 0x4($sp)
    /* 445C4 8008FFE4 AFA20000 */  sw         $v0, 0x0($sp)
    /* 445C8 8008FFE8 18600005 */  blez       $v1, .L80090000
    /* 445CC 8008FFEC AFA30004 */   sw        $v1, 0x4($sp)
    /* 445D0 8008FFF0 24420001 */  addiu      $v0, $v0, 0x1
    /* 445D4 8008FFF4 00661823 */  subu       $v1, $v1, $a2
    /* 445D8 8008FFF8 AFA30004 */  sw         $v1, 0x4($sp)
    /* 445DC 8008FFFC AFA20000 */  sw         $v0, 0x0($sp)
  .L80090000:
    /* 445E0 80090000 8DE10000 */  lw         $at, 0x0($t7)
    /* 445E4 80090004 00801025 */  or         $v0, $a0, $zero
    /* 445E8 80090008 AC810000 */  sw         $at, 0x0($a0)
    /* 445EC 8009000C 8DE80004 */  lw         $t0, 0x4($t7)
    /* 445F0 80090010 27BD0008 */  addiu      $sp, $sp, 0x8
    /* 445F4 80090014 03E00008 */  jr         $ra
    /* 445F8 80090018 AC880004 */   sw        $t0, 0x4($a0)
endlabel func_8008FFA0
    /* 445FC 8009001C 00000000 */  nop
    /* 44600 80090020 00000000 */  nop
    /* 44604 80090024 00000000 */  nop
