.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_8008155C, 0x180

glabel func_8008155C
    /* 35B3C 8008155C 27BDFFC0 */  addiu      $sp, $sp, -0x40
    /* 35B40 80081560 AFBF0024 */  sw         $ra, 0x24($sp)
    /* 35B44 80081564 AFB10020 */  sw         $s1, 0x20($sp)
    /* 35B48 80081568 AFB0001C */  sw         $s0, 0x1C($sp)
    /* 35B4C 8008156C 8CA6000C */  lw         $a2, 0xC($a1)
    /* 35B50 80081570 AC800020 */  sw         $zero, 0x20($a0)
    /* 35B54 80081574 AC800018 */  sw         $zero, 0x18($a0)
    /* 35B58 80081578 3C0E8009 */  lui        $t6, %hi(D_800952D0)
    /* 35B5C 8008157C 8DCE52D0 */  lw         $t6, %lo(D_800952D0)($t6)
    /* 35B60 80081580 240F00FF */  addiu      $t7, $zero, 0xFF
    /* 35B64 80081584 241801E8 */  addiu      $t8, $zero, 0x1E8
    /* 35B68 80081588 24197FFF */  addiu      $t9, $zero, 0x7FFF
    /* 35B6C 8008158C A48F0030 */  sh         $t7, 0x30($a0)
    /* 35B70 80081590 AC980024 */  sw         $t8, 0x24($a0)
    /* 35B74 80081594 AC800028 */  sw         $zero, 0x28($a0)
    /* 35B78 80081598 AC80002C */  sw         $zero, 0x2C($a0)
    /* 35B7C 8008159C A4990032 */  sh         $t9, 0x32($a0)
    /* 35B80 800815A0 AC8E0014 */  sw         $t6, 0x14($a0)
    /* 35B84 800815A4 90A80009 */  lbu        $t0, 0x9($a1)
    /* 35B88 800815A8 24093E80 */  addiu      $t1, $zero, 0x3E80
    /* 35B8C 800815AC AC89005C */  sw         $t1, 0x5C($a0)
    /* 35B90 800815B0 AC80001C */  sw         $zero, 0x1C($a0)
    /* 35B94 800815B4 A0880035 */  sb         $t0, 0x35($a0)
    /* 35B98 800815B8 8CAA0010 */  lw         $t2, 0x10($a1)
    /* 35B9C 800815BC 240D0009 */  addiu      $t5, $zero, 0x9
    /* 35BA0 800815C0 00A08825 */  or         $s1, $a1, $zero
    /* 35BA4 800815C4 AC8A0070 */  sw         $t2, 0x70($a0)
    /* 35BA8 800815C8 8CAB0014 */  lw         $t3, 0x14($a1)
    /* 35BAC 800815CC 00808025 */  or         $s0, $a0, $zero
    /* 35BB0 800815D0 240F0010 */  addiu      $t7, $zero, 0x10
    /* 35BB4 800815D4 AC8B0074 */  sw         $t3, 0x74($a0)
    /* 35BB8 800815D8 8CAC0018 */  lw         $t4, 0x18($a1)
    /* 35BBC 800815DC AC80007C */  sw         $zero, 0x7C($a0)
    /* 35BC0 800815E0 AC800080 */  sw         $zero, 0x80($a0)
    /* 35BC4 800815E4 AC800084 */  sw         $zero, 0x84($a0)
    /* 35BC8 800815E8 A48D0038 */  sh         $t5, 0x38($a0)
    /* 35BCC 800815EC AC8C0078 */  sw         $t4, 0x78($a0)
    /* 35BD0 800815F0 90AE0008 */  lbu        $t6, 0x8($a1)
    /* 35BD4 800815F4 00002825 */  or         $a1, $zero, $zero
    /* 35BD8 800815F8 A08E0034 */  sb         $t6, 0x34($a0)
    /* 35BDC 800815FC 92270008 */  lbu        $a3, 0x8($s1)
    /* 35BE0 80081600 AFAF0010 */  sw         $t7, 0x10($sp)
    /* 35BE4 80081604 00002025 */  or         $a0, $zero, $zero
    /* 35BE8 80081608 0C01FF52 */  jal        func_8007FD48
    /* 35BEC 8008160C AFA6002C */   sw        $a2, 0x2C($sp)
    /* 35BF0 80081610 AE020060 */  sw         $v0, 0x60($s0)
    /* 35BF4 80081614 0C02053B */  jal        func_800814EC
    /* 35BF8 80081618 02002025 */   or        $a0, $s0, $zero
    /* 35BFC 8008161C 8E270000 */  lw         $a3, 0x0($s1)
    /* 35C00 80081620 24180038 */  addiu      $t8, $zero, 0x38
    /* 35C04 80081624 AFB80010 */  sw         $t8, 0x10($sp)
    /* 35C08 80081628 00002025 */  or         $a0, $zero, $zero
    /* 35C0C 8008162C 00002825 */  or         $a1, $zero, $zero
    /* 35C10 80081630 0C01FF52 */  jal        func_8007FD48
    /* 35C14 80081634 8FA6002C */   lw        $a2, 0x2C($sp)
    /* 35C18 80081638 AE00006C */  sw         $zero, 0x6C($s0)
    /* 35C1C 8008163C 8E390000 */  lw         $t9, 0x0($s1)
    /* 35C20 80081640 00002025 */  or         $a0, $zero, $zero
    /* 35C24 80081644 00002825 */  or         $a1, $zero, $zero
    /* 35C28 80081648 1B20000B */  blez       $t9, .L80081678
    /* 35C2C 8008164C 240A001C */   addiu     $t2, $zero, 0x1C
    /* 35C30 80081650 00401825 */  or         $v1, $v0, $zero
    /* 35C34 80081654 8E08006C */  lw         $t0, 0x6C($s0)
  .L80081658:
    /* 35C38 80081658 24840001 */  addiu      $a0, $a0, 0x1
    /* 35C3C 8008165C AC680000 */  sw         $t0, 0x0($v1)
    /* 35C40 80081660 AE03006C */  sw         $v1, 0x6C($s0)
    /* 35C44 80081664 8E290000 */  lw         $t1, 0x0($s1)
    /* 35C48 80081668 24630038 */  addiu      $v1, $v1, 0x38
    /* 35C4C 8008166C 0089082A */  slt        $at, $a0, $t1
    /* 35C50 80081670 5420FFF9 */  bnel       $at, $zero, .L80081658
    /* 35C54 80081674 8E08006C */   lw        $t0, 0x6C($s0)
  .L80081678:
    /* 35C58 80081678 AE000064 */  sw         $zero, 0x64($s0)
    /* 35C5C 8008167C AE000068 */  sw         $zero, 0x68($s0)
    /* 35C60 80081680 8E270004 */  lw         $a3, 0x4($s1)
    /* 35C64 80081684 AFAA0010 */  sw         $t2, 0x10($sp)
    /* 35C68 80081688 8FA6002C */  lw         $a2, 0x2C($sp)
    /* 35C6C 8008168C 0C01FF52 */  jal        func_8007FD48
    /* 35C70 80081690 00002025 */   or        $a0, $zero, $zero
    /* 35C74 80081694 26040048 */  addiu      $a0, $s0, 0x48
    /* 35C78 80081698 00402825 */  or         $a1, $v0, $zero
    /* 35C7C 8008169C 0C01FA39 */  jal        func_8007E8E4
    /* 35C80 800816A0 8E260004 */   lw        $a2, 0x4($s1)
    /* 35C84 800816A4 3C0B8008 */  lui        $t3, %hi(func_80080DC4)
    /* 35C88 800816A8 256B0DC4 */  addiu      $t3, $t3, %lo(func_80080DC4)
    /* 35C8C 800816AC AE000000 */  sw         $zero, 0x0($s0)
    /* 35C90 800816B0 AE0B0008 */  sw         $t3, 0x8($s0)
    /* 35C94 800816B4 AE100004 */  sw         $s0, 0x4($s0)
    /* 35C98 800816B8 3C048009 */  lui        $a0, %hi(D_800952D0)
    /* 35C9C 800816BC 8C8452D0 */  lw         $a0, %lo(D_800952D0)($a0)
    /* 35CA0 800816C0 0C021822 */  jal        func_80086088
    /* 35CA4 800816C4 02002825 */   or        $a1, $s0, $zero
    /* 35CA8 800816C8 8FBF0024 */  lw         $ra, 0x24($sp)
    /* 35CAC 800816CC 8FB0001C */  lw         $s0, 0x1C($sp)
    /* 35CB0 800816D0 8FB10020 */  lw         $s1, 0x20($sp)
    /* 35CB4 800816D4 03E00008 */  jr         $ra
    /* 35CB8 800816D8 27BD0040 */   addiu     $sp, $sp, 0x40
endlabel func_8008155C
    /* 35CBC 800816DC 00000000 */  nop
    /* 35CC0 800816E0 00000000 */  nop
    /* 35CC4 800816E4 00000000 */  nop

nonmatching func_800816E8, 0x1C

glabel func_800816E8
    /* 35CC8 800816E8 8C8E0008 */  lw         $t6, 0x8($a0)
    /* 35CCC 800816EC ACAE0000 */  sw         $t6, 0x0($a1)
    /* 35CD0 800816F0 848F001A */  lh         $t7, 0x1A($a0)
    /* 35CD4 800816F4 A4AF000C */  sh         $t7, 0xC($a1)
    /* 35CD8 800816F8 8C98000C */  lw         $t8, 0xC($a0)
    /* 35CDC 800816FC 03E00008 */  jr         $ra
    /* 35CE0 80081700 ACB80004 */   sw        $t8, 0x4($a1)
endlabel func_800816E8

nonmatching func_80081704, 0x1C

glabel func_80081704
    /* 35CE4 80081704 8CAE0000 */  lw         $t6, 0x0($a1)
    /* 35CE8 80081708 AC8E0008 */  sw         $t6, 0x8($a0)
    /* 35CEC 8008170C 84AF000C */  lh         $t7, 0xC($a1)
    /* 35CF0 80081710 A48F001A */  sh         $t7, 0x1A($a0)
    /* 35CF4 80081714 8CB80004 */  lw         $t8, 0x4($a1)
    /* 35CF8 80081718 03E00008 */  jr         $ra
    /* 35CFC 8008171C AC98000C */   sw        $t8, 0xC($a0)
endlabel func_80081704

nonmatching func_80081720, 0x8

glabel func_80081720
    /* 35D00 80081720 03E00008 */  jr         $ra
    /* 35D04 80081724 8C82000C */   lw        $v0, 0xC($a0)
endlabel func_80081720

nonmatching func_80081728, 0x8

glabel func_80081728
    /* 35D08 80081728 03E00008 */  jr         $ra
    /* 35D0C 8008172C 00000000 */   nop
endlabel func_80081728

nonmatching func_80081730, 0x4C

glabel func_80081730
    /* 35D10 80081730 8C830008 */  lw         $v1, 0x8($a0)
    /* 35D14 80081734 90620000 */  lbu        $v0, 0x0($v1)
    /* 35D18 80081738 246E0001 */  addiu      $t6, $v1, 0x1
    /* 35D1C 8008173C AC8E0008 */  sw         $t6, 0x8($a0)
    /* 35D20 80081740 304F0080 */  andi       $t7, $v0, 0x80
    /* 35D24 80081744 11E0000B */  beqz       $t7, .L80081774
    /* 35D28 80081748 00402825 */   or        $a1, $v0, $zero
    /* 35D2C 8008174C 3045007F */  andi       $a1, $v0, 0x7F
  .L80081750:
    /* 35D30 80081750 8C830008 */  lw         $v1, 0x8($a0)
    /* 35D34 80081754 0005C9C0 */  sll        $t9, $a1, 7
    /* 35D38 80081758 90620000 */  lbu        $v0, 0x0($v1)
    /* 35D3C 8008175C 24780001 */  addiu      $t8, $v1, 0x1
    /* 35D40 80081760 AC980008 */  sw         $t8, 0x8($a0)
    /* 35D44 80081764 304E007F */  andi       $t6, $v0, 0x7F
    /* 35D48 80081768 304F0080 */  andi       $t7, $v0, 0x80
    /* 35D4C 8008176C 15E0FFF8 */  bnez       $t7, .L80081750
    /* 35D50 80081770 032E2821 */   addu      $a1, $t9, $t6
  .L80081774:
    /* 35D54 80081774 03E00008 */  jr         $ra
    /* 35D58 80081778 00A01025 */   or        $v0, $a1, $zero
endlabel func_80081730
