.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_8004F440, 0x6C

glabel func_8004F440
    /* 3A20 8004F440 27BDFFD8 */  addiu      $sp, $sp, -0x28
    /* 3A24 8004F444 AFB00018 */  sw         $s0, 0x18($sp)
    /* 3A28 8004F448 00808021 */  addu       $s0, $a0, $zero
    /* 3A2C 8004F44C AFB20020 */  sw         $s2, 0x20($sp)
    /* 3A30 8004F450 27B20010 */  addiu      $s2, $sp, 0x10
    /* 3A34 8004F454 AFBF0024 */  sw         $ra, 0x24($sp)
    /* 3A38 8004F458 AFB1001C */  sw         $s1, 0x1C($sp)
    /* 3A3C 8004F45C 8E060160 */  lw         $a2, 0x160($s0)
    /* 3A40 8004F460 02402821 */  addu       $a1, $s2, $zero
    /* 3A44 8004F464 A7A00010 */  sh         $zero, 0x10($sp)
    /* 3A48 8004F468 8E110050 */  lw         $s1, 0x50($s0)
    /* 3A4C 8004F46C 8E070164 */  lw         $a3, 0x164($s0)
    /* 3A50 8004F470 3C028018 */  lui        $v0, %hi(D_8017CCB4)
    /* 3A54 8004F474 AC40CCB4 */  sw         $zero, %lo(D_8017CCB4)($v0)
    /* 3A58 8004F478 0C013CC7 */  jal        func_8004F31C
    /* 3A5C 8004F47C 02202021 */   addu      $a0, $s1, $zero
    /* 3A60 8004F480 8E060168 */  lw         $a2, 0x168($s0)
    /* 3A64 8004F484 10C00003 */  beqz       $a2, .L8004F494
    /* 3A68 8004F488 02202021 */   addu      $a0, $s1, $zero
    /* 3A6C 8004F48C 0C013CEE */  jal        func_8004F3B8
    /* 3A70 8004F490 02402821 */   addu      $a1, $s2, $zero
  .L8004F494:
    /* 3A74 8004F494 8FBF0024 */  lw         $ra, 0x24($sp)
    /* 3A78 8004F498 8FB20020 */  lw         $s2, 0x20($sp)
    /* 3A7C 8004F49C 8FB1001C */  lw         $s1, 0x1C($sp)
    /* 3A80 8004F4A0 8FB00018 */  lw         $s0, 0x18($sp)
    /* 3A84 8004F4A4 03E00008 */  jr         $ra
    /* 3A88 8004F4A8 27BD0028 */   addiu     $sp, $sp, 0x28
endlabel func_8004F440
