.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_80086848, 0xA8

glabel func_80086848
    /* 3AE28 80086848 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* 3AE2C 8008684C 3C0F8009 */  lui        $t7, %hi(D_800955B0)
    /* 3AE30 80086850 91EF55B0 */  lbu        $t7, %lo(D_800955B0)($t7)
    /* 3AE34 80086854 AFA40020 */  sw         $a0, 0x20($sp)
    /* 3AE38 80086858 8FAE0020 */  lw         $t6, 0x20($sp)
    /* 3AE3C 8008685C AFBF0014 */  sw         $ra, 0x14($sp)
    /* 3AE40 80086860 AFA50024 */  sw         $a1, 0x24($sp)
    /* 3AE44 80086864 11E00003 */  beqz       $t7, .L80086874
    /* 3AE48 80086868 AFAE001C */   sw        $t6, 0x1C($sp)
    /* 3AE4C 8008686C 25D8E000 */  addiu      $t8, $t6, -0x2000
    /* 3AE50 80086870 AFB8001C */  sw         $t8, 0x1C($sp)
  .L80086874:
    /* 3AE54 80086874 8FB90020 */  lw         $t9, 0x20($sp)
    /* 3AE58 80086878 8FA80024 */  lw         $t0, 0x24($sp)
    /* 3AE5C 8008687C 24012000 */  addiu      $at, $zero, 0x2000
    /* 3AE60 80086880 03284821 */  addu       $t1, $t9, $t0
    /* 3AE64 80086884 312A3FFF */  andi       $t2, $t1, 0x3FFF
    /* 3AE68 80086888 15410005 */  bne        $t2, $at, .L800868A0
    /* 3AE6C 8008688C 00000000 */   nop
    /* 3AE70 80086890 240B0001 */  addiu      $t3, $zero, 0x1
    /* 3AE74 80086894 3C018009 */  lui        $at, %hi(D_800955B0)
    /* 3AE78 80086898 10000003 */  b          .L800868A8
    /* 3AE7C 8008689C A02B55B0 */   sb        $t3, %lo(D_800955B0)($at)
  .L800868A0:
    /* 3AE80 800868A0 3C018009 */  lui        $at, %hi(D_800955B0)
    /* 3AE84 800868A4 A02055B0 */  sb         $zero, %lo(D_800955B0)($at)
  .L800868A8:
    /* 3AE88 800868A8 0C021A3E */  jal        func_800868F8
    /* 3AE8C 800868AC 00000000 */   nop
    /* 3AE90 800868B0 10400003 */  beqz       $v0, .L800868C0
    /* 3AE94 800868B4 00000000 */   nop
    /* 3AE98 800868B8 10000009 */  b          .L800868E0
    /* 3AE9C 800868BC 2402FFFF */   addiu     $v0, $zero, -0x1
  .L800868C0:
    /* 3AEA0 800868C0 0C01F5A2 */  jal        func_8007D688
    /* 3AEA4 800868C4 8FA4001C */   lw        $a0, 0x1C($sp)
    /* 3AEA8 800868C8 3C0CA450 */  lui        $t4, %hi(D_A4500000)
    /* 3AEAC 800868CC AD820000 */  sw         $v0, %lo(D_A4500000)($t4)
    /* 3AEB0 800868D0 8FAD0024 */  lw         $t5, 0x24($sp)
    /* 3AEB4 800868D4 3C0FA450 */  lui        $t7, %hi(D_A4500004)
    /* 3AEB8 800868D8 00001025 */  or         $v0, $zero, $zero
    /* 3AEBC 800868DC ADED0004 */  sw         $t5, %lo(D_A4500004)($t7)
  .L800868E0:
    /* 3AEC0 800868E0 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 3AEC4 800868E4 27BD0020 */  addiu      $sp, $sp, 0x20
    /* 3AEC8 800868E8 03E00008 */  jr         $ra
    /* 3AECC 800868EC 00000000 */   nop
endlabel func_80086848
    /* 3AED0 800868F0 00000000 */  nop
    /* 3AED4 800868F4 00000000 */  nop

nonmatching func_800868F8, 0xC

glabel func_800868F8
    /* 3AED8 800868F8 3C0EA450 */  lui        $t6, %hi(D_A450000C)
    /* 3AEDC 800868FC 8DC4000C */  lw         $a0, %lo(D_A450000C)($t6)
    /* 3AEE0 80086900 3C018000 */  lui        $at, (0x80000000 >> 16)
endlabel func_800868F8
