.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_8008E628, 0x150

glabel func_8008E628
    /* 42C08 8008E628 27BDFFD8 */  addiu      $sp, $sp, -0x28
    /* 42C0C 8008E62C AFBF001C */  sw         $ra, 0x1C($sp)
    /* 42C10 8008E630 AFA40028 */  sw         $a0, 0x28($sp)
    /* 42C14 8008E634 AFA5002C */  sw         $a1, 0x2C($sp)
    /* 42C18 8008E638 AFA60030 */  sw         $a2, 0x30($sp)
    /* 42C1C 8008E63C AFB10018 */  sw         $s1, 0x18($sp)
    /* 42C20 8008E640 0C01F1DA */  jal        func_8007C768
    /* 42C24 8008E644 AFB00014 */   sw        $s0, 0x14($sp)
    /* 42C28 8008E648 8FAE0028 */  lw         $t6, 0x28($sp)
    /* 42C2C 8008E64C 00408025 */  or         $s0, $v0, $zero
    /* 42C30 8008E650 8DCF0008 */  lw         $t7, 0x8($t6)
    /* 42C34 8008E654 8DD80010 */  lw         $t8, 0x10($t6)
    /* 42C38 8008E658 01F8082A */  slt        $at, $t7, $t8
    /* 42C3C 8008E65C 14200018 */  bnez       $at, .L8008E6C0
    /* 42C40 8008E660 00000000 */   nop
  .L8008E664:
    /* 42C44 8008E664 8FB90030 */  lw         $t9, 0x30($sp)
    /* 42C48 8008E668 24010001 */  addiu      $at, $zero, 0x1
    /* 42C4C 8008E66C 1721000A */  bne        $t9, $at, .L8008E698
    /* 42C50 8008E670 00000000 */   nop
    /* 42C54 8008E674 3C098009 */  lui        $t1, %hi(D_800952B0)
    /* 42C58 8008E678 8D2952B0 */  lw         $t1, %lo(D_800952B0)($t1)
    /* 42C5C 8008E67C 24080008 */  addiu      $t0, $zero, 0x8
    /* 42C60 8008E680 A5280010 */  sh         $t0, 0x10($t1)
    /* 42C64 8008E684 8FA40028 */  lw         $a0, 0x28($sp)
    /* 42C68 8008E688 0C01F121 */  jal        func_8007C484
    /* 42C6C 8008E68C 24840004 */   addiu     $a0, $a0, 0x4
    /* 42C70 8008E690 10000005 */  b          .L8008E6A8
    /* 42C74 8008E694 00000000 */   nop
  .L8008E698:
    /* 42C78 8008E698 0C01F1E2 */  jal        func_8007C788
    /* 42C7C 8008E69C 02002025 */   or        $a0, $s0, $zero
    /* 42C80 8008E6A0 10000030 */  b          .L8008E764
    /* 42C84 8008E6A4 2402FFFF */   addiu     $v0, $zero, -0x1
  .L8008E6A8:
    /* 42C88 8008E6A8 8FAA0028 */  lw         $t2, 0x28($sp)
    /* 42C8C 8008E6AC 8D4B0008 */  lw         $t3, 0x8($t2)
    /* 42C90 8008E6B0 8D4C0010 */  lw         $t4, 0x10($t2)
    /* 42C94 8008E6B4 016C082A */  slt        $at, $t3, $t4
    /* 42C98 8008E6B8 1020FFEA */  beqz       $at, .L8008E664
    /* 42C9C 8008E6BC 00000000 */   nop
  .L8008E6C0:
    /* 42CA0 8008E6C0 8FAD0028 */  lw         $t5, 0x28($sp)
    /* 42CA4 8008E6C4 8DAE000C */  lw         $t6, 0xC($t5)
    /* 42CA8 8008E6C8 8DAF0010 */  lw         $t7, 0x10($t5)
    /* 42CAC 8008E6CC 01CFC021 */  addu       $t8, $t6, $t7
    /* 42CB0 8008E6D0 2719FFFF */  addiu      $t9, $t8, -0x1
    /* 42CB4 8008E6D4 032F001A */  div        $zero, $t9, $t7
    /* 42CB8 8008E6D8 00004010 */  mfhi       $t0
    /* 42CBC 8008E6DC ADA8000C */  sw         $t0, 0xC($t5)
    /* 42CC0 8008E6E0 8FAA0028 */  lw         $t2, 0x28($sp)
    /* 42CC4 8008E6E4 8FA9002C */  lw         $t1, 0x2C($sp)
    /* 42CC8 8008E6E8 15E00002 */  bnez       $t7, .L8008E6F4
    /* 42CCC 8008E6EC 00000000 */   nop
    /* 42CD0 8008E6F0 0007000D */  break      7
  .L8008E6F4:
    /* 42CD4 8008E6F4 2401FFFF */  addiu      $at, $zero, -0x1
    /* 42CD8 8008E6F8 15E10004 */  bne        $t7, $at, .L8008E70C
    /* 42CDC 8008E6FC 3C018000 */   lui       $at, (0x80000000 >> 16)
    /* 42CE0 8008E700 17210002 */  bne        $t9, $at, .L8008E70C
    /* 42CE4 8008E704 00000000 */   nop
    /* 42CE8 8008E708 0006000D */  break      6
  .L8008E70C:
    /* 42CEC 8008E70C 8D4C000C */  lw         $t4, 0xC($t2)
    /* 42CF0 8008E710 8D4B0014 */  lw         $t3, 0x14($t2)
    /* 42CF4 8008E714 000C7080 */  sll        $t6, $t4, 2
    /* 42CF8 8008E718 016EC021 */  addu       $t8, $t3, $t6
    /* 42CFC 8008E71C AF090000 */  sw         $t1, 0x0($t8)
    /* 42D00 8008E720 8FB90028 */  lw         $t9, 0x28($sp)
    /* 42D04 8008E724 8F2F0008 */  lw         $t7, 0x8($t9)
    /* 42D08 8008E728 25E80001 */  addiu      $t0, $t7, 0x1
    /* 42D0C 8008E72C AF280008 */  sw         $t0, 0x8($t9)
    /* 42D10 8008E730 8FAD0028 */  lw         $t5, 0x28($sp)
    /* 42D14 8008E734 8DAA0000 */  lw         $t2, 0x0($t5)
    /* 42D18 8008E738 8D4C0000 */  lw         $t4, 0x0($t2)
    /* 42D1C 8008E73C 11800006 */  beqz       $t4, .L8008E758
    /* 42D20 8008E740 00000000 */   nop
    /* 42D24 8008E744 0C01F173 */  jal        func_8007C5CC
    /* 42D28 8008E748 01A02025 */   or        $a0, $t5, $zero
    /* 42D2C 8008E74C 00408825 */  or         $s1, $v0, $zero
    /* 42D30 8008E750 0C01F43A */  jal        func_8007D0E8
    /* 42D34 8008E754 02202025 */   or        $a0, $s1, $zero
  .L8008E758:
    /* 42D38 8008E758 0C01F1E2 */  jal        func_8007C788
    /* 42D3C 8008E75C 02002025 */   or        $a0, $s0, $zero
    /* 42D40 8008E760 00001025 */  or         $v0, $zero, $zero
  .L8008E764:
    /* 42D44 8008E764 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 42D48 8008E768 8FB00014 */  lw         $s0, 0x14($sp)
    /* 42D4C 8008E76C 8FB10018 */  lw         $s1, 0x18($sp)
    /* 42D50 8008E770 03E00008 */  jr         $ra
    /* 42D54 8008E774 27BD0028 */   addiu     $sp, $sp, 0x28
endlabel func_8008E628

nonmatching func_8008E778, 0x28

glabel func_8008E778
    /* 42D58 8008E778 3C0E8009 */  lui        $t6, %hi(D_80096480)
    /* 42D5C 8008E77C 8DCE6480 */  lw         $t6, %lo(D_80096480)($t6)
    /* 42D60 8008E780 15C00003 */  bnez       $t6, .L8008E790
    /* 42D64 8008E784 00000000 */   nop
    /* 42D68 8008E788 03E00008 */  jr         $ra
    /* 42D6C 8008E78C 00001025 */   or        $v0, $zero, $zero
  .L8008E790:
    /* 42D70 8008E790 3C028009 */  lui        $v0, %hi(D_80096488)
    /* 42D74 8008E794 8C426488 */  lw         $v0, %lo(D_80096488)($v0)
    /* 42D78 8008E798 03E00008 */  jr         $ra
    /* 42D7C 8008E79C 00000000 */   nop
endlabel func_8008E778
    /* 42D80 8008E7A0 00000000 */  nop
    /* 42D84 8008E7A4 00000000 */  nop

/* Handwritten function */
nonmatching func_8008E7A8, 0x304

glabel func_8008E7A8
    /* 42D88 8008E7A8 10C0001A */  beqz       $a2, .L8008E814
    /* 42D8C 8008E7AC 00A03825 */   or        $a3, $a1, $zero
    /* 42D90 8008E7B0 10850018 */  beq        $a0, $a1, .L8008E814
    /* 42D94 8008E7B4 00A4082A */   slt       $at, $a1, $a0
    /* 42D98 8008E7B8 54200008 */  bnel       $at, $zero, .L8008E7DC
    /* 42D9C 8008E7BC 28C10010 */   slti      $at, $a2, 0x10
    /* 42DA0 8008E7C0 00861020 */  add        $v0, $a0, $a2 /* handwritten instruction */
    /* 42DA4 8008E7C4 00A2082A */  slt        $at, $a1, $v0
    /* 42DA8 8008E7C8 50200004 */  beql       $at, $zero, .L8008E7DC
    /* 42DAC 8008E7CC 28C10010 */   slti      $at, $a2, 0x10
    /* 42DB0 8008E7D0 1000005B */  b          .L8008E940
    /* 42DB4 8008E7D4 28C10010 */   slti      $at, $a2, 0x10
    /* 42DB8 8008E7D8 28C10010 */  slti       $at, $a2, 0x10
  .L8008E7DC:
    /* 42DBC 8008E7DC 14200005 */  bnez       $at, .L8008E7F4
    /* 42DC0 8008E7E0 00000000 */   nop
    /* 42DC4 8008E7E4 30820003 */  andi       $v0, $a0, 0x3
    /* 42DC8 8008E7E8 30A30003 */  andi       $v1, $a1, 0x3
    /* 42DCC 8008E7EC 1043000B */  beq        $v0, $v1, .L8008E81C
    /* 42DD0 8008E7F0 00000000 */   nop
  .L8008E7F4:
    /* 42DD4 8008E7F4 10C00007 */  beqz       $a2, .L8008E814
    /* 42DD8 8008E7F8 00000000 */   nop
    /* 42DDC 8008E7FC 00861821 */  addu       $v1, $a0, $a2
  .L8008E800:
    /* 42DE0 8008E800 80820000 */  lb         $v0, 0x0($a0)
    /* 42DE4 8008E804 24840001 */  addiu      $a0, $a0, 0x1
    /* 42DE8 8008E808 24A50001 */  addiu      $a1, $a1, 0x1
    /* 42DEC 8008E80C 1483FFFC */  bne        $a0, $v1, .L8008E800
    /* 42DF0 8008E810 A0A2FFFF */   sb        $v0, -0x1($a1)
  .L8008E814:
    /* 42DF4 8008E814 03E00008 */  jr         $ra
    /* 42DF8 8008E818 00E01025 */   or        $v0, $a3, $zero
  .L8008E81C:
    /* 42DFC 8008E81C 10400018 */  beqz       $v0, .L8008E880
    /* 42E00 8008E820 24010001 */   addiu     $at, $zero, 0x1
    /* 42E04 8008E824 1041000F */  beq        $v0, $at, .L8008E864
    /* 42E08 8008E828 24010002 */   addiu     $at, $zero, 0x2
    /* 42E0C 8008E82C 50410008 */  beql       $v0, $at, .L8008E850
    /* 42E10 8008E830 84820000 */   lh        $v0, 0x0($a0)
    /* 42E14 8008E834 80820000 */  lb         $v0, 0x0($a0)
    /* 42E18 8008E838 24840001 */  addiu      $a0, $a0, 0x1
    /* 42E1C 8008E83C 24A50001 */  addiu      $a1, $a1, 0x1
    /* 42E20 8008E840 24C6FFFF */  addiu      $a2, $a2, -0x1
    /* 42E24 8008E844 1000000E */  b          .L8008E880
    /* 42E28 8008E848 A0A2FFFF */   sb        $v0, -0x1($a1)
    /* 42E2C 8008E84C 84820000 */  lh         $v0, 0x0($a0)
  .L8008E850:
    /* 42E30 8008E850 24840002 */  addiu      $a0, $a0, 0x2
    /* 42E34 8008E854 24A50002 */  addiu      $a1, $a1, 0x2
    /* 42E38 8008E858 24C6FFFE */  addiu      $a2, $a2, -0x2
    /* 42E3C 8008E85C 10000008 */  b          .L8008E880
    /* 42E40 8008E860 A4A2FFFE */   sh        $v0, -0x2($a1)
  .L8008E864:
    /* 42E44 8008E864 80820000 */  lb         $v0, 0x0($a0)
    /* 42E48 8008E868 84830001 */  lh         $v1, 0x1($a0)
    /* 42E4C 8008E86C 24840003 */  addiu      $a0, $a0, 0x3
    /* 42E50 8008E870 24A50003 */  addiu      $a1, $a1, 0x3
    /* 42E54 8008E874 24C6FFFD */  addiu      $a2, $a2, -0x3
    /* 42E58 8008E878 A0A2FFFD */  sb         $v0, -0x3($a1)
    /* 42E5C 8008E87C A4A3FFFE */  sh         $v1, -0x2($a1)
  .L8008E880:
    /* 42E60 8008E880 28C10020 */  slti       $at, $a2, 0x20
    /* 42E64 8008E884 54200016 */  bnel       $at, $zero, .L8008E8E0
    /* 42E68 8008E888 28C10010 */   slti      $at, $a2, 0x10
    /* 42E6C 8008E88C 8C820000 */  lw         $v0, 0x0($a0)
    /* 42E70 8008E890 8C830004 */  lw         $v1, 0x4($a0)
    /* 42E74 8008E894 8C880008 */  lw         $t0, 0x8($a0)
    /* 42E78 8008E898 8C89000C */  lw         $t1, 0xC($a0)
    /* 42E7C 8008E89C 8C8A0010 */  lw         $t2, 0x10($a0)
    /* 42E80 8008E8A0 8C8B0014 */  lw         $t3, 0x14($a0)
    /* 42E84 8008E8A4 8C8C0018 */  lw         $t4, 0x18($a0)
    /* 42E88 8008E8A8 8C8D001C */  lw         $t5, 0x1C($a0)
    /* 42E8C 8008E8AC 24840020 */  addiu      $a0, $a0, 0x20
    /* 42E90 8008E8B0 24A50020 */  addiu      $a1, $a1, 0x20
    /* 42E94 8008E8B4 24C6FFE0 */  addiu      $a2, $a2, -0x20
    /* 42E98 8008E8B8 ACA2FFE0 */  sw         $v0, -0x20($a1)
    /* 42E9C 8008E8BC ACA3FFE4 */  sw         $v1, -0x1C($a1)
    /* 42EA0 8008E8C0 ACA8FFE8 */  sw         $t0, -0x18($a1)
    /* 42EA4 8008E8C4 ACA9FFEC */  sw         $t1, -0x14($a1)
    /* 42EA8 8008E8C8 ACAAFFF0 */  sw         $t2, -0x10($a1)
    /* 42EAC 8008E8CC ACABFFF4 */  sw         $t3, -0xC($a1)
    /* 42EB0 8008E8D0 ACACFFF8 */  sw         $t4, -0x8($a1)
    /* 42EB4 8008E8D4 1000FFEA */  b          .L8008E880
    /* 42EB8 8008E8D8 ACADFFFC */   sw        $t5, -0x4($a1)
  .L8008E8DC:
    /* 42EBC 8008E8DC 28C10010 */  slti       $at, $a2, 0x10
  .L8008E8E0:
    /* 42EC0 8008E8E0 5420000E */  bnel       $at, $zero, .L8008E91C
    /* 42EC4 8008E8E4 28C10004 */   slti      $at, $a2, 0x4
    /* 42EC8 8008E8E8 8C820000 */  lw         $v0, 0x0($a0)
    /* 42ECC 8008E8EC 8C830004 */  lw         $v1, 0x4($a0)
    /* 42ED0 8008E8F0 8C880008 */  lw         $t0, 0x8($a0)
    /* 42ED4 8008E8F4 8C89000C */  lw         $t1, 0xC($a0)
    /* 42ED8 8008E8F8 24840010 */  addiu      $a0, $a0, 0x10
    /* 42EDC 8008E8FC 24A50010 */  addiu      $a1, $a1, 0x10
    /* 42EE0 8008E900 24C6FFF0 */  addiu      $a2, $a2, -0x10
    /* 42EE4 8008E904 ACA2FFF0 */  sw         $v0, -0x10($a1)
    /* 42EE8 8008E908 ACA3FFF4 */  sw         $v1, -0xC($a1)
    /* 42EEC 8008E90C ACA8FFF8 */  sw         $t0, -0x8($a1)
    /* 42EF0 8008E910 1000FFF2 */  b          .L8008E8DC
    /* 42EF4 8008E914 ACA9FFFC */   sw        $t1, -0x4($a1)
  .L8008E918:
    /* 42EF8 8008E918 28C10004 */  slti       $at, $a2, 0x4
  .L8008E91C:
    /* 42EFC 8008E91C 1420FFB5 */  bnez       $at, .L8008E7F4
    /* 42F00 8008E920 00000000 */   nop
    /* 42F04 8008E924 8C820000 */  lw         $v0, 0x0($a0)
    /* 42F08 8008E928 24840004 */  addiu      $a0, $a0, 0x4
    /* 42F0C 8008E92C 24A50004 */  addiu      $a1, $a1, 0x4
    /* 42F10 8008E930 24C6FFFC */  addiu      $a2, $a2, -0x4
    /* 42F14 8008E934 1000FFF8 */  b          .L8008E918
    /* 42F18 8008E938 ACA2FFFC */   sw        $v0, -0x4($a1)
    /* 42F1C 8008E93C 28C10010 */  slti       $at, $a2, 0x10
  .L8008E940:
    /* 42F20 8008E940 00862020 */  add        $a0, $a0, $a2 /* handwritten instruction */
    /* 42F24 8008E944 14200005 */  bnez       $at, .L8008E95C
    /* 42F28 8008E948 00A62820 */   add       $a1, $a1, $a2 /* handwritten instruction */
    /* 42F2C 8008E94C 30820003 */  andi       $v0, $a0, 0x3
    /* 42F30 8008E950 30A30003 */  andi       $v1, $a1, 0x3
    /* 42F34 8008E954 1043000D */  beq        $v0, $v1, .L8008E98C
    /* 42F38 8008E958 00000000 */   nop
  .L8008E95C:
    /* 42F3C 8008E95C 10C0FFAD */  beqz       $a2, .L8008E814
    /* 42F40 8008E960 00000000 */   nop
    /* 42F44 8008E964 2484FFFF */  addiu      $a0, $a0, -0x1
    /* 42F48 8008E968 24A5FFFF */  addiu      $a1, $a1, -0x1
    /* 42F4C 8008E96C 00861823 */  subu       $v1, $a0, $a2
  .L8008E970:
    /* 42F50 8008E970 80820000 */  lb         $v0, 0x0($a0)
    /* 42F54 8008E974 2484FFFF */  addiu      $a0, $a0, -0x1
    /* 42F58 8008E978 24A5FFFF */  addiu      $a1, $a1, -0x1
    /* 42F5C 8008E97C 1483FFFC */  bne        $a0, $v1, .L8008E970
    /* 42F60 8008E980 A0A20001 */   sb        $v0, 0x1($a1)
    /* 42F64 8008E984 03E00008 */  jr         $ra
    /* 42F68 8008E988 00E01025 */   or        $v0, $a3, $zero
  .L8008E98C:
    /* 42F6C 8008E98C 10400018 */  beqz       $v0, .L8008E9F0
    /* 42F70 8008E990 24010003 */   addiu     $at, $zero, 0x3
    /* 42F74 8008E994 1041000F */  beq        $v0, $at, .L8008E9D4
    /* 42F78 8008E998 24010002 */   addiu     $at, $zero, 0x2
    /* 42F7C 8008E99C 50410008 */  beql       $v0, $at, .L8008E9C0
    /* 42F80 8008E9A0 8482FFFE */   lh        $v0, -0x2($a0)
    /* 42F84 8008E9A4 8082FFFF */  lb         $v0, -0x1($a0)
    /* 42F88 8008E9A8 2484FFFF */  addiu      $a0, $a0, -0x1
    /* 42F8C 8008E9AC 24A5FFFF */  addiu      $a1, $a1, -0x1
    /* 42F90 8008E9B0 24C6FFFF */  addiu      $a2, $a2, -0x1
    /* 42F94 8008E9B4 1000000E */  b          .L8008E9F0
    /* 42F98 8008E9B8 A0A20000 */   sb        $v0, 0x0($a1)
    /* 42F9C 8008E9BC 8482FFFE */  lh         $v0, -0x2($a0)
  .L8008E9C0:
    /* 42FA0 8008E9C0 2484FFFE */  addiu      $a0, $a0, -0x2
    /* 42FA4 8008E9C4 24A5FFFE */  addiu      $a1, $a1, -0x2
    /* 42FA8 8008E9C8 24C6FFFE */  addiu      $a2, $a2, -0x2
    /* 42FAC 8008E9CC 10000008 */  b          .L8008E9F0
    /* 42FB0 8008E9D0 A4A20000 */   sh        $v0, 0x0($a1)
  .L8008E9D4:
    /* 42FB4 8008E9D4 8082FFFF */  lb         $v0, -0x1($a0)
    /* 42FB8 8008E9D8 8483FFFD */  lh         $v1, -0x3($a0)
    /* 42FBC 8008E9DC 2484FFFD */  addiu      $a0, $a0, -0x3
    /* 42FC0 8008E9E0 24A5FFFD */  addiu      $a1, $a1, -0x3
    /* 42FC4 8008E9E4 24C6FFFD */  addiu      $a2, $a2, -0x3
    /* 42FC8 8008E9E8 A0A20002 */  sb         $v0, 0x2($a1)
    /* 42FCC 8008E9EC A4A30000 */  sh         $v1, 0x0($a1)
  .L8008E9F0:
    /* 42FD0 8008E9F0 28C10020 */  slti       $at, $a2, 0x20
    /* 42FD4 8008E9F4 54200016 */  bnel       $at, $zero, .L8008EA50
    /* 42FD8 8008E9F8 28C10010 */   slti      $at, $a2, 0x10
    /* 42FDC 8008E9FC 8C82FFFC */  lw         $v0, -0x4($a0)
    /* 42FE0 8008EA00 8C83FFF8 */  lw         $v1, -0x8($a0)
    /* 42FE4 8008EA04 8C88FFF4 */  lw         $t0, -0xC($a0)
    /* 42FE8 8008EA08 8C89FFF0 */  lw         $t1, -0x10($a0)
    /* 42FEC 8008EA0C 8C8AFFEC */  lw         $t2, -0x14($a0)
    /* 42FF0 8008EA10 8C8BFFE8 */  lw         $t3, -0x18($a0)
    /* 42FF4 8008EA14 8C8CFFE4 */  lw         $t4, -0x1C($a0)
    /* 42FF8 8008EA18 8C8DFFE0 */  lw         $t5, -0x20($a0)
    /* 42FFC 8008EA1C 2484FFE0 */  addiu      $a0, $a0, -0x20
    /* 43000 8008EA20 24A5FFE0 */  addiu      $a1, $a1, -0x20
    /* 43004 8008EA24 24C6FFE0 */  addiu      $a2, $a2, -0x20
    /* 43008 8008EA28 ACA2001C */  sw         $v0, 0x1C($a1)
    /* 4300C 8008EA2C ACA30018 */  sw         $v1, 0x18($a1)
    /* 43010 8008EA30 ACA80014 */  sw         $t0, 0x14($a1)
    /* 43014 8008EA34 ACA90010 */  sw         $t1, 0x10($a1)
    /* 43018 8008EA38 ACAA000C */  sw         $t2, 0xC($a1)
    /* 4301C 8008EA3C ACAB0008 */  sw         $t3, 0x8($a1)
    /* 43020 8008EA40 ACAC0004 */  sw         $t4, 0x4($a1)
    /* 43024 8008EA44 1000FFEA */  b          .L8008E9F0
    /* 43028 8008EA48 ACAD0000 */   sw        $t5, 0x0($a1)
  .L8008EA4C:
    /* 4302C 8008EA4C 28C10010 */  slti       $at, $a2, 0x10
  .L8008EA50:
    /* 43030 8008EA50 5420000E */  bnel       $at, $zero, .L8008EA8C
    /* 43034 8008EA54 28C10004 */   slti      $at, $a2, 0x4
    /* 43038 8008EA58 8C82FFFC */  lw         $v0, -0x4($a0)
    /* 4303C 8008EA5C 8C83FFF8 */  lw         $v1, -0x8($a0)
    /* 43040 8008EA60 8C88FFF4 */  lw         $t0, -0xC($a0)
    /* 43044 8008EA64 8C89FFF0 */  lw         $t1, -0x10($a0)
    /* 43048 8008EA68 2484FFF0 */  addiu      $a0, $a0, -0x10
    /* 4304C 8008EA6C 24A5FFF0 */  addiu      $a1, $a1, -0x10
    /* 43050 8008EA70 24C6FFF0 */  addiu      $a2, $a2, -0x10
    /* 43054 8008EA74 ACA2000C */  sw         $v0, 0xC($a1)
    /* 43058 8008EA78 ACA30008 */  sw         $v1, 0x8($a1)
    /* 4305C 8008EA7C ACA80004 */  sw         $t0, 0x4($a1)
    /* 43060 8008EA80 1000FFF2 */  b          .L8008EA4C
    /* 43064 8008EA84 ACA90000 */   sw        $t1, 0x0($a1)
  .L8008EA88:
    /* 43068 8008EA88 28C10004 */  slti       $at, $a2, 0x4
  .L8008EA8C:
    /* 4306C 8008EA8C 1420FFB3 */  bnez       $at, .L8008E95C
    /* 43070 8008EA90 00000000 */   nop
    /* 43074 8008EA94 8C82FFFC */  lw         $v0, -0x4($a0)
    /* 43078 8008EA98 2484FFFC */  addiu      $a0, $a0, -0x4
    /* 4307C 8008EA9C 24A5FFFC */  addiu      $a1, $a1, -0x4
    /* 43080 8008EAA0 24C6FFFC */  addiu      $a2, $a2, -0x4
    /* 43084 8008EAA4 1000FFF8 */  b          .L8008EA88
    /* 43088 8008EAA8 ACA20000 */   sw        $v0, 0x0($a1)
endlabel func_8008E7A8
    /* 4308C 8008EAAC 00000000 */  nop
    /* 43090 8008EAB0 00000000 */  nop
    /* 43094 8008EAB4 00000000 */  nop

nonmatching func_8008EAB8, 0x9C

glabel func_8008EAB8
    /* 43098 8008EAB8 28A1000C */  slti       $at, $a1, 0xC
    /* 4309C 8008EABC 1420001D */  bnez       $at, .L8008EB34
    /* 430A0 8008EAC0 00041823 */   negu      $v1, $a0
    /* 430A4 8008EAC4 30630003 */  andi       $v1, $v1, 0x3
    /* 430A8 8008EAC8 10600003 */  beqz       $v1, .L8008EAD8
    /* 430AC 8008EACC 00A32823 */   subu      $a1, $a1, $v1
    /* 430B0 8008EAD0 A8800000 */  swl        $zero, 0x0($a0)
    /* 430B4 8008EAD4 00832021 */  addu       $a0, $a0, $v1
  .L8008EAD8:
    /* 430B8 8008EAD8 2401FFE0 */  addiu      $at, $zero, -0x20
    /* 430BC 8008EADC 00A13824 */  and        $a3, $a1, $at
    /* 430C0 8008EAE0 10E0000C */  beqz       $a3, .L8008EB14
    /* 430C4 8008EAE4 00A72823 */   subu      $a1, $a1, $a3
    /* 430C8 8008EAE8 00E43821 */  addu       $a3, $a3, $a0
  .L8008EAEC:
    /* 430CC 8008EAEC 24840020 */  addiu      $a0, $a0, 0x20
    /* 430D0 8008EAF0 AC80FFE0 */  sw         $zero, -0x20($a0)
    /* 430D4 8008EAF4 AC80FFE4 */  sw         $zero, -0x1C($a0)
    /* 430D8 8008EAF8 AC80FFE8 */  sw         $zero, -0x18($a0)
    /* 430DC 8008EAFC AC80FFEC */  sw         $zero, -0x14($a0)
    /* 430E0 8008EB00 AC80FFF0 */  sw         $zero, -0x10($a0)
    /* 430E4 8008EB04 AC80FFF4 */  sw         $zero, -0xC($a0)
    /* 430E8 8008EB08 AC80FFF8 */  sw         $zero, -0x8($a0)
    /* 430EC 8008EB0C 1487FFF7 */  bne        $a0, $a3, .L8008EAEC
    /* 430F0 8008EB10 AC80FFFC */   sw        $zero, -0x4($a0)
  .L8008EB14:
    /* 430F4 8008EB14 2401FFFC */  addiu      $at, $zero, -0x4
    /* 430F8 8008EB18 00A13824 */  and        $a3, $a1, $at
    /* 430FC 8008EB1C 10E00005 */  beqz       $a3, .L8008EB34
    /* 43100 8008EB20 00A72823 */   subu      $a1, $a1, $a3
    /* 43104 8008EB24 00E43821 */  addu       $a3, $a3, $a0
  .L8008EB28:
    /* 43108 8008EB28 24840004 */  addiu      $a0, $a0, 0x4
    /* 4310C 8008EB2C 1487FFFE */  bne        $a0, $a3, .L8008EB28
    /* 43110 8008EB30 AC80FFFC */   sw        $zero, -0x4($a0)
  .L8008EB34:
    /* 43114 8008EB34 18A00005 */  blez       $a1, .L8008EB4C
    /* 43118 8008EB38 00000000 */   nop
    /* 4311C 8008EB3C 00A42821 */  addu       $a1, $a1, $a0
  .L8008EB40:
    /* 43120 8008EB40 24840001 */  addiu      $a0, $a0, 0x1
    /* 43124 8008EB44 1485FFFE */  bne        $a0, $a1, .L8008EB40
    /* 43128 8008EB48 A080FFFF */   sb        $zero, -0x1($a0)
  .L8008EB4C:
    /* 4312C 8008EB4C 03E00008 */  jr         $ra
    /* 43130 8008EB50 00000000 */   nop
endlabel func_8008EAB8
    /* 43134 8008EB54 00000000 */  nop

nonmatching func_8008EB58, 0x2C

glabel func_8008EB58
    /* 43138 8008EB58 AFA40000 */  sw         $a0, 0x0($sp)
    /* 4313C 8008EB5C AFA50004 */  sw         $a1, 0x4($sp)
    /* 43140 8008EB60 AFA60008 */  sw         $a2, 0x8($sp)
    /* 43144 8008EB64 AFA7000C */  sw         $a3, 0xC($sp)
    /* 43148 8008EB68 DFAF0008 */  ld         $t7, 0x8($sp)
    /* 4314C 8008EB6C DFAE0000 */  ld         $t6, 0x0($sp)
    /* 43150 8008EB70 01EE1016 */  dsrlv      $v0, $t6, $t7
    /* 43154 8008EB74 0002183C */  dsll32     $v1, $v0, 0
    /* 43158 8008EB78 0003183F */  dsra32     $v1, $v1, 0
    /* 4315C 8008EB7C 03E00008 */  jr         $ra
    /* 43160 8008EB80 0002103F */   dsra32    $v0, $v0, 0
endlabel func_8008EB58

nonmatching func_8008EB84, 0x3C

glabel func_8008EB84
    /* 43164 8008EB84 AFA40000 */  sw         $a0, 0x0($sp)
    /* 43168 8008EB88 AFA50004 */  sw         $a1, 0x4($sp)
    /* 4316C 8008EB8C AFA60008 */  sw         $a2, 0x8($sp)
    /* 43170 8008EB90 AFA7000C */  sw         $a3, 0xC($sp)
    /* 43174 8008EB94 DFAF0008 */  ld         $t7, 0x8($sp)
    /* 43178 8008EB98 DFAE0000 */  ld         $t6, 0x0($sp)
    /* 4317C 8008EB9C 01CF001F */  ddivu      $zero, $t6, $t7
    /* 43180 8008EBA0 15E00002 */  bnez       $t7, .L8008EBAC
    /* 43184 8008EBA4 00000000 */   nop
    /* 43188 8008EBA8 0007000D */  break      7
  .L8008EBAC:
    /* 4318C 8008EBAC 00001010 */  mfhi       $v0
    /* 43190 8008EBB0 0002183C */  dsll32     $v1, $v0, 0
    /* 43194 8008EBB4 0003183F */  dsra32     $v1, $v1, 0
    /* 43198 8008EBB8 03E00008 */  jr         $ra
    /* 4319C 8008EBBC 0002103F */   dsra32    $v0, $v0, 0
endlabel func_8008EB84

nonmatching func_8008EBC0, 0x3C

glabel func_8008EBC0
    /* 431A0 8008EBC0 AFA40000 */  sw         $a0, 0x0($sp)
    /* 431A4 8008EBC4 AFA50004 */  sw         $a1, 0x4($sp)
    /* 431A8 8008EBC8 AFA60008 */  sw         $a2, 0x8($sp)
    /* 431AC 8008EBCC AFA7000C */  sw         $a3, 0xC($sp)
    /* 431B0 8008EBD0 DFAF0008 */  ld         $t7, 0x8($sp)
    /* 431B4 8008EBD4 DFAE0000 */  ld         $t6, 0x0($sp)
    /* 431B8 8008EBD8 01CF001F */  ddivu      $zero, $t6, $t7
    /* 431BC 8008EBDC 15E00002 */  bnez       $t7, .L8008EBE8
    /* 431C0 8008EBE0 00000000 */   nop
    /* 431C4 8008EBE4 0007000D */  break      7
  .L8008EBE8:
    /* 431C8 8008EBE8 00001012 */  mflo       $v0
    /* 431CC 8008EBEC 0002183C */  dsll32     $v1, $v0, 0
    /* 431D0 8008EBF0 0003183F */  dsra32     $v1, $v1, 0
    /* 431D4 8008EBF4 03E00008 */  jr         $ra
    /* 431D8 8008EBF8 0002103F */   dsra32    $v0, $v0, 0
endlabel func_8008EBC0

nonmatching func_8008EBFC, 0x2C

glabel func_8008EBFC
    /* 431DC 8008EBFC AFA40000 */  sw         $a0, 0x0($sp)
    /* 431E0 8008EC00 AFA50004 */  sw         $a1, 0x4($sp)
    /* 431E4 8008EC04 AFA60008 */  sw         $a2, 0x8($sp)
    /* 431E8 8008EC08 AFA7000C */  sw         $a3, 0xC($sp)
    /* 431EC 8008EC0C DFAF0008 */  ld         $t7, 0x8($sp)
    /* 431F0 8008EC10 DFAE0000 */  ld         $t6, 0x0($sp)
    /* 431F4 8008EC14 01EE1014 */  dsllv      $v0, $t6, $t7
    /* 431F8 8008EC18 0002183C */  dsll32     $v1, $v0, 0
    /* 431FC 8008EC1C 0003183F */  dsra32     $v1, $v1, 0
    /* 43200 8008EC20 03E00008 */  jr         $ra
    /* 43204 8008EC24 0002103F */   dsra32    $v0, $v0, 0
endlabel func_8008EBFC

nonmatching func_8008EC28, 0x3C

glabel func_8008EC28
    /* 43208 8008EC28 AFA40000 */  sw         $a0, 0x0($sp)
    /* 4320C 8008EC2C AFA50004 */  sw         $a1, 0x4($sp)
    /* 43210 8008EC30 AFA60008 */  sw         $a2, 0x8($sp)
    /* 43214 8008EC34 AFA7000C */  sw         $a3, 0xC($sp)
    /* 43218 8008EC38 DFAF0008 */  ld         $t7, 0x8($sp)
    /* 4321C 8008EC3C DFAE0000 */  ld         $t6, 0x0($sp)
    /* 43220 8008EC40 01CF001F */  ddivu      $zero, $t6, $t7
    /* 43224 8008EC44 15E00002 */  bnez       $t7, .L8008EC50
    /* 43228 8008EC48 00000000 */   nop
    /* 4322C 8008EC4C 0007000D */  break      7
  .L8008EC50:
    /* 43230 8008EC50 00001010 */  mfhi       $v0
    /* 43234 8008EC54 0002183C */  dsll32     $v1, $v0, 0
    /* 43238 8008EC58 0003183F */  dsra32     $v1, $v1, 0
    /* 4323C 8008EC5C 03E00008 */  jr         $ra
    /* 43240 8008EC60 0002103F */   dsra32    $v0, $v0, 0
endlabel func_8008EC28

nonmatching func_8008EC64, 0x5C

glabel func_8008EC64
    /* 43244 8008EC64 AFA40000 */  sw         $a0, 0x0($sp)
    /* 43248 8008EC68 AFA50004 */  sw         $a1, 0x4($sp)
    /* 4324C 8008EC6C AFA60008 */  sw         $a2, 0x8($sp)
    /* 43250 8008EC70 AFA7000C */  sw         $a3, 0xC($sp)
    /* 43254 8008EC74 DFAF0008 */  ld         $t7, 0x8($sp)
    /* 43258 8008EC78 DFAE0000 */  ld         $t6, 0x0($sp)
    /* 4325C 8008EC7C 01CF001E */  ddiv       $zero, $t6, $t7
    /* 43260 8008EC80 00000000 */  nop
    /* 43264 8008EC84 15E00002 */  bnez       $t7, .L8008EC90
    /* 43268 8008EC88 00000000 */   nop
    /* 4326C 8008EC8C 0007000D */  break      7
  .L8008EC90:
    /* 43270 8008EC90 6401FFFF */  daddiu     $at, $zero, -0x1
    /* 43274 8008EC94 15E10005 */  bne        $t7, $at, .L8008ECAC
    /* 43278 8008EC98 64010001 */   daddiu    $at, $zero, 0x1
    /* 4327C 8008EC9C 00010FFC */  dsll32     $at, $at, 31
    /* 43280 8008ECA0 15C10002 */  bne        $t6, $at, .L8008ECAC
    /* 43284 8008ECA4 00000000 */   nop
    /* 43288 8008ECA8 0006000D */  break      6
  .L8008ECAC:
    /* 4328C 8008ECAC 00001012 */  mflo       $v0
    /* 43290 8008ECB0 0002183C */  dsll32     $v1, $v0, 0
    /* 43294 8008ECB4 0003183F */  dsra32     $v1, $v1, 0
    /* 43298 8008ECB8 03E00008 */  jr         $ra
    /* 4329C 8008ECBC 0002103F */   dsra32    $v0, $v0, 0
endlabel func_8008EC64

nonmatching func_8008ECC0, 0x30

glabel func_8008ECC0
    /* 432A0 8008ECC0 AFA40000 */  sw         $a0, 0x0($sp)
    /* 432A4 8008ECC4 AFA50004 */  sw         $a1, 0x4($sp)
    /* 432A8 8008ECC8 AFA60008 */  sw         $a2, 0x8($sp)
    /* 432AC 8008ECCC AFA7000C */  sw         $a3, 0xC($sp)
    /* 432B0 8008ECD0 DFAF0008 */  ld         $t7, 0x8($sp)
    /* 432B4 8008ECD4 DFAE0000 */  ld         $t6, 0x0($sp)
    /* 432B8 8008ECD8 01CF001D */  dmultu     $t6, $t7
    /* 432BC 8008ECDC 00001012 */  mflo       $v0
    /* 432C0 8008ECE0 0002183C */  dsll32     $v1, $v0, 0
    /* 432C4 8008ECE4 0003183F */  dsra32     $v1, $v1, 0
    /* 432C8 8008ECE8 03E00008 */  jr         $ra
    /* 432CC 8008ECEC 0002103F */   dsra32    $v0, $v0, 0
endlabel func_8008ECC0

nonmatching func_8008ECF0, 0x60

glabel func_8008ECF0
    /* 432D0 8008ECF0 87AF0012 */  lh         $t7, 0x12($sp)
    /* 432D4 8008ECF4 AFA60008 */  sw         $a2, 0x8($sp)
    /* 432D8 8008ECF8 AFA7000C */  sw         $a3, 0xC($sp)
    /* 432DC 8008ECFC DFAE0008 */  ld         $t6, 0x8($sp)
    /* 432E0 8008ED00 01E0C025 */  or         $t8, $t7, $zero
    /* 432E4 8008ED04 0300C825 */  or         $t9, $t8, $zero
    /* 432E8 8008ED08 01D9001F */  ddivu      $zero, $t6, $t9
    /* 432EC 8008ED0C 17200002 */  bnez       $t9, .L8008ED18
    /* 432F0 8008ED10 00000000 */   nop
    /* 432F4 8008ED14 0007000D */  break      7
  .L8008ED18:
    /* 432F8 8008ED18 00004012 */  mflo       $t0
    /* 432FC 8008ED1C FC880000 */  sd         $t0, 0x0($a0)
    /* 43300 8008ED20 87AA0012 */  lh         $t2, 0x12($sp)
    /* 43304 8008ED24 DFA90008 */  ld         $t1, 0x8($sp)
    /* 43308 8008ED28 01405825 */  or         $t3, $t2, $zero
    /* 4330C 8008ED2C 01606025 */  or         $t4, $t3, $zero
    /* 43310 8008ED30 012C001F */  ddivu      $zero, $t1, $t4
    /* 43314 8008ED34 15800002 */  bnez       $t4, .L8008ED40
    /* 43318 8008ED38 00000000 */   nop
    /* 4331C 8008ED3C 0007000D */  break      7
  .L8008ED40:
    /* 43320 8008ED40 00006810 */  mfhi       $t5
    /* 43324 8008ED44 FCAD0000 */  sd         $t5, 0x0($a1)
    /* 43328 8008ED48 03E00008 */  jr         $ra
    /* 4332C 8008ED4C 00000000 */   nop
endlabel func_8008ECF0
