.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_80066400, 0x174

glabel func_80066400
    /* 1A9E0 80066400 27BDFFC0 */  addiu      $sp, $sp, -0x40
    /* 1A9E4 80066404 AFB30024 */  sw         $s3, 0x24($sp)
    /* 1A9E8 80066408 00809821 */  addu       $s3, $a0, $zero
    /* 1A9EC 8006640C AFB1001C */  sw         $s1, 0x1C($sp)
    /* 1A9F0 80066410 00C08821 */  addu       $s1, $a2, $zero
    /* 1A9F4 80066414 AFBF003C */  sw         $ra, 0x3C($sp)
    /* 1A9F8 80066418 AFBE0038 */  sw         $fp, 0x38($sp)
    /* 1A9FC 8006641C AFB70034 */  sw         $s7, 0x34($sp)
    /* 1AA00 80066420 AFB60030 */  sw         $s6, 0x30($sp)
    /* 1AA04 80066424 AFB5002C */  sw         $s5, 0x2C($sp)
    /* 1AA08 80066428 AFB40028 */  sw         $s4, 0x28($sp)
    /* 1AA0C 8006642C AFB20020 */  sw         $s2, 0x20($sp)
    /* 1AA10 80066430 AFB00018 */  sw         $s0, 0x18($sp)
    /* 1AA14 80066434 96220000 */  lhu        $v0, 0x0($s1)
    /* 1AA18 80066438 1040003F */  beqz       $v0, .L80066538
    /* 1AA1C 8006643C 00A09021 */   addu      $s2, $a1, $zero
    /* 1AA20 80066440 3C1E8018 */  lui        $fp, %hi(D_80182E74)
    /* 1AA24 80066444 3C148018 */  lui        $s4, %hi(D_80182E76)
    /* 1AA28 80066448 3C168018 */  lui        $s6, %hi(D_80182E8C)
    /* 1AA2C 8006644C 26D72E8C */  addiu      $s7, $s6, %lo(D_80182E8C)
    /* 1AA30 80066450 3C158018 */  lui        $s5, %hi(D_80182E68)
    /* 1AA34 80066454 3043FFFF */  andi       $v1, $v0, 0xFFFF
  .L80066458:
    /* 1AA38 80066458 2402000A */  addiu      $v0, $zero, 0xA
    /* 1AA3C 8006645C 10620003 */  beq        $v1, $v0, .L8006646C
    /* 1AA40 80066460 2402000D */   addiu     $v0, $zero, 0xD
    /* 1AA44 80066464 1462001A */  bne        $v1, $v0, .L800664D0
    /* 1AA48 80066468 27A50010 */   addiu     $a1, $sp, 0x10
  .L8006646C:
    /* 1AA4C 8006646C 02602021 */  addu       $a0, $s3, $zero
    /* 1AA50 80066470 0C019869 */  jal        func_800661A4
    /* 1AA54 80066474 02402821 */   addu      $a1, $s2, $zero
    /* 1AA58 80066478 02602021 */  addu       $a0, $s3, $zero
    /* 1AA5C 8006647C 96260000 */  lhu        $a2, 0x0($s1)
    /* 1AA60 80066480 02402821 */  addu       $a1, $s2, $zero
    /* 1AA64 80066484 38C6000A */  xori       $a2, $a2, 0xA
    /* 1AA68 80066488 0C0196F7 */  jal        func_80065BDC
    /* 1AA6C 8006648C 0006302B */   sltu      $a2, $zero, $a2
    /* 1AA70 80066490 3C028018 */  lui        $v0, %hi(D_80182E94)
    /* 1AA74 80066494 94442E94 */  lhu        $a0, %lo(D_80182E94)($v0)
    /* 1AA78 80066498 86822E76 */  lh         $v0, %lo(D_80182E76)($s4)
    /* 1AA7C 8006649C 8EC32E8C */  lw         $v1, %lo(D_80182E8C)($s6)
    /* 1AA80 800664A0 00431021 */  addu       $v0, $v0, $v1
    /* 1AA84 800664A4 96832E76 */  lhu        $v1, %lo(D_80182E76)($s4)
    /* 1AA88 800664A8 28420100 */  slti       $v0, $v0, 0x100
    /* 1AA8C 800664AC 14400004 */  bnez       $v0, .L800664C0
    /* 1AA90 800664B0 A7C42E74 */   sh        $a0, %lo(D_80182E74)($fp)
    /* 1AA94 800664B4 240200FF */  addiu      $v0, $zero, 0xFF
    /* 1AA98 800664B8 0801994A */  j          func_80066528
    /* 1AA9C 800664BC A6822E76 */   sh        $v0, %lo(D_80182E76)($s4)
  .L800664C0:
    /* 1AAA0 800664C0 96E20002 */  lhu        $v0, 0x2($s7)
    /* 1AAA4 800664C4 00621021 */  addu       $v0, $v1, $v0
    /* 1AAA8 800664C8 0801994A */  j          func_80066528
    /* 1AAAC 800664CC A6822E76 */   sh        $v0, %lo(D_80182E76)($s4)
  .L800664D0:
    /* 1AAB0 800664D0 96240000 */  lhu        $a0, 0x0($s1)
    /* 1AAB4 800664D4 0C018FDF */  jal        func_80063F7C
    /* 1AAB8 800664D8 27A60014 */   addiu     $a2, $sp, 0x14
    /* 1AABC 800664DC 00408021 */  addu       $s0, $v0, $zero
    /* 1AAC0 800664E0 16000005 */  bnez       $s0, .L800664F8
    /* 1AAC4 800664E4 3C038018 */   lui       $v1, %hi(D_80182E84)
    /* 1AAC8 800664E8 02602021 */  addu       $a0, $s3, $zero
    /* 1AACC 800664EC 0C019869 */  jal        func_800661A4
    /* 1AAD0 800664F0 02402821 */   addu      $a1, $s2, $zero
    /* 1AAD4 800664F4 3C038018 */  lui        $v1, %hi(D_80182E84)
  .L800664F8:
    /* 1AAD8 800664F8 96A42E68 */  lhu        $a0, %lo(D_80182E68)($s5)
    /* 1AADC 800664FC 8FA50014 */  lw         $a1, 0x14($sp)
    /* 1AAE0 80066500 8FA60010 */  lw         $a2, 0x10($sp)
    /* 1AAE4 80066504 8C632E84 */  lw         $v1, %lo(D_80182E84)($v1)
    /* 1AAE8 80066508 00041100 */  sll        $v0, $a0, 4
    /* 1AAEC 8006650C 00521021 */  addu       $v0, $v0, $s2
    /* 1AAF0 80066510 24840001 */  addiu      $a0, $a0, 0x1
    /* 1AAF4 80066514 AC500000 */  sw         $s0, 0x0($v0)
    /* 1AAF8 80066518 AC450004 */  sw         $a1, 0x4($v0)
    /* 1AAFC 8006651C AC460008 */  sw         $a2, 0x8($v0)
    /* 1AB00 80066520 AC43000C */  sw         $v1, 0xC($v0)
    /* 1AB04 80066524 A6A42E68 */  sh         $a0, %lo(D_80182E68)($s5)
  alabel func_80066528
    /* 1AB08 80066528 26310002 */  addiu      $s1, $s1, 0x2
    /* 1AB0C 8006652C 96220000 */  lhu        $v0, 0x0($s1)
    /* 1AB10 80066530 1440FFC9 */  bnez       $v0, .L80066458
    /* 1AB14 80066534 3043FFFF */   andi      $v1, $v0, 0xFFFF
  .L80066538:
    /* 1AB18 80066538 02602021 */  addu       $a0, $s3, $zero
    /* 1AB1C 8006653C 0C019869 */  jal        func_800661A4
    /* 1AB20 80066540 02402821 */   addu      $a1, $s2, $zero
    /* 1AB24 80066544 8FBF003C */  lw         $ra, 0x3C($sp)
    /* 1AB28 80066548 8FBE0038 */  lw         $fp, 0x38($sp)
    /* 1AB2C 8006654C 8FB70034 */  lw         $s7, 0x34($sp)
    /* 1AB30 80066550 8FB60030 */  lw         $s6, 0x30($sp)
    /* 1AB34 80066554 8FB5002C */  lw         $s5, 0x2C($sp)
    /* 1AB38 80066558 8FB40028 */  lw         $s4, 0x28($sp)
    /* 1AB3C 8006655C 8FB30024 */  lw         $s3, 0x24($sp)
    /* 1AB40 80066560 8FB20020 */  lw         $s2, 0x20($sp)
    /* 1AB44 80066564 8FB1001C */  lw         $s1, 0x1C($sp)
    /* 1AB48 80066568 8FB00018 */  lw         $s0, 0x18($sp)
    /* 1AB4C 8006656C 03E00008 */  jr         $ra
    /* 1AB50 80066570 27BD0040 */   addiu     $sp, $sp, 0x40
endlabel func_80066400

nonmatching func_80066574, 0xC

glabel func_80066574
    /* 1AB54 80066574 AFA50004 */  sw         $a1, 0x4($sp)
    /* 1AB58 80066578 AFA60008 */  sw         $a2, 0x8($sp)
    /* 1AB5C 8006657C AFA7000C */  sw         $a3, 0xC($sp)
endlabel func_80066574
