.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_8008E458, 0x50

glabel func_8008E458
    /* 42A38 8008E458 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 42A3C 8008E45C AFBF0014 */  sw         $ra, 0x14($sp)
    /* 42A40 8008E460 240E0001 */  addiu      $t6, $zero, 0x1
    /* 42A44 8008E464 3C018009 */  lui        $at, %hi(D_800964B0)
    /* 42A48 8008E468 3C048019 */  lui        $a0, %hi(D_8018D310)
    /* 42A4C 8008E46C 3C058019 */  lui        $a1, %hi(D_8018D308)
    /* 42A50 8008E470 AC2E64B0 */  sw         $t6, %lo(D_800964B0)($at)
    /* 42A54 8008E474 24A5D308 */  addiu      $a1, $a1, %lo(D_8018D308)
    /* 42A58 8008E478 2484D310 */  addiu      $a0, $a0, %lo(D_8018D310)
    /* 42A5C 8008E47C 0C01EF36 */  jal        func_8007BCD8
    /* 42A60 8008E480 24060001 */   addiu     $a2, $zero, 0x1
    /* 42A64 8008E484 3C048019 */  lui        $a0, %hi(D_8018D310)
    /* 42A68 8008E488 2484D310 */  addiu      $a0, $a0, %lo(D_8018D310)
    /* 42A6C 8008E48C 00002825 */  or         $a1, $zero, $zero
    /* 42A70 8008E490 0C01F392 */  jal        func_8007CE48
    /* 42A74 8008E494 00003025 */   or        $a2, $zero, $zero
    /* 42A78 8008E498 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 42A7C 8008E49C 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 42A80 8008E4A0 03E00008 */  jr         $ra
    /* 42A84 8008E4A4 00000000 */   nop
endlabel func_8008E458

nonmatching func_8008E4A8, 0x8

glabel func_8008E4A8
    /* 42A88 8008E4A8 3C0E8009 */  lui        $t6, %hi(D_800964B0)
    /* 42A8C 8008E4AC 8DCE64B0 */  lw         $t6, %lo(D_800964B0)($t6)
endlabel func_8008E4A8
