.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_80089A68, 0xFC

glabel func_80089A68
    /* 3E048 80089A68 27BDFFC0 */  addiu      $sp, $sp, -0x40
    /* 3E04C 80089A6C AFA40040 */  sw         $a0, 0x40($sp)
    /* 3E050 80089A70 8FAE0040 */  lw         $t6, 0x40($sp)
    /* 3E054 80089A74 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 3E058 80089A78 91CF0065 */  lbu        $t7, 0x65($t6)
    /* 3E05C 80089A7C 11E0000A */  beqz       $t7, .L80089AA8
    /* 3E060 80089A80 00000000 */   nop
    /* 3E064 80089A84 A1C00065 */  sb         $zero, 0x65($t6)
    /* 3E068 80089A88 0C0227A1 */  jal        func_80089E84
    /* 3E06C 80089A8C 8FA40040 */   lw        $a0, 0x40($sp)
    /* 3E070 80089A90 AFA20018 */  sw         $v0, 0x18($sp)
    /* 3E074 80089A94 8FB80018 */  lw         $t8, 0x18($sp)
    /* 3E078 80089A98 13000003 */  beqz       $t8, .L80089AA8
    /* 3E07C 80089A9C 00000000 */   nop
    /* 3E080 80089AA0 1000002C */  b          .L80089B54
    /* 3E084 80089AA4 03001025 */   or        $v0, $t8, $zero
  .L80089AA8:
    /* 3E088 80089AA8 8FB90040 */  lw         $t9, 0x40($sp)
    /* 3E08C 80089AAC 24060001 */  addiu      $a2, $zero, 0x1
    /* 3E090 80089AB0 27A7001C */  addiu      $a3, $sp, 0x1C
    /* 3E094 80089AB4 8F240004 */  lw         $a0, 0x4($t9)
    /* 3E098 80089AB8 0C0227BE */  jal        func_80089EF8
    /* 3E09C 80089ABC 8F250008 */   lw        $a1, 0x8($t9)
    /* 3E0A0 80089AC0 AFA20018 */  sw         $v0, 0x18($sp)
    /* 3E0A4 80089AC4 8FA80018 */  lw         $t0, 0x18($sp)
    /* 3E0A8 80089AC8 11000011 */  beqz       $t0, .L80089B10
    /* 3E0AC 80089ACC 24010002 */   addiu     $at, $zero, 0x2
    /* 3E0B0 80089AD0 11010003 */  beq        $t0, $at, .L80089AE0
    /* 3E0B4 80089AD4 00000000 */   nop
    /* 3E0B8 80089AD8 1000001E */  b          .L80089B54
    /* 3E0BC 80089ADC 01001025 */   or        $v0, $t0, $zero
  .L80089AE0:
    /* 3E0C0 80089AE0 8FA90040 */  lw         $t1, 0x40($sp)
    /* 3E0C4 80089AE4 24060001 */  addiu      $a2, $zero, 0x1
    /* 3E0C8 80089AE8 27A7001C */  addiu      $a3, $sp, 0x1C
    /* 3E0CC 80089AEC 8D240004 */  lw         $a0, 0x4($t1)
    /* 3E0D0 80089AF0 0C0227BE */  jal        func_80089EF8
    /* 3E0D4 80089AF4 8D250008 */   lw        $a1, 0x8($t1)
    /* 3E0D8 80089AF8 AFA20018 */  sw         $v0, 0x18($sp)
    /* 3E0DC 80089AFC 8FAA0018 */  lw         $t2, 0x18($sp)
    /* 3E0E0 80089B00 11400003 */  beqz       $t2, .L80089B10
    /* 3E0E4 80089B04 00000000 */   nop
    /* 3E0E8 80089B08 10000012 */  b          .L80089B54
    /* 3E0EC 80089B0C 01401025 */   or        $v0, $t2, $zero
  .L80089B10:
    /* 3E0F0 80089B10 AFA0003C */  sw         $zero, 0x3C($sp)
  .L80089B14:
    /* 3E0F4 80089B14 8FAB003C */  lw         $t3, 0x3C($sp)
    /* 3E0F8 80089B18 8FAD0040 */  lw         $t5, 0x40($sp)
    /* 3E0FC 80089B1C 03AB6021 */  addu       $t4, $sp, $t3
    /* 3E100 80089B20 01AB7821 */  addu       $t7, $t5, $t3
    /* 3E104 80089B24 91EE000C */  lbu        $t6, 0xC($t7)
    /* 3E108 80089B28 918C001C */  lbu        $t4, 0x1C($t4)
    /* 3E10C 80089B2C 118E0003 */  beq        $t4, $t6, .L80089B3C
    /* 3E110 80089B30 00000000 */   nop
    /* 3E114 80089B34 10000007 */  b          .L80089B54
    /* 3E118 80089B38 24020002 */   addiu     $v0, $zero, 0x2
  .L80089B3C:
    /* 3E11C 80089B3C 8FB8003C */  lw         $t8, 0x3C($sp)
    /* 3E120 80089B40 27190001 */  addiu      $t9, $t8, 0x1
    /* 3E124 80089B44 2B210020 */  slti       $at, $t9, 0x20
    /* 3E128 80089B48 1420FFF2 */  bnez       $at, .L80089B14
    /* 3E12C 80089B4C AFB9003C */   sw        $t9, 0x3C($sp)
    /* 3E130 80089B50 00001025 */  or         $v0, $zero, $zero
  .L80089B54:
    /* 3E134 80089B54 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 3E138 80089B58 27BD0040 */  addiu      $sp, $sp, 0x40
    /* 3E13C 80089B5C 03E00008 */  jr         $ra
    /* 3E140 80089B60 00000000 */   nop
endlabel func_80089A68
