.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_80082598, 0x4C

glabel func_80082598
    /* 36B78 80082598 27BDFFD0 */  addiu      $sp, $sp, -0x30
    /* 36B7C 8008259C AFBF0014 */  sw         $ra, 0x14($sp)
    /* 36B80 800825A0 8C820040 */  lw         $v0, 0x40($a0)
    /* 36B84 800825A4 240E0001 */  addiu      $t6, $zero, 0x1
    /* 36B88 800825A8 A7AE0020 */  sh         $t6, 0x20($sp)
    /* 36B8C 800825AC 8C8F003C */  lw         $t7, 0x3C($a0)
    /* 36B90 800825B0 27A50020 */  addiu      $a1, $sp, 0x20
    /* 36B94 800825B4 24840014 */  addiu      $a0, $a0, 0x14
    /* 36B98 800825B8 000FC080 */  sll        $t8, $t7, 2
    /* 36B9C 800825BC 030FC023 */  subu       $t8, $t8, $t7
    /* 36BA0 800825C0 0018C100 */  sll        $t8, $t8, 4
    /* 36BA4 800825C4 0302C821 */  addu       $t9, $t8, $v0
    /* 36BA8 800825C8 AFB90024 */  sw         $t9, 0x24($sp)
    /* 36BAC 800825CC 0C01F9CD */  jal        func_8007E734
    /* 36BB0 800825D0 00003025 */   or        $a2, $zero, $zero
    /* 36BB4 800825D4 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 36BB8 800825D8 27BD0030 */  addiu      $sp, $sp, 0x30
    /* 36BBC 800825DC 03E00008 */  jr         $ra
    /* 36BC0 800825E0 00000000 */   nop
endlabel func_80082598
    /* 36BC4 800825E4 00000000 */  nop

nonmatching func_800825E8, 0x20

glabel func_800825E8
    /* 36BC8 800825E8 8C8E003C */  lw         $t6, 0x3C($a0)
    /* 36BCC 800825EC 8C830040 */  lw         $v1, 0x40($a0)
    /* 36BD0 800825F0 000E7880 */  sll        $t7, $t6, 2
    /* 36BD4 800825F4 01EE7823 */  subu       $t7, $t7, $t6
    /* 36BD8 800825F8 000F7900 */  sll        $t7, $t7, 4
    /* 36BDC 800825FC 01E3C021 */  addu       $t8, $t7, $v1
    /* 36BE0 80082600 03E00008 */  jr         $ra
    /* 36BE4 80082604 8F020028 */   lw        $v0, 0x28($t8)
endlabel func_800825E8
