.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_8007D688, 0x7C

glabel func_8007D688
    /* 31C68 8007D688 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 31C6C 8007D68C AFA40018 */  sw         $a0, 0x18($sp)
    /* 31C70 8007D690 8FAE0018 */  lw         $t6, 0x18($sp)
    /* 31C74 8007D694 3C018000 */  lui        $at, (0x80000000 >> 16)
    /* 31C78 8007D698 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 31C7C 8007D69C 01C1082B */  sltu       $at, $t6, $at
    /* 31C80 8007D6A0 14200007 */  bnez       $at, .L8007D6C0
    /* 31C84 8007D6A4 3C01A000 */   lui       $at, (0xA0000000 >> 16)
    /* 31C88 8007D6A8 01C1082B */  sltu       $at, $t6, $at
    /* 31C8C 8007D6AC 10200004 */  beqz       $at, .L8007D6C0
    /* 31C90 8007D6B0 3C011FFF */   lui       $at, (0x1FFFFFFF >> 16)
    /* 31C94 8007D6B4 3421FFFF */  ori        $at, $at, (0x1FFFFFFF & 0xFFFF)
    /* 31C98 8007D6B8 1000000E */  b          .L8007D6F4
    /* 31C9C 8007D6BC 01C11024 */   and       $v0, $t6, $at
  .L8007D6C0:
    /* 31CA0 8007D6C0 8FAF0018 */  lw         $t7, 0x18($sp)
    /* 31CA4 8007D6C4 3C01A000 */  lui        $at, (0xA0000000 >> 16)
    /* 31CA8 8007D6C8 01E1082B */  sltu       $at, $t7, $at
    /* 31CAC 8007D6CC 14200007 */  bnez       $at, .L8007D6EC
    /* 31CB0 8007D6D0 3C01C000 */   lui       $at, (0xC0000000 >> 16)
    /* 31CB4 8007D6D4 01E1082B */  sltu       $at, $t7, $at
    /* 31CB8 8007D6D8 10200004 */  beqz       $at, .L8007D6EC
    /* 31CBC 8007D6DC 3C011FFF */   lui       $at, (0x1FFFFFFF >> 16)
    /* 31CC0 8007D6E0 3421FFFF */  ori        $at, $at, (0x1FFFFFFF & 0xFFFF)
    /* 31CC4 8007D6E4 10000003 */  b          .L8007D6F4
    /* 31CC8 8007D6E8 01E11024 */   and       $v0, $t7, $at
  .L8007D6EC:
    /* 31CCC 8007D6EC 0C01F5C2 */  jal        func_8007D708
    /* 31CD0 8007D6F0 8FA40018 */   lw        $a0, 0x18($sp)
  .L8007D6F4:
    /* 31CD4 8007D6F4 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 31CD8 8007D6F8 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 31CDC 8007D6FC 03E00008 */  jr         $ra
    /* 31CE0 8007D700 00000000 */   nop
endlabel func_8007D688
    /* 31CE4 8007D704 00000000 */  nop

/* Handwritten function */
nonmatching func_8007D708, 0xB8

glabel func_8007D708
    /* 31CE8 8007D708 40085000 */  mfc0       $t0, $10 /* handwritten instruction */
    /* 31CEC 8007D70C 310900FF */  andi       $t1, $t0, 0xFF
    /* 31CF0 8007D710 2401E000 */  addiu      $at, $zero, -0x2000
    /* 31CF4 8007D714 00815024 */  and        $t2, $a0, $at
    /* 31CF8 8007D718 012A4825 */  or         $t1, $t1, $t2
    /* 31CFC 8007D71C 40895000 */  mtc0       $t1, $10 /* handwritten instruction */
    /* 31D00 8007D720 00000000 */  nop
    /* 31D04 8007D724 00000000 */  nop
    /* 31D08 8007D728 00000000 */  nop
    /* 31D0C 8007D72C 42000008 */  tlbp /* handwritten instruction */
    /* 31D10 8007D730 00000000 */  nop
    /* 31D14 8007D734 00000000 */  nop
    /* 31D18 8007D738 400B0000 */  mfc0       $t3, $0 /* handwritten instruction */
    /* 31D1C 8007D73C 3C018000 */  lui        $at, (0x80000000 >> 16)
    /* 31D20 8007D740 01615824 */  and        $t3, $t3, $at
    /* 31D24 8007D744 1560001A */  bnez       $t3, .L8007D7B0
    /* 31D28 8007D748 00000000 */   nop
    /* 31D2C 8007D74C 42000001 */  tlbr /* handwritten instruction */
    /* 31D30 8007D750 00000000 */  nop
    /* 31D34 8007D754 00000000 */  nop
    /* 31D38 8007D758 00000000 */  nop
    /* 31D3C 8007D75C 400B2800 */  mfc0       $t3, $5 /* handwritten instruction */
    /* 31D40 8007D760 216B2000 */  addi       $t3, $t3, 0x2000 /* handwritten instruction */
    /* 31D44 8007D764 000B5842 */  srl        $t3, $t3, 1
    /* 31D48 8007D768 01646024 */  and        $t4, $t3, $a0
    /* 31D4C 8007D76C 15800004 */  bnez       $t4, .L8007D780
    /* 31D50 8007D770 216BFFFF */   addi      $t3, $t3, -0x1 /* handwritten instruction */
    /* 31D54 8007D774 40021000 */  mfc0       $v0, $2 /* handwritten instruction */
    /* 31D58 8007D778 10000002 */  b          .L8007D784
    /* 31D5C 8007D77C 00000000 */   nop
  .L8007D780:
    /* 31D60 8007D780 40021800 */  mfc0       $v0, $3 /* handwritten instruction */
  .L8007D784:
    /* 31D64 8007D784 304D0002 */  andi       $t5, $v0, 0x2
    /* 31D68 8007D788 11A00009 */  beqz       $t5, .L8007D7B0
    /* 31D6C 8007D78C 00000000 */   nop
    /* 31D70 8007D790 3C013FFF */  lui        $at, (0x3FFFFFC0 >> 16)
    /* 31D74 8007D794 3421FFC0 */  ori        $at, $at, (0x3FFFFFC0 & 0xFFFF)
    /* 31D78 8007D798 00411024 */  and        $v0, $v0, $at
    /* 31D7C 8007D79C 00021180 */  sll        $v0, $v0, 6
    /* 31D80 8007D7A0 008B6824 */  and        $t5, $a0, $t3
    /* 31D84 8007D7A4 004D1020 */  add        $v0, $v0, $t5 /* handwritten instruction */
    /* 31D88 8007D7A8 10000002 */  b          .L8007D7B4
    /* 31D8C 8007D7AC 00000000 */   nop
  .L8007D7B0:
    /* 31D90 8007D7B0 2402FFFF */  addiu      $v0, $zero, -0x1
  .L8007D7B4:
    /* 31D94 8007D7B4 40885000 */  mtc0       $t0, $10 /* handwritten instruction */
    /* 31D98 8007D7B8 03E00008 */  jr         $ra
    /* 31D9C 8007D7BC 00000000 */   nop
endlabel func_8007D708
    /* 31DA0 8007D7C0 00000000 */  nop
    /* 31DA4 8007D7C4 00000000 */  nop

nonmatching func_8007D7C8, 0x10

glabel func_8007D7C8
    /* 31DA8 8007D7C8 03E00008 */  jr         $ra
    /* 31DAC 8007D7CC 00000000 */   nop
    /* 31DB0 8007D7D0 03E00008 */  jr         $ra
    /* 31DB4 8007D7D4 00000000 */   nop
endlabel func_8007D7C8

nonmatching func_8007D7D8, 0xF4

glabel func_8007D7D8
    /* 31DB8 8007D7D8 908E0003 */  lbu        $t6, 0x3($a0)
    /* 31DBC 8007D7DC 15C00037 */  bnez       $t6, .L8007D8BC
    /* 31DC0 8007D7E0 00000000 */   nop
    /* 31DC4 8007D7E4 848F000E */  lh         $t7, 0xE($a0)
    /* 31DC8 8007D7E8 24090001 */  addiu      $t1, $zero, 0x1
    /* 31DCC 8007D7EC A0890003 */  sb         $t1, 0x3($a0)
    /* 31DD0 8007D7F0 19E00032 */  blez       $t7, .L8007D8BC
    /* 31DD4 8007D7F4 00001025 */   or        $v0, $zero, $zero
    /* 31DD8 8007D7F8 00801825 */  or         $v1, $a0, $zero
    /* 31DDC 8007D7FC 240A0001 */  addiu      $t2, $zero, 0x1
    /* 31DE0 8007D800 8C780010 */  lw         $t8, 0x10($v1)
  .L8007D804:
    /* 31DE4 8007D804 0305C821 */  addu       $t9, $t8, $a1
    /* 31DE8 8007D808 AC790010 */  sw         $t9, 0x10($v1)
    /* 31DEC 8007D80C 932E000E */  lbu        $t6, 0xE($t9)
    /* 31DF0 8007D810 03203025 */  or         $a2, $t9, $zero
    /* 31DF4 8007D814 55C00024 */  bnel       $t6, $zero, .L8007D8A8
    /* 31DF8 8007D818 8498000E */   lh        $t8, 0xE($a0)
    /* 31DFC 8007D81C 8F2F0000 */  lw         $t7, 0x0($t9)
    /* 31E00 8007D820 A329000E */  sb         $t1, 0xE($t9)
    /* 31E04 8007D824 01E5C021 */  addu       $t8, $t7, $a1
    /* 31E08 8007D828 AF380000 */  sw         $t8, 0x0($t9)
    /* 31E0C 8007D82C 8F390004 */  lw         $t9, 0x4($t9)
    /* 31E10 8007D830 8CCF0008 */  lw         $t7, 0x8($a2)
    /* 31E14 8007D834 03257021 */  addu       $t6, $t9, $a1
    /* 31E18 8007D838 01E5C021 */  addu       $t8, $t7, $a1
    /* 31E1C 8007D83C ACCE0004 */  sw         $t6, 0x4($a2)
    /* 31E20 8007D840 ACD80008 */  sw         $t8, 0x8($a2)
    /* 31E24 8007D844 93190009 */  lbu        $t9, 0x9($t8)
    /* 31E28 8007D848 03004025 */  or         $t0, $t8, $zero
    /* 31E2C 8007D84C 57200016 */  bnel       $t9, $zero, .L8007D8A8
    /* 31E30 8007D850 8498000E */   lh        $t8, 0xE($a0)
    /* 31E34 8007D854 8F0E0000 */  lw         $t6, 0x0($t8)
    /* 31E38 8007D858 93060008 */  lbu        $a2, 0x8($t8)
    /* 31E3C 8007D85C A3090009 */  sb         $t1, 0x9($t8)
    /* 31E40 8007D860 01C77821 */  addu       $t7, $t6, $a3
    /* 31E44 8007D864 14C00009 */  bnez       $a2, .L8007D88C
    /* 31E48 8007D868 AF0F0000 */   sw        $t7, 0x0($t8)
    /* 31E4C 8007D86C 8F180010 */  lw         $t8, 0x10($t8)
    /* 31E50 8007D870 8D06000C */  lw         $a2, 0xC($t0)
    /* 31E54 8007D874 0305C821 */  addu       $t9, $t8, $a1
    /* 31E58 8007D878 10C0000A */  beqz       $a2, .L8007D8A4
    /* 31E5C 8007D87C AD190010 */   sw        $t9, 0x10($t0)
    /* 31E60 8007D880 00C57021 */  addu       $t6, $a2, $a1
    /* 31E64 8007D884 10000007 */  b          .L8007D8A4
    /* 31E68 8007D888 AD0E000C */   sw        $t6, 0xC($t0)
  .L8007D88C:
    /* 31E6C 8007D88C 55460006 */  bnel       $t2, $a2, .L8007D8A8
    /* 31E70 8007D890 8498000E */   lh        $t8, 0xE($a0)
    /* 31E74 8007D894 8D06000C */  lw         $a2, 0xC($t0)
    /* 31E78 8007D898 10C00002 */  beqz       $a2, .L8007D8A4
    /* 31E7C 8007D89C 00C57821 */   addu      $t7, $a2, $a1
    /* 31E80 8007D8A0 AD0F000C */  sw         $t7, 0xC($t0)
  .L8007D8A4:
    /* 31E84 8007D8A4 8498000E */  lh         $t8, 0xE($a0)
  .L8007D8A8:
    /* 31E88 8007D8A8 24420001 */  addiu      $v0, $v0, 0x1
    /* 31E8C 8007D8AC 24630004 */  addiu      $v1, $v1, 0x4
    /* 31E90 8007D8B0 0058082A */  slt        $at, $v0, $t8
    /* 31E94 8007D8B4 5420FFD3 */  bnel       $at, $zero, .L8007D804
    /* 31E98 8007D8B8 8C780010 */   lw        $t8, 0x10($v1)
  .L8007D8BC:
    /* 31E9C 8007D8BC 03E00008 */  jr         $ra
    /* 31EA0 8007D8C0 00000000 */   nop
    /* 31EA4 8007D8C4 03E00008 */  jr         $ra
    /* 31EA8 8007D8C8 00000000 */   nop
endlabel func_8007D7D8
