.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_8007AE7C, 0x68

glabel func_8007AE7C
    /* 2F45C 8007AE7C 27BDFF98 */  addiu      $sp, $sp, -0x68
    /* 2F460 8007AE80 44856000 */  mtc1       $a1, $fa0
    /* 2F464 8007AE84 44867000 */  mtc1       $a2, $fa1
    /* 2F468 8007AE88 44878000 */  mtc1       $a3, $ft4
    /* 2F46C 8007AE8C C7A40078 */  lwc1       $ft0, 0x78($sp)
    /* 2F470 8007AE90 C7A6007C */  lwc1       $ft1, 0x7C($sp)
    /* 2F474 8007AE94 C7A80080 */  lwc1       $ft2, 0x80($sp)
    /* 2F478 8007AE98 C7AA0084 */  lwc1       $ft3, 0x84($sp)
    /* 2F47C 8007AE9C AFBF0024 */  sw         $ra, 0x24($sp)
    /* 2F480 8007AEA0 AFA40068 */  sw         $a0, 0x68($sp)
    /* 2F484 8007AEA4 44056000 */  mfc1       $a1, $fa0
    /* 2F488 8007AEA8 44067000 */  mfc1       $a2, $fa1
    /* 2F48C 8007AEAC 44078000 */  mfc1       $a3, $ft4
    /* 2F490 8007AEB0 27A40028 */  addiu      $a0, $sp, 0x28
    /* 2F494 8007AEB4 E7A40010 */  swc1       $ft0, 0x10($sp)
    /* 2F498 8007AEB8 E7A60014 */  swc1       $ft1, 0x14($sp)
    /* 2F49C 8007AEBC E7A80018 */  swc1       $ft2, 0x18($sp)
    /* 2F4A0 8007AEC0 0C01EB4A */  jal        func_8007AD28
    /* 2F4A4 8007AEC4 E7AA001C */   swc1      $ft3, 0x1C($sp)
    /* 2F4A8 8007AEC8 27A40028 */  addiu      $a0, $sp, 0x28
    /* 2F4AC 8007AECC 0C01E9D6 */  jal        func_8007A758
    /* 2F4B0 8007AED0 8FA50068 */   lw        $a1, 0x68($sp)
    /* 2F4B4 8007AED4 8FBF0024 */  lw         $ra, 0x24($sp)
    /* 2F4B8 8007AED8 27BD0068 */  addiu      $sp, $sp, 0x68
    /* 2F4BC 8007AEDC 03E00008 */  jr         $ra
    /* 2F4C0 8007AEE0 00000000 */   nop
endlabel func_8007AE7C
    /* 2F4C4 8007AEE4 00000000 */  nop
