.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_8004F4AC, 0x7E8

glabel func_8004F4AC
    /* 3A8C 8004F4AC 27BDFF90 */  addiu      $sp, $sp, -0x70
    /* 3A90 8004F4B0 AFB30044 */  sw         $s3, 0x44($sp)
    /* 3A94 8004F4B4 00809821 */  addu       $s3, $a0, $zero
    /* 3A98 8004F4B8 AFBF005C */  sw         $ra, 0x5C($sp)
    /* 3A9C 8004F4BC AFBE0058 */  sw         $fp, 0x58($sp)
    /* 3AA0 8004F4C0 AFB70054 */  sw         $s7, 0x54($sp)
    /* 3AA4 8004F4C4 AFB60050 */  sw         $s6, 0x50($sp)
    /* 3AA8 8004F4C8 AFB5004C */  sw         $s5, 0x4C($sp)
    /* 3AAC 8004F4CC AFB40048 */  sw         $s4, 0x48($sp)
    /* 3AB0 8004F4D0 AFB20040 */  sw         $s2, 0x40($sp)
    /* 3AB4 8004F4D4 AFB1003C */  sw         $s1, 0x3C($sp)
    /* 3AB8 8004F4D8 AFB00038 */  sw         $s0, 0x38($sp)
    /* 3ABC 8004F4DC F7B60068 */  sdc1       $fs1, 0x68($sp)
    /* 3AC0 8004F4E0 F7B40060 */  sdc1       $fs0, 0x60($sp)
    /* 3AC4 8004F4E4 8E630020 */  lw         $v1, 0x20($s3)
    /* 3AC8 8004F4E8 10600005 */  beqz       $v1, .L8004F500
    /* 3ACC 8004F4EC 3C0200FF */   lui       $v0, (0xFFFFFF >> 16)
    /* 3AD0 8004F4F0 3442FFFF */  ori        $v0, $v0, (0xFFFFFF & 0xFFFF)
    /* 3AD4 8004F4F4 00621024 */  and        $v0, $v1, $v0
    /* 3AD8 8004F4F8 00451021 */  addu       $v0, $v0, $a1
    /* 3ADC 8004F4FC AE620020 */  sw         $v0, 0x20($s3)
  .L8004F500:
    /* 3AE0 8004F500 8E630028 */  lw         $v1, 0x28($s3)
    /* 3AE4 8004F504 10600005 */  beqz       $v1, .L8004F51C
    /* 3AE8 8004F508 3C0200FF */   lui       $v0, (0xFFFFFF >> 16)
    /* 3AEC 8004F50C 3442FFFF */  ori        $v0, $v0, (0xFFFFFF & 0xFFFF)
    /* 3AF0 8004F510 00621024 */  and        $v0, $v1, $v0
    /* 3AF4 8004F514 00451021 */  addu       $v0, $v0, $a1
    /* 3AF8 8004F518 AE620028 */  sw         $v0, 0x28($s3)
  .L8004F51C:
    /* 3AFC 8004F51C 8E630030 */  lw         $v1, 0x30($s3)
    /* 3B00 8004F520 10600005 */  beqz       $v1, .L8004F538
    /* 3B04 8004F524 3C0200FF */   lui       $v0, (0xFFFFFF >> 16)
    /* 3B08 8004F528 3442FFFF */  ori        $v0, $v0, (0xFFFFFF & 0xFFFF)
    /* 3B0C 8004F52C 00621024 */  and        $v0, $v1, $v0
    /* 3B10 8004F530 00451021 */  addu       $v0, $v0, $a1
    /* 3B14 8004F534 AE620030 */  sw         $v0, 0x30($s3)
  .L8004F538:
    /* 3B18 8004F538 8E63005C */  lw         $v1, 0x5C($s3)
    /* 3B1C 8004F53C 10600005 */  beqz       $v1, .L8004F554
    /* 3B20 8004F540 3C0200FF */   lui       $v0, (0xFFFFFF >> 16)
    /* 3B24 8004F544 3442FFFF */  ori        $v0, $v0, (0xFFFFFF & 0xFFFF)
    /* 3B28 8004F548 00621024 */  and        $v0, $v1, $v0
    /* 3B2C 8004F54C 00451021 */  addu       $v0, $v0, $a1
    /* 3B30 8004F550 AE62005C */  sw         $v0, 0x5C($s3)
  .L8004F554:
    /* 3B34 8004F554 8E63004C */  lw         $v1, 0x4C($s3)
    /* 3B38 8004F558 10600005 */  beqz       $v1, .L8004F570
    /* 3B3C 8004F55C 3C0200FF */   lui       $v0, (0xFFFFFF >> 16)
    /* 3B40 8004F560 3442FFFF */  ori        $v0, $v0, (0xFFFFFF & 0xFFFF)
    /* 3B44 8004F564 00621024 */  and        $v0, $v1, $v0
    /* 3B48 8004F568 00451021 */  addu       $v0, $v0, $a1
    /* 3B4C 8004F56C AE62004C */  sw         $v0, 0x4C($s3)
  .L8004F570:
    /* 3B50 8004F570 8E63001C */  lw         $v1, 0x1C($s3)
    /* 3B54 8004F574 10600005 */  beqz       $v1, .L8004F58C
    /* 3B58 8004F578 3C0200FF */   lui       $v0, (0xFFFFFF >> 16)
    /* 3B5C 8004F57C 3442FFFF */  ori        $v0, $v0, (0xFFFFFF & 0xFFFF)
    /* 3B60 8004F580 00621024 */  and        $v0, $v1, $v0
    /* 3B64 8004F584 00451021 */  addu       $v0, $v0, $a1
    /* 3B68 8004F588 AE62001C */  sw         $v0, 0x1C($s3)
  .L8004F58C:
    /* 3B6C 8004F58C 8E630038 */  lw         $v1, 0x38($s3)
    /* 3B70 8004F590 10600005 */  beqz       $v1, .L8004F5A8
    /* 3B74 8004F594 3C0200FF */   lui       $v0, (0xFFFFFF >> 16)
    /* 3B78 8004F598 3442FFFF */  ori        $v0, $v0, (0xFFFFFF & 0xFFFF)
    /* 3B7C 8004F59C 00621024 */  and        $v0, $v1, $v0
    /* 3B80 8004F5A0 00451021 */  addu       $v0, $v0, $a1
    /* 3B84 8004F5A4 AE620038 */  sw         $v0, 0x38($s3)
  .L8004F5A8:
    /* 3B88 8004F5A8 8E630040 */  lw         $v1, 0x40($s3)
    /* 3B8C 8004F5AC 10600005 */  beqz       $v1, .L8004F5C4
    /* 3B90 8004F5B0 3C0200FF */   lui       $v0, (0xFFFFFF >> 16)
    /* 3B94 8004F5B4 3442FFFF */  ori        $v0, $v0, (0xFFFFFF & 0xFFFF)
    /* 3B98 8004F5B8 00621024 */  and        $v0, $v1, $v0
    /* 3B9C 8004F5BC 00451021 */  addu       $v0, $v0, $a1
    /* 3BA0 8004F5C0 AE620040 */  sw         $v0, 0x40($s3)
  .L8004F5C4:
    /* 3BA4 8004F5C4 8E630050 */  lw         $v1, 0x50($s3)
    /* 3BA8 8004F5C8 10600005 */  beqz       $v1, .L8004F5E0
    /* 3BAC 8004F5CC 3C0200FF */   lui       $v0, (0xFFFFFF >> 16)
    /* 3BB0 8004F5D0 3442FFFF */  ori        $v0, $v0, (0xFFFFFF & 0xFFFF)
    /* 3BB4 8004F5D4 00621024 */  and        $v0, $v1, $v0
    /* 3BB8 8004F5D8 00451021 */  addu       $v0, $v0, $a1
    /* 3BBC 8004F5DC AE620050 */  sw         $v0, 0x50($s3)
  .L8004F5E0:
    /* 3BC0 8004F5E0 8E630054 */  lw         $v1, 0x54($s3)
    /* 3BC4 8004F5E4 10600005 */  beqz       $v1, .L8004F5FC
    /* 3BC8 8004F5E8 3C0200FF */   lui       $v0, (0xFFFFFF >> 16)
    /* 3BCC 8004F5EC 3442FFFF */  ori        $v0, $v0, (0xFFFFFF & 0xFFFF)
    /* 3BD0 8004F5F0 00621024 */  and        $v0, $v1, $v0
    /* 3BD4 8004F5F4 00451021 */  addu       $v0, $v0, $a1
    /* 3BD8 8004F5F8 AE620054 */  sw         $v0, 0x54($s3)
  .L8004F5FC:
    /* 3BDC 8004F5FC 8E630160 */  lw         $v1, 0x160($s3)
    /* 3BE0 8004F600 10600005 */  beqz       $v1, .L8004F618
    /* 3BE4 8004F604 3C0200FF */   lui       $v0, (0xFFFFFF >> 16)
    /* 3BE8 8004F608 3442FFFF */  ori        $v0, $v0, (0xFFFFFF & 0xFFFF)
    /* 3BEC 8004F60C 00621024 */  and        $v0, $v1, $v0
    /* 3BF0 8004F610 00451021 */  addu       $v0, $v0, $a1
    /* 3BF4 8004F614 AE620160 */  sw         $v0, 0x160($s3)
  .L8004F618:
    /* 3BF8 8004F618 8E630164 */  lw         $v1, 0x164($s3)
    /* 3BFC 8004F61C 10600005 */  beqz       $v1, .L8004F634
    /* 3C00 8004F620 3C0200FF */   lui       $v0, (0xFFFFFF >> 16)
    /* 3C04 8004F624 3442FFFF */  ori        $v0, $v0, (0xFFFFFF & 0xFFFF)
    /* 3C08 8004F628 00621024 */  and        $v0, $v1, $v0
    /* 3C0C 8004F62C 00451021 */  addu       $v0, $v0, $a1
    /* 3C10 8004F630 AE620164 */  sw         $v0, 0x164($s3)
  .L8004F634:
    /* 3C14 8004F634 8E630168 */  lw         $v1, 0x168($s3)
    /* 3C18 8004F638 10600005 */  beqz       $v1, .L8004F650
    /* 3C1C 8004F63C 3C0200FF */   lui       $v0, (0xFFFFFF >> 16)
    /* 3C20 8004F640 3442FFFF */  ori        $v0, $v0, (0xFFFFFF & 0xFFFF)
    /* 3C24 8004F644 00621024 */  and        $v0, $v1, $v0
    /* 3C28 8004F648 00451021 */  addu       $v0, $v0, $a1
    /* 3C2C 8004F64C AE620168 */  sw         $v0, 0x168($s3)
  .L8004F650:
    /* 3C30 8004F650 8E63016C */  lw         $v1, 0x16C($s3)
    /* 3C34 8004F654 10600005 */  beqz       $v1, .L8004F66C
    /* 3C38 8004F658 3C0200FF */   lui       $v0, (0xFFFFFF >> 16)
    /* 3C3C 8004F65C 3442FFFF */  ori        $v0, $v0, (0xFFFFFF & 0xFFFF)
    /* 3C40 8004F660 00621024 */  and        $v0, $v1, $v0
    /* 3C44 8004F664 00451021 */  addu       $v0, $v0, $a1
    /* 3C48 8004F668 AE62016C */  sw         $v0, 0x16C($s3)
  .L8004F66C:
    /* 3C4C 8004F66C 8E630170 */  lw         $v1, 0x170($s3)
    /* 3C50 8004F670 10600005 */  beqz       $v1, .L8004F688
    /* 3C54 8004F674 3C0200FF */   lui       $v0, (0xFFFFFF >> 16)
    /* 3C58 8004F678 3442FFFF */  ori        $v0, $v0, (0xFFFFFF & 0xFFFF)
    /* 3C5C 8004F67C 00621024 */  and        $v0, $v1, $v0
    /* 3C60 8004F680 00451021 */  addu       $v0, $v0, $a1
    /* 3C64 8004F684 AE620170 */  sw         $v0, 0x170($s3)
  .L8004F688:
    /* 3C68 8004F688 8E630174 */  lw         $v1, 0x174($s3)
    /* 3C6C 8004F68C 10600005 */  beqz       $v1, .L8004F6A4
    /* 3C70 8004F690 3C0200FF */   lui       $v0, (0xFFFFFF >> 16)
    /* 3C74 8004F694 3442FFFF */  ori        $v0, $v0, (0xFFFFFF & 0xFFFF)
    /* 3C78 8004F698 00621024 */  and        $v0, $v1, $v0
    /* 3C7C 8004F69C 00451021 */  addu       $v0, $v0, $a1
    /* 3C80 8004F6A0 AE620174 */  sw         $v0, 0x174($s3)
  .L8004F6A4:
    /* 3C84 8004F6A4 00008021 */  addu       $s0, $zero, $zero
    /* 3C88 8004F6A8 0200B021 */  addu       $s6, $s0, $zero
    /* 3C8C 8004F6AC 0200A821 */  addu       $s5, $s0, $zero
    /* 3C90 8004F6B0 8E620058 */  lw         $v0, 0x58($s3)
    /* 3C94 8004F6B4 8E740050 */  lw         $s4, 0x50($s3)
    /* 3C98 8004F6B8 1840000A */  blez       $v0, .L8004F6E4
    /* 3C9C 8004F6BC 02008821 */   addu      $s1, $s0, $zero
    /* 3CA0 8004F6C0 26840002 */  addiu      $a0, $s4, 0x2
  .L8004F6C4:
    /* 3CA4 8004F6C4 90820000 */  lbu        $v0, 0x0($a0)
    /* 3CA8 8004F6C8 26310001 */  addiu      $s1, $s1, 0x1
    /* 3CAC 8004F6CC 304200EF */  andi       $v0, $v0, 0xEF
    /* 3CB0 8004F6D0 A0820000 */  sb         $v0, 0x0($a0)
    /* 3CB4 8004F6D4 8E620058 */  lw         $v0, 0x58($s3)
    /* 3CB8 8004F6D8 0222102A */  slt        $v0, $s1, $v0
    /* 3CBC 8004F6DC 1440FFF9 */  bnez       $v0, .L8004F6C4
    /* 3CC0 8004F6E0 2484000C */   addiu     $a0, $a0, 0xC
  .L8004F6E4:
    /* 3CC4 8004F6E4 0C013D10 */  jal        func_8004F440
    /* 3CC8 8004F6E8 02602021 */   addu      $a0, $s3, $zero
    /* 3CCC 8004F6EC 0C0134E0 */  jal        func_8004D380
    /* 3CD0 8004F6F0 00008821 */   addu      $s1, $zero, $zero
    /* 3CD4 8004F6F4 00409021 */  addu       $s2, $v0, $zero
    /* 3CD8 8004F6F8 00101040 */  sll        $v0, $s0, 1
    /* 3CDC 8004F6FC 00521021 */  addu       $v0, $v0, $s2
    /* 3CE0 8004F700 A4400000 */  sh         $zero, 0x0($v0)
    /* 3CE4 8004F704 8E620058 */  lw         $v0, 0x58($s3)
    /* 3CE8 8004F708 8E740050 */  lw         $s4, 0x50($s3)
    /* 3CEC 8004F70C 5840002C */  blezl      $v0, .L8004F7C0
    /* 3CF0 8004F710 00008821 */   addu      $s1, $zero, $zero
    /* 3CF4 8004F714 26840006 */  addiu      $a0, $s4, 0x6
  .L8004F718:
    /* 3CF8 8004F718 94820000 */  lhu        $v0, 0x0($a0)
    /* 3CFC 8004F71C 00561021 */  addu       $v0, $v0, $s6
    /* 3D00 8004F720 A4820000 */  sh         $v0, 0x0($a0)
    /* 3D04 8004F724 9482FFFE */  lhu        $v0, -0x2($a0)
    /* 3D08 8004F728 94960000 */  lhu        $s6, 0x0($a0)
    /* 3D0C 8004F72C 00551021 */  addu       $v0, $v0, $s5
    /* 3D10 8004F730 02C01821 */  addu       $v1, $s6, $zero
    /* 3D14 8004F734 A482FFFE */  sh         $v0, -0x2($a0)
    /* 3D18 8004F738 3055FFFF */  andi       $s5, $v0, 0xFFFF
    /* 3D1C 8004F73C 0203102A */  slt        $v0, $s0, $v1
    /* 3D20 8004F740 10400004 */  beqz       $v0, .L8004F754
    /* 3D24 8004F744 00031040 */   sll       $v0, $v1, 1
    /* 3D28 8004F748 00608021 */  addu       $s0, $v1, $zero
    /* 3D2C 8004F74C 00521021 */  addu       $v0, $v0, $s2
    /* 3D30 8004F750 A4400000 */  sh         $zero, 0x0($v0)
  .L8004F754:
    /* 3D34 8004F754 8E620058 */  lw         $v0, 0x58($s3)
    /* 3D38 8004F758 26310001 */  addiu      $s1, $s1, 0x1
    /* 3D3C 8004F75C 0222102A */  slt        $v0, $s1, $v0
    /* 3D40 8004F760 1440FFED */  bnez       $v0, .L8004F718
    /* 3D44 8004F764 2484000C */   addiu     $a0, $a0, 0xC
    /* 3D48 8004F768 8E620058 */  lw         $v0, 0x58($s3)
    /* 3D4C 8004F76C 8E740050 */  lw         $s4, 0x50($s3)
    /* 3D50 8004F770 18400013 */  blez       $v0, .L8004F7C0
    /* 3D54 8004F774 00008821 */   addu      $s1, $zero, $zero
    /* 3D58 8004F778 24050001 */  addiu      $a1, $zero, 0x1
    /* 3D5C 8004F77C 3C028009 */  lui        $v0, %hi(D_80091FD0)
    /* 3D60 8004F780 8C421FD0 */  lw         $v0, %lo(D_80091FD0)($v0)
    /* 3D64 8004F784 26840006 */  addiu      $a0, $s4, 0x6
    /* 3D68 8004F788 34430010 */  ori        $v1, $v0, 0x10
  .L8004F78C:
    /* 3D6C 8004F78C 9082FFFC */  lbu        $v0, -0x4($a0)
    /* 3D70 8004F790 00431024 */  and        $v0, $v0, $v1
    /* 3D74 8004F794 10400005 */  beqz       $v0, .L8004F7AC
    /* 3D78 8004F798 00000000 */   nop
    /* 3D7C 8004F79C 94820000 */  lhu        $v0, 0x0($a0)
    /* 3D80 8004F7A0 00021040 */  sll        $v0, $v0, 1
    /* 3D84 8004F7A4 00521021 */  addu       $v0, $v0, $s2
    /* 3D88 8004F7A8 A4450000 */  sh         $a1, 0x0($v0)
  .L8004F7AC:
    /* 3D8C 8004F7AC 8E620058 */  lw         $v0, 0x58($s3)
    /* 3D90 8004F7B0 26310001 */  addiu      $s1, $s1, 0x1
    /* 3D94 8004F7B4 0222102A */  slt        $v0, $s1, $v0
    /* 3D98 8004F7B8 1440FFF4 */  bnez       $v0, .L8004F78C
    /* 3D9C 8004F7BC 2484000C */   addiu     $a0, $a0, 0xC
  .L8004F7C0:
    /* 3DA0 8004F7C0 00002821 */  addu       $a1, $zero, $zero
    /* 3DA4 8004F7C4 26020001 */  addiu      $v0, $s0, 0x1
    /* 3DA8 8004F7C8 1840000A */  blez       $v0, .L8004F7F4
    /* 3DAC 8004F7CC 00A08821 */   addu      $s1, $a1, $zero
    /* 3DB0 8004F7D0 00402021 */  addu       $a0, $v0, $zero
    /* 3DB4 8004F7D4 02401821 */  addu       $v1, $s2, $zero
  .L8004F7D8:
    /* 3DB8 8004F7D8 94620000 */  lhu        $v0, 0x0($v1)
    /* 3DBC 8004F7DC 54400001 */  bnel       $v0, $zero, .L8004F7E4
    /* 3DC0 8004F7E0 24A50001 */   addiu     $a1, $a1, 0x1
  .L8004F7E4:
    /* 3DC4 8004F7E4 26310001 */  addiu      $s1, $s1, 0x1
    /* 3DC8 8004F7E8 0224102A */  slt        $v0, $s1, $a0
    /* 3DCC 8004F7EC 1440FFFA */  bnez       $v0, .L8004F7D8
    /* 3DD0 8004F7F0 24630002 */   addiu     $v1, $v1, 0x2
  .L8004F7F4:
    /* 3DD4 8004F7F4 00052040 */  sll        $a0, $a1, 1
    /* 3DD8 8004F7F8 00852021 */  addu       $a0, $a0, $a1
    /* 3DDC 8004F7FC 0C01352A */  jal        func_8004D4A8
    /* 3DE0 8004F800 00042080 */   sll       $a0, $a0, 2
    /* 3DE4 8004F804 0C0134E0 */  jal        func_8004D380
    /* 3DE8 8004F808 AE62004C */   sw        $v0, 0x4C($s3)
    /* 3DEC 8004F80C 00002821 */  addu       $a1, $zero, $zero
    /* 3DF0 8004F810 0040F021 */  addu       $fp, $v0, $zero
    /* 3DF4 8004F814 26020001 */  addiu      $v0, $s0, 0x1
    /* 3DF8 8004F818 1840000F */  blez       $v0, .L8004F858
    /* 3DFC 8004F81C 00A08821 */   addu      $s1, $a1, $zero
    /* 3E00 8004F820 3406FFFF */  ori        $a2, $zero, 0xFFFF
    /* 3E04 8004F824 00403821 */  addu       $a3, $v0, $zero
    /* 3E08 8004F828 03C01821 */  addu       $v1, $fp, $zero
    /* 3E0C 8004F82C 02402021 */  addu       $a0, $s2, $zero
  .L8004F830:
    /* 3E10 8004F830 94820000 */  lhu        $v0, 0x0($a0)
    /* 3E14 8004F834 50400003 */  beql       $v0, $zero, .L8004F844
    /* 3E18 8004F838 A4660000 */   sh        $a2, 0x0($v1)
    /* 3E1C 8004F83C A4650000 */  sh         $a1, 0x0($v1)
    /* 3E20 8004F840 24A50001 */  addiu      $a1, $a1, 0x1
  .L8004F844:
    /* 3E24 8004F844 24630002 */  addiu      $v1, $v1, 0x2
    /* 3E28 8004F848 26310001 */  addiu      $s1, $s1, 0x1
    /* 3E2C 8004F84C 0227102A */  slt        $v0, $s1, $a3
    /* 3E30 8004F850 1440FFF7 */  bnez       $v0, .L8004F830
    /* 3E34 8004F854 24840002 */   addiu     $a0, $a0, 0x2
  .L8004F858:
    /* 3E38 8004F858 0000B021 */  addu       $s6, $zero, $zero
    /* 3E3C 8004F85C 8E740050 */  lw         $s4, 0x50($s3)
    /* 3E40 8004F860 8E690044 */  lw         $t1, 0x44($s3)
    /* 3E44 8004F864 AFA90030 */  sw         $t1, 0x30($sp)
    /* 3E48 8004F868 8E620058 */  lw         $v0, 0x58($s3)
    /* 3E4C 8004F86C 8E75004C */  lw         $s5, 0x4C($s3)
    /* 3E50 8004F870 184000A5 */  blez       $v0, .L8004FB08
    /* 3E54 8004F874 02C08821 */   addu      $s1, $s6, $zero
    /* 3E58 8004F878 26920003 */  addiu      $s2, $s4, 0x3
    /* 3E5C 8004F87C 3C018005 */  lui        $at, %hi(D_8004BBF8)
    /* 3E60 8004F880 C436BBF8 */  lwc1       $fs1, %lo(D_8004BBF8)($at)
    /* 3E64 8004F884 4480A000 */  mtc1       $zero, $fs0
  .L8004F888:
    /* 3E68 8004F888 96420003 */  lhu        $v0, 0x3($s2)
    /* 3E6C 8004F88C 00021040 */  sll        $v0, $v0, 1
    /* 3E70 8004F890 005E1021 */  addu       $v0, $v0, $fp
    /* 3E74 8004F894 94430000 */  lhu        $v1, 0x0($v0)
    /* 3E78 8004F898 3402FFFF */  ori        $v0, $zero, 0xFFFF
    /* 3E7C 8004F89C 14620005 */  bne        $v1, $v0, .L8004F8B4
    /* 3E80 8004F8A0 00000000 */   nop
    /* 3E84 8004F8A4 A6400003 */  sh         $zero, 0x3($s2)
    /* 3E88 8004F8A8 2652000C */  addiu      $s2, $s2, 0xC
    /* 3E8C 8004F8AC 08013EBD */  j          func_8004FAF4
    /* 3E90 8004F8B0 2694000C */   addiu     $s4, $s4, 0xC
  .L8004F8B4:
    /* 3E94 8004F8B4 96840000 */  lhu        $a0, 0x0($s4)
    /* 3E98 8004F8B8 3083FFFF */  andi       $v1, $a0, 0xFFFF
    /* 3E9C 8004F8BC 00031142 */  srl        $v0, $v1, 5
    /* 3EA0 8004F8C0 3046001F */  andi       $a2, $v0, 0x1F
    /* 3EA4 8004F8C4 00031A82 */  srl        $v1, $v1, 10
    /* 3EA8 8004F8C8 3068001F */  andi       $t0, $v1, 0x1F
    /* 3EAC 8004F8CC 3C028009 */  lui        $v0, %hi(D_80091FCC)
    /* 3EB0 8004F8D0 8C421FCC */  lw         $v0, %lo(D_80091FCC)($v0)
    /* 3EB4 8004F8D4 1040000E */  beqz       $v0, .L8004F910
    /* 3EB8 8004F8D8 3085001F */   andi      $a1, $a0, 0x1F
    /* 3EBC 8004F8DC 00081940 */  sll        $v1, $t0, 5
    /* 3EC0 8004F8E0 01002021 */  addu       $a0, $t0, $zero
    /* 3EC4 8004F8E4 00C04021 */  addu       $t0, $a2, $zero
    /* 3EC8 8004F8E8 00081280 */  sll        $v0, $t0, 10
    /* 3ECC 8004F8EC 00621825 */  or         $v1, $v1, $v0
    /* 3ED0 8004F8F0 00651825 */  or         $v1, $v1, $a1
    /* 3ED4 8004F8F4 A6830000 */  sh         $v1, 0x0($s4)
    /* 3ED8 8004F8F8 92430000 */  lbu        $v1, 0x0($s2)
    /* 3EDC 8004F8FC 30620080 */  andi       $v0, $v1, 0x80
    /* 3EE0 8004F900 10400003 */  beqz       $v0, .L8004F910
    /* 3EE4 8004F904 00803021 */   addu      $a2, $a0, $zero
    /* 3EE8 8004F908 38620020 */  xori       $v0, $v1, 0x20
    /* 3EEC 8004F90C A2420000 */  sb         $v0, 0x0($s2)
  .L8004F910:
    /* 3EF0 8004F910 96420003 */  lhu        $v0, 0x3($s2)
    /* 3EF4 8004F914 00021040 */  sll        $v0, $v0, 1
    /* 3EF8 8004F918 005E1021 */  addu       $v0, $v0, $fp
    /* 3EFC 8004F91C 94420000 */  lhu        $v0, 0x0($v0)
    /* 3F00 8004F920 3050FFFF */  andi       $s0, $v0, 0xFFFF
    /* 3F04 8004F924 16160022 */  bne        $s0, $s6, .L8004F9B0
    /* 3F08 8004F928 A6420003 */   sh        $v0, 0x3($s2)
    /* 3F0C 8004F92C 96420001 */  lhu        $v0, 0x1($s2)
    /* 3F10 8004F930 8FA90030 */  lw         $t1, 0x30($sp)
    /* 3F14 8004F934 00021100 */  sll        $v0, $v0, 4
    /* 3F18 8004F938 00491021 */  addu       $v0, $v0, $t1
    /* 3F1C 8004F93C 8C470000 */  lw         $a3, 0x0($v0)
    /* 3F20 8004F940 3C028000 */  lui        $v0, (0x80000000 >> 16)
    /* 3F24 8004F944 00E21824 */  and        $v1, $a3, $v0
    /* 3F28 8004F948 1060000D */  beqz       $v1, .L8004F980
    /* 3F2C 8004F94C 00E23825 */   or        $a3, $a3, $v0
    /* 3F30 8004F950 00052040 */  sll        $a0, $a1, 1
    /* 3F34 8004F954 00852021 */  addu       $a0, $a0, $a1
    /* 3F38 8004F958 00042040 */  sll        $a0, $a0, 1
    /* 3F3C 8004F95C 00E42021 */  addu       $a0, $a3, $a0
    /* 3F40 8004F960 00062840 */  sll        $a1, $a2, 1
    /* 3F44 8004F964 00A62821 */  addu       $a1, $a1, $a2
    /* 3F48 8004F968 00052840 */  sll        $a1, $a1, 1
    /* 3F4C 8004F96C 00E52821 */  addu       $a1, $a3, $a1
    /* 3F50 8004F970 00083040 */  sll        $a2, $t0, 1
    /* 3F54 8004F974 00C83021 */  addu       $a2, $a2, $t0
    /* 3F58 8004F978 08013E65 */  j          func_8004F994
    /* 3F5C 8004F97C 00063040 */   sll       $a2, $a2, 1
  .L8004F980:
    /* 3F60 8004F980 00052100 */  sll        $a0, $a1, 4
    /* 3F64 8004F984 00E42021 */  addu       $a0, $a3, $a0
    /* 3F68 8004F988 00062900 */  sll        $a1, $a2, 4
    /* 3F6C 8004F98C 00E52821 */  addu       $a1, $a3, $a1
    /* 3F70 8004F990 00083100 */  sll        $a2, $t0, 4
  alabel func_8004F994
    /* 3F74 8004F994 00E63021 */  addu       $a2, $a3, $a2
    /* 3F78 8004F998 00103840 */  sll        $a3, $s0, 1
    /* 3F7C 8004F99C 00F03821 */  addu       $a3, $a3, $s0
    /* 3F80 8004F9A0 00073880 */  sll        $a3, $a3, 2
    /* 3F84 8004F9A4 0C015F08 */  jal        func_80057C20
    /* 3F88 8004F9A8 02A73821 */   addu      $a3, $s5, $a3
    /* 3F8C 8004F9AC 26D60001 */  addiu      $s6, $s6, 0x1
  .L8004F9B0:
    /* 3F90 8004F9B0 00101040 */  sll        $v0, $s0, 1
    /* 3F94 8004F9B4 00501021 */  addu       $v0, $v0, $s0
    /* 3F98 8004F9B8 00021080 */  sll        $v0, $v0, 2
    /* 3F9C 8004F9BC 00551021 */  addu       $v0, $v0, $s5
    /* 3FA0 8004F9C0 E7B60020 */  swc1       $fs1, 0x20($sp)
    /* 3FA4 8004F9C4 AFA00024 */  sw         $zero, 0x24($sp)
    /* 3FA8 8004F9C8 AFA00028 */  sw         $zero, 0x28($sp)
    /* 3FAC 8004F9CC C4460000 */  lwc1       $ft1, 0x0($v0)
    /* 3FB0 8004F9D0 C7A20024 */  lwc1       $fv1, 0x24($sp)
    /* 3FB4 8004F9D4 E7B60024 */  swc1       $fs1, 0x24($sp)
    /* 3FB8 8004F9D8 46003306 */  mov.s      $fa0, $ft1
    /* 3FBC 8004F9DC E7A20020 */  swc1       $fv1, 0x20($sp)
    /* 3FC0 8004F9E0 E7A20028 */  swc1       $fv1, 0x28($sp)
    /* 3FC4 8004F9E4 C4440004 */  lwc1       $ft0, 0x4($v0)
    /* 3FC8 8004F9E8 4602603C */  c.lt.s     $fa0, $fv1
    /* 3FCC 8004F9EC E7A20024 */  swc1       $fv1, 0x24($sp)
    /* 3FD0 8004F9F0 E7B60028 */  swc1       $fs1, 0x28($sp)
    /* 3FD4 8004F9F4 C4400008 */  lwc1       $fv0, 0x8($v0)
    /* 3FD8 8004F9F8 46002286 */  mov.s      $ft3, $ft0
    /* 3FDC 8004F9FC 45000002 */  bc1f       .L8004FA08
    /* 3FE0 8004FA00 46000206 */   mov.s     $ft2, $fv0
    /* 3FE4 8004FA04 46006187 */  neg.s      $ft1, $fa0
  .L8004FA08:
    /* 3FE8 8004FA08 4602503C */  c.lt.s     $ft3, $fv1
    /* 3FEC 8004FA0C 00000000 */  nop
    /* 3FF0 8004FA10 45030001 */  bc1tl      .L8004FA18
    /* 3FF4 8004FA14 46005107 */   neg.s     $ft0, $ft3
  .L8004FA18:
    /* 3FF8 8004FA18 4602403C */  c.lt.s     $ft2, $fv1
    /* 3FFC 8004FA1C 00000000 */  nop
    /* 4000 8004FA20 45030001 */  bc1tl      .L8004FA28
    /* 4004 8004FA24 46004007 */   neg.s     $fv0, $ft2
  .L8004FA28:
    /* 4008 8004FA28 4606203C */  c.lt.s     $ft0, $ft1
    /* 400C 8004FA2C 00000000 */  nop
    /* 4010 8004FA30 45000005 */  bc1f       .L8004FA48
    /* 4014 8004FA34 00001821 */   addu      $v1, $zero, $zero
    /* 4018 8004FA38 4606003C */  c.lt.s     $fv0, $ft1
    /* 401C 8004FA3C 00000000 */  nop
    /* 4020 8004FA40 45030001 */  bc1tl      .L8004FA48
    /* 4024 8004FA44 24030002 */   addiu     $v1, $zero, 0x2
  .L8004FA48:
    /* 4028 8004FA48 4600203C */  c.lt.s     $ft0, $fv0
    /* 402C 8004FA4C 00000000 */  nop
    /* 4030 8004FA50 45000006 */  bc1f       .L8004FA6C
    /* 4034 8004FA54 24020001 */   addiu     $v0, $zero, 0x1
    /* 4038 8004FA58 4600303E */  c.le.s     $ft1, $fv0
    /* 403C 8004FA5C 00000000 */  nop
    /* 4040 8004FA60 45030002 */  bc1tl      .L8004FA6C
    /* 4044 8004FA64 24030001 */   addiu     $v1, $zero, 0x1
    /* 4048 8004FA68 24020001 */  addiu      $v0, $zero, 0x1
  .L8004FA6C:
    /* 404C 8004FA6C 10620011 */  beq        $v1, $v0, .L8004FAB4
    /* 4050 8004FA70 28620002 */   slti      $v0, $v1, 0x2
    /* 4054 8004FA74 10400005 */  beqz       $v0, .L8004FA8C
    /* 4058 8004FA78 24020002 */   addiu     $v0, $zero, 0x2
    /* 405C 8004FA7C 10600007 */  beqz       $v1, .L8004FA9C
    /* 4060 8004FA80 00000000 */   nop
    /* 4064 8004FA84 08013EB5 */  j          func_8004FAD4
    /* 4068 8004FA88 2694000C */   addiu     $s4, $s4, 0xC
  .L8004FA8C:
    /* 406C 8004FA8C 5062000C */  beql       $v1, $v0, .L8004FAC0
    /* 4070 8004FA90 0000B821 */   addu      $s7, $zero, $zero
    /* 4074 8004FA94 08013EB5 */  j          func_8004FAD4
    /* 4078 8004FA98 2694000C */   addiu     $s4, $s4, 0xC
  .L8004FA9C:
    /* 407C 8004FA9C 4614503C */  c.lt.s     $ft3, $fs0
    /* 4080 8004FAA0 00000000 */  nop
    /* 4084 8004FAA4 4500000A */  bc1f       func_8004FAD0
    /* 4088 8004FAA8 24170001 */   addiu     $s7, $zero, 0x1
    /* 408C 8004FAAC 08013EB4 */  j          func_8004FAD0
    /* 4090 8004FAB0 0000B821 */   addu      $s7, $zero, $zero
  .L8004FAB4:
    /* 4094 8004FAB4 4614403C */  c.lt.s     $ft2, $fs0
    /* 4098 8004FAB8 08013EB1 */  j          func_8004FAC4
    /* 409C 8004FABC 0000B821 */   addu      $s7, $zero, $zero
  .L8004FAC0:
    /* 40A0 8004FAC0 4614603C */  c.lt.s     $fa0, $fs0
  alabel func_8004FAC4
    /* 40A4 8004FAC4 00000000 */  nop
    /* 40A8 8004FAC8 45030001 */  bc1tl      func_8004FAD0
    /* 40AC 8004FACC 24170001 */   addiu     $s7, $zero, 0x1
  alabel func_8004FAD0
    /* 40B0 8004FAD0 2694000C */  addiu      $s4, $s4, 0xC
  alabel func_8004FAD4
    /* 40B4 8004FAD4 00031980 */  sll        $v1, $v1, 6
    /* 40B8 8004FAD8 00172140 */  sll        $a0, $s7, 5
    /* 40BC 8004FADC 92420000 */  lbu        $v0, 0x0($s2)
    /* 40C0 8004FAE0 00641825 */  or         $v1, $v1, $a0
    /* 40C4 8004FAE4 3042001F */  andi       $v0, $v0, 0x1F
    /* 40C8 8004FAE8 00431025 */  or         $v0, $v0, $v1
    /* 40CC 8004FAEC A2420000 */  sb         $v0, 0x0($s2)
    /* 40D0 8004FAF0 2652000C */  addiu      $s2, $s2, 0xC
  alabel func_8004FAF4
    /* 40D4 8004FAF4 8E620058 */  lw         $v0, 0x58($s3)
    /* 40D8 8004FAF8 26310001 */  addiu      $s1, $s1, 0x1
    /* 40DC 8004FAFC 0222102A */  slt        $v0, $s1, $v0
    /* 40E0 8004FB00 1440FF61 */  bnez       $v0, .L8004F888
    /* 40E4 8004FB04 00000000 */   nop
  .L8004FB08:
    /* 40E8 8004FB08 3C028009 */  lui        $v0, %hi(D_80091FCC)
    /* 40EC 8004FB0C 8C421FCC */  lw         $v0, %lo(D_80091FCC)($v0)
    /* 40F0 8004FB10 10400036 */  beqz       $v0, .L8004FBEC
    /* 40F4 8004FB14 00000000 */   nop
    /* 40F8 8004FB18 8E630008 */  lw         $v1, 0x8($s3)
    /* 40FC 8004FB1C 8E620004 */  lw         $v0, 0x4($s3)
    /* 4100 8004FB20 00620018 */  mult       $v1, $v0
    /* 4104 8004FB24 8E65001C */  lw         $a1, 0x1C($s3)
    /* 4108 8004FB28 8E620010 */  lw         $v0, 0x10($s3)
    /* 410C 8004FB2C 00004812 */  mflo       $t1
    /* 4110 8004FB30 00491021 */  addu       $v0, $v0, $t1
    /* 4114 8004FB34 00021023 */  negu       $v0, $v0
    /* 4118 8004FB38 10A0002C */  beqz       $a1, .L8004FBEC
    /* 411C 8004FB3C AE620010 */   sw        $v0, 0x10($s3)
    /* 4120 8004FB40 8E62000C */  lw         $v0, 0xC($s3)
    /* 4124 8004FB44 18400029 */  blez       $v0, .L8004FBEC
    /* 4128 8004FB48 00008821 */   addu      $s1, $zero, $zero
  .L8004FB4C:
    /* 412C 8004FB4C 8E640008 */  lw         $a0, 0x8($s3)
    /* 4130 8004FB50 000417C2 */  srl        $v0, $a0, 31
    /* 4134 8004FB54 00821021 */  addu       $v0, $a0, $v0
    /* 4138 8004FB58 00021043 */  sra        $v0, $v0, 1
    /* 413C 8004FB5C 1840001E */  blez       $v0, .L8004FBD8
    /* 4140 8004FB60 00008021 */   addu      $s0, $zero, $zero
    /* 4144 8004FB64 02240018 */  mult       $s1, $a0
  .L8004FB68:
    /* 4148 8004FB68 00001012 */  mflo       $v0
    /* 414C 8004FB6C 00501821 */  addu       $v1, $v0, $s0
    /* 4150 8004FB70 00031880 */  sll        $v1, $v1, 2
    /* 4154 8004FB74 00651821 */  addu       $v1, $v1, $a1
    /* 4158 8004FB78 00441021 */  addu       $v0, $v0, $a0
    /* 415C 8004FB7C 00501023 */  subu       $v0, $v0, $s0
    /* 4160 8004FB80 00021080 */  sll        $v0, $v0, 2
    /* 4164 8004FB84 00451021 */  addu       $v0, $v0, $a1
    /* 4168 8004FB88 8C42FFFC */  lw         $v0, -0x4($v0)
    /* 416C 8004FB8C 8C640000 */  lw         $a0, 0x0($v1)
    /* 4170 8004FB90 AC620000 */  sw         $v0, 0x0($v1)
    /* 4174 8004FB94 8E620008 */  lw         $v0, 0x8($s3)
    /* 4178 8004FB98 02220018 */  mult       $s1, $v0
    /* 417C 8004FB9C 00001812 */  mflo       $v1
    /* 4180 8004FBA0 00621021 */  addu       $v0, $v1, $v0
    /* 4184 8004FBA4 00501023 */  subu       $v0, $v0, $s0
    /* 4188 8004FBA8 00021080 */  sll        $v0, $v0, 2
    /* 418C 8004FBAC 00451021 */  addu       $v0, $v0, $a1
    /* 4190 8004FBB0 AC44FFFC */  sw         $a0, -0x4($v0)
    /* 4194 8004FBB4 8E640008 */  lw         $a0, 0x8($s3)
    /* 4198 8004FBB8 26100001 */  addiu      $s0, $s0, 0x1
    /* 419C 8004FBBC 000417C2 */  srl        $v0, $a0, 31
    /* 41A0 8004FBC0 00821021 */  addu       $v0, $a0, $v0
    /* 41A4 8004FBC4 00021043 */  sra        $v0, $v0, 1
    /* 41A8 8004FBC8 0202102A */  slt        $v0, $s0, $v0
    /* 41AC 8004FBCC 02240018 */  mult       $s1, $a0
    /* 41B0 8004FBD0 1440FFE5 */  bnez       $v0, .L8004FB68
    /* 41B4 8004FBD4 00000000 */   nop
  .L8004FBD8:
    /* 41B8 8004FBD8 8E62000C */  lw         $v0, 0xC($s3)
    /* 41BC 8004FBDC 26310001 */  addiu      $s1, $s1, 0x1
    /* 41C0 8004FBE0 0222102A */  slt        $v0, $s1, $v0
    /* 41C4 8004FBE4 1440FFD9 */  bnez       $v0, .L8004FB4C
    /* 41C8 8004FBE8 00000000 */   nop
  .L8004FBEC:
    /* 41CC 8004FBEC 4480A000 */  mtc1       $zero, $fs0
    /* 41D0 8004FBF0 4405A000 */  mfc1       $a1, $fs0
    /* 41D4 8004FBF4 4406A000 */  mfc1       $a2, $fs0
    /* 41D8 8004FBF8 4407A000 */  mfc1       $a3, $fs0
    /* 41DC 8004FBFC 0C015AA4 */  jal        func_80056A90
    /* 41E0 8004FC00 26640060 */   addiu     $a0, $s3, 0x60
    /* 41E4 8004FC04 4405A000 */  mfc1       $a1, $fs0
    /* 41E8 8004FC08 4406A000 */  mfc1       $a2, $fs0
    /* 41EC 8004FC0C 4407A000 */  mfc1       $a3, $fs0
    /* 41F0 8004FC10 0C015AA4 */  jal        func_80056A90
    /* 41F4 8004FC14 266400A0 */   addiu     $a0, $s3, 0xA0
    /* 41F8 8004FC18 4405A000 */  mfc1       $a1, $fs0
    /* 41FC 8004FC1C 4406A000 */  mfc1       $a2, $fs0
    /* 4200 8004FC20 4407A000 */  mfc1       $a3, $fs0
    /* 4204 8004FC24 0C015AA4 */  jal        func_80056A90
    /* 4208 8004FC28 266400E0 */   addiu     $a0, $s3, 0xE0
    /* 420C 8004FC2C 4405A000 */  mfc1       $a1, $fs0
    /* 4210 8004FC30 26640120 */  addiu      $a0, $s3, 0x120
    /* 4214 8004FC34 00A03021 */  addu       $a2, $a1, $zero
    /* 4218 8004FC38 0C015AA4 */  jal        func_80056A90
    /* 421C 8004FC3C 00A03821 */   addu      $a3, $a1, $zero
    /* 4220 8004FC40 3C028009 */  lui        $v0, %hi(D_80091FCC)
    /* 4224 8004FC44 8C421FCC */  lw         $v0, %lo(D_80091FCC)($v0)
    /* 4228 8004FC48 10400004 */  beqz       $v0, .L8004FC5C
    /* 422C 8004FC4C 00000000 */   nop
    /* 4230 8004FC50 8E64005C */  lw         $a0, 0x5C($s3)
    /* 4234 8004FC54 0C04EF7D */  jal        func_8013BDF4
    /* 4238 8004FC58 00000000 */   nop
  .L8004FC5C:
    /* 423C 8004FC5C 8FBF005C */  lw         $ra, 0x5C($sp)
    /* 4240 8004FC60 8FBE0058 */  lw         $fp, 0x58($sp)
    /* 4244 8004FC64 8FB70054 */  lw         $s7, 0x54($sp)
    /* 4248 8004FC68 8FB60050 */  lw         $s6, 0x50($sp)
    /* 424C 8004FC6C 8FB5004C */  lw         $s5, 0x4C($sp)
    /* 4250 8004FC70 8FB40048 */  lw         $s4, 0x48($sp)
    /* 4254 8004FC74 8FB30044 */  lw         $s3, 0x44($sp)
    /* 4258 8004FC78 8FB20040 */  lw         $s2, 0x40($sp)
    /* 425C 8004FC7C 8FB1003C */  lw         $s1, 0x3C($sp)
    /* 4260 8004FC80 8FB00038 */  lw         $s0, 0x38($sp)
    /* 4264 8004FC84 D7B60068 */  ldc1       $fs1, 0x68($sp)
    /* 4268 8004FC88 D7B40060 */  ldc1       $fs0, 0x60($sp)
    /* 426C 8004FC8C 03E00008 */  jr         $ra
    /* 4270 8004FC90 27BD0070 */   addiu     $sp, $sp, 0x70
endlabel func_8004F4AC

nonmatching func_8004FC94, 0x64

glabel func_8004FC94
    /* 4274 8004FC94 3C028017 */  lui        $v0, %hi(D_80174BF8)
    /* 4278 8004FC98 8C434BF8 */  lw         $v1, %lo(D_80174BF8)($v0)
    /* 427C 8004FC9C 10600014 */  beqz       $v1, .L8004FCF0
    /* 4280 8004FCA0 00002021 */   addu      $a0, $zero, $zero
    /* 4284 8004FCA4 24050063 */  addiu      $a1, $zero, 0x63
    /* 4288 8004FCA8 00403021 */  addu       $a2, $v0, $zero
  .L8004FCAC:
    /* 428C 8004FCAC 8C620084 */  lw         $v0, 0x84($v1)
    /* 4290 8004FCB0 8C420008 */  lw         $v0, 0x8($v0)
    /* 4294 8004FCB4 8C42005C */  lw         $v0, 0x5C($v0)
    /* 4298 8004FCB8 8C420000 */  lw         $v0, 0x0($v0)
    /* 429C 8004FCBC 54450009 */  bnel       $v0, $a1, .L8004FCE4
    /* 42A0 8004FCC0 00602021 */   addu      $a0, $v1, $zero
    /* 42A4 8004FCC4 10800004 */  beqz       $a0, .L8004FCD8
    /* 42A8 8004FCC8 00000000 */   nop
    /* 42AC 8004FCCC 8C620000 */  lw         $v0, 0x0($v1)
    /* 42B0 8004FCD0 03E00008 */  jr         $ra
    /* 42B4 8004FCD4 AC820000 */   sw        $v0, 0x0($a0)
  .L8004FCD8:
    /* 42B8 8004FCD8 8C620000 */  lw         $v0, 0x0($v1)
    /* 42BC 8004FCDC 03E00008 */  jr         $ra
    /* 42C0 8004FCE0 ACC24BF8 */   sw        $v0, %lo(D_80174BF8)($a2)
  .L8004FCE4:
    /* 42C4 8004FCE4 8C630000 */  lw         $v1, 0x0($v1)
    /* 42C8 8004FCE8 1460FFF0 */  bnez       $v1, .L8004FCAC
    /* 42CC 8004FCEC 00000000 */   nop
  .L8004FCF0:
    /* 42D0 8004FCF0 03E00008 */  jr         $ra
    /* 42D4 8004FCF4 00000000 */   nop
endlabel func_8004FC94
