.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_8008EE3C, 0x58

glabel func_8008EE3C
    /* 4341C 8008EE3C 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* 43420 8008EE40 AFA40020 */  sw         $a0, 0x20($sp)
    /* 43424 8008EE44 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 43428 8008EE48 AFA50024 */  sw         $a1, 0x24($sp)
    /* 4342C 8008EE4C AFA60028 */  sw         $a2, 0x28($sp)
    /* 43430 8008EE50 AFA7002C */  sw         $a3, 0x2C($sp)
    /* 43434 8008EE54 3C048009 */  lui        $a0, %hi(func_8008EE18)
    /* 43438 8008EE58 2484EE18 */  addiu      $a0, $a0, %lo(func_8008EE18)
    /* 4343C 8008EE5C 27A70028 */  addiu      $a3, $sp, 0x28
    /* 43440 8008EE60 8FA60024 */  lw         $a2, 0x24($sp)
    /* 43444 8008EE64 0C023D6A */  jal        func_8008F5A8
    /* 43448 8008EE68 8FA50020 */   lw        $a1, 0x20($sp)
    /* 4344C 8008EE6C 04400004 */  bltz       $v0, .L8008EE80
    /* 43450 8008EE70 00401825 */   or        $v1, $v0, $zero
    /* 43454 8008EE74 8FAE0020 */  lw         $t6, 0x20($sp)
    /* 43458 8008EE78 01C27821 */  addu       $t7, $t6, $v0
    /* 4345C 8008EE7C A1E00000 */  sb         $zero, 0x0($t7)
  .L8008EE80:
    /* 43460 8008EE80 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 43464 8008EE84 27BD0020 */  addiu      $sp, $sp, 0x20
    /* 43468 8008EE88 00601025 */  or         $v0, $v1, $zero
    /* 4346C 8008EE8C 03E00008 */  jr         $ra
    /* 43470 8008EE90 00000000 */   nop
endlabel func_8008EE3C
    /* 43474 8008EE94 00000000 */  nop

nonmatching func_8008EE98, 0x2C

glabel func_8008EE98
    /* 43478 8008EE98 00801025 */  or         $v0, $a0, $zero
    /* 4347C 8008EE9C 10C00007 */  beqz       $a2, .L8008EEBC
    /* 43480 8008EEA0 00A01825 */   or        $v1, $a1, $zero
  .L8008EEA4:
    /* 43484 8008EEA4 906E0000 */  lbu        $t6, 0x0($v1)
    /* 43488 8008EEA8 24C6FFFF */  addiu      $a2, $a2, -0x1
    /* 4348C 8008EEAC 24420001 */  addiu      $v0, $v0, 0x1
    /* 43490 8008EEB0 24630001 */  addiu      $v1, $v1, 0x1
    /* 43494 8008EEB4 14C0FFFB */  bnez       $a2, .L8008EEA4
    /* 43498 8008EEB8 A04EFFFF */   sb        $t6, -0x1($v0)
  .L8008EEBC:
    /* 4349C 8008EEBC 03E00008 */  jr         $ra
    /* 434A0 8008EEC0 00801025 */   or        $v0, $a0, $zero
endlabel func_8008EE98

nonmatching func_8008EEC4, 0x28

glabel func_8008EEC4
    /* 434A4 8008EEC4 908E0000 */  lbu        $t6, 0x0($a0)
    /* 434A8 8008EEC8 00801825 */  or         $v1, $a0, $zero
    /* 434AC 8008EECC 11C00005 */  beqz       $t6, .L8008EEE4
    /* 434B0 8008EED0 00000000 */   nop
    /* 434B4 8008EED4 906F0001 */  lbu        $t7, 0x1($v1)
  .L8008EED8:
    /* 434B8 8008EED8 24630001 */  addiu      $v1, $v1, 0x1
    /* 434BC 8008EEDC 55E0FFFE */  bnel       $t7, $zero, .L8008EED8
    /* 434C0 8008EEE0 906F0001 */   lbu       $t7, 0x1($v1)
  .L8008EEE4:
    /* 434C4 8008EEE4 03E00008 */  jr         $ra
    /* 434C8 8008EEE8 00641023 */   subu      $v0, $v1, $a0
endlabel func_8008EEC4

nonmatching func_8008EEEC, 0x40

glabel func_8008EEEC
    /* 434CC 8008EEEC 90830000 */  lbu        $v1, 0x0($a0)
    /* 434D0 8008EEF0 30AE00FF */  andi       $t6, $a1, 0xFF
    /* 434D4 8008EEF4 30A200FF */  andi       $v0, $a1, 0xFF
    /* 434D8 8008EEF8 51C3000A */  beql       $t6, $v1, .L8008EF24
    /* 434DC 8008EEFC 00801025 */   or        $v0, $a0, $zero
  .L8008EF00:
    /* 434E0 8008EF00 54600004 */  bnel       $v1, $zero, .L8008EF14
    /* 434E4 8008EF04 90830001 */   lbu       $v1, 0x1($a0)
    /* 434E8 8008EF08 03E00008 */  jr         $ra
    /* 434EC 8008EF0C 00001025 */   or        $v0, $zero, $zero
    /* 434F0 8008EF10 90830001 */  lbu        $v1, 0x1($a0)
  .L8008EF14:
    /* 434F4 8008EF14 24840001 */  addiu      $a0, $a0, 0x1
    /* 434F8 8008EF18 1443FFF9 */  bne        $v0, $v1, .L8008EF00
    /* 434FC 8008EF1C 00000000 */   nop
    /* 43500 8008EF20 00801025 */  or         $v0, $a0, $zero
  .L8008EF24:
    /* 43504 8008EF24 03E00008 */  jr         $ra
    /* 43508 8008EF28 00000000 */   nop
endlabel func_8008EEEC
    /* 4350C 8008EF2C 00000000 */  nop
    /* 43510 8008EF30 00000000 */  nop
    /* 43514 8008EF34 00000000 */  nop
