.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_80089EF8, 0x21C

glabel func_80089EF8
    /* 3E4D8 80089EF8 27BDFFA0 */  addiu      $sp, $sp, -0x60
    /* 3E4DC 80089EFC 3C0E8019 */  lui        $t6, %hi(D_8018ADB8)
    /* 3E4E0 80089F00 AFBF001C */  sw         $ra, 0x1C($sp)
    /* 3E4E4 80089F04 25CEADB8 */  addiu      $t6, $t6, %lo(D_8018ADB8)
    /* 3E4E8 80089F08 240F0002 */  addiu      $t7, $zero, 0x2
    /* 3E4EC 80089F0C AFA40060 */  sw         $a0, 0x60($sp)
    /* 3E4F0 80089F10 AFA50064 */  sw         $a1, 0x64($sp)
    /* 3E4F4 80089F14 AFA60068 */  sw         $a2, 0x68($sp)
    /* 3E4F8 80089F18 AFA7006C */  sw         $a3, 0x6C($sp)
    /* 3E4FC 80089F1C AFB00018 */  sw         $s0, 0x18($sp)
    /* 3E500 80089F20 AFA0005C */  sw         $zero, 0x5C($sp)
    /* 3E504 80089F24 AFAE0054 */  sw         $t6, 0x54($sp)
    /* 3E508 80089F28 0C021F5E */  jal        func_80087D78
    /* 3E50C 80089F2C AFAF0028 */   sw        $t7, 0x28($sp)
    /* 3E510 80089F30 24180002 */  addiu      $t8, $zero, 0x2
    /* 3E514 80089F34 3C018019 */  lui        $at, %hi(D_8018AD68)
    /* 3E518 80089F38 A038AD68 */  sb         $t8, %lo(D_8018AD68)($at)
    /* 3E51C 80089F3C 8FA40064 */  lw         $a0, 0x64($sp)
    /* 3E520 80089F40 0C022845 */  jal        func_8008A114
    /* 3E524 80089F44 97A5006A */   lhu       $a1, 0x6A($sp)
    /* 3E528 80089F48 3C058019 */  lui        $a1, %hi(D_8018ADB8)
    /* 3E52C 80089F4C 24A5ADB8 */  addiu      $a1, $a1, %lo(D_8018ADB8)
    /* 3E530 80089F50 0C021F1E */  jal        func_80087C78
    /* 3E534 80089F54 24040001 */   addiu     $a0, $zero, 0x1
    /* 3E538 80089F58 AFA2005C */  sw         $v0, 0x5C($sp)
    /* 3E53C 80089F5C 8FA40060 */  lw         $a0, 0x60($sp)
    /* 3E540 80089F60 00002825 */  or         $a1, $zero, $zero
    /* 3E544 80089F64 0C01F342 */  jal        func_8007CD08
    /* 3E548 80089F68 24060001 */   addiu     $a2, $zero, 0x1
  .L80089F6C:
    /* 3E54C 80089F6C 3C058019 */  lui        $a1, %hi(D_8018ADB8)
    /* 3E550 80089F70 24A5ADB8 */  addiu      $a1, $a1, %lo(D_8018ADB8)
    /* 3E554 80089F74 0C021F1E */  jal        func_80087C78
    /* 3E558 80089F78 00002025 */   or        $a0, $zero, $zero
    /* 3E55C 80089F7C AFA2005C */  sw         $v0, 0x5C($sp)
    /* 3E560 80089F80 8FA40060 */  lw         $a0, 0x60($sp)
    /* 3E564 80089F84 00002825 */  or         $a1, $zero, $zero
    /* 3E568 80089F88 0C01F342 */  jal        func_8007CD08
    /* 3E56C 80089F8C 24060001 */   addiu     $a2, $zero, 0x1
    /* 3E570 80089F90 8FA80064 */  lw         $t0, 0x64($sp)
    /* 3E574 80089F94 3C198019 */  lui        $t9, %hi(D_8018ADB8)
    /* 3E578 80089F98 2739ADB8 */  addiu      $t9, $t9, %lo(D_8018ADB8)
    /* 3E57C 80089F9C 1100000C */  beqz       $t0, .L80089FD0
    /* 3E580 80089FA0 AFB90054 */   sw        $t9, 0x54($sp)
    /* 3E584 80089FA4 1900000A */  blez       $t0, .L80089FD0
    /* 3E588 80089FA8 AFA00058 */   sw        $zero, 0x58($sp)
  .L80089FAC:
    /* 3E58C 80089FAC 8FAB0058 */  lw         $t3, 0x58($sp)
    /* 3E590 80089FB0 8FAD0064 */  lw         $t5, 0x64($sp)
    /* 3E594 80089FB4 8FA90054 */  lw         $t1, 0x54($sp)
    /* 3E598 80089FB8 256C0001 */  addiu      $t4, $t3, 0x1
    /* 3E59C 80089FBC 018D082A */  slt        $at, $t4, $t5
    /* 3E5A0 80089FC0 252A0001 */  addiu      $t2, $t1, 0x1
    /* 3E5A4 80089FC4 AFAC0058 */  sw         $t4, 0x58($sp)
    /* 3E5A8 80089FC8 1420FFF8 */  bnez       $at, .L80089FAC
    /* 3E5AC 80089FCC AFAA0054 */   sw        $t2, 0x54($sp)
  .L80089FD0:
    /* 3E5B0 80089FD0 8FAF0054 */  lw         $t7, 0x54($sp)
    /* 3E5B4 80089FD4 27AE002C */  addiu      $t6, $sp, 0x2C
    /* 3E5B8 80089FD8 25F90024 */  addiu      $t9, $t7, 0x24
  .L80089FDC:
    /* 3E5BC 80089FDC 89E10000 */  lwl        $at, 0x0($t7)
    /* 3E5C0 80089FE0 99E10003 */  lwr        $at, 0x3($t7)
    /* 3E5C4 80089FE4 25EF000C */  addiu      $t7, $t7, 0xC
    /* 3E5C8 80089FE8 25CE000C */  addiu      $t6, $t6, 0xC
    /* 3E5CC 80089FEC ADC1FFF4 */  sw         $at, -0xC($t6)
    /* 3E5D0 80089FF0 89E1FFF8 */  lwl        $at, -0x8($t7)
    /* 3E5D4 80089FF4 99E1FFFB */  lwr        $at, -0x5($t7)
    /* 3E5D8 80089FF8 ADC1FFF8 */  sw         $at, -0x8($t6)
    /* 3E5DC 80089FFC 89E1FFFC */  lwl        $at, -0x4($t7)
    /* 3E5E0 8008A000 99E1FFFF */  lwr        $at, -0x1($t7)
    /* 3E5E4 8008A004 15F9FFF5 */  bne        $t7, $t9, .L80089FDC
    /* 3E5E8 8008A008 ADC1FFFC */   sw        $at, -0x4($t6)
    /* 3E5EC 8008A00C 89E10000 */  lwl        $at, 0x0($t7)
    /* 3E5F0 8008A010 99E10003 */  lwr        $at, 0x3($t7)
    /* 3E5F4 8008A014 ADC10000 */  sw         $at, 0x0($t6)
    /* 3E5F8 8008A018 93A8002E */  lbu        $t0, 0x2E($sp)
    /* 3E5FC 8008A01C 310900C0 */  andi       $t1, $t0, 0xC0
    /* 3E600 8008A020 00095103 */  sra        $t2, $t1, 4
    /* 3E604 8008A024 15400027 */  bnez       $t2, .L8008A0C4
    /* 3E608 8008A028 AFAA005C */   sw        $t2, 0x5C($sp)
    /* 3E60C 8008A02C 27A4002C */  addiu      $a0, $sp, 0x2C
    /* 3E610 8008A030 0C022432 */  jal        func_800890C8
    /* 3E614 8008A034 24840006 */   addiu     $a0, $a0, 0x6
    /* 3E618 8008A038 A3A20027 */  sb         $v0, 0x27($sp)
    /* 3E61C 8008A03C 93AB0027 */  lbu        $t3, 0x27($sp)
    /* 3E620 8008A040 93AC0052 */  lbu        $t4, 0x52($sp)
    /* 3E624 8008A044 116C000F */  beq        $t3, $t4, .L8008A084
    /* 3E628 8008A048 00000000 */   nop
    /* 3E62C 8008A04C 8FA40060 */  lw         $a0, 0x60($sp)
    /* 3E630 8008A050 0C0231E2 */  jal        func_8008C788
    /* 3E634 8008A054 8FA50064 */   lw        $a1, 0x64($sp)
    /* 3E638 8008A058 AFA2005C */  sw         $v0, 0x5C($sp)
    /* 3E63C 8008A05C 8FAD005C */  lw         $t5, 0x5C($sp)
    /* 3E640 8008A060 11A00005 */  beqz       $t5, .L8008A078
    /* 3E644 8008A064 00000000 */   nop
    /* 3E648 8008A068 0C021F6F */  jal        func_80087DBC
    /* 3E64C 8008A06C 00000000 */   nop
    /* 3E650 8008A070 10000023 */  b          .L8008A100
    /* 3E654 8008A074 8FA2005C */   lw        $v0, 0x5C($sp)
  .L8008A078:
    /* 3E658 8008A078 24180004 */  addiu      $t8, $zero, 0x4
    /* 3E65C 8008A07C 10000013 */  b          .L8008A0CC
    /* 3E660 8008A080 AFB8005C */   sw        $t8, 0x5C($sp)
  .L8008A084:
    /* 3E664 8008A084 AFA00058 */  sw         $zero, 0x58($sp)
  .L8008A088:
    /* 3E668 8008A088 8FB90058 */  lw         $t9, 0x58($sp)
    /* 3E66C 8008A08C 8FAE006C */  lw         $t6, 0x6C($sp)
    /* 3E670 8008A090 03B97821 */  addu       $t7, $sp, $t9
    /* 3E674 8008A094 91EF0032 */  lbu        $t7, 0x32($t7)
    /* 3E678 8008A098 A1CF0000 */  sb         $t7, 0x0($t6)
    /* 3E67C 8008A09C 8FAA0058 */  lw         $t2, 0x58($sp)
    /* 3E680 8008A0A0 8FA8006C */  lw         $t0, 0x6C($sp)
    /* 3E684 8008A0A4 254B0001 */  addiu      $t3, $t2, 0x1
    /* 3E688 8008A0A8 29610020 */  slti       $at, $t3, 0x20
    /* 3E68C 8008A0AC 25090001 */  addiu      $t1, $t0, 0x1
    /* 3E690 8008A0B0 AFAB0058 */  sw         $t3, 0x58($sp)
    /* 3E694 8008A0B4 1420FFF4 */  bnez       $at, .L8008A088
    /* 3E698 8008A0B8 AFA9006C */   sw        $t1, 0x6C($sp)
    /* 3E69C 8008A0BC 10000003 */  b          .L8008A0CC
    /* 3E6A0 8008A0C0 00000000 */   nop
  .L8008A0C4:
    /* 3E6A4 8008A0C4 240C0001 */  addiu      $t4, $zero, 0x1
    /* 3E6A8 8008A0C8 AFAC005C */  sw         $t4, 0x5C($sp)
  .L8008A0CC:
    /* 3E6AC 8008A0CC 8FAD005C */  lw         $t5, 0x5C($sp)
    /* 3E6B0 8008A0D0 24010004 */  addiu      $at, $zero, 0x4
    /* 3E6B4 8008A0D4 15A10007 */  bne        $t5, $at, .L8008A0F4
    /* 3E6B8 8008A0D8 00000000 */   nop
    /* 3E6BC 8008A0DC 8FB80028 */  lw         $t8, 0x28($sp)
    /* 3E6C0 8008A0E0 2B100000 */  slti       $s0, $t8, 0x0
    /* 3E6C4 8008A0E4 3A100001 */  xori       $s0, $s0, 0x1
    /* 3E6C8 8008A0E8 2719FFFF */  addiu      $t9, $t8, -0x1
    /* 3E6CC 8008A0EC 1600FF9F */  bnez       $s0, .L80089F6C
    /* 3E6D0 8008A0F0 AFB90028 */   sw        $t9, 0x28($sp)
  .L8008A0F4:
    /* 3E6D4 8008A0F4 0C021F6F */  jal        func_80087DBC
    /* 3E6D8 8008A0F8 00000000 */   nop
    /* 3E6DC 8008A0FC 8FA2005C */  lw         $v0, 0x5C($sp)
  .L8008A100:
    /* 3E6E0 8008A100 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 3E6E4 8008A104 8FB00018 */  lw         $s0, 0x18($sp)
    /* 3E6E8 8008A108 27BD0060 */  addiu      $sp, $sp, 0x60
    /* 3E6EC 8008A10C 03E00008 */  jr         $ra
    /* 3E6F0 8008A110 00000000 */   nop
endlabel func_80089EF8
