.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_8007BA28, 0x68

glabel func_8007BA28
    /* 30008 8007BA28 27BDFF98 */  addiu      $sp, $sp, -0x68
    /* 3000C 8007BA2C 44856000 */  mtc1       $a1, $fa0
    /* 30010 8007BA30 44867000 */  mtc1       $a2, $fa1
    /* 30014 8007BA34 44878000 */  mtc1       $a3, $ft4
    /* 30018 8007BA38 C7A40078 */  lwc1       $ft0, 0x78($sp)
    /* 3001C 8007BA3C C7A6007C */  lwc1       $ft1, 0x7C($sp)
    /* 30020 8007BA40 C7A80080 */  lwc1       $ft2, 0x80($sp)
    /* 30024 8007BA44 C7AA0084 */  lwc1       $ft3, 0x84($sp)
    /* 30028 8007BA48 AFBF0024 */  sw         $ra, 0x24($sp)
    /* 3002C 8007BA4C AFA40068 */  sw         $a0, 0x68($sp)
    /* 30030 8007BA50 44056000 */  mfc1       $a1, $fa0
    /* 30034 8007BA54 44067000 */  mfc1       $a2, $fa1
    /* 30038 8007BA58 44078000 */  mfc1       $a3, $ft4
    /* 3003C 8007BA5C 27A40028 */  addiu      $a0, $sp, 0x28
    /* 30040 8007BA60 E7A40010 */  swc1       $ft0, 0x10($sp)
    /* 30044 8007BA64 E7A60014 */  swc1       $ft1, 0x14($sp)
    /* 30048 8007BA68 E7A80018 */  swc1       $ft2, 0x18($sp)
    /* 3004C 8007BA6C 0C01EE1E */  jal        func_8007B878
    /* 30050 8007BA70 E7AA001C */   swc1      $ft3, 0x1C($sp)
    /* 30054 8007BA74 27A40028 */  addiu      $a0, $sp, 0x28
    /* 30058 8007BA78 0C01E9D6 */  jal        func_8007A758
    /* 3005C 8007BA7C 8FA50068 */   lw        $a1, 0x68($sp)
    /* 30060 8007BA80 8FBF0024 */  lw         $ra, 0x24($sp)
    /* 30064 8007BA84 27BD0068 */  addiu      $sp, $sp, 0x68
    /* 30068 8007BA88 03E00008 */  jr         $ra
    /* 3006C 8007BA8C 00000000 */   nop
endlabel func_8007BA28
    /* 30070 8007BA90 00000000 */  nop
    /* 30074 8007BA94 00000000 */  nop

/* Handwritten function */
nonmatching func_8007BA98, 0xAC

glabel func_8007BA98
    /* 30078 8007BA98 18A0001F */  blez       $a1, .L8007BB18
    /* 3007C 8007BA9C 00000000 */   nop
    /* 30080 8007BAA0 240B2000 */  addiu      $t3, $zero, 0x2000
    /* 30084 8007BAA4 00AB082B */  sltu       $at, $a1, $t3
    /* 30088 8007BAA8 1020001D */  beqz       $at, .L8007BB20
    /* 3008C 8007BAAC 00000000 */   nop
    /* 30090 8007BAB0 00804025 */  or         $t0, $a0, $zero
    /* 30094 8007BAB4 00854821 */  addu       $t1, $a0, $a1
    /* 30098 8007BAB8 0109082B */  sltu       $at, $t0, $t1
    /* 3009C 8007BABC 10200016 */  beqz       $at, .L8007BB18
    /* 300A0 8007BAC0 00000000 */   nop
    /* 300A4 8007BAC4 310A000F */  andi       $t2, $t0, 0xF
    /* 300A8 8007BAC8 11400007 */  beqz       $t2, .L8007BAE8
    /* 300AC 8007BACC 2529FFF0 */   addiu     $t1, $t1, -0x10
    /* 300B0 8007BAD0 010A4023 */  subu       $t0, $t0, $t2
    /* 300B4 8007BAD4 BD150000 */  cache      0x15, 0x0($t0) /* handwritten instruction */
    /* 300B8 8007BAD8 0109082B */  sltu       $at, $t0, $t1
    /* 300BC 8007BADC 1020000E */  beqz       $at, .L8007BB18
    /* 300C0 8007BAE0 00000000 */   nop
    /* 300C4 8007BAE4 25080010 */  addiu      $t0, $t0, 0x10
  .L8007BAE8:
    /* 300C8 8007BAE8 312A000F */  andi       $t2, $t1, 0xF
    /* 300CC 8007BAEC 11400006 */  beqz       $t2, .L8007BB08
    /* 300D0 8007BAF0 00000000 */   nop
    /* 300D4 8007BAF4 012A4823 */  subu       $t1, $t1, $t2
    /* 300D8 8007BAF8 BD350010 */  cache      0x15, 0x10($t1) /* handwritten instruction */
    /* 300DC 8007BAFC 0128082B */  sltu       $at, $t1, $t0
    /* 300E0 8007BB00 14200005 */  bnez       $at, .L8007BB18
    /* 300E4 8007BB04 00000000 */   nop
  .L8007BB08:
    /* 300E8 8007BB08 BD110000 */  cache      0x11, 0x0($t0) /* handwritten instruction */
    /* 300EC 8007BB0C 0109082B */  sltu       $at, $t0, $t1
    /* 300F0 8007BB10 1420FFFD */  bnez       $at, .L8007BB08
    /* 300F4 8007BB14 25080010 */   addiu     $t0, $t0, 0x10
  .L8007BB18:
    /* 300F8 8007BB18 03E00008 */  jr         $ra
    /* 300FC 8007BB1C 00000000 */   nop
  .L8007BB20:
    /* 30100 8007BB20 3C088000 */  lui        $t0, 0x8000
    /* 30104 8007BB24 010B4821 */  addu       $t1, $t0, $t3
    /* 30108 8007BB28 2529FFF0 */  addiu      $t1, $t1, -0x10
  .L8007BB2C:
    /* 3010C 8007BB2C BD010000 */  cache      0x01, 0x0($t0) /* handwritten instruction */
    /* 30110 8007BB30 0109082B */  sltu       $at, $t0, $t1
    /* 30114 8007BB34 1420FFFD */  bnez       $at, .L8007BB2C
    /* 30118 8007BB38 25080010 */   addiu     $t0, $t0, (0x80000010 & 0xFFFF)
    /* 3011C 8007BB3C 03E00008 */  jr         $ra
    /* 30120 8007BB40 00000000 */   nop
endlabel func_8007BA98
    /* 30124 8007BB44 00000000 */  nop

/* Handwritten function */
nonmatching func_8007BB48, 0x74

glabel func_8007BB48
    /* 30128 8007BB48 18A00011 */  blez       $a1, .L8007BB90
    /* 3012C 8007BB4C 00000000 */   nop
    /* 30130 8007BB50 240B4000 */  addiu      $t3, $zero, 0x4000
    /* 30134 8007BB54 00AB082B */  sltu       $at, $a1, $t3
    /* 30138 8007BB58 1020000F */  beqz       $at, .L8007BB98
    /* 3013C 8007BB5C 00000000 */   nop
    /* 30140 8007BB60 00804025 */  or         $t0, $a0, $zero
    /* 30144 8007BB64 00854821 */  addu       $t1, $a0, $a1
    /* 30148 8007BB68 0109082B */  sltu       $at, $t0, $t1
    /* 3014C 8007BB6C 10200008 */  beqz       $at, .L8007BB90
    /* 30150 8007BB70 00000000 */   nop
    /* 30154 8007BB74 310A001F */  andi       $t2, $t0, 0x1F
    /* 30158 8007BB78 2529FFE0 */  addiu      $t1, $t1, -0x20
    /* 3015C 8007BB7C 010A4023 */  subu       $t0, $t0, $t2
  .L8007BB80:
    /* 30160 8007BB80 BD100000 */  cache      0x10, 0x0($t0) /* handwritten instruction */
    /* 30164 8007BB84 0109082B */  sltu       $at, $t0, $t1
    /* 30168 8007BB88 1420FFFD */  bnez       $at, .L8007BB80
    /* 3016C 8007BB8C 25080020 */   addiu     $t0, $t0, 0x20
  .L8007BB90:
    /* 30170 8007BB90 03E00008 */  jr         $ra
    /* 30174 8007BB94 00000000 */   nop
  .L8007BB98:
    /* 30178 8007BB98 3C088000 */  lui        $t0, 0x8000
    /* 3017C 8007BB9C 010B4821 */  addu       $t1, $t0, $t3
    /* 30180 8007BBA0 2529FFE0 */  addiu      $t1, $t1, -0x20
  .L8007BBA4:
    /* 30184 8007BBA4 BD000000 */  cache      0x00, 0x0($t0) /* handwritten instruction */
    /* 30188 8007BBA8 0109082B */  sltu       $at, $t0, $t1
    /* 3018C 8007BBAC 1420FFFD */  bnez       $at, .L8007BBA4
    /* 30190 8007BBB0 25080020 */   addiu     $t0, $t0, (0x80000020 & 0xFFFF)
    /* 30194 8007BBB4 03E00008 */  jr         $ra
    /* 30198 8007BBB8 00000000 */   nop
endlabel func_8007BB48
    /* 3019C 8007BBBC 00000000 */  nop
    /* 301A0 8007BBC0 00000000 */  nop
    /* 301A4 8007BBC4 00000000 */  nop
    /* 301A8 8007BBC8 00000000 */  nop
    /* 301AC 8007BBCC 00000000 */  nop
    /* 301B0 8007BBD0 00000000 */  nop
    /* 301B4 8007BBD4 00000000 */  nop
    /* 301B8 8007BBD8 00000000 */  nop
    /* 301BC 8007BBDC 00000000 */  nop
    /* 301C0 8007BBE0 00000000 */  nop
    /* 301C4 8007BBE4 00000000 */  nop
    /* 301C8 8007BBE8 00000000 */  nop
    /* 301CC 8007BBEC 00000000 */  nop
    /* 301D0 8007BBF0 00000000 */  nop
    /* 301D4 8007BBF4 00000000 */  nop
    /* 301D8 8007BBF8 00000000 */  nop
    /* 301DC 8007BBFC 00000000 */  nop
    /* 301E0 8007BC00 00000000 */  nop
    /* 301E4 8007BC04 00000000 */  nop
    /* 301E8 8007BC08 00000000 */  nop
    /* 301EC 8007BC0C 00000000 */  nop
    /* 301F0 8007BC10 00000000 */  nop
    /* 301F4 8007BC14 00000000 */  nop
    /* 301F8 8007BC18 00000000 */  nop
    /* 301FC 8007BC1C 00000000 */  nop
    /* 30200 8007BC20 00000000 */  nop
    /* 30204 8007BC24 00000000 */  nop

/* Handwritten function */
nonmatching func_8007BC28, 0x74

glabel func_8007BC28
    /* 30208 8007BC28 18A00011 */  blez       $a1, .L8007BC70
    /* 3020C 8007BC2C 00000000 */   nop
    /* 30210 8007BC30 240B2000 */  addiu      $t3, $zero, 0x2000
    /* 30214 8007BC34 00AB082B */  sltu       $at, $a1, $t3
    /* 30218 8007BC38 1020000F */  beqz       $at, .L8007BC78
    /* 3021C 8007BC3C 00000000 */   nop
    /* 30220 8007BC40 00804025 */  or         $t0, $a0, $zero
    /* 30224 8007BC44 00854821 */  addu       $t1, $a0, $a1
    /* 30228 8007BC48 0109082B */  sltu       $at, $t0, $t1
    /* 3022C 8007BC4C 10200008 */  beqz       $at, .L8007BC70
    /* 30230 8007BC50 00000000 */   nop
    /* 30234 8007BC54 310A000F */  andi       $t2, $t0, 0xF
    /* 30238 8007BC58 2529FFF0 */  addiu      $t1, $t1, -0x10
    /* 3023C 8007BC5C 010A4023 */  subu       $t0, $t0, $t2
  .L8007BC60:
    /* 30240 8007BC60 BD190000 */  cache      0x19, 0x0($t0) /* handwritten instruction */
    /* 30244 8007BC64 0109082B */  sltu       $at, $t0, $t1
    /* 30248 8007BC68 1420FFFD */  bnez       $at, .L8007BC60
    /* 3024C 8007BC6C 25080010 */   addiu     $t0, $t0, 0x10
  .L8007BC70:
    /* 30250 8007BC70 03E00008 */  jr         $ra
    /* 30254 8007BC74 00000000 */   nop
  .L8007BC78:
    /* 30258 8007BC78 3C088000 */  lui        $t0, 0x8000
    /* 3025C 8007BC7C 010B4821 */  addu       $t1, $t0, $t3
    /* 30260 8007BC80 2529FFF0 */  addiu      $t1, $t1, -0x10
  .L8007BC84:
    /* 30264 8007BC84 BD010000 */  cache      0x01, 0x0($t0) /* handwritten instruction */
    /* 30268 8007BC88 0109082B */  sltu       $at, $t0, $t1
    /* 3026C 8007BC8C 1420FFFD */  bnez       $at, .L8007BC84
    /* 30270 8007BC90 25080010 */   addiu     $t0, $t0, (0x80000010 & 0xFFFF)
    /* 30274 8007BC94 03E00008 */  jr         $ra
    /* 30278 8007BC98 00000000 */   nop
endlabel func_8007BC28
    /* 3027C 8007BC9C 00000000 */  nop
    /* 30280 8007BCA0 00000000 */  nop
    /* 30284 8007BCA4 00000000 */  nop

/* Handwritten function */
nonmatching func_8007BCA8, 0x28

glabel func_8007BCA8
    /* 30288 8007BCA8 3C088000 */  lui        $t0, 0x8000
    /* 3028C 8007BCAC 240A2000 */  addiu      $t2, $zero, 0x2000
    /* 30290 8007BCB0 010A4821 */  addu       $t1, $t0, $t2
    /* 30294 8007BCB4 2529FFF0 */  addiu      $t1, $t1, -0x10
  .L8007BCB8:
    /* 30298 8007BCB8 BD010000 */  cache      0x01, 0x0($t0) /* handwritten instruction */
    /* 3029C 8007BCBC 0109082B */  sltu       $at, $t0, $t1
    /* 302A0 8007BCC0 1420FFFD */  bnez       $at, .L8007BCB8
    /* 302A4 8007BCC4 25080010 */   addiu     $t0, $t0, (0x80000010 & 0xFFFF)
    /* 302A8 8007BCC8 03E00008 */  jr         $ra
    /* 302AC 8007BCCC 00000000 */   nop
endlabel func_8007BCA8
    /* 302B0 8007BCD0 00000000 */  nop
    /* 302B4 8007BCD4 00000000 */  nop

nonmatching func_8007BCD8, 0x2C

glabel func_8007BCD8
    /* 302B8 8007BCD8 3C0E8009 */  lui        $t6, %hi(D_800952A0)
    /* 302BC 8007BCDC 3C0F8009 */  lui        $t7, %hi(D_800952A0)
    /* 302C0 8007BCE0 25CE52A0 */  addiu      $t6, $t6, %lo(D_800952A0)
    /* 302C4 8007BCE4 25EF52A0 */  addiu      $t7, $t7, %lo(D_800952A0)
    /* 302C8 8007BCE8 AC8E0000 */  sw         $t6, 0x0($a0)
    /* 302CC 8007BCEC AC8F0004 */  sw         $t7, 0x4($a0)
    /* 302D0 8007BCF0 AC800008 */  sw         $zero, 0x8($a0)
    /* 302D4 8007BCF4 AC80000C */  sw         $zero, 0xC($a0)
    /* 302D8 8007BCF8 AC860010 */  sw         $a2, 0x10($a0)
    /* 302DC 8007BCFC 03E00008 */  jr         $ra
    /* 302E0 8007BD00 AC850014 */   sw        $a1, 0x14($a0)
endlabel func_8007BCD8
    /* 302E4 8007BD04 00000000 */  nop
