.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_80057DB4, 0x30C

glabel func_80057DB4
    /* C394 80057DB4 27BDFF68 */  addiu      $sp, $sp, -0x98
    /* C398 80057DB8 C7A000A8 */  lwc1       $fv0, 0xA8($sp)
    /* C39C 80057DBC C7A200AC */  lwc1       $fv1, 0xAC($sp)
    /* C3A0 80057DC0 C7A400B0 */  lwc1       $ft0, 0xB0($sp)
    /* C3A4 80057DC4 44856000 */  mtc1       $a1, $fa0
    /* C3A8 80057DC8 AFB3008C */  sw         $s3, 0x8C($sp)
    /* C3AC 80057DCC 00809821 */  addu       $s3, $a0, $zero
    /* C3B0 80057DD0 AFBF0090 */  sw         $ra, 0x90($sp)
    /* C3B4 80057DD4 AFB20088 */  sw         $s2, 0x88($sp)
    /* C3B8 80057DD8 AFB10084 */  sw         $s1, 0x84($sp)
    /* C3BC 80057DDC AFB00080 */  sw         $s0, 0x80($sp)
    /* C3C0 80057DE0 46006187 */  neg.s      $ft1, $fa0
    /* C3C4 80057DE4 46000007 */  neg.s      $fv0, $fv0
    /* C3C8 80057DE8 44866000 */  mtc1       $a2, $fa0
    /* C3CC 80057DEC 46001087 */  neg.s      $fv1, $fv1
    /* C3D0 80057DF0 E7A00060 */  swc1       $fv0, 0x60($sp)
    /* C3D4 80057DF4 44800000 */  mtc1       $zero, $fv0
    /* C3D8 80057DF8 46002107 */  neg.s      $ft0, $ft0
    /* C3DC 80057DFC E7A60070 */  swc1       $ft1, 0x70($sp)
    /* C3E0 80057E00 E7A20064 */  swc1       $fv1, 0x64($sp)
    /* C3E4 80057E04 E7A40068 */  swc1       $ft0, 0x68($sp)
    /* C3E8 80057E08 46006207 */  neg.s      $ft2, $fa0
    /* C3EC 80057E0C 44876000 */  mtc1       $a3, $fa0
    /* C3F0 80057E10 46003032 */  c.eq.s     $ft1, $fv0
    /* C3F4 80057E14 E7A80074 */  swc1       $ft2, 0x74($sp)
    /* C3F8 80057E18 46006287 */  neg.s      $ft3, $fa0
    /* C3FC 80057E1C 4500000C */  bc1f       .L80057E50
    /* C400 80057E20 E7AA0078 */   swc1      $ft3, 0x78($sp)
    /* C404 80057E24 46004032 */  c.eq.s     $ft2, $fv0
    /* C408 80057E28 00000000 */  nop
    /* C40C 80057E2C 45000008 */  bc1f       .L80057E50
    /* C410 80057E30 00000000 */   nop
    /* C414 80057E34 46005032 */  c.eq.s     $ft3, $fv0
    /* C418 80057E38 00000000 */  nop
    /* C41C 80057E3C 45000004 */  bc1f       .L80057E50
    /* C420 80057E40 00000000 */   nop
    /* C424 80057E44 3C018005 */  lui        $at, %hi(D_8004BDB0)
    /* C428 80057E48 C420BDB0 */  lwc1       $fv0, %lo(D_8004BDB0)($at)
    /* C42C 80057E4C E7A00078 */  swc1       $fv0, 0x78($sp)
  .L80057E50:
    /* C430 80057E50 C7A00060 */  lwc1       $fv0, 0x60($sp)
    /* C434 80057E54 44801000 */  mtc1       $zero, $fv1
    /* C438 80057E58 46020032 */  c.eq.s     $fv0, $fv1
    /* C43C 80057E5C 00000000 */  nop
    /* C440 80057E60 4500000F */  bc1f       .L80057EA0
    /* C444 80057E64 27B10070 */   addiu     $s1, $sp, 0x70
    /* C448 80057E68 C7A00064 */  lwc1       $fv0, 0x64($sp)
    /* C44C 80057E6C 46020032 */  c.eq.s     $fv0, $fv1
    /* C450 80057E70 00000000 */  nop
    /* C454 80057E74 4500000B */  bc1f       .L80057EA4
    /* C458 80057E78 02202021 */   addu      $a0, $s1, $zero
    /* C45C 80057E7C C7A00068 */  lwc1       $fv0, 0x68($sp)
    /* C460 80057E80 46020032 */  c.eq.s     $fv0, $fv1
    /* C464 80057E84 00000000 */  nop
    /* C468 80057E88 45000007 */  bc1f       .L80057EA8
    /* C46C 80057E8C 27B20060 */   addiu     $s2, $sp, 0x60
    /* C470 80057E90 3C018005 */  lui        $at, %hi(D_8004BDB4)
    /* C474 80057E94 C420BDB4 */  lwc1       $fv0, %lo(D_8004BDB4)($at)
    /* C478 80057E98 E7A00064 */  swc1       $fv0, 0x64($sp)
    /* C47C 80057E9C 27B10070 */  addiu      $s1, $sp, 0x70
  .L80057EA0:
    /* C480 80057EA0 02202021 */  addu       $a0, $s1, $zero
  .L80057EA4:
    /* C484 80057EA4 27B20060 */  addiu      $s2, $sp, 0x60
  .L80057EA8:
    /* C488 80057EA8 02402821 */  addu       $a1, $s2, $zero
    /* C48C 80057EAC 27B00050 */  addiu      $s0, $sp, 0x50
    /* C490 80057EB0 0C015EDD */  jal        func_80057B74
    /* C494 80057EB4 02003021 */   addu      $a2, $s0, $zero
    /* C498 80057EB8 C7A00050 */  lwc1       $fv0, 0x50($sp)
    /* C49C 80057EBC 44801000 */  mtc1       $zero, $fv1
    /* C4A0 80057EC0 46020032 */  c.eq.s     $fv0, $fv1
    /* C4A4 80057EC4 00000000 */  nop
    /* C4A8 80057EC8 45020014 */  bc1fl      .L80057F1C
    /* C4AC 80057ECC 27B20070 */   addiu     $s2, $sp, 0x70
    /* C4B0 80057ED0 C7A00054 */  lwc1       $fv0, 0x54($sp)
    /* C4B4 80057ED4 46020032 */  c.eq.s     $fv0, $fv1
    /* C4B8 80057ED8 00000000 */  nop
    /* C4BC 80057EDC 4502000F */  bc1fl      .L80057F1C
    /* C4C0 80057EE0 27B20070 */   addiu     $s2, $sp, 0x70
    /* C4C4 80057EE4 C7A00058 */  lwc1       $fv0, 0x58($sp)
    /* C4C8 80057EE8 46020032 */  c.eq.s     $fv0, $fv1
    /* C4CC 80057EEC 00000000 */  nop
    /* C4D0 80057EF0 45000009 */  bc1f       .L80057F18
    /* C4D4 80057EF4 02202021 */   addu      $a0, $s1, $zero
    /* C4D8 80057EF8 C7A00068 */  lwc1       $fv0, 0x68($sp)
    /* C4DC 80057EFC 3C018005 */  lui        $at, %hi(D_8004BDB8)
    /* C4E0 80057F00 C422BDB8 */  lwc1       $fv1, %lo(D_8004BDB8)($at)
    /* C4E4 80057F04 46020000 */  add.s      $fv0, $fv0, $fv1
    /* C4E8 80057F08 02402821 */  addu       $a1, $s2, $zero
    /* C4EC 80057F0C 02003021 */  addu       $a2, $s0, $zero
    /* C4F0 80057F10 0C015EDD */  jal        func_80057B74
    /* C4F4 80057F14 E7A00068 */   swc1      $fv0, 0x68($sp)
  .L80057F18:
    /* C4F8 80057F18 27B20070 */  addiu      $s2, $sp, 0x70
  .L80057F1C:
    /* C4FC 80057F1C 02402021 */  addu       $a0, $s2, $zero
    /* C500 80057F20 27B00050 */  addiu      $s0, $sp, 0x50
    /* C504 80057F24 02002821 */  addu       $a1, $s0, $zero
    /* C508 80057F28 27B10060 */  addiu      $s1, $sp, 0x60
    /* C50C 80057F2C 0C015EDD */  jal        func_80057B74
    /* C510 80057F30 02203021 */   addu      $a2, $s1, $zero
    /* C514 80057F34 02002021 */  addu       $a0, $s0, $zero
    /* C518 80057F38 27A50054 */  addiu      $a1, $sp, 0x54
    /* C51C 80057F3C 0C0159E2 */  jal        func_80056788
    /* C520 80057F40 27A60058 */   addiu     $a2, $sp, 0x58
    /* C524 80057F44 02202021 */  addu       $a0, $s1, $zero
    /* C528 80057F48 27A50064 */  addiu      $a1, $sp, 0x64
    /* C52C 80057F4C 0C0159E2 */  jal        func_80056788
    /* C530 80057F50 27A60068 */   addiu     $a2, $sp, 0x68
    /* C534 80057F54 02402021 */  addu       $a0, $s2, $zero
    /* C538 80057F58 27A50074 */  addiu      $a1, $sp, 0x74
    /* C53C 80057F5C 0C0159E2 */  jal        func_80056788
    /* C540 80057F60 27A60078 */   addiu     $a2, $sp, 0x78
    /* C544 80057F64 C7A40050 */  lwc1       $ft0, 0x50($sp)
    /* C548 80057F68 3C018005 */  lui        $at, %hi(D_8004BDBC)
    /* C54C 80057F6C C426BDBC */  lwc1       $ft1, %lo(D_8004BDBC)($at)
    /* C550 80057F70 46062102 */  mul.s      $ft0, $ft0, $ft1
    /* C554 80057F74 C7A20054 */  lwc1       $fv1, 0x54($sp)
    /* C558 80057F78 46061082 */  mul.s      $fv1, $fv1, $ft1
    /* C55C 80057F7C C7A00058 */  lwc1       $fv0, 0x58($sp)
    /* C560 80057F80 46060002 */  mul.s      $fv0, $fv0, $ft1
    /* C564 80057F84 3C04FFFF */  lui        $a0, (0xFFFF0000 >> 16)
    /* C568 80057F88 4600230D */  trunc.w.s  $fa0, $ft0
    /* C56C 80057F8C 44056000 */  mfc1       $a1, $fa0
    /* C570 80057F90 4600130D */  trunc.w.s  $fa0, $fv1
    /* C574 80057F94 44066000 */  mfc1       $a2, $fa0
    /* C578 80057F98 4600030D */  trunc.w.s  $fa0, $fv0
    /* C57C 80057F9C 44076000 */  mfc1       $a3, $fa0
    /* C580 80057FA0 00A41024 */  and        $v0, $a1, $a0
    /* C584 80057FA4 00061C02 */  srl        $v1, $a2, 16
    /* C588 80057FA8 00431025 */  or         $v0, $v0, $v1
    /* C58C 80057FAC AE620000 */  sw         $v0, 0x0($s3)
    /* C590 80057FB0 00E41024 */  and        $v0, $a3, $a0
    /* C594 80057FB4 AE620004 */  sw         $v0, 0x4($s3)
    /* C598 80057FB8 00051400 */  sll        $v0, $a1, 16
    /* C59C 80057FBC 30C3FFFF */  andi       $v1, $a2, 0xFFFF
    /* C5A0 80057FC0 00431025 */  or         $v0, $v0, $v1
    /* C5A4 80057FC4 AE620020 */  sw         $v0, 0x20($s3)
    /* C5A8 80057FC8 00071400 */  sll        $v0, $a3, 16
    /* C5AC 80057FCC AE620024 */  sw         $v0, 0x24($s3)
    /* C5B0 80057FD0 C7A40060 */  lwc1       $ft0, 0x60($sp)
    /* C5B4 80057FD4 46062102 */  mul.s      $ft0, $ft0, $ft1
    /* C5B8 80057FD8 C7A20064 */  lwc1       $fv1, 0x64($sp)
    /* C5BC 80057FDC 46061082 */  mul.s      $fv1, $fv1, $ft1
    /* C5C0 80057FE0 C7A00068 */  lwc1       $fv0, 0x68($sp)
    /* C5C4 80057FE4 46060002 */  mul.s      $fv0, $fv0, $ft1
    /* C5C8 80057FE8 4600230D */  trunc.w.s  $fa0, $ft0
    /* C5CC 80057FEC 44056000 */  mfc1       $a1, $fa0
    /* C5D0 80057FF0 4600130D */  trunc.w.s  $fa0, $fv1
    /* C5D4 80057FF4 44066000 */  mfc1       $a2, $fa0
    /* C5D8 80057FF8 4600030D */  trunc.w.s  $fa0, $fv0
    /* C5DC 80057FFC 44076000 */  mfc1       $a3, $fa0
    /* C5E0 80058000 00A41024 */  and        $v0, $a1, $a0
    /* C5E4 80058004 00061C02 */  srl        $v1, $a2, 16
    /* C5E8 80058008 00431025 */  or         $v0, $v0, $v1
    /* C5EC 8005800C AE620008 */  sw         $v0, 0x8($s3)
    /* C5F0 80058010 00E41024 */  and        $v0, $a3, $a0
    /* C5F4 80058014 AE62000C */  sw         $v0, 0xC($s3)
    /* C5F8 80058018 00051400 */  sll        $v0, $a1, 16
    /* C5FC 8005801C 30C3FFFF */  andi       $v1, $a2, 0xFFFF
    /* C600 80058020 00431025 */  or         $v0, $v0, $v1
    /* C604 80058024 AE620028 */  sw         $v0, 0x28($s3)
    /* C608 80058028 00071400 */  sll        $v0, $a3, 16
    /* C60C 8005802C AE62002C */  sw         $v0, 0x2C($s3)
    /* C610 80058030 C7A40070 */  lwc1       $ft0, 0x70($sp)
    /* C614 80058034 46062102 */  mul.s      $ft0, $ft0, $ft1
    /* C618 80058038 C7A20074 */  lwc1       $fv1, 0x74($sp)
    /* C61C 8005803C 46061082 */  mul.s      $fv1, $fv1, $ft1
    /* C620 80058040 C7A00078 */  lwc1       $fv0, 0x78($sp)
    /* C624 80058044 24020001 */  addiu      $v0, $zero, 0x1
    /* C628 80058048 AE600018 */  sw         $zero, 0x18($s3)
    /* C62C 8005804C AE62001C */  sw         $v0, 0x1C($s3)
    /* C630 80058050 46060002 */  mul.s      $fv0, $fv0, $ft1
    /* C634 80058054 AE600038 */  sw         $zero, 0x38($s3)
    /* C638 80058058 AE60003C */  sw         $zero, 0x3C($s3)
    /* C63C 8005805C 4600230D */  trunc.w.s  $fa0, $ft0
    /* C640 80058060 44056000 */  mfc1       $a1, $fa0
    /* C644 80058064 4600130D */  trunc.w.s  $fa0, $fv1
    /* C648 80058068 44066000 */  mfc1       $a2, $fa0
    /* C64C 8005806C 4600030D */  trunc.w.s  $fa0, $fv0
    /* C650 80058070 44076000 */  mfc1       $a3, $fa0
    /* C654 80058074 00A41024 */  and        $v0, $a1, $a0
    /* C658 80058078 00061C02 */  srl        $v1, $a2, 16
    /* C65C 8005807C 00431025 */  or         $v0, $v0, $v1
    /* C660 80058080 00E42024 */  and        $a0, $a3, $a0
    /* C664 80058084 AE620010 */  sw         $v0, 0x10($s3)
    /* C668 80058088 00051400 */  sll        $v0, $a1, 16
    /* C66C 8005808C 30C3FFFF */  andi       $v1, $a2, 0xFFFF
    /* C670 80058090 00431025 */  or         $v0, $v0, $v1
    /* C674 80058094 AE620030 */  sw         $v0, 0x30($s3)
    /* C678 80058098 00071400 */  sll        $v0, $a3, 16
    /* C67C 8005809C AE640014 */  sw         $a0, 0x14($s3)
    /* C680 800580A0 AE620034 */  sw         $v0, 0x34($s3)
    /* C684 800580A4 8FBF0090 */  lw         $ra, 0x90($sp)
    /* C688 800580A8 8FB3008C */  lw         $s3, 0x8C($sp)
    /* C68C 800580AC 8FB20088 */  lw         $s2, 0x88($sp)
    /* C690 800580B0 8FB10084 */  lw         $s1, 0x84($sp)
    /* C694 800580B4 8FB00080 */  lw         $s0, 0x80($sp)
    /* C698 800580B8 03E00008 */  jr         $ra
    /* C69C 800580BC 27BD0098 */   addiu     $sp, $sp, 0x98
endlabel func_80057DB4

nonmatching func_800580C0, 0x78

glabel func_800580C0
    /* C6A0 800580C0 1085001B */  beq        $a0, $a1, .L80058130
    /* C6A4 800580C4 00000000 */   nop
    /* C6A8 800580C8 C4800000 */  lwc1       $fv0, 0x0($a0)
    /* C6AC 800580CC E4A00000 */  swc1       $fv0, 0x0($a1)
    /* C6B0 800580D0 C4800004 */  lwc1       $fv0, 0x4($a0)
    /* C6B4 800580D4 E4A00010 */  swc1       $fv0, 0x10($a1)
    /* C6B8 800580D8 C4800008 */  lwc1       $fv0, 0x8($a0)
    /* C6BC 800580DC E4A00020 */  swc1       $fv0, 0x20($a1)
    /* C6C0 800580E0 C4800010 */  lwc1       $fv0, 0x10($a0)
    /* C6C4 800580E4 E4A00004 */  swc1       $fv0, 0x4($a1)
    /* C6C8 800580E8 C4800014 */  lwc1       $fv0, 0x14($a0)
    /* C6CC 800580EC E4A00014 */  swc1       $fv0, 0x14($a1)
    /* C6D0 800580F0 C4800018 */  lwc1       $fv0, 0x18($a0)
    /* C6D4 800580F4 E4A00024 */  swc1       $fv0, 0x24($a1)
    /* C6D8 800580F8 C4800020 */  lwc1       $fv0, 0x20($a0)
    /* C6DC 800580FC E4A00008 */  swc1       $fv0, 0x8($a1)
    /* C6E0 80058100 C4800014 */  lwc1       $fv0, 0x14($a0)
    /* C6E4 80058104 E4A00018 */  swc1       $fv0, 0x18($a1)
    /* C6E8 80058108 44800000 */  mtc1       $zero, $fv0
    /* C6EC 8005810C C4820008 */  lwc1       $fv1, 0x8($a0)
    /* C6F0 80058110 E4A0003C */  swc1       $fv0, 0x3C($a1)
    /* C6F4 80058114 E4A00038 */  swc1       $fv0, 0x38($a1)
    /* C6F8 80058118 E4A00034 */  swc1       $fv0, 0x34($a1)
    /* C6FC 8005811C E4A00030 */  swc1       $fv0, 0x30($a1)
    /* C700 80058120 E4A0002C */  swc1       $fv0, 0x2C($a1)
    /* C704 80058124 E4A0001C */  swc1       $fv0, 0x1C($a1)
    /* C708 80058128 E4A0000C */  swc1       $fv0, 0xC($a1)
    /* C70C 8005812C E4A20028 */  swc1       $fv1, 0x28($a1)
  .L80058130:
    /* C710 80058130 03E00008 */  jr         $ra
    /* C714 80058134 00000000 */   nop
endlabel func_800580C0
