.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_8007EBC4, 0x1D0

glabel func_8007EBC4
    /* 331A4 8007EBC4 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 331A8 8007EBC8 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 331AC 8007EBCC 90AE0008 */  lbu        $t6, 0x8($a1)
    /* 331B0 8007EBD0 240100FF */  addiu      $at, $zero, 0xFF
    /* 331B4 8007EBD4 00008025 */  or         $s0, $zero, $zero
    /* 331B8 8007EBD8 15C1006A */  bne        $t6, $at, .L8007ED84
    /* 331BC 8007EBDC 00009825 */   or        $s3, $zero, $zero
    /* 331C0 8007EBE0 90AF0009 */  lbu        $t7, 0x9($a1)
    /* 331C4 8007EBE4 24010051 */  addiu      $at, $zero, 0x51
    /* 331C8 8007EBE8 24A20004 */  addiu      $v0, $a1, 0x4
    /* 331CC 8007EBEC 55E10066 */  bnel       $t7, $at, .L8007ED88
    /* 331D0 8007EBF0 8FBF0014 */   lw        $ra, 0x14($sp)
    /* 331D4 8007EBF4 904E0008 */  lbu        $t6, 0x8($v0)
    /* 331D8 8007EBF8 90580007 */  lbu        $t8, 0x7($v0)
    /* 331DC 8007EBFC 8EFE0024 */  lw         $fp, 0x24($s7)
    /* 331E0 8007EC00 000E7A00 */  sll        $t7, $t6, 8
    /* 331E4 8007EC04 904E0009 */  lbu        $t6, 0x9($v0)
    /* 331E8 8007EC08 0018CC00 */  sll        $t9, $t8, 16
    /* 331EC 8007EC0C 032FC025 */  or         $t8, $t9, $t7
    /* 331F0 8007EC10 030E1825 */  or         $v1, $t8, $t6
    /* 331F4 8007EC14 44832000 */  mtc1       $v1, $ft0
    /* 331F8 8007EC18 02E02025 */  or         $a0, $s7, $zero
    /* 331FC 8007EC1C 0C01FAE2 */  jal        func_8007EB88
    /* 33200 8007EC20 46802320 */   cvt.s.w   $fa0, $ft0
    /* 33204 8007EC24 8EF10050 */  lw         $s1, 0x50($s7)
    /* 33208 8007EC28 1220001D */  beqz       $s1, .L8007ECA0
    /* 3320C 8007EC2C 00000000 */   nop
    /* 33210 8007EC30 24140015 */  addiu      $s4, $zero, 0x15
  .L8007EC34:
    /* 33214 8007EC34 862F000C */  lh         $t7, 0xC($s1)
    /* 33218 8007EC38 8E390008 */  lw         $t9, 0x8($s1)
    /* 3321C 8007EC3C 8E320000 */  lw         $s2, 0x0($s1)
    /* 33220 8007EC40 168F0015 */  bne        $s4, $t7, .L8007EC98
    /* 33224 8007EC44 02198021 */   addu      $s0, $s0, $t9
    /* 33228 8007EC48 0C01F686 */  jal        func_8007DA18
    /* 3322C 8007EC4C 02202025 */   or        $a0, $s1, $zero
    /* 33230 8007EC50 52600007 */  beql       $s3, $zero, .L8007EC70
    /* 33234 8007EC54 AE200000 */   sw        $zero, 0x0($s1)
    /* 33238 8007EC58 02202025 */  or         $a0, $s1, $zero
    /* 3323C 8007EC5C 0C01F692 */  jal        func_8007DA48
    /* 33240 8007EC60 02602825 */   or        $a1, $s3, $zero
    /* 33244 8007EC64 10000004 */  b          .L8007EC78
    /* 33248 8007EC68 00000000 */   nop
    /* 3324C 8007EC6C AE200000 */  sw         $zero, 0x0($s1)
  .L8007EC70:
    /* 33250 8007EC70 AE200004 */  sw         $zero, 0x4($s1)
    /* 33254 8007EC74 02209825 */  or         $s3, $s1, $zero
  .L8007EC78:
    /* 33258 8007EC78 12400006 */  beqz       $s2, .L8007EC94
    /* 3325C 8007EC7C 02001825 */   or        $v1, $s0, $zero
    /* 33260 8007EC80 8E220008 */  lw         $v0, 0x8($s1)
    /* 33264 8007EC84 8E580008 */  lw         $t8, 0x8($s2)
    /* 33268 8007EC88 02028023 */  subu       $s0, $s0, $v0
    /* 3326C 8007EC8C 03027021 */  addu       $t6, $t8, $v0
    /* 33270 8007EC90 AE4E0008 */  sw         $t6, 0x8($s2)
  .L8007EC94:
    /* 33274 8007EC94 AE230008 */  sw         $v1, 0x8($s1)
  .L8007EC98:
    /* 33278 8007EC98 1640FFE6 */  bnez       $s2, .L8007EC34
    /* 3327C 8007EC9C 02408825 */   or        $s1, $s2, $zero
  .L8007ECA0:
    /* 33280 8007ECA0 12600038 */  beqz       $s3, .L8007ED84
    /* 33284 8007ECA4 02608825 */   or        $s1, $s3, $zero
    /* 33288 8007ECA8 26F40048 */  addiu      $s4, $s7, 0x48
    /* 3328C 8007ECAC 26950008 */  addiu      $s5, $s4, 0x8
    /* 33290 8007ECB0 2416FFF8 */  addiu      $s6, $zero, -0x8
  .L8007ECB4:
    /* 33294 8007ECB4 8E390008 */  lw         $t9, 0x8($s1)
    /* 33298 8007ECB8 8EEF0024 */  lw         $t7, 0x24($s7)
    /* 3329C 8007ECBC 8E320000 */  lw         $s2, 0x0($s1)
    /* 332A0 8007ECC0 033E001A */  div        $zero, $t9, $fp
    /* 332A4 8007ECC4 00001012 */  mflo       $v0
    /* 332A8 8007ECC8 24040001 */  addiu      $a0, $zero, 0x1
    /* 332AC 8007ECCC 17C00002 */  bnez       $fp, .L8007ECD8
    /* 332B0 8007ECD0 00000000 */   nop
    /* 332B4 8007ECD4 0007000D */  break      7
  .L8007ECD8:
    /* 332B8 8007ECD8 2401FFFF */  addiu      $at, $zero, -0x1
    /* 332BC 8007ECDC 17C10004 */  bne        $fp, $at, .L8007ECF0
    /* 332C0 8007ECE0 3C018000 */   lui       $at, (0x80000000 >> 16)
    /* 332C4 8007ECE4 17210002 */  bne        $t9, $at, .L8007ECF0
    /* 332C8 8007ECE8 00000000 */   nop
    /* 332CC 8007ECEC 0006000D */  break      6
  .L8007ECF0:
    /* 332D0 8007ECF0 01E20019 */  multu      $t7, $v0
    /* 332D4 8007ECF4 02A08025 */  or         $s0, $s5, $zero
    /* 332D8 8007ECF8 0000C012 */  mflo       $t8
    /* 332DC 8007ECFC AE380008 */  sw         $t8, 0x8($s1)
    /* 332E0 8007ED00 0C01F1EA */  jal        func_8007C7A8
    /* 332E4 8007ED04 00000000 */   nop
    /* 332E8 8007ED08 1296001A */  beq        $s4, $s6, .L8007ED74
    /* 332EC 8007ED0C 00409825 */   or        $s3, $v0, $zero
    /* 332F0 8007ED10 8E040000 */  lw         $a0, 0x0($s0)
  .L8007ED14:
    /* 332F4 8007ED14 54800007 */  bnel       $a0, $zero, .L8007ED34
    /* 332F8 8007ED18 8E220008 */   lw        $v0, 0x8($s1)
    /* 332FC 8007ED1C 02202025 */  or         $a0, $s1, $zero
    /* 33300 8007ED20 0C01F692 */  jal        func_8007DA48
    /* 33304 8007ED24 02002825 */   or        $a1, $s0, $zero
    /* 33308 8007ED28 10000012 */  b          .L8007ED74
    /* 3330C 8007ED2C 00000000 */   nop
    /* 33310 8007ED30 8E220008 */  lw         $v0, 0x8($s1)
  .L8007ED34:
    /* 33314 8007ED34 8C830008 */  lw         $v1, 0x8($a0)
    /* 33318 8007ED38 00803025 */  or         $a2, $a0, $zero
    /* 3331C 8007ED3C 0043082A */  slt        $at, $v0, $v1
    /* 33320 8007ED40 10200008 */  beqz       $at, .L8007ED64
    /* 33324 8007ED44 0043C823 */   subu      $t9, $v0, $v1
    /* 33328 8007ED48 00627023 */  subu       $t6, $v1, $v0
    /* 3332C 8007ED4C AC8E0008 */  sw         $t6, 0x8($a0)
    /* 33330 8007ED50 02202025 */  or         $a0, $s1, $zero
    /* 33334 8007ED54 0C01F692 */  jal        func_8007DA48
    /* 33338 8007ED58 02002825 */   or        $a1, $s0, $zero
    /* 3333C 8007ED5C 10000005 */  b          .L8007ED74
    /* 33340 8007ED60 00000000 */   nop
  .L8007ED64:
    /* 33344 8007ED64 AE390008 */  sw         $t9, 0x8($s1)
    /* 33348 8007ED68 8E100000 */  lw         $s0, 0x0($s0)
    /* 3334C 8007ED6C 5600FFE9 */  bnel       $s0, $zero, .L8007ED14
    /* 33350 8007ED70 8E040000 */   lw        $a0, 0x0($s0)
  .L8007ED74:
    /* 33354 8007ED74 0C01F1EA */  jal        func_8007C7A8
    /* 33358 8007ED78 02602025 */   or        $a0, $s3, $zero
    /* 3335C 8007ED7C 1640FFCD */  bnez       $s2, .L8007ECB4
    /* 33360 8007ED80 02408825 */   or        $s1, $s2, $zero
  .L8007ED84:
    /* 33364 8007ED84 8FBF0014 */  lw         $ra, 0x14($sp)
  .L8007ED88:
    /* 33368 8007ED88 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 3336C 8007ED8C 03E00008 */  jr         $ra
    /* 33370 8007ED90 00000000 */   nop
endlabel func_8007EBC4
