.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_800891F4, 0x68

glabel func_800891F4
    /* 3D7D4 800891F4 27BDFFF8 */  addiu      $sp, $sp, -0x8
    /* 3D7D8 800891F8 A7A00006 */  sh         $zero, 0x6($sp)
    /* 3D7DC 800891FC A4C00000 */  sh         $zero, 0x0($a2)
    /* 3D7E0 80089200 94CE0000 */  lhu        $t6, 0x0($a2)
    /* 3D7E4 80089204 A4AE0000 */  sh         $t6, 0x0($a1)
    /* 3D7E8 80089208 AFA00000 */  sw         $zero, 0x0($sp)
  .L8008920C:
    /* 3D7EC 8008920C 8FAF0000 */  lw         $t7, 0x0($sp)
    /* 3D7F0 80089210 008FC021 */  addu       $t8, $a0, $t7
    /* 3D7F4 80089214 97190000 */  lhu        $t9, 0x0($t8)
    /* 3D7F8 80089218 A7B90006 */  sh         $t9, 0x6($sp)
    /* 3D7FC 8008921C 94A80000 */  lhu        $t0, 0x0($a1)
    /* 3D800 80089220 01194821 */  addu       $t1, $t0, $t9
    /* 3D804 80089224 A4A90000 */  sh         $t1, 0x0($a1)
    /* 3D808 80089228 97AB0006 */  lhu        $t3, 0x6($sp)
    /* 3D80C 8008922C 94CA0000 */  lhu        $t2, 0x0($a2)
    /* 3D810 80089230 01606027 */  not        $t4, $t3
    /* 3D814 80089234 014C6821 */  addu       $t5, $t2, $t4
    /* 3D818 80089238 A4CD0000 */  sh         $t5, 0x0($a2)
    /* 3D81C 8008923C 8FAE0000 */  lw         $t6, 0x0($sp)
    /* 3D820 80089240 25CF0002 */  addiu      $t7, $t6, 0x2
    /* 3D824 80089244 2DE1001C */  sltiu      $at, $t7, 0x1C
    /* 3D828 80089248 1420FFF0 */  bnez       $at, .L8008920C
    /* 3D82C 8008924C AFAF0000 */   sw        $t7, 0x0($sp)
    /* 3D830 80089250 00001025 */  or         $v0, $zero, $zero
    /* 3D834 80089254 03E00008 */  jr         $ra
    /* 3D838 80089258 27BD0008 */   addiu     $sp, $sp, 0x8
endlabel func_800891F4
