.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_8005F6B8, 0x180

glabel func_8005F6B8
    /* 13C98 8005F6B8 27BDFF40 */  addiu      $sp, $sp, -0xC0
    /* 13C9C 8005F6BC 24040028 */  addiu      $a0, $zero, 0x28
    /* 13CA0 8005F6C0 AFBF00AC */  sw         $ra, 0xAC($sp)
    /* 13CA4 8005F6C4 AFB000A8 */  sw         $s0, 0xA8($sp)
    /* 13CA8 8005F6C8 F7B600B8 */  sdc1       $fs1, 0xB8($sp)
    /* 13CAC 8005F6CC F7B400B0 */  sdc1       $fs0, 0xB0($sp)
    /* 13CB0 8005F6D0 0C01723B */  jal        func_8005C8EC
    /* 13CB4 8005F6D4 00002821 */   addu      $a1, $zero, $zero
    /* 13CB8 8005F6D8 0C01722E */  jal        func_8005C8B8
    /* 13CBC 8005F6DC 00000000 */   nop
    /* 13CC0 8005F6E0 00002021 */  addu       $a0, $zero, $zero
    /* 13CC4 8005F6E4 3C028018 */  lui        $v0, %hi(D_801820D8)
    /* 13CC8 8005F6E8 244320D8 */  addiu      $v1, $v0, %lo(D_801820D8)
  .L8005F6EC:
    /* 13CCC 8005F6EC AC600000 */  sw         $zero, 0x0($v1)
    /* 13CD0 8005F6F0 AC60000C */  sw         $zero, 0xC($v1)
    /* 13CD4 8005F6F4 AC600010 */  sw         $zero, 0x10($v1)
    /* 13CD8 8005F6F8 AC600018 */  sw         $zero, 0x18($v1)
    /* 13CDC 8005F6FC AC600014 */  sw         $zero, 0x14($v1)
    /* 13CE0 8005F700 AC600008 */  sw         $zero, 0x8($v1)
    /* 13CE4 8005F704 AC600004 */  sw         $zero, 0x4($v1)
    /* 13CE8 8005F708 AC60001C */  sw         $zero, 0x1C($v1)
    /* 13CEC 8005F70C AC600020 */  sw         $zero, 0x20($v1)
    /* 13CF0 8005F710 24840001 */  addiu      $a0, $a0, 0x1
    /* 13CF4 8005F714 28820004 */  slti       $v0, $a0, 0x4
    /* 13CF8 8005F718 1440FFF4 */  bnez       $v0, .L8005F6EC
    /* 13CFC 8005F71C 24630024 */   addiu     $v1, $v1, 0x24
    /* 13D00 8005F720 3C048018 */  lui        $a0, %hi(D_80181EB0)
    /* 13D04 8005F724 0C01EA38 */  jal        func_8007A8E0
    /* 13D08 8005F728 24841EB0 */   addiu     $a0, $a0, %lo(D_80181EB0)
    /* 13D0C 8005F72C 3C048018 */  lui        $a0, %hi(D_80182078)
    /* 13D10 8005F730 3C0643A0 */  lui        $a2, (0x43A00000 >> 16)
    /* 13D14 8005F734 4480B000 */  mtc1       $zero, $fs1
    /* 13D18 8005F738 3C074370 */  lui        $a3, (0x43700000 >> 16)
    /* 13D1C 8005F73C 3C018005 */  lui        $at, %hi(D_8004BF58)
    /* 13D20 8005F740 C420BF58 */  lwc1       $fv0, %lo(D_8004BF58)($at)
    /* 13D24 8005F744 3C018005 */  lui        $at, %hi(D_8004BF5C)
    /* 13D28 8005F748 C422BF5C */  lwc1       $fv1, %lo(D_8004BF5C)($at)
    /* 13D2C 8005F74C 3C018005 */  lui        $at, %hi(D_8004BF60)
    /* 13D30 8005F750 C434BF60 */  lwc1       $fs0, %lo(D_8004BF60)($at)
    /* 13D34 8005F754 4405B000 */  mfc1       $a1, $fs1
    /* 13D38 8005F758 24842078 */  addiu      $a0, $a0, %lo(D_80182078)
    /* 13D3C 8005F75C E7B60010 */  swc1       $fs1, 0x10($sp)
    /* 13D40 8005F760 E7A00014 */  swc1       $fv0, 0x14($sp)
    /* 13D44 8005F764 E7A20018 */  swc1       $fv1, 0x18($sp)
    /* 13D48 8005F768 0C01EB9F */  jal        func_8007AE7C
    /* 13D4C 8005F76C E7B4001C */   swc1      $fs0, 0x1C($sp)
    /* 13D50 8005F770 27A40028 */  addiu      $a0, $sp, 0x28
    /* 13D54 8005F774 3C058018 */  lui        $a1, %hi(D_801822D8)
    /* 13D58 8005F778 3C064204 */  lui        $a2, (0x42040000 >> 16)
    /* 13D5C 8005F77C 3C073FAA */  lui        $a3, (0x3FAAAAAB >> 16)
    /* 13D60 8005F780 34E7AAAB */  ori        $a3, $a3, (0x3FAAAAAB & 0xFFFF)
    /* 13D64 8005F784 3C018005 */  lui        $at, %hi(D_8004BF64)
    /* 13D68 8005F788 C420BF64 */  lwc1       $fv0, %lo(D_8004BF64)($at)
    /* 13D6C 8005F78C 24A522D8 */  addiu      $a1, $a1, %lo(D_801822D8)
    /* 13D70 8005F790 E7B40010 */  swc1       $fs0, 0x10($sp)
    /* 13D74 8005F794 E7B40018 */  swc1       $fs0, 0x18($sp)
    /* 13D78 8005F798 0C01EC46 */  jal        func_8007B118
    /* 13D7C 8005F79C E7A00014 */   swc1      $fv0, 0x14($sp)
    /* 13D80 8005F7A0 27B00068 */  addiu      $s0, $sp, 0x68
    /* 13D84 8005F7A4 3C07C3CB */  lui        $a3, (0xC3CB0000 >> 16)
    /* 13D88 8005F7A8 3C018005 */  lui        $at, %hi(D_8004BF68)
    /* 13D8C 8005F7AC C420BF68 */  lwc1       $fv0, %lo(D_8004BF68)($at)
    /* 13D90 8005F7B0 3C018005 */  lui        $at, %hi(D_8004BF6C)
    /* 13D94 8005F7B4 C422BF6C */  lwc1       $fv1, %lo(D_8004BF6C)($at)
    /* 13D98 8005F7B8 44050000 */  mfc1       $a1, $fv0
    /* 13D9C 8005F7BC 44061000 */  mfc1       $a2, $fv1
    /* 13DA0 8005F7C0 3C018005 */  lui        $at, %hi(D_8004BF70)
    /* 13DA4 8005F7C4 C420BF70 */  lwc1       $fv0, %lo(D_8004BF70)($at)
    /* 13DA8 8005F7C8 02002021 */  addu       $a0, $s0, $zero
    /* 13DAC 8005F7CC E7B60018 */  swc1       $fs1, 0x18($sp)
    /* 13DB0 8005F7D0 E7B6001C */  swc1       $fs1, 0x1C($sp)
    /* 13DB4 8005F7D4 E7B60024 */  swc1       $fs1, 0x24($sp)
    /* 13DB8 8005F7D8 AFA50010 */  sw         $a1, 0x10($sp)
    /* 13DBC 8005F7DC AFA60014 */  sw         $a2, 0x14($sp)
    /* 13DC0 8005F7E0 0C01E884 */  jal        func_8007A210
    /* 13DC4 8005F7E4 E7A00020 */   swc1      $fv0, 0x20($sp)
    /* 13DC8 8005F7E8 02002021 */  addu       $a0, $s0, $zero
    /* 13DCC 8005F7EC 27A50028 */  addiu      $a1, $sp, 0x28
    /* 13DD0 8005F7F0 3C068018 */  lui        $a2, %hi(D_80181E70)
    /* 13DD4 8005F7F4 0C01EB0E */  jal        func_8007AC38
    /* 13DD8 8005F7F8 24C61E70 */   addiu     $a2, $a2, %lo(D_80181E70)
    /* 13DDC 8005F7FC 3C028018 */  lui        $v0, %hi(D_80181E48)
    /* 13DE0 8005F800 AC401E48 */  sw         $zero, %lo(D_80181E48)($v0)
    /* 13DE4 8005F804 3C028018 */  lui        $v0, %hi(D_80181E4C)
    /* 13DE8 8005F808 8FBF00AC */  lw         $ra, 0xAC($sp)
    /* 13DEC 8005F80C 8FB000A8 */  lw         $s0, 0xA8($sp)
    /* 13DF0 8005F810 D7B600B8 */  ldc1       $fs1, 0xB8($sp)
    /* 13DF4 8005F814 D7B400B0 */  ldc1       $fs0, 0xB0($sp)
    /* 13DF8 8005F818 3C038009 */  lui        $v1, %hi(D_80092CC4)
    /* 13DFC 8005F81C AC401E4C */  sw         $zero, %lo(D_80181E4C)($v0)
    /* 13E00 8005F820 2402FFFF */  addiu      $v0, $zero, -0x1
    /* 13E04 8005F824 AC622CC4 */  sw         $v0, %lo(D_80092CC4)($v1)
    /* 13E08 8005F828 3C028009 */  lui        $v0, %hi(D_80093F04)
    /* 13E0C 8005F82C AC403F04 */  sw         $zero, %lo(D_80093F04)($v0)
    /* 13E10 8005F830 03E00008 */  jr         $ra
    /* 13E14 8005F834 27BD00C0 */   addiu     $sp, $sp, 0xC0
endlabel func_8005F6B8
