.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_80061894, 0x70

glabel func_80061894
    /* 15E74 80061894 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 15E78 80061898 AFB00010 */  sw         $s0, 0x10($sp)
    /* 15E7C 8006189C 00808021 */  addu       $s0, $a0, $zero
    /* 15E80 800618A0 24020011 */  addiu      $v0, $zero, 0x11
    /* 15E84 800618A4 16020003 */  bne        $s0, $v0, .L800618B4
    /* 15E88 800618A8 AFBF0014 */   sw        $ra, 0x14($sp)
    /* 15E8C 800618AC 08018630 */  j          func_800618C0
    /* 15E90 800618B0 24100022 */   addiu     $s0, $zero, 0x22
  .L800618B4:
    /* 15E94 800618B4 2402001E */  addiu      $v0, $zero, 0x1E
    /* 15E98 800618B8 52020001 */  beql       $s0, $v0, func_800618C0
    /* 15E9C 800618BC 24100023 */   addiu     $s0, $zero, 0x23
  alabel func_800618C0
    /* 15EA0 800618C0 06010003 */  bgez       $s0, .L800618D0
    /* 15EA4 800618C4 3C038009 */   lui       $v1, %hi(D_80092B78)
    /* 15EA8 800618C8 0801863D */  j          func_800618F4
    /* 15EAC 800618CC 02001021 */   addu      $v0, $s0, $zero
  .L800618D0:
    /* 15EB0 800618D0 94622B78 */  lhu        $v0, %lo(D_80092B78)($v1)
    /* 15EB4 800618D4 50400007 */  beql       $v0, $zero, func_800618F4
    /* 15EB8 800618D8 00001021 */   addu      $v0, $zero, $zero
    /* 15EBC 800618DC 0C018E6C */  jal        func_800639B0
    /* 15EC0 800618E0 00402021 */   addu      $a0, $v0, $zero
    /* 15EC4 800618E4 00101880 */  sll        $v1, $s0, 2
    /* 15EC8 800618E8 00621821 */  addu       $v1, $v1, $v0
    /* 15ECC 800618EC 8C630000 */  lw         $v1, 0x0($v1)
    /* 15ED0 800618F0 00431021 */  addu       $v0, $v0, $v1
  alabel func_800618F4
    /* 15ED4 800618F4 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 15ED8 800618F8 8FB00010 */  lw         $s0, 0x10($sp)
    /* 15EDC 800618FC 03E00008 */  jr         $ra
    /* 15EE0 80061900 27BD0018 */   addiu     $sp, $sp, 0x18
endlabel func_80061894

nonmatching func_80061904, 0x20

glabel func_80061904
    /* 15EE4 80061904 00802821 */  addu       $a1, $a0, $zero
    /* 15EE8 80061908 00002021 */  addu       $a0, $zero, $zero
    /* 15EEC 8006190C 3C018009 */  lui        $at, %hi(D_80092CB0)
    /* 15EF0 80061910 AC242CB0 */  sw         $a0, %lo(D_80092CB0)($at)
    /* 15EF4 80061914 3C018009 */  lui        $at, %hi(D_80092CB4)
    /* 15EF8 80061918 AC252CB4 */  sw         $a1, %lo(D_80092CB4)($at)
    /* 15EFC 8006191C 03E00008 */  jr         $ra
    /* 15F00 80061920 00000000 */   nop
endlabel func_80061904

nonmatching func_80061924, 0x8C

glabel func_80061924
    /* 15F04 80061924 3C0741C6 */  lui        $a3, (0x41C64E6D >> 16)
    /* 15F08 80061928 3C068009 */  lui        $a2, %hi(D_80092CB0)
    /* 15F0C 8006192C 24C62CB0 */  addiu      $a2, $a2, %lo(D_80092CB0)
    /* 15F10 80061930 8CC40000 */  lw         $a0, 0x0($a2)
    /* 15F14 80061934 8CC50004 */  lw         $a1, 0x4($a2)
    /* 15F18 80061938 34E74E6D */  ori        $a3, $a3, (0x41C64E6D & 0xFFFF)
    /* 15F1C 8006193C 00A70019 */  multu      $a1, $a3
    /* 15F20 80061940 00001010 */  mfhi       $v0
    /* 15F24 80061944 00001812 */  mflo       $v1
    /* 15F28 80061948 00000000 */  nop
    /* 15F2C 8006194C 00000000 */  nop
    /* 15F30 80061950 00870018 */  mult       $a0, $a3
    /* 15F34 80061954 00002012 */  mflo       $a0
    /* 15F38 80061958 00441021 */  addu       $v0, $v0, $a0
    /* 15F3C 8006195C 24633039 */  addiu      $v1, $v1, 0x3039
    /* 15F40 80061960 2C643039 */  sltiu      $a0, $v1, 0x3039
    /* 15F44 80061964 00441021 */  addu       $v0, $v0, $a0
    /* 15F48 80061968 000223C0 */  sll        $a0, $v0, 15
    /* 15F4C 8006196C 00033C42 */  srl        $a3, $v1, 17
    /* 15F50 80061970 00872025 */  or         $a0, $a0, $a3
    /* 15F54 80061974 00032BC0 */  sll        $a1, $v1, 15
    /* 15F58 80061978 00031EC2 */  srl        $v1, $v1, 27
    /* 15F5C 8006197C 00023940 */  sll        $a3, $v0, 5
    /* 15F60 80061980 00671825 */  or         $v1, $v1, $a3
    /* 15F64 80061984 000216C2 */  srl        $v0, $v0, 27
    /* 15F68 80061988 00822026 */  xor        $a0, $a0, $v0
    /* 15F6C 8006198C 00A32826 */  xor        $a1, $a1, $v1
    /* 15F70 80061990 ACC40000 */  sw         $a0, 0x0($a2)
    /* 15F74 80061994 ACC50004 */  sw         $a1, 0x4($a2)
    /* 15F78 80061998 00052902 */  srl        $a1, $a1, 4
    /* 15F7C 8006199C 00041700 */  sll        $v0, $a0, 28
    /* 15F80 800619A0 00A22825 */  or         $a1, $a1, $v0
    /* 15F84 800619A4 00042102 */  srl        $a0, $a0, 4
    /* 15F88 800619A8 03E00008 */  jr         $ra
    /* 15F8C 800619AC 00A01021 */   addu      $v0, $a1, $zero
endlabel func_80061924

nonmatching func_800619B0, 0xEC

glabel func_800619B0
    /* 15F90 800619B0 00A4102B */  sltu       $v0, $a1, $a0
    /* 15F94 800619B4 10400004 */  beqz       $v0, .L800619C8
    /* 15F98 800619B8 00A61021 */   addu      $v0, $a1, $a2
    /* 15F9C 800619BC 0082102B */  sltu       $v0, $a0, $v0
    /* 15FA0 800619C0 14400028 */  bnez       $v0, .L80061A64
    /* 15FA4 800619C4 24C2FFFF */   addiu     $v0, $a2, -0x1
  .L800619C8:
    /* 15FA8 800619C8 30820003 */  andi       $v0, $a0, 0x3
    /* 15FAC 800619CC 1440001A */  bnez       $v0, .L80061A38
    /* 15FB0 800619D0 00C01021 */   addu      $v0, $a2, $zero
    /* 15FB4 800619D4 30A20003 */  andi       $v0, $a1, 0x3
    /* 15FB8 800619D8 14400017 */  bnez       $v0, .L80061A38
    /* 15FBC 800619DC 00C01021 */   addu      $v0, $a2, $zero
    /* 15FC0 800619E0 2CC20004 */  sltiu      $v0, $a2, 0x4
    /* 15FC4 800619E4 14400009 */  bnez       $v0, .L80061A0C
    /* 15FC8 800619E8 00C01021 */   addu      $v0, $a2, $zero
  .L800619EC:
    /* 15FCC 800619EC 8CA20000 */  lw         $v0, 0x0($a1)
    /* 15FD0 800619F0 24A50004 */  addiu      $a1, $a1, 0x4
    /* 15FD4 800619F4 24C6FFFC */  addiu      $a2, $a2, -0x4
    /* 15FD8 800619F8 AC820000 */  sw         $v0, 0x0($a0)
    /* 15FDC 800619FC 2CC20004 */  sltiu      $v0, $a2, 0x4
    /* 15FE0 80061A00 1040FFFA */  beqz       $v0, .L800619EC
    /* 15FE4 80061A04 24840004 */   addiu     $a0, $a0, 0x4
    /* 15FE8 80061A08 00C01021 */  addu       $v0, $a2, $zero
  .L80061A0C:
    /* 15FEC 80061A0C 10400008 */  beqz       $v0, .L80061A30
    /* 15FF0 80061A10 24C6FFFF */   addiu     $a2, $a2, -0x1
  .L80061A14:
    /* 15FF4 80061A14 90A20000 */  lbu        $v0, 0x0($a1)
    /* 15FF8 80061A18 24A50001 */  addiu      $a1, $a1, 0x1
    /* 15FFC 80061A1C 00C01821 */  addu       $v1, $a2, $zero
    /* 16000 80061A20 24C6FFFF */  addiu      $a2, $a2, -0x1
    /* 16004 80061A24 A0820000 */  sb         $v0, 0x0($a0)
    /* 16008 80061A28 1460FFFA */  bnez       $v1, .L80061A14
    /* 1600C 80061A2C 24840001 */   addiu     $a0, $a0, 0x1
  .L80061A30:
    /* 16010 80061A30 03E00008 */  jr         $ra
    /* 16014 80061A34 00000000 */   nop
  .L80061A38:
    /* 16018 80061A38 1040FFFD */  beqz       $v0, .L80061A30
    /* 1601C 80061A3C 24C6FFFF */   addiu     $a2, $a2, -0x1
  .L80061A40:
    /* 16020 80061A40 90A20000 */  lbu        $v0, 0x0($a1)
    /* 16024 80061A44 24A50001 */  addiu      $a1, $a1, 0x1
    /* 16028 80061A48 00C01821 */  addu       $v1, $a2, $zero
    /* 1602C 80061A4C 24C6FFFF */  addiu      $a2, $a2, -0x1
    /* 16030 80061A50 A0820000 */  sb         $v0, 0x0($a0)
    /* 16034 80061A54 1460FFFA */  bnez       $v1, .L80061A40
    /* 16038 80061A58 24840001 */   addiu     $a0, $a0, 0x1
    /* 1603C 80061A5C 03E00008 */  jr         $ra
    /* 16040 80061A60 00000000 */   nop
  .L80061A64:
    /* 16044 80061A64 00822021 */  addu       $a0, $a0, $v0
    /* 16048 80061A68 00A22821 */  addu       $a1, $a1, $v0
    /* 1604C 80061A6C 00C01821 */  addu       $v1, $a2, $zero
    /* 16050 80061A70 1060FFEF */  beqz       $v1, .L80061A30
    /* 16054 80061A74 00403021 */   addu      $a2, $v0, $zero
  .L80061A78:
    /* 16058 80061A78 90A20000 */  lbu        $v0, 0x0($a1)
    /* 1605C 80061A7C 24A5FFFF */  addiu      $a1, $a1, -0x1
    /* 16060 80061A80 00C01821 */  addu       $v1, $a2, $zero
    /* 16064 80061A84 24C6FFFF */  addiu      $a2, $a2, -0x1
    /* 16068 80061A88 A0820000 */  sb         $v0, 0x0($a0)
    /* 1606C 80061A8C 1460FFFA */  bnez       $v1, .L80061A78
    /* 16070 80061A90 2484FFFF */   addiu     $a0, $a0, -0x1
    /* 16074 80061A94 03E00008 */  jr         $ra
    /* 16078 80061A98 00000000 */   nop
endlabel func_800619B0

nonmatching func_80061A9C, 0x2C

glabel func_80061A9C
    /* 1607C 80061A9C 00801021 */  addu       $v0, $a0, $zero
    /* 16080 80061AA0 00403821 */  addu       $a3, $v0, $zero
    /* 16084 80061AA4 10C00006 */  beqz       $a2, .L80061AC0
    /* 16088 80061AA8 24C3FFFF */   addiu     $v1, $a2, -0x1
    /* 1608C 80061AAC 2406FFFF */  addiu      $a2, $zero, -0x1
  .L80061AB0:
    /* 16090 80061AB0 A0E50000 */  sb         $a1, 0x0($a3)
    /* 16094 80061AB4 2463FFFF */  addiu      $v1, $v1, -0x1
    /* 16098 80061AB8 1466FFFD */  bne        $v1, $a2, .L80061AB0
    /* 1609C 80061ABC 24E70001 */   addiu     $a3, $a3, 0x1
  .L80061AC0:
    /* 160A0 80061AC0 03E00008 */  jr         $ra
    /* 160A4 80061AC4 00000000 */   nop
endlabel func_80061A9C

nonmatching func_80061AC8, 0x8

glabel func_80061AC8
    /* 160A8 80061AC8 080186B7 */  j          func_80061ADC
    /* 160AC 80061ACC 00C01021 */   addu      $v0, $a2, $zero
endlabel func_80061AC8

nonmatching func_80061AD0, 0x1C

glabel func_80061AD0
    /* 160B0 80061AD0 AC850000 */  sw         $a1, 0x0($a0)
    /* 160B4 80061AD4 24840004 */  addiu      $a0, $a0, 0x4
    /* 160B8 80061AD8 00C01021 */  addu       $v0, $a2, $zero
  alabel func_80061ADC
    /* 160BC 80061ADC 1440FFFC */  bnez       $v0, func_80061AD0
    /* 160C0 80061AE0 24C6FFFF */   addiu     $a2, $a2, -0x1
    /* 160C4 80061AE4 03E00008 */  jr         $ra
    /* 160C8 80061AE8 00000000 */   nop
endlabel func_80061AD0

nonmatching func_80061AEC, 0x8

glabel func_80061AEC
    /* 160CC 80061AEC 080186CA */  j          func_80061B28
    /* 160D0 80061AF0 00C01021 */   addu      $v0, $a2, $zero
endlabel func_80061AEC

nonmatching func_80061AF4, 0x44

glabel func_80061AF4
    /* 160D4 80061AF4 90870000 */  lbu        $a3, 0x0($a0)
    /* 160D8 80061AF8 90A30000 */  lbu        $v1, 0x0($a1)
    /* 160DC 80061AFC 00E3102B */  sltu       $v0, $a3, $v1
    /* 160E0 80061B00 10400003 */  beqz       $v0, .L80061B10
    /* 160E4 80061B04 0067102B */   sltu      $v0, $v1, $a3
    /* 160E8 80061B08 03E00008 */  jr         $ra
    /* 160EC 80061B0C 2402FFFF */   addiu     $v0, $zero, -0x1
  .L80061B10:
    /* 160F0 80061B10 10400003 */  beqz       $v0, .L80061B20
    /* 160F4 80061B14 24840001 */   addiu     $a0, $a0, 0x1
    /* 160F8 80061B18 03E00008 */  jr         $ra
    /* 160FC 80061B1C 24020001 */   addiu     $v0, $zero, 0x1
  .L80061B20:
    /* 16100 80061B20 24A50001 */  addiu      $a1, $a1, 0x1
    /* 16104 80061B24 00C01021 */  addu       $v0, $a2, $zero
  alabel func_80061B28
    /* 16108 80061B28 1440FFF2 */  bnez       $v0, func_80061AF4
    /* 1610C 80061B2C 24C6FFFF */   addiu     $a2, $a2, -0x1
    /* 16110 80061B30 03E00008 */  jr         $ra
    /* 16114 80061B34 00001021 */   addu      $v0, $zero, $zero
endlabel func_80061AF4

nonmatching func_80061B38, 0xB0

glabel func_80061B38
    /* 16118 80061B38 00806021 */  addu       $t4, $a0, $zero
    /* 1611C 80061B3C 00A06821 */  addu       $t5, $a1, $zero
    /* 16120 80061B40 00004021 */  addu       $t0, $zero, $zero
    /* 16124 80061B44 00004821 */  addu       $t1, $zero, $zero
    /* 16128 80061B48 01005021 */  addu       $t2, $t0, $zero
    /* 1612C 80061B4C 01205821 */  addu       $t3, $t1, $zero
    /* 16130 80061B50 240E0000 */  addiu      $t6, $zero, 0x0
    /* 16134 80061B54 240F0001 */  addiu      $t7, $zero, 0x1
    /* 16138 80061B58 2405003F */  addiu      $a1, $zero, 0x3F
    /* 1613C 80061B5C 000A5040 */  sll        $t2, $t2, 1
  .L80061B60:
    /* 16140 80061B60 000B17C2 */  srl        $v0, $t3, 31
    /* 16144 80061B64 01425025 */  or         $t2, $t2, $v0
    /* 16148 80061B68 000B5840 */  sll        $t3, $t3, 1
    /* 1614C 80061B6C 00084040 */  sll        $t0, $t0, 1
    /* 16150 80061B70 000917C2 */  srl        $v0, $t1, 31
    /* 16154 80061B74 01024025 */  or         $t0, $t0, $v0
    /* 16158 80061B78 00094840 */  sll        $t1, $t1, 1
    /* 1615C 80061B7C 000C1FC2 */  srl        $v1, $t4, 31
    /* 16160 80061B80 00001021 */  addu       $v0, $zero, $zero
    /* 16164 80061B84 01024025 */  or         $t0, $t0, $v0
    /* 16168 80061B88 01234825 */  or         $t1, $t1, $v1
    /* 1616C 80061B8C 000C6040 */  sll        $t4, $t4, 1
    /* 16170 80061B90 000D17C2 */  srl        $v0, $t5, 31
    /* 16174 80061B94 01826025 */  or         $t4, $t4, $v0
    /* 16178 80061B98 000D6840 */  sll        $t5, $t5, 1
    /* 1617C 80061B9C 0106102B */  sltu       $v0, $t0, $a2
    /* 16180 80061BA0 5440000C */  bnel       $v0, $zero, .L80061BD4
    /* 16184 80061BA4 24A5FFFF */   addiu     $a1, $a1, -0x1
    /* 16188 80061BA8 14C80004 */  bne        $a2, $t0, .L80061BBC
    /* 1618C 80061BAC 0127102B */   sltu      $v0, $t1, $a3
    /* 16190 80061BB0 54400008 */  bnel       $v0, $zero, .L80061BD4
    /* 16194 80061BB4 24A5FFFF */   addiu     $a1, $a1, -0x1
    /* 16198 80061BB8 0127102B */  sltu       $v0, $t1, $a3
  .L80061BBC:
    /* 1619C 80061BBC 01274823 */  subu       $t1, $t1, $a3
    /* 161A0 80061BC0 01064023 */  subu       $t0, $t0, $a2
    /* 161A4 80061BC4 01024023 */  subu       $t0, $t0, $v0
    /* 161A8 80061BC8 014E5025 */  or         $t2, $t2, $t6
    /* 161AC 80061BCC 016F5825 */  or         $t3, $t3, $t7
    /* 161B0 80061BD0 24A5FFFF */  addiu      $a1, $a1, -0x1
  .L80061BD4:
    /* 161B4 80061BD4 04A3FFE2 */  bgezl      $a1, .L80061B60
    /* 161B8 80061BD8 000A5040 */   sll       $t2, $t2, 1
    /* 161BC 80061BDC 01401021 */  addu       $v0, $t2, $zero
    /* 161C0 80061BE0 03E00008 */  jr         $ra
    /* 161C4 80061BE4 01601821 */   addu      $v1, $t3, $zero
endlabel func_80061B38

nonmatching func_80061BE8, 0x88

glabel func_80061BE8
    /* 161C8 80061BE8 00805021 */  addu       $t2, $a0, $zero
    /* 161CC 80061BEC 00A05821 */  addu       $t3, $a1, $zero
    /* 161D0 80061BF0 00004021 */  addu       $t0, $zero, $zero
    /* 161D4 80061BF4 00004821 */  addu       $t1, $zero, $zero
    /* 161D8 80061BF8 2405003F */  addiu      $a1, $zero, 0x3F
    /* 161DC 80061BFC 00084040 */  sll        $t0, $t0, 1
  .L80061C00:
    /* 161E0 80061C00 000917C2 */  srl        $v0, $t1, 31
    /* 161E4 80061C04 01024025 */  or         $t0, $t0, $v0
    /* 161E8 80061C08 00094840 */  sll        $t1, $t1, 1
    /* 161EC 80061C0C 000A1FC2 */  srl        $v1, $t2, 31
    /* 161F0 80061C10 00001021 */  addu       $v0, $zero, $zero
    /* 161F4 80061C14 01024025 */  or         $t0, $t0, $v0
    /* 161F8 80061C18 01234825 */  or         $t1, $t1, $v1
    /* 161FC 80061C1C 000A5040 */  sll        $t2, $t2, 1
    /* 16200 80061C20 000B17C2 */  srl        $v0, $t3, 31
    /* 16204 80061C24 01425025 */  or         $t2, $t2, $v0
    /* 16208 80061C28 000B5840 */  sll        $t3, $t3, 1
    /* 1620C 80061C2C 0106102B */  sltu       $v0, $t0, $a2
    /* 16210 80061C30 5440000A */  bnel       $v0, $zero, .L80061C5C
    /* 16214 80061C34 24A5FFFF */   addiu     $a1, $a1, -0x1
    /* 16218 80061C38 14C80004 */  bne        $a2, $t0, .L80061C4C
    /* 1621C 80061C3C 0127102B */   sltu      $v0, $t1, $a3
    /* 16220 80061C40 54400006 */  bnel       $v0, $zero, .L80061C5C
    /* 16224 80061C44 24A5FFFF */   addiu     $a1, $a1, -0x1
    /* 16228 80061C48 0127102B */  sltu       $v0, $t1, $a3
  .L80061C4C:
    /* 1622C 80061C4C 01274823 */  subu       $t1, $t1, $a3
    /* 16230 80061C50 01064023 */  subu       $t0, $t0, $a2
    /* 16234 80061C54 01024023 */  subu       $t0, $t0, $v0
    /* 16238 80061C58 24A5FFFF */  addiu      $a1, $a1, -0x1
  .L80061C5C:
    /* 1623C 80061C5C 04A3FFE8 */  bgezl      $a1, .L80061C00
    /* 16240 80061C60 00084040 */   sll       $t0, $t0, 1
    /* 16244 80061C64 01001021 */  addu       $v0, $t0, $zero
    /* 16248 80061C68 03E00008 */  jr         $ra
    /* 1624C 80061C6C 01201821 */   addu      $v1, $t1, $zero
endlabel func_80061BE8
