.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_8007EA18, 0x48

glabel func_8007EA18
    /* 32FF8 8007EA18 27BDFFD8 */  addiu      $sp, $sp, -0x28
    /* 32FFC 8007EA1C AFBF0014 */  sw         $ra, 0x14($sp)
    /* 33000 8007EA20 AFA5002C */  sw         $a1, 0x2C($sp)
    /* 33004 8007EA24 AFA60030 */  sw         $a2, 0x30($sp)
    /* 33008 8007EA28 00A03825 */  or         $a3, $a1, $zero
    /* 3300C 8007EA2C 00C04025 */  or         $t0, $a2, $zero
    /* 33010 8007EA30 240E000C */  addiu      $t6, $zero, 0xC
    /* 33014 8007EA34 A7AE0018 */  sh         $t6, 0x18($sp)
    /* 33018 8007EA38 A3A7001C */  sb         $a3, 0x1C($sp)
    /* 3301C 8007EA3C A3A8001D */  sb         $t0, 0x1D($sp)
    /* 33020 8007EA40 00003025 */  or         $a2, $zero, $zero
    /* 33024 8007EA44 27A50018 */  addiu      $a1, $sp, 0x18
    /* 33028 8007EA48 0C01F9CD */  jal        func_8007E734
    /* 3302C 8007EA4C 24840048 */   addiu     $a0, $a0, 0x48
    /* 33030 8007EA50 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 33034 8007EA54 27BD0028 */  addiu      $sp, $sp, 0x28
    /* 33038 8007EA58 03E00008 */  jr         $ra
    /* 3303C 8007EA5C 00000000 */   nop
endlabel func_8007EA18
    /* 33040 8007EA60 00000000 */  nop
    /* 33044 8007EA64 00000000 */  nop
