.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_8006CE9C, 0xFC

glabel func_8006CE9C
    /* 2147C 8006CE9C 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 21480 8006CEA0 00803021 */  addu       $a2, $a0, $zero
    /* 21484 8006CEA4 24020001 */  addiu      $v0, $zero, 0x1
    /* 21488 8006CEA8 3C038007 */  lui        $v1, %hi(D_800777C8)
    /* 2148C 8006CEAC 246377C8 */  addiu      $v1, $v1, %lo(D_800777C8)
    /* 21490 8006CEB0 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 21494 8006CEB4 AFB00010 */  sw         $s0, 0x10($sp)
    /* 21498 8006CEB8 ACC20010 */  sw         $v0, 0x10($a2)
    /* 2149C 8006CEBC 3C028007 */  lui        $v0, %hi(D_80077898)
    /* 214A0 8006CEC0 24427898 */  addiu      $v0, $v0, %lo(D_80077898)
    /* 214A4 8006CEC4 00431023 */  subu       $v0, $v0, $v1
    /* 214A8 8006CEC8 ACC2001C */  sw         $v0, 0x1C($a2)
    /* 214AC 8006CECC 3C028009 */  lui        $v0, %hi(D_80092B88)
    /* 214B0 8006CED0 8C422B88 */  lw         $v0, %lo(D_80092B88)($v0)
    /* 214B4 8006CED4 ACC30018 */  sw         $v1, 0x18($a2)
    /* 214B8 8006CED8 24C30058 */  addiu      $v1, $a2, 0x58
    /* 214BC 8006CEDC 30420004 */  andi       $v0, $v0, 0x4
    /* 214C0 8006CEE0 10400007 */  beqz       $v0, .L8006CF00
    /* 214C4 8006CEE4 ACC00014 */   sw        $zero, 0x14($a2)
    /* 214C8 8006CEE8 3C028007 */  lui        $v0, %hi(D_80077898)
    /* 214CC 8006CEEC 24427898 */  addiu      $v0, $v0, %lo(D_80077898)
    /* 214D0 8006CEF0 ACC20020 */  sw         $v0, 0x20($a2)
    /* 214D4 8006CEF4 3C028009 */  lui        $v0, %hi(D_80094250)
    /* 214D8 8006CEF8 0801B3C5 */  j          func_8006CF14
    /* 214DC 8006CEFC 24424250 */   addiu     $v0, $v0, %lo(D_80094250)
  .L8006CF00:
    /* 214E0 8006CF00 3C028008 */  lui        $v0, %hi(D_80078A28)
    /* 214E4 8006CF04 24428A28 */  addiu      $v0, $v0, %lo(D_80078A28)
    /* 214E8 8006CF08 ACC20020 */  sw         $v0, 0x20($a2)
    /* 214EC 8006CF0C 3C028009 */  lui        $v0, %hi(D_80094640)
    /* 214F0 8006CF10 24424640 */  addiu      $v0, $v0, %lo(D_80094640)
  alabel func_8006CF14
    /* 214F4 8006CF14 ACC20028 */  sw         $v0, 0x28($a2)
    /* 214F8 8006CF18 24D00010 */  addiu      $s0, $a2, 0x10
    /* 214FC 8006CF1C 02002021 */  addu       $a0, $s0, $zero
    /* 21500 8006CF20 24021000 */  addiu      $v0, $zero, 0x1000
    /* 21504 8006CF24 ACC20024 */  sw         $v0, 0x24($a2)
    /* 21508 8006CF28 24020800 */  addiu      $v0, $zero, 0x800
    /* 2150C 8006CF2C ACC2002C */  sw         $v0, 0x2C($a2)
    /* 21510 8006CF30 3C028019 */  lui        $v0, %hi(D_80190810)
    /* 21514 8006CF34 24420810 */  addiu      $v0, $v0, %lo(D_80190810)
    /* 21518 8006CF38 ACC20030 */  sw         $v0, 0x30($a2)
    /* 2151C 8006CF3C 24020400 */  addiu      $v0, $zero, 0x400
    /* 21520 8006CF40 ACC20034 */  sw         $v0, 0x34($a2)
    /* 21524 8006CF44 3C028019 */  lui        $v0, %hi(D_801928A0)
    /* 21528 8006CF48 244228A0 */  addiu      $v0, $v0, %lo(D_801928A0)
    /* 2152C 8006CF4C ACC20038 */  sw         $v0, 0x38($a2)
    /* 21530 8006CF50 3C02801A */  lui        $v0, %hi(D_801A28A0)
    /* 21534 8006CF54 244228A0 */  addiu      $v0, $v0, %lo(D_801A28A0)
    /* 21538 8006CF58 ACC2003C */  sw         $v0, 0x3C($a2)
    /* 2153C 8006CF5C 3C028017 */  lui        $v0, %hi(D_8016C5D0)
    /* 21540 8006CF60 2442C5D0 */  addiu      $v0, $v0, %lo(D_8016C5D0)
    /* 21544 8006CF64 ACC20048 */  sw         $v0, 0x48($a2)
    /* 21548 8006CF68 24020C00 */  addiu      $v0, $zero, 0xC00
    /* 2154C 8006CF6C ACC30040 */  sw         $v1, 0x40($a2)
    /* 21550 8006CF70 ACC50044 */  sw         $a1, 0x44($a2)
    /* 21554 8006CF74 0C021A91 */  jal        func_80086A44
    /* 21558 8006CF78 ACC2004C */   sw        $v0, 0x4C($a2)
    /* 2155C 8006CF7C 0C021AF5 */  jal        func_80086BD4
    /* 21560 8006CF80 02002021 */   addu      $a0, $s0, $zero
    /* 21564 8006CF84 02001021 */  addu       $v0, $s0, $zero
    /* 21568 8006CF88 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 2156C 8006CF8C 8FB00010 */  lw         $s0, 0x10($sp)
    /* 21570 8006CF90 03E00008 */  jr         $ra
    /* 21574 8006CF94 27BD0018 */   addiu     $sp, $sp, 0x18
endlabel func_8006CE9C
