.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_80071360, 0xA8

glabel func_80071360
    /* 25940 80071360 27BDFFD8 */  addiu      $sp, $sp, -0x28
    /* 25944 80071364 00802821 */  addu       $a1, $a0, $zero
    /* 25948 80071368 00001821 */  addu       $v1, $zero, $zero
    /* 2594C 8007136C AFBF0024 */  sw         $ra, 0x24($sp)
    /* 25950 80071370 18A0000D */  blez       $a1, .L800713A8
    /* 25954 80071374 AFB00020 */   sw        $s0, 0x20($sp)
    /* 25958 80071378 24070002 */  addiu      $a3, $zero, 0x2
    /* 2595C 8007137C 24060004 */  addiu      $a2, $zero, 0x4
    /* 25960 80071380 3C028019 */  lui        $v0, %hi(D_801887D0)
    /* 25964 80071384 244487D0 */  addiu      $a0, $v0, %lo(D_801887D0)
  .L80071388:
    /* 25968 80071388 8C82031C */  lw         $v0, 0x31C($a0)
    /* 2596C 8007138C 1047001A */  beq        $v0, $a3, func_800713F8
    /* 25970 80071390 00000000 */   nop
    /* 25974 80071394 10460018 */  beq        $v0, $a2, func_800713F8
    /* 25978 80071398 24630001 */   addiu     $v1, $v1, 0x1
    /* 2597C 8007139C 0065102A */  slt        $v0, $v1, $a1
    /* 25980 800713A0 1440FFF9 */  bnez       $v0, .L80071388
    /* 25984 800713A4 24840004 */   addiu     $a0, $a0, 0x4
  .L800713A8:
    /* 25988 800713A8 3C028019 */  lui        $v0, %hi(D_801887D0)
    /* 2598C 800713AC 245087D0 */  addiu      $s0, $v0, %lo(D_801887D0)
    /* 25990 800713B0 8E020170 */  lw         $v0, 0x170($s0)
    /* 25994 800713B4 10400009 */  beqz       $v0, .L800713DC
    /* 25998 800713B8 24040051 */   addiu     $a0, $zero, 0x51
    /* 2599C 800713BC 00003021 */  addu       $a2, $zero, $zero
    /* 259A0 800713C0 00C03821 */  addu       $a3, $a2, $zero
    /* 259A4 800713C4 AFA00010 */  sw         $zero, 0x10($sp)
    /* 259A8 800713C8 AFA00014 */  sw         $zero, 0x14($sp)
    /* 259AC 800713CC 0C01C3D4 */  jal        func_80070F50
    /* 259B0 800713D0 AFA00018 */   sw        $zero, 0x18($sp)
    /* 259B4 800713D4 0801C4FE */  j          func_800713F8
    /* 259B8 800713D8 AE000170 */   sw        $zero, 0x170($s0)
  .L800713DC:
    /* 259BC 800713DC 24040041 */  addiu      $a0, $zero, 0x41
    /* 259C0 800713E0 00003021 */  addu       $a2, $zero, $zero
    /* 259C4 800713E4 00C03821 */  addu       $a3, $a2, $zero
    /* 259C8 800713E8 AFA00010 */  sw         $zero, 0x10($sp)
    /* 259CC 800713EC AFA00014 */  sw         $zero, 0x14($sp)
    /* 259D0 800713F0 0C01C3D4 */  jal        func_80070F50
    /* 259D4 800713F4 AFA00018 */   sw        $zero, 0x18($sp)
  alabel func_800713F8
    /* 259D8 800713F8 8FBF0024 */  lw         $ra, 0x24($sp)
    /* 259DC 800713FC 8FB00020 */  lw         $s0, 0x20($sp)
    /* 259E0 80071400 03E00008 */  jr         $ra
    /* 259E4 80071404 27BD0028 */   addiu     $sp, $sp, 0x28
endlabel func_80071360
