.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */


glabel func_80081B58
    /* 36138 80081B58 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 3613C 80081B5C AFBF0014 */  sw         $ra, 0x14($sp)
    /* 36140 80081B60 8C8F0010 */  lw         $t7, 0x10($a0)
    /* 36144 80081B64 8C8E0000 */  lw         $t6, 0x0($a0)
    /* 36148 80081B68 8C820008 */  lw         $v0, 0x8($a0)
    /* 3614C 80081B6C 00803025 */  or         $a2, $a0, $zero
    /* 36150 80081B70 01CFC021 */  addu       $t8, $t6, $t7
    /* 36154 80081B74 0058082B */  sltu       $at, $v0, $t8
    /* 36158 80081B78 14200003 */  bnez       $at, .L80081B88
    /* 3615C 80081B7C 00A04025 */   or        $t0, $a1, $zero
    /* 36160 80081B80 10000007 */  b          .L80081BA0
    /* 36164 80081B84 00001025 */   or        $v0, $zero, $zero
  .L80081B88:
    /* 36168 80081B88 00403825 */  or         $a3, $v0, $zero
    /* 3616C 80081B8C 0C0205CC */  jal        func_80081730
    /* 36170 80081B90 00C02025 */   or        $a0, $a2, $zero
    /* 36174 80081B94 AD020000 */  sw         $v0, 0x0($t0)
    /* 36178 80081B98 ACC70008 */  sw         $a3, 0x8($a2)
    /* 3617C 80081B9C 24020001 */  addiu      $v0, $zero, 0x1
  .L80081BA0:
    /* 36180 80081BA0 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 36184 80081BA4 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 36188 80081BA8 03E00008 */  jr         $ra
    /* 3618C 80081BAC 00000000 */   nop
endlabel func_80081B58

nonmatching func_80081BB0, 0x50

glabel func_80081BB0
    /* 36190 80081BB0 8C850008 */  lw         $a1, 0x8($a0)
    /* 36194 80081BB4 90A30000 */  lbu        $v1, 0x0($a1)
    /* 36198 80081BB8 24AF0001 */  addiu      $t7, $a1, 0x1
    /* 3619C 80081BBC AC8F0008 */  sw         $t7, 0x8($a0)
    /* 361A0 80081BC0 91F80000 */  lbu        $t8, 0x0($t7)
    /* 361A4 80081BC4 00037600 */  sll        $t6, $v1, 24
    /* 361A8 80081BC8 0018CC00 */  sll        $t9, $t8, 16
    /* 361AC 80081BCC 01D91825 */  or         $v1, $t6, $t9
    /* 361B0 80081BD0 25EE0001 */  addiu      $t6, $t7, 0x1
    /* 361B4 80081BD4 AC8E0008 */  sw         $t6, 0x8($a0)
    /* 361B8 80081BD8 91CF0000 */  lbu        $t7, 0x0($t6)
    /* 361BC 80081BDC 25D90001 */  addiu      $t9, $t6, 0x1
    /* 361C0 80081BE0 AC990008 */  sw         $t9, 0x8($a0)
    /* 361C4 80081BE4 000FC200 */  sll        $t8, $t7, 8
    /* 361C8 80081BE8 932E0000 */  lbu        $t6, 0x0($t9)
    /* 361CC 80081BEC 00781825 */  or         $v1, $v1, $t8
    /* 361D0 80081BF0 272F0001 */  addiu      $t7, $t9, 0x1
    /* 361D4 80081BF4 AC8F0008 */  sw         $t7, 0x8($a0)
    /* 361D8 80081BF8 03E00008 */  jr         $ra
    /* 361DC 80081BFC 006E1025 */   or        $v0, $v1, $t6
endlabel func_80081BB0

nonmatching func_80081C00, 0x30

glabel func_80081C00
    /* 361E0 80081C00 8C850008 */  lw         $a1, 0x8($a0)
    /* 361E4 80081C04 90A30000 */  lbu        $v1, 0x0($a1)
    /* 361E8 80081C08 24B90001 */  addiu      $t9, $a1, 0x1
    /* 361EC 80081C0C AC990008 */  sw         $t9, 0x8($a0)
    /* 361F0 80081C10 932E0000 */  lbu        $t6, 0x0($t9)
    /* 361F4 80081C14 0003C200 */  sll        $t8, $v1, 8
    /* 361F8 80081C18 27390001 */  addiu      $t9, $t9, 0x1
    /* 361FC 80081C1C 030E1825 */  or         $v1, $t8, $t6
    /* 36200 80081C20 00037C00 */  sll        $t7, $v1, 16
    /* 36204 80081C24 000F1403 */  sra        $v0, $t7, 16
    /* 36208 80081C28 03E00008 */  jr         $ra
    /* 3620C 80081C2C AC990008 */   sw        $t9, 0x8($a0)
endlabel func_80081C00
