.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */


glabel func_80081C30
    /* 36210 80081C30 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 36214 80081C34 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 36218 80081C38 00803825 */  or         $a3, $a0, $zero
    /* 3621C 80081C3C AC850000 */  sw         $a1, 0x0($a0)
    /* 36220 80081C40 AC860010 */  sw         $a2, 0x10($a0)
    /* 36224 80081C44 A480001A */  sh         $zero, 0x1A($a0)
    /* 36228 80081C48 AC80000C */  sw         $zero, 0xC($a0)
    /* 3622C 80081C4C 0C0206EC */  jal        func_80081BB0
    /* 36230 80081C50 AC850008 */   sw        $a1, 0x8($a0)
    /* 36234 80081C54 3C014D54 */  lui        $at, (0x4D546864 >> 16)
    /* 36238 80081C58 34216864 */  ori        $at, $at, (0x4D546864 & 0xFFFF)
    /* 3623C 80081C5C 54410027 */  bnel       $v0, $at, .L80081CFC
    /* 36240 80081C60 8FBF0014 */   lw        $ra, 0x14($sp)
    /* 36244 80081C64 0C0206EC */  jal        func_80081BB0
    /* 36248 80081C68 00E02025 */   or        $a0, $a3, $zero
    /* 3624C 80081C6C 0C020700 */  jal        func_80081C00
    /* 36250 80081C70 00E02025 */   or        $a0, $a3, $zero
    /* 36254 80081C74 54400021 */  bnel       $v0, $zero, .L80081CFC
    /* 36258 80081C78 8FBF0014 */   lw        $ra, 0x14($sp)
    /* 3625C 80081C7C 0C020700 */  jal        func_80081C00
    /* 36260 80081C80 00E02025 */   or        $a0, $a3, $zero
    /* 36264 80081C84 24010001 */  addiu      $at, $zero, 0x1
    /* 36268 80081C88 5441001C */  bnel       $v0, $at, .L80081CFC
    /* 3626C 80081C8C 8FBF0014 */   lw        $ra, 0x14($sp)
    /* 36270 80081C90 0C020700 */  jal        func_80081C00
    /* 36274 80081C94 00E02025 */   or        $a0, $a3, $zero
    /* 36278 80081C98 A4E20018 */  sh         $v0, 0x18($a3)
    /* 3627C 80081C9C 84E30018 */  lh         $v1, 0x18($a3)
    /* 36280 80081CA0 306E8000 */  andi       $t6, $v1, 0x8000
    /* 36284 80081CA4 55C00015 */  bnel       $t6, $zero, .L80081CFC
    /* 36288 80081CA8 8FBF0014 */   lw        $ra, 0x14($sp)
    /* 3628C 80081CAC 44833000 */  mtc1       $v1, $ft1
    /* 36290 80081CB0 3C013FF0 */  lui        $at, (0x3FF00000 >> 16)
    /* 36294 80081CB4 44812800 */  mtc1       $at, $ft0f
    /* 36298 80081CB8 46803220 */  cvt.s.w    $ft2, $ft1
    /* 3629C 80081CBC 44802000 */  mtc1       $zero, $ft0
    /* 362A0 80081CC0 00E02025 */  or         $a0, $a3, $zero
    /* 362A4 80081CC4 460042A1 */  cvt.d.s    $ft3, $ft2
    /* 362A8 80081CC8 462A2183 */  div.d      $ft1, $ft0, $ft3
    /* 362AC 80081CCC 46203220 */  cvt.s.d    $ft2, $ft1
    /* 362B0 80081CD0 0C0206EC */  jal        func_80081BB0
    /* 362B4 80081CD4 E4E80014 */   swc1      $ft2, 0x14($a3)
    /* 362B8 80081CD8 3C014D54 */  lui        $at, (0x4D54726B >> 16)
    /* 362BC 80081CDC 3421726B */  ori        $at, $at, (0x4D54726B & 0xFFFF)
    /* 362C0 80081CE0 54410006 */  bnel       $v0, $at, .L80081CFC
    /* 362C4 80081CE4 8FBF0014 */   lw        $ra, 0x14($sp)
    /* 362C8 80081CE8 0C0206EC */  jal        func_80081BB0
    /* 362CC 80081CEC 00E02025 */   or        $a0, $a3, $zero
    /* 362D0 80081CF0 8CEF0008 */  lw         $t7, 0x8($a3)
    /* 362D4 80081CF4 ACEF0004 */  sw         $t7, 0x4($a3)
    /* 362D8 80081CF8 8FBF0014 */  lw         $ra, 0x14($sp)
  .L80081CFC:
    /* 362DC 80081CFC 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 362E0 80081D00 03E00008 */  jr         $ra
    /* 362E4 80081D04 00000000 */   nop
endlabel func_80081C30
