.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_8007E734, 0x124

glabel func_8007E734
    /* 32D14 8007E734 27BDFFD0 */  addiu      $sp, $sp, -0x30
    /* 32D18 8007E738 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 32D1C 8007E73C AFA40030 */  sw         $a0, 0x30($sp)
    /* 32D20 8007E740 AFA50034 */  sw         $a1, 0x34($sp)
    /* 32D24 8007E744 AFA00020 */  sw         $zero, 0x20($sp)
    /* 32D28 8007E748 24040001 */  addiu      $a0, $zero, 0x1
    /* 32D2C 8007E74C 0C01F1EA */  jal        func_8007C7A8
    /* 32D30 8007E750 AFA60038 */   sw        $a2, 0x38($sp)
    /* 32D34 8007E754 8FAE0030 */  lw         $t6, 0x30($sp)
    /* 32D38 8007E758 8FA70038 */  lw         $a3, 0x38($sp)
    /* 32D3C 8007E75C 00402825 */  or         $a1, $v0, $zero
    /* 32D40 8007E760 8DC80000 */  lw         $t0, 0x0($t6)
    /* 32D44 8007E764 15000005 */  bnez       $t0, .L8007E77C
    /* 32D48 8007E768 01002025 */   or        $a0, $t0, $zero
    /* 32D4C 8007E76C 0C01F1EA */  jal        func_8007C7A8
    /* 32D50 8007E770 00402025 */   or        $a0, $v0, $zero
    /* 32D54 8007E774 10000035 */  b          .L8007E84C
    /* 32D58 8007E778 8FBF0014 */   lw        $ra, 0x14($sp)
  .L8007E77C:
    /* 32D5C 8007E77C AFA5001C */  sw         $a1, 0x1C($sp)
    /* 32D60 8007E780 AFA70038 */  sw         $a3, 0x38($sp)
    /* 32D64 8007E784 0C01F686 */  jal        func_8007DA18
    /* 32D68 8007E788 AFA8002C */   sw        $t0, 0x2C($sp)
    /* 32D6C 8007E78C 8FA8002C */  lw         $t0, 0x2C($sp)
    /* 32D70 8007E790 8FA40034 */  lw         $a0, 0x34($sp)
    /* 32D74 8007E794 24060010 */  addiu      $a2, $zero, 0x10
    /* 32D78 8007E798 0C01FA56 */  jal        func_8007E958
    /* 32D7C 8007E79C 2505000C */   addiu     $a1, $t0, 0xC
    /* 32D80 8007E7A0 8FA70038 */  lw         $a3, 0x38($sp)
    /* 32D84 8007E7A4 3C017FFF */  lui        $at, (0x7FFFFFFF >> 16)
    /* 32D88 8007E7A8 3421FFFF */  ori        $at, $at, (0x7FFFFFFF & 0xFFFF)
    /* 32D8C 8007E7AC 14E10003 */  bne        $a3, $at, .L8007E7BC
    /* 32D90 8007E7B0 8FA8002C */   lw        $t0, 0x2C($sp)
    /* 32D94 8007E7B4 240FFFFF */  addiu      $t7, $zero, -0x1
    /* 32D98 8007E7B8 AFAF0020 */  sw         $t7, 0x20($sp)
  .L8007E7BC:
    /* 32D9C 8007E7BC 8FA20030 */  lw         $v0, 0x30($sp)
    /* 32DA0 8007E7C0 2401FFF8 */  addiu      $at, $zero, -0x8
    /* 32DA4 8007E7C4 8FB80020 */  lw         $t8, 0x20($sp)
    /* 32DA8 8007E7C8 1041001D */  beq        $v0, $at, .L8007E840
    /* 32DAC 8007E7CC 24450008 */   addiu     $a1, $v0, 0x8
  .L8007E7D0:
    /* 32DB0 8007E7D0 8CA20000 */  lw         $v0, 0x0($a1)
    /* 32DB4 8007E7D4 5440000B */  bnel       $v0, $zero, .L8007E804
    /* 32DB8 8007E7D8 8C430008 */   lw        $v1, 0x8($v0)
    /* 32DBC 8007E7DC 53000004 */  beql       $t8, $zero, .L8007E7F0
    /* 32DC0 8007E7E0 AD070008 */   sw        $a3, 0x8($t0)
    /* 32DC4 8007E7E4 10000002 */  b          .L8007E7F0
    /* 32DC8 8007E7E8 AD000008 */   sw        $zero, 0x8($t0)
    /* 32DCC 8007E7EC AD070008 */  sw         $a3, 0x8($t0)
  .L8007E7F0:
    /* 32DD0 8007E7F0 0C01F692 */  jal        func_8007DA48
    /* 32DD4 8007E7F4 01002025 */   or        $a0, $t0, $zero
    /* 32DD8 8007E7F8 10000011 */  b          .L8007E840
    /* 32DDC 8007E7FC 00000000 */   nop
    /* 32DE0 8007E800 8C430008 */  lw         $v1, 0x8($v0)
  .L8007E804:
    /* 32DE4 8007E804 00403025 */  or         $a2, $v0, $zero
    /* 32DE8 8007E808 00E3082A */  slt        $at, $a3, $v1
    /* 32DEC 8007E80C 5020000A */  beql       $at, $zero, .L8007E838
    /* 32DF0 8007E810 00402825 */   or        $a1, $v0, $zero
    /* 32DF4 8007E814 AD070008 */  sw         $a3, 0x8($t0)
    /* 32DF8 8007E818 8CD90008 */  lw         $t9, 0x8($a2)
    /* 32DFC 8007E81C 01002025 */  or         $a0, $t0, $zero
    /* 32E00 8007E820 03274823 */  subu       $t1, $t9, $a3
    /* 32E04 8007E824 0C01F692 */  jal        func_8007DA48
    /* 32E08 8007E828 ACC90008 */   sw        $t1, 0x8($a2)
    /* 32E0C 8007E82C 10000004 */  b          .L8007E840
    /* 32E10 8007E830 00000000 */   nop
    /* 32E14 8007E834 00402825 */  or         $a1, $v0, $zero
  .L8007E838:
    /* 32E18 8007E838 1440FFE5 */  bnez       $v0, .L8007E7D0
    /* 32E1C 8007E83C 00E33823 */   subu      $a3, $a3, $v1
  .L8007E840:
    /* 32E20 8007E840 0C01F1EA */  jal        func_8007C7A8
    /* 32E24 8007E844 8FA4001C */   lw        $a0, 0x1C($sp)
    /* 32E28 8007E848 8FBF0014 */  lw         $ra, 0x14($sp)
  .L8007E84C:
    /* 32E2C 8007E84C 27BD0030 */  addiu      $sp, $sp, 0x30
    /* 32E30 8007E850 03E00008 */  jr         $ra
    /* 32E34 8007E854 00000000 */   nop
endlabel func_8007E734
