.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_8005C8B8, 0x1C

glabel func_8005C8B8
    /* 10E98 8005C8B8 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 10E9C 8005C8BC AFBF0010 */  sw         $ra, 0x10($sp)
    /* 10EA0 8005C8C0 0C017223 */  jal        func_8005C88C
    /* 10EA4 8005C8C4 2404FFFF */   addiu     $a0, $zero, -0x1
    /* 10EA8 8005C8C8 8FBF0010 */  lw         $ra, 0x10($sp)
    /* 10EAC 8005C8CC 03E00008 */  jr         $ra
    /* 10EB0 8005C8D0 27BD0018 */   addiu     $sp, $sp, 0x18
endlabel func_8005C8B8

nonmatching func_8005C8D4, 0x18

glabel func_8005C8D4
    /* 10EB4 8005C8D4 3C028009 */  lui        $v0, %hi(D_80092804)
    /* 10EB8 8005C8D8 3C038009 */  lui        $v1, %hi(D_80092824)
    /* 10EBC 8005C8DC AC442804 */  sw         $a0, %lo(D_80092804)($v0)
    /* 10EC0 8005C8E0 24020001 */  addiu      $v0, $zero, 0x1
    /* 10EC4 8005C8E4 03E00008 */  jr         $ra
    /* 10EC8 8005C8E8 AC622824 */   sw        $v0, %lo(D_80092824)($v1)
endlabel func_8005C8D4

nonmatching func_8005C8EC, 0xC8

glabel func_8005C8EC
    /* 10ECC 8005C8EC 3C078009 */  lui        $a3, %hi(D_80092818)
    /* 10ED0 8005C8F0 3C030001 */  lui        $v1, (0x10000 >> 16)
    /* 10ED4 8005C8F4 ACE32818 */  sw         $v1, %lo(D_80092818)($a3)
    /* 10ED8 8005C8F8 0064302A */  slt        $a2, $v1, $a0
    /* 10EDC 8005C8FC 10C00002 */  beqz       $a2, .L8005C908
    /* 10EE0 8005C900 00801021 */   addu      $v0, $a0, $zero
    /* 10EE4 8005C904 00601021 */  addu       $v0, $v1, $zero
  .L8005C908:
    /* 10EE8 8005C908 28420002 */  slti       $v0, $v0, 0x2
    /* 10EEC 8005C90C 54400010 */  bnel       $v0, $zero, .L8005C950
    /* 10EF0 8005C910 3C068009 */   lui       $a2, %hi(D_8009281C)
    /* 10EF4 8005C914 54C00001 */  bnel       $a2, $zero, .L8005C91C
    /* 10EF8 8005C918 3C040001 */   lui       $a0, (0x10000 >> 16)
  .L8005C91C:
    /* 10EFC 8005C91C 0064001A */  div        $zero, $v1, $a0
    /* 10F00 8005C920 14800002 */  bnez       $a0, .L8005C92C
    /* 10F04 8005C924 00000000 */   nop
    /* 10F08 8005C928 0007000D */  break      7
  .L8005C92C:
    /* 10F0C 8005C92C 2401FFFF */  addiu      $at, $zero, -0x1
    /* 10F10 8005C930 14810004 */  bne        $a0, $at, .L8005C944
    /* 10F14 8005C934 3C018000 */   lui       $at, (0x80000000 >> 16)
    /* 10F18 8005C938 14610002 */  bne        $v1, $at, .L8005C944
    /* 10F1C 8005C93C 00000000 */   nop
    /* 10F20 8005C940 0006000D */  break      6
  .L8005C944:
    /* 10F24 8005C944 00001012 */  mflo       $v0
    /* 10F28 8005C948 ACE22818 */  sw         $v0, %lo(D_80092818)($a3)
    /* 10F2C 8005C94C 3C068009 */  lui        $a2, %hi(D_8009281C)
  .L8005C950:
    /* 10F30 8005C950 3C030001 */  lui        $v1, (0x10000 >> 16)
    /* 10F34 8005C954 ACC3281C */  sw         $v1, %lo(D_8009281C)($a2)
    /* 10F38 8005C958 0065202A */  slt        $a0, $v1, $a1
    /* 10F3C 8005C95C 10800002 */  beqz       $a0, .L8005C968
    /* 10F40 8005C960 00A01021 */   addu      $v0, $a1, $zero
    /* 10F44 8005C964 00601021 */  addu       $v0, $v1, $zero
  .L8005C968:
    /* 10F48 8005C968 28420002 */  slti       $v0, $v0, 0x2
    /* 10F4C 8005C96C 1440000F */  bnez       $v0, .L8005C9AC
    /* 10F50 8005C970 00000000 */   nop
    /* 10F54 8005C974 54800001 */  bnel       $a0, $zero, .L8005C97C
    /* 10F58 8005C978 3C050001 */   lui       $a1, (0x10000 >> 16)
  .L8005C97C:
    /* 10F5C 8005C97C 0065001A */  div        $zero, $v1, $a1
    /* 10F60 8005C980 14A00002 */  bnez       $a1, .L8005C98C
    /* 10F64 8005C984 00000000 */   nop
    /* 10F68 8005C988 0007000D */  break      7
  .L8005C98C:
    /* 10F6C 8005C98C 2401FFFF */  addiu      $at, $zero, -0x1
    /* 10F70 8005C990 14A10004 */  bne        $a1, $at, .L8005C9A4
    /* 10F74 8005C994 3C018000 */   lui       $at, (0x80000000 >> 16)
    /* 10F78 8005C998 14610002 */  bne        $v1, $at, .L8005C9A4
    /* 10F7C 8005C99C 00000000 */   nop
    /* 10F80 8005C9A0 0006000D */  break      6
  .L8005C9A4:
    /* 10F84 8005C9A4 00001012 */  mflo       $v0
    /* 10F88 8005C9A8 ACC2281C */  sw         $v0, %lo(D_8009281C)($a2)
  .L8005C9AC:
    /* 10F8C 8005C9AC 03E00008 */  jr         $ra
    /* 10F90 8005C9B0 00000000 */   nop
endlabel func_8005C8EC

nonmatching func_8005C9B4, 0x8

glabel func_8005C9B4
    /* 10F94 8005C9B4 3C028009 */  lui        $v0, %hi(D_80092800)
    /* 10F98 8005C9B8 8C432800 */  lw         $v1, %lo(D_80092800)($v0)
endlabel func_8005C9B4
