.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_80075B78, 0xB8

glabel func_80075B78
    /* 2A158 80075B78 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* 2A15C 80075B7C AFB00010 */  sw         $s0, 0x10($sp)
    /* 2A160 80075B80 00808021 */  addu       $s0, $a0, $zero
    /* 2A164 80075B84 3C04B1FF */  lui        $a0, (0xB1FFFFE4 >> 16)
    /* 2A168 80075B88 3484FFE4 */  ori        $a0, $a0, (0xB1FFFFE4 & 0xFFFF)
    /* 2A16C 80075B8C AFB10014 */  sw         $s1, 0x14($sp)
    /* 2A170 80075B90 00C08821 */  addu       $s1, $a2, $zero
    /* 2A174 80075B94 AFB20018 */  sw         $s2, 0x18($sp)
    /* 2A178 80075B98 AFBF001C */  sw         $ra, 0x1C($sp)
    /* 2A17C 80075B9C 0C01D3C2 */  jal        func_80074F08
    /* 2A180 80075BA0 00E09021 */   addu      $s2, $a3, $zero
    /* 2A184 80075BA4 3C04B1FF */  lui        $a0, (0xB1FFFFE8 >> 16)
    /* 2A188 80075BA8 3484FFE8 */  ori        $a0, $a0, (0xB1FFFFE8 & 0xFFFF)
    /* 2A18C 80075BAC 0C01D3C2 */  jal        func_80074F08
    /* 2A190 80075BB0 02202821 */   addu      $a1, $s1, $zero
    /* 2A194 80075BB4 3C04B1FF */  lui        $a0, (0xB1FFFFEC >> 16)
    /* 2A198 80075BB8 3484FFEC */  ori        $a0, $a0, (0xB1FFFFEC & 0xFFFF)
    /* 2A19C 80075BBC 0C01D3C2 */  jal        func_80074F08
    /* 2A1A0 80075BC0 02402821 */   addu      $a1, $s2, $zero
    /* 2A1A4 80075BC4 3C04B1FF */  lui        $a0, (0xB1FFFFE0 >> 16)
    /* 2A1A8 80075BC8 3484FFE0 */  ori        $a0, $a0, (0xB1FFFFE0 & 0xFFFF)
    /* 2A1AC 80075BCC 0C01D3C2 */  jal        func_80074F08
    /* 2A1B0 80075BD0 02002821 */   addu      $a1, $s0, $zero
  .L80075BD4:
    /* 2A1B4 80075BD4 0C01D3DF */  jal        func_80074F7C
    /* 2A1B8 80075BD8 240403E8 */   addiu     $a0, $zero, 0x3E8
    /* 2A1BC 80075BDC 3C04B1FF */  lui        $a0, (0xB1FFFFF0 >> 16)
    /* 2A1C0 80075BE0 0C01D3D0 */  jal        func_80074F40
    /* 2A1C4 80075BE4 3484FFF0 */   ori       $a0, $a0, (0xB1FFFFF0 & 0xFFFF)
    /* 2A1C8 80075BE8 50400003 */  beql       $v0, $zero, .L80075BF8
    /* 2A1CC 80075BEC 3C04B1FF */   lui       $a0, (0xB1FFFFE0 >> 16)
    /* 2A1D0 80075BF0 0001000D */  break      1
    /* 2A1D4 80075BF4 3C04B1FF */  lui        $a0, (0xB1FFFFE0 >> 16)
  .L80075BF8:
    /* 2A1D8 80075BF8 0C01D3D0 */  jal        func_80074F40
    /* 2A1DC 80075BFC 3484FFE0 */   ori       $a0, $a0, (0xB1FFFFE0 & 0xFFFF)
    /* 2A1E0 80075C00 1440FFF4 */  bnez       $v0, .L80075BD4
    /* 2A1E4 80075C04 00000000 */   nop
    /* 2A1E8 80075C08 3C04B1FF */  lui        $a0, (0xB1FFFFDC >> 16)
    /* 2A1EC 80075C0C 0C01D3D0 */  jal        func_80074F40
    /* 2A1F0 80075C10 3484FFDC */   ori       $a0, $a0, (0xB1FFFFDC & 0xFFFF)
    /* 2A1F4 80075C14 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 2A1F8 80075C18 8FB20018 */  lw         $s2, 0x18($sp)
    /* 2A1FC 80075C1C 8FB10014 */  lw         $s1, 0x14($sp)
    /* 2A200 80075C20 8FB00010 */  lw         $s0, 0x10($sp)
    /* 2A204 80075C24 27BD0020 */  addiu      $sp, $sp, 0x20
    /* 2A208 80075C28 03E00008 */  jr         $ra
    /* 2A20C 80075C2C 00000000 */   nop
endlabel func_80075B78
