.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_8008B4EC, 0xC8

glabel func_8008B4EC
    /* 3FACC 8008B4EC 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 3FAD0 8008B4F0 3C0E8019 */  lui        $t6, %hi(D_8018ADB8)
    /* 3FAD4 8008B4F4 25CEADB8 */  addiu      $t6, $t6, %lo(D_8018ADB8)
    /* 3FAD8 8008B4F8 A3A00007 */  sb         $zero, 0x7($sp)
    /* 3FADC 8008B4FC AFAE0014 */  sw         $t6, 0x14($sp)
    /* 3FAE0 8008B500 19E00028 */  blez       $t7, .L8008B5A4
    /* 3FAE4 8008B504 AFA00008 */   sw        $zero, 0x8($sp)
  .L8008B508:
    /* 3FAE8 8008B508 8FB90014 */  lw         $t9, 0x14($sp)
    /* 3FAEC 8008B50C 27B8000C */  addiu      $t8, $sp, 0xC
    /* 3FAF0 8008B510 8B210000 */  lwl        $at, 0x0($t9)
    /* 3FAF4 8008B514 9B210003 */  lwr        $at, 0x3($t9)
    /* 3FAF8 8008B518 AF010000 */  sw         $at, 0x0($t8)
    /* 3FAFC 8008B51C 8B290004 */  lwl        $t1, 0x4($t9)
    /* 3FB00 8008B520 9B290007 */  lwr        $t1, 0x7($t9)
    /* 3FB04 8008B524 AF090004 */  sw         $t1, 0x4($t8)
    /* 3FB08 8008B528 93AA000E */  lbu        $t2, 0xE($sp)
    /* 3FB0C 8008B52C 314B00C0 */  andi       $t3, $t2, 0xC0
    /* 3FB10 8008B530 000B6103 */  sra        $t4, $t3, 4
    /* 3FB14 8008B534 A0AC0003 */  sb         $t4, 0x3($a1)
    /* 3FB18 8008B538 90AD0003 */  lbu        $t5, 0x3($a1)
    /* 3FB1C 8008B53C 15A0000E */  bnez       $t5, .L8008B578
    /* 3FB20 8008B540 00000000 */   nop
    /* 3FB24 8008B544 93AE0011 */  lbu        $t6, 0x11($sp)
    /* 3FB28 8008B548 93A80010 */  lbu        $t0, 0x10($sp)
    /* 3FB2C 8008B54C 240B0001 */  addiu      $t3, $zero, 0x1
    /* 3FB30 8008B550 000E7A00 */  sll        $t7, $t6, 8
    /* 3FB34 8008B554 01E8C025 */  or         $t8, $t7, $t0
    /* 3FB38 8008B558 A4B80000 */  sh         $t8, 0x0($a1)
    /* 3FB3C 8008B55C 93B90012 */  lbu        $t9, 0x12($sp)
    /* 3FB40 8008B560 A0B90002 */  sb         $t9, 0x2($a1)
    /* 3FB44 8008B564 8FAA0008 */  lw         $t2, 0x8($sp)
    /* 3FB48 8008B568 93A90007 */  lbu        $t1, 0x7($sp)
    /* 3FB4C 8008B56C 014B6004 */  sllv       $t4, $t3, $t2
    /* 3FB50 8008B570 012C6825 */  or         $t5, $t1, $t4
    /* 3FB54 8008B574 A3AD0007 */  sb         $t5, 0x7($sp)
  .L8008B578:
    /* 3FB58 8008B578 8FAE0008 */  lw         $t6, 0x8($sp)
    /* 3FB5C 8008B57C 3C198019 */  lui        $t9, %hi(D_8018AD69)
    /* 3FB60 8008B580 9339AD69 */  lbu        $t9, %lo(D_8018AD69)($t9)
    /* 3FB64 8008B584 8FA80014 */  lw         $t0, 0x14($sp)
    /* 3FB68 8008B588 25CF0001 */  addiu      $t7, $t6, 0x1
    /* 3FB6C 8008B58C 01F9082A */  slt        $at, $t7, $t9
    /* 3FB70 8008B590 25180008 */  addiu      $t8, $t0, 0x8
    /* 3FB74 8008B594 AFB80014 */  sw         $t8, 0x14($sp)
    /* 3FB78 8008B598 AFAF0008 */  sw         $t7, 0x8($sp)
    /* 3FB7C 8008B59C 1420FFDA */  bnez       $at, .L8008B508
    /* 3FB80 8008B5A0 24A50004 */   addiu     $a1, $a1, 0x4
  .L8008B5A4:
    /* 3FB84 8008B5A4 93AB0007 */  lbu        $t3, 0x7($sp)
    /* 3FB88 8008B5A8 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 3FB8C 8008B5AC 03E00008 */  jr         $ra
    /* 3FB90 8008B5B0 A08B0000 */   sb        $t3, 0x0($a0)
endlabel func_8008B4EC
    /* 3FB94 8008B5B4 00000000 */  nop
