.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_80070B24, 0xA8

glabel func_80070B24
    /* 25104 80070B24 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* 25108 80070B28 3C028019 */  lui        $v0, %hi(D_80188770)
    /* 2510C 80070B2C AC448770 */  sw         $a0, %lo(D_80188770)($v0)
    /* 25110 80070B30 3C048019 */  lui        $a0, %hi(D_801887A0)
    /* 25114 80070B34 248487A0 */  addiu      $a0, $a0, %lo(D_801887A0)
    /* 25118 80070B38 3C058019 */  lui        $a1, %hi(D_80188780)
    /* 2511C 80070B3C 24A58780 */  addiu      $a1, $a1, %lo(D_80188780)
    /* 25120 80070B40 24060008 */  addiu      $a2, $zero, 0x8
    /* 25124 80070B44 AFBF001C */  sw         $ra, 0x1C($sp)
    /* 25128 80070B48 0C01EF36 */  jal        func_8007BCD8
    /* 2512C 80070B4C AFB00018 */   sw        $s0, 0x18($sp)
    /* 25130 80070B50 3C048019 */  lui        $a0, %hi(D_801887B8)
    /* 25134 80070B54 248487B8 */  addiu      $a0, $a0, %lo(D_801887B8)
    /* 25138 80070B58 3C058019 */  lui        $a1, %hi(D_80188774)
    /* 2513C 80070B5C 24A58774 */  addiu      $a1, $a1, %lo(D_80188774)
    /* 25140 80070B60 0C01EF36 */  jal        func_8007BCD8
    /* 25144 80070B64 24060001 */   addiu     $a2, $zero, 0x1
    /* 25148 80070B68 3C108018 */  lui        $s0, %hi(D_801875C0)
    /* 2514C 80070B6C 261075C0 */  addiu      $s0, $s0, %lo(D_801875C0)
    /* 25150 80070B70 02002021 */  addu       $a0, $s0, $zero
    /* 25154 80070B74 24050005 */  addiu      $a1, $zero, 0x5
    /* 25158 80070B78 3C068007 */  lui        $a2, %hi(func_80070B0C)
    /* 2515C 80070B7C 24C60B0C */  addiu      $a2, $a2, %lo(func_80070B0C)
    /* 25160 80070B80 3C028019 */  lui        $v0, %hi(D_80188770)
    /* 25164 80070B84 24428770 */  addiu      $v0, $v0, %lo(D_80188770)
    /* 25168 80070B88 AFA20010 */  sw         $v0, 0x10($sp)
    /* 2516C 80070B8C 00A01021 */  addu       $v0, $a1, $zero
    /* 25170 80070B90 00003821 */  addu       $a3, $zero, $zero
    /* 25174 80070B94 0C01EF42 */  jal        func_8007BD08
    /* 25178 80070B98 AFA20014 */   sw        $v0, 0x14($sp)
    /* 2517C 80070B9C 02002021 */  addu       $a0, $s0, $zero
    /* 25180 80070BA0 3C028019 */  lui        $v0, %hi(D_801887D0)
    /* 25184 80070BA4 244287D0 */  addiu      $v0, $v0, %lo(D_801887D0)
    /* 25188 80070BA8 24030001 */  addiu      $v1, $zero, 0x1
    /* 2518C 80070BAC AC43016C */  sw         $v1, 0x16C($v0)
    /* 25190 80070BB0 2403FFFF */  addiu      $v1, $zero, -0x1
    /* 25194 80070BB4 0C01F43A */  jal        func_8007D0E8
    /* 25198 80070BB8 AC430160 */   sw        $v1, 0x160($v0)
    /* 2519C 80070BBC 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 251A0 80070BC0 8FB00018 */  lw         $s0, 0x18($sp)
    /* 251A4 80070BC4 03E00008 */  jr         $ra
    /* 251A8 80070BC8 27BD0020 */   addiu     $sp, $sp, 0x20
endlabel func_80070B24
