.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_80086C98, 0x8C

glabel func_80086C98
    /* 3B278 80086C98 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 3B27C 80086C9C AFBF0014 */  sw         $ra, 0x14($sp)
    /* 3B280 80086CA0 AFA40018 */  sw         $a0, 0x18($sp)
    /* 3B284 80086CA4 AFA5001C */  sw         $a1, 0x1C($sp)
    /* 3B288 80086CA8 AFA60020 */  sw         $a2, 0x20($sp)
    /* 3B28C 80086CAC 0C021B06 */  jal        func_80086C18
    /* 3B290 80086CB0 AFA70024 */   sw        $a3, 0x24($sp)
    /* 3B294 80086CB4 10400003 */  beqz       $v0, .L80086CC4
    /* 3B298 80086CB8 00000000 */   nop
    /* 3B29C 80086CBC 10000015 */  b          .L80086D14
    /* 3B2A0 80086CC0 2402FFFF */   addiu     $v0, $zero, -0x1
  .L80086CC4:
    /* 3B2A4 80086CC4 8FAE001C */  lw         $t6, 0x1C($sp)
    /* 3B2A8 80086CC8 3C0FA404 */  lui        $t7, %hi(D_A4040000)
    /* 3B2AC 80086CCC ADEE0000 */  sw         $t6, %lo(D_A4040000)($t7)
    /* 3B2B0 80086CD0 0C01F5A2 */  jal        func_8007D688
    /* 3B2B4 80086CD4 8FA40020 */   lw        $a0, 0x20($sp)
    /* 3B2B8 80086CD8 3C18A404 */  lui        $t8, %hi(D_A4040004)
    /* 3B2BC 80086CDC AF020004 */  sw         $v0, %lo(D_A4040004)($t8)
    /* 3B2C0 80086CE0 8FB90018 */  lw         $t9, 0x18($sp)
    /* 3B2C4 80086CE4 17200006 */  bnez       $t9, .L80086D00
    /* 3B2C8 80086CE8 00000000 */   nop
    /* 3B2CC 80086CEC 8FA80024 */  lw         $t0, 0x24($sp)
    /* 3B2D0 80086CF0 3C0AA404 */  lui        $t2, %hi(D_A404000C)
    /* 3B2D4 80086CF4 2509FFFF */  addiu      $t1, $t0, -0x1
    /* 3B2D8 80086CF8 10000005 */  b          .L80086D10
    /* 3B2DC 80086CFC AD49000C */   sw        $t1, %lo(D_A404000C)($t2)
  .L80086D00:
    /* 3B2E0 80086D00 8FAB0024 */  lw         $t3, 0x24($sp)
    /* 3B2E4 80086D04 3C0DA404 */  lui        $t5, %hi(D_A4040008)
    /* 3B2E8 80086D08 256CFFFF */  addiu      $t4, $t3, -0x1
    /* 3B2EC 80086D0C ADAC0008 */  sw         $t4, %lo(D_A4040008)($t5)
  .L80086D10:
    /* 3B2F0 80086D10 00001025 */  or         $v0, $zero, $zero
  .L80086D14:
    /* 3B2F4 80086D14 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 3B2F8 80086D18 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 3B2FC 80086D1C 03E00008 */  jr         $ra
    /* 3B300 80086D20 00000000 */   nop
endlabel func_80086C98
    /* 3B304 80086D24 00000000 */  nop
