.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_8008D0A8, 0xE0

glabel func_8008D0A8
    /* 41688 8008D0A8 27BDFFD8 */  addiu      $sp, $sp, -0x28
    /* 4168C 8008D0AC AFBF001C */  sw         $ra, 0x1C($sp)
    /* 41690 8008D0B0 AFA40028 */  sw         $a0, 0x28($sp)
    /* 41694 8008D0B4 AFA5002C */  sw         $a1, 0x2C($sp)
    /* 41698 8008D0B8 AFA60030 */  sw         $a2, 0x30($sp)
    /* 4169C 8008D0BC AFA70034 */  sw         $a3, 0x34($sp)
    /* 416A0 8008D0C0 AFB10018 */  sw         $s1, 0x18($sp)
    /* 416A4 8008D0C4 AFB00014 */  sw         $s0, 0x14($sp)
    /* 416A8 8008D0C8 3C0EA460 */  lui        $t6, %hi(D_A4600010)
    /* 416AC 8008D0CC 8DD00010 */  lw         $s0, %lo(D_A4600010)($t6)
    /* 416B0 8008D0D0 320F0003 */  andi       $t7, $s0, 0x3
    /* 416B4 8008D0D4 11E00006 */  beqz       $t7, .L8008D0F0
    /* 416B8 8008D0D8 00000000 */   nop
  .L8008D0DC:
    /* 416BC 8008D0DC 3C18A460 */  lui        $t8, %hi(D_A4600010)
    /* 416C0 8008D0E0 8F100010 */  lw         $s0, %lo(D_A4600010)($t8)
    /* 416C4 8008D0E4 32190003 */  andi       $t9, $s0, 0x3
    /* 416C8 8008D0E8 1720FFFC */  bnez       $t9, .L8008D0DC
    /* 416CC 8008D0EC 00000000 */   nop
  .L8008D0F0:
    /* 416D0 8008D0F0 0C01F5A2 */  jal        func_8007D688
    /* 416D4 8008D0F4 8FA40030 */   lw        $a0, 0x30($sp)
    /* 416D8 8008D0F8 3C08A460 */  lui        $t0, %hi(D_A4600000)
    /* 416DC 8008D0FC AD020000 */  sw         $v0, %lo(D_A4600000)($t0)
    /* 416E0 8008D100 3C098000 */  lui        $t1, %hi(D_80000308)
    /* 416E4 8008D104 8D290308 */  lw         $t1, %lo(D_80000308)($t1)
    /* 416E8 8008D108 8FAA002C */  lw         $t2, 0x2C($sp)
    /* 416EC 8008D10C 3C011FFF */  lui        $at, (0x1FFFFFFF >> 16)
    /* 416F0 8008D110 3421FFFF */  ori        $at, $at, (0x1FFFFFFF & 0xFFFF)
    /* 416F4 8008D114 012A5825 */  or         $t3, $t1, $t2
    /* 416F8 8008D118 01616024 */  and        $t4, $t3, $at
    /* 416FC 8008D11C 3C0DA460 */  lui        $t5, %hi(D_A4600004)
    /* 41700 8008D120 ADAC0004 */  sw         $t4, %lo(D_A4600004)($t5)
    /* 41704 8008D124 8FB10028 */  lw         $s1, 0x28($sp)
    /* 41708 8008D128 12200005 */  beqz       $s1, .L8008D140
    /* 4170C 8008D12C 24010001 */   addiu     $at, $zero, 0x1
    /* 41710 8008D130 12210008 */  beq        $s1, $at, .L8008D154
    /* 41714 8008D134 00000000 */   nop
    /* 41718 8008D138 1000000B */  b          .L8008D168
    /* 4171C 8008D13C 00000000 */   nop
  .L8008D140:
    /* 41720 8008D140 8FAE0034 */  lw         $t6, 0x34($sp)
    /* 41724 8008D144 3C18A460 */  lui        $t8, %hi(D_A460000C)
    /* 41728 8008D148 25CFFFFF */  addiu      $t7, $t6, -0x1
    /* 4172C 8008D14C 10000008 */  b          .L8008D170
    /* 41730 8008D150 AF0F000C */   sw        $t7, %lo(D_A460000C)($t8)
  .L8008D154:
    /* 41734 8008D154 8FB90034 */  lw         $t9, 0x34($sp)
    /* 41738 8008D158 3C09A460 */  lui        $t1, %hi(D_A4600008)
    /* 4173C 8008D15C 2728FFFF */  addiu      $t0, $t9, -0x1
    /* 41740 8008D160 10000003 */  b          .L8008D170
    /* 41744 8008D164 AD280008 */   sw        $t0, %lo(D_A4600008)($t1)
  .L8008D168:
    /* 41748 8008D168 10000002 */  b          .L8008D174
    /* 4174C 8008D16C 2402FFFF */   addiu     $v0, $zero, -0x1
  .L8008D170:
    /* 41750 8008D170 00001025 */  or         $v0, $zero, $zero
  .L8008D174:
    /* 41754 8008D174 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 41758 8008D178 8FB00014 */  lw         $s0, 0x14($sp)
    /* 4175C 8008D17C 8FB10018 */  lw         $s1, 0x18($sp)
    /* 41760 8008D180 03E00008 */  jr         $ra
    /* 41764 8008D184 27BD0028 */   addiu     $sp, $sp, 0x28
endlabel func_8008D0A8
