.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_8007E8E4, 0x74

glabel func_8007E8E4
    /* 32EC4 8007E8E4 27BDFFD8 */  addiu      $sp, $sp, -0x28
    /* 32EC8 8007E8E8 AFB30020 */  sw         $s3, 0x20($sp)
    /* 32ECC 8007E8EC AFB2001C */  sw         $s2, 0x1C($sp)
    /* 32ED0 8007E8F0 AFB00014 */  sw         $s0, 0x14($sp)
    /* 32ED4 8007E8F4 AFBF0024 */  sw         $ra, 0x24($sp)
    /* 32ED8 8007E8F8 AFB10018 */  sw         $s1, 0x18($sp)
    /* 32EDC 8007E8FC 00809025 */  or         $s2, $a0, $zero
    /* 32EE0 8007E900 00C09825 */  or         $s3, $a2, $zero
    /* 32EE4 8007E904 AC800010 */  sw         $zero, 0x10($a0)
    /* 32EE8 8007E908 AC800008 */  sw         $zero, 0x8($a0)
    /* 32EEC 8007E90C AC80000C */  sw         $zero, 0xC($a0)
    /* 32EF0 8007E910 AC800000 */  sw         $zero, 0x0($a0)
    /* 32EF4 8007E914 AC800004 */  sw         $zero, 0x4($a0)
    /* 32EF8 8007E918 18C00008 */  blez       $a2, .L8007E93C
    /* 32EFC 8007E91C 00008025 */   or        $s0, $zero, $zero
    /* 32F00 8007E920 00A08825 */  or         $s1, $a1, $zero
  .L8007E924:
    /* 32F04 8007E924 02202025 */  or         $a0, $s1, $zero
    /* 32F08 8007E928 0C01F692 */  jal        func_8007DA48
    /* 32F0C 8007E92C 02402825 */   or        $a1, $s2, $zero
    /* 32F10 8007E930 26100001 */  addiu      $s0, $s0, 0x1
    /* 32F14 8007E934 1613FFFB */  bne        $s0, $s3, .L8007E924
    /* 32F18 8007E938 2631001C */   addiu     $s1, $s1, 0x1C
  .L8007E93C:
    /* 32F1C 8007E93C 8FBF0024 */  lw         $ra, 0x24($sp)
    /* 32F20 8007E940 8FB00014 */  lw         $s0, 0x14($sp)
    /* 32F24 8007E944 8FB10018 */  lw         $s1, 0x18($sp)
    /* 32F28 8007E948 8FB2001C */  lw         $s2, 0x1C($sp)
    /* 32F2C 8007E94C 8FB30020 */  lw         $s3, 0x20($sp)
    /* 32F30 8007E950 03E00008 */  jr         $ra
    /* 32F34 8007E954 27BD0028 */   addiu     $sp, $sp, 0x28
endlabel func_8007E8E4

nonmatching func_8007E958, 0x74

glabel func_8007E958
    /* 32F38 8007E958 00801025 */  or         $v0, $a0, $zero
    /* 32F3C 8007E95C 00A01825 */  or         $v1, $a1, $zero
    /* 32F40 8007E960 18C00018 */  blez       $a2, .L8007E9C4
    /* 32F44 8007E964 00003825 */   or        $a3, $zero, $zero
    /* 32F48 8007E968 30C50003 */  andi       $a1, $a2, 0x3
    /* 32F4C 8007E96C 10A00009 */  beqz       $a1, .L8007E994
    /* 32F50 8007E970 00A02025 */   or        $a0, $a1, $zero
  .L8007E974:
    /* 32F54 8007E974 904E0000 */  lbu        $t6, 0x0($v0)
    /* 32F58 8007E978 24E70001 */  addiu      $a3, $a3, 0x1
    /* 32F5C 8007E97C 24630001 */  addiu      $v1, $v1, 0x1
    /* 32F60 8007E980 24420001 */  addiu      $v0, $v0, 0x1
    /* 32F64 8007E984 1487FFFB */  bne        $a0, $a3, .L8007E974
    /* 32F68 8007E988 A06EFFFF */   sb        $t6, -0x1($v1)
    /* 32F6C 8007E98C 10E6000D */  beq        $a3, $a2, .L8007E9C4
    /* 32F70 8007E990 00000000 */   nop
  .L8007E994:
    /* 32F74 8007E994 904F0000 */  lbu        $t7, 0x0($v0)
    /* 32F78 8007E998 24E70004 */  addiu      $a3, $a3, 0x4
    /* 32F7C 8007E99C 24630004 */  addiu      $v1, $v1, 0x4
    /* 32F80 8007E9A0 A06FFFFC */  sb         $t7, -0x4($v1)
    /* 32F84 8007E9A4 90580001 */  lbu        $t8, 0x1($v0)
    /* 32F88 8007E9A8 24420004 */  addiu      $v0, $v0, 0x4
    /* 32F8C 8007E9AC A078FFFD */  sb         $t8, -0x3($v1)
    /* 32F90 8007E9B0 9059FFFE */  lbu        $t9, -0x2($v0)
    /* 32F94 8007E9B4 A079FFFE */  sb         $t9, -0x2($v1)
    /* 32F98 8007E9B8 9048FFFF */  lbu        $t0, -0x1($v0)
    /* 32F9C 8007E9BC 14E6FFF5 */  bne        $a3, $a2, .L8007E994
    /* 32FA0 8007E9C0 A068FFFF */   sb        $t0, -0x1($v1)
  .L8007E9C4:
    /* 32FA4 8007E9C4 03E00008 */  jr         $ra
    /* 32FA8 8007E9C8 00000000 */   nop
endlabel func_8007E958
    /* 32FAC 8007E9CC 00000000 */  nop
    /* 32FB0 8007E9D0 00000000 */  nop
    /* 32FB4 8007E9D4 00000000 */  nop
