.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_8007FBD8, 0x16C

glabel func_8007FBD8
    /* 341B8 8007FBD8 27BDFFC0 */  addiu      $sp, $sp, -0x40
    /* 341BC 8007FBDC AFBF0024 */  sw         $ra, 0x24($sp)
    /* 341C0 8007FBE0 AFB10020 */  sw         $s1, 0x20($sp)
    /* 341C4 8007FBE4 AFB0001C */  sw         $s0, 0x1C($sp)
    /* 341C8 8007FBE8 8CA6000C */  lw         $a2, 0xC($a1)
    /* 341CC 8007FBEC AC800020 */  sw         $zero, 0x20($a0)
    /* 341D0 8007FBF0 AC800018 */  sw         $zero, 0x18($a0)
    /* 341D4 8007FBF4 3C0E8009 */  lui        $t6, %hi(D_800952D0)
    /* 341D8 8007FBF8 8DCE52D0 */  lw         $t6, %lo(D_800952D0)($t6)
    /* 341DC 8007FBFC 240F00FF */  addiu      $t7, $zero, 0xFF
    /* 341E0 8007FC00 241801E8 */  addiu      $t8, $zero, 0x1E8
    /* 341E4 8007FC04 24197FFF */  addiu      $t9, $zero, 0x7FFF
    /* 341E8 8007FC08 24083E80 */  addiu      $t0, $zero, 0x3E80
    /* 341EC 8007FC0C A48F0030 */  sh         $t7, 0x30($a0)
    /* 341F0 8007FC10 AC980024 */  sw         $t8, 0x24($a0)
    /* 341F4 8007FC14 AC800028 */  sw         $zero, 0x28($a0)
    /* 341F8 8007FC18 AC80002C */  sw         $zero, 0x2C($a0)
    /* 341FC 8007FC1C A4990032 */  sh         $t9, 0x32($a0)
    /* 34200 8007FC20 AC88005C */  sw         $t0, 0x5C($a0)
    /* 34204 8007FC24 AC80001C */  sw         $zero, 0x1C($a0)
    /* 34208 8007FC28 AC8E0014 */  sw         $t6, 0x14($a0)
    /* 3420C 8007FC2C 8CA90010 */  lw         $t1, 0x10($a1)
    /* 34210 8007FC30 240C0009 */  addiu      $t4, $zero, 0x9
    /* 34214 8007FC34 00A08825 */  or         $s1, $a1, $zero
    /* 34218 8007FC38 AC890070 */  sw         $t1, 0x70($a0)
    /* 3421C 8007FC3C 8CAA0014 */  lw         $t2, 0x14($a1)
    /* 34220 8007FC40 00808025 */  or         $s0, $a0, $zero
    /* 34224 8007FC44 240E0010 */  addiu      $t6, $zero, 0x10
    /* 34228 8007FC48 AC8A0074 */  sw         $t2, 0x74($a0)
    /* 3422C 8007FC4C 8CAB0018 */  lw         $t3, 0x18($a1)
    /* 34230 8007FC50 A48C0038 */  sh         $t4, 0x38($a0)
    /* 34234 8007FC54 AC8B0078 */  sw         $t3, 0x78($a0)
    /* 34238 8007FC58 90AD0008 */  lbu        $t5, 0x8($a1)
    /* 3423C 8007FC5C 00002825 */  or         $a1, $zero, $zero
    /* 34240 8007FC60 A08D0034 */  sb         $t5, 0x34($a0)
    /* 34244 8007FC64 92270008 */  lbu        $a3, 0x8($s1)
    /* 34248 8007FC68 AFAE0010 */  sw         $t6, 0x10($sp)
    /* 3424C 8007FC6C 00002025 */  or         $a0, $zero, $zero
    /* 34250 8007FC70 0C01FF52 */  jal        func_8007FD48
    /* 34254 8007FC74 AFA6002C */   sw        $a2, 0x2C($sp)
    /* 34258 8007FC78 AE020060 */  sw         $v0, 0x60($s0)
    /* 3425C 8007FC7C 0C02053B */  jal        func_800814EC
    /* 34260 8007FC80 02002025 */   or        $a0, $s0, $zero
    /* 34264 8007FC84 8E270000 */  lw         $a3, 0x0($s1)
    /* 34268 8007FC88 240F0038 */  addiu      $t7, $zero, 0x38
    /* 3426C 8007FC8C AFAF0010 */  sw         $t7, 0x10($sp)
    /* 34270 8007FC90 00002025 */  or         $a0, $zero, $zero
    /* 34274 8007FC94 00002825 */  or         $a1, $zero, $zero
    /* 34278 8007FC98 0C01FF52 */  jal        func_8007FD48
    /* 3427C 8007FC9C 8FA6002C */   lw        $a2, 0x2C($sp)
    /* 34280 8007FCA0 AE00006C */  sw         $zero, 0x6C($s0)
    /* 34284 8007FCA4 8E380000 */  lw         $t8, 0x0($s1)
    /* 34288 8007FCA8 00002025 */  or         $a0, $zero, $zero
    /* 3428C 8007FCAC 00002825 */  or         $a1, $zero, $zero
    /* 34290 8007FCB0 1B00000B */  blez       $t8, .L8007FCE0
    /* 34294 8007FCB4 2409001C */   addiu     $t1, $zero, 0x1C
    /* 34298 8007FCB8 00401825 */  or         $v1, $v0, $zero
    /* 3429C 8007FCBC 8E19006C */  lw         $t9, 0x6C($s0)
  .L8007FCC0:
    /* 342A0 8007FCC0 24840001 */  addiu      $a0, $a0, 0x1
    /* 342A4 8007FCC4 AC790000 */  sw         $t9, 0x0($v1)
    /* 342A8 8007FCC8 AE03006C */  sw         $v1, 0x6C($s0)
    /* 342AC 8007FCCC 8E280000 */  lw         $t0, 0x0($s1)
    /* 342B0 8007FCD0 24630038 */  addiu      $v1, $v1, 0x38
    /* 342B4 8007FCD4 0088082A */  slt        $at, $a0, $t0
    /* 342B8 8007FCD8 5420FFF9 */  bnel       $at, $zero, .L8007FCC0
    /* 342BC 8007FCDC 8E19006C */   lw        $t9, 0x6C($s0)
  .L8007FCE0:
    /* 342C0 8007FCE0 AE000064 */  sw         $zero, 0x64($s0)
    /* 342C4 8007FCE4 AE000068 */  sw         $zero, 0x68($s0)
    /* 342C8 8007FCE8 8E270004 */  lw         $a3, 0x4($s1)
    /* 342CC 8007FCEC AFA90010 */  sw         $t1, 0x10($sp)
    /* 342D0 8007FCF0 8FA6002C */  lw         $a2, 0x2C($sp)
    /* 342D4 8007FCF4 0C01FF52 */  jal        func_8007FD48
    /* 342D8 8007FCF8 00002025 */   or        $a0, $zero, $zero
    /* 342DC 8007FCFC 26040048 */  addiu      $a0, $s0, 0x48
    /* 342E0 8007FD00 00402825 */  or         $a1, $v0, $zero
    /* 342E4 8007FD04 0C01FA39 */  jal        func_8007E8E4
    /* 342E8 8007FD08 8E260004 */   lw        $a2, 0x4($s1)
    /* 342EC 8007FD0C 3C0A8008 */  lui        $t2, %hi(func_8007F5C4)
    /* 342F0 8007FD10 254AF5C4 */  addiu      $t2, $t2, %lo(func_8007F5C4)
    /* 342F4 8007FD14 AE000000 */  sw         $zero, 0x0($s0)
    /* 342F8 8007FD18 AE0A0008 */  sw         $t2, 0x8($s0)
    /* 342FC 8007FD1C AE100004 */  sw         $s0, 0x4($s0)
    /* 34300 8007FD20 3C048009 */  lui        $a0, %hi(D_800952D0)
    /* 34304 8007FD24 8C8452D0 */  lw         $a0, %lo(D_800952D0)($a0)
    /* 34308 8007FD28 0C021822 */  jal        func_80086088
    /* 3430C 8007FD2C 02002825 */   or        $a1, $s0, $zero
    /* 34310 8007FD30 8FBF0024 */  lw         $ra, 0x24($sp)
    /* 34314 8007FD34 8FB0001C */  lw         $s0, 0x1C($sp)
    /* 34318 8007FD38 8FB10020 */  lw         $s1, 0x20($sp)
    /* 3431C 8007FD3C 03E00008 */  jr         $ra
    /* 34320 8007FD40 27BD0040 */   addiu     $sp, $sp, 0x40
endlabel func_8007FBD8
    /* 34324 8007FD44 00000000 */  nop

nonmatching func_8007FD48, 0x54

glabel func_8007FD48
    /* 34328 8007FD48 8FAE0010 */  lw         $t6, 0x10($sp)
    /* 3432C 8007FD4C AFA40000 */  sw         $a0, 0x0($sp)
    /* 34330 8007FD50 AFA50004 */  sw         $a1, 0x4($sp)
    /* 34334 8007FD54 00EE0019 */  multu      $a3, $t6
    /* 34338 8007FD58 8CD90008 */  lw         $t9, 0x8($a2)
    /* 3433C 8007FD5C 8CD80000 */  lw         $t8, 0x0($a2)
    /* 34340 8007FD60 8CC40004 */  lw         $a0, 0x4($a2)
    /* 34344 8007FD64 2401FFF0 */  addiu      $at, $zero, -0x10
    /* 34348 8007FD68 03194021 */  addu       $t0, $t8, $t9
    /* 3434C 8007FD6C 00001825 */  or         $v1, $zero, $zero
    /* 34350 8007FD70 00001012 */  mflo       $v0
    /* 34354 8007FD74 2442000F */  addiu      $v0, $v0, 0xF
    /* 34358 8007FD78 00417824 */  and        $t7, $v0, $at
    /* 3435C 8007FD7C 008F4821 */  addu       $t1, $a0, $t7
    /* 34360 8007FD80 0109082B */  sltu       $at, $t0, $t1
    /* 34364 8007FD84 14200003 */  bnez       $at, .L8007FD94
    /* 34368 8007FD88 008F5021 */   addu      $t2, $a0, $t7
    /* 3436C 8007FD8C 00801825 */  or         $v1, $a0, $zero
    /* 34370 8007FD90 ACCA0004 */  sw         $t2, 0x4($a2)
  .L8007FD94:
    /* 34374 8007FD94 03E00008 */  jr         $ra
    /* 34378 8007FD98 00601025 */   or        $v0, $v1, $zero
endlabel func_8007FD48
    /* 3437C 8007FD9C 00000000 */  nop
    /* 34380 8007FDA0 00000000 */  nop
    /* 34384 8007FDA4 00000000 */  nop

nonmatching func_8007FDA8, 0x54

glabel func_8007FDA8
    /* 34388 8007FDA8 8C8E0060 */  lw         $t6, 0x60($a0)
    /* 3438C 8007FDAC 00061100 */  sll        $v0, $a2, 4
    /* 34390 8007FDB0 01C27821 */  addu       $t7, $t6, $v0
    /* 34394 8007FDB4 ADE50000 */  sw         $a1, 0x0($t7)
    /* 34398 8007FDB8 8C990060 */  lw         $t9, 0x60($a0)
    /* 3439C 8007FDBC 90B80001 */  lbu        $t8, 0x1($a1)
    /* 343A0 8007FDC0 03224021 */  addu       $t0, $t9, $v0
    /* 343A4 8007FDC4 A1180007 */  sb         $t8, 0x7($t0)
    /* 343A8 8007FDC8 8C8A0060 */  lw         $t2, 0x60($a0)
    /* 343AC 8007FDCC 90A90000 */  lbu        $t1, 0x0($a1)
    /* 343B0 8007FDD0 01425821 */  addu       $t3, $t2, $v0
    /* 343B4 8007FDD4 A1690009 */  sb         $t1, 0x9($t3)
    /* 343B8 8007FDD8 8C8D0060 */  lw         $t5, 0x60($a0)
    /* 343BC 8007FDDC 90AC0002 */  lbu        $t4, 0x2($a1)
    /* 343C0 8007FDE0 01A27021 */  addu       $t6, $t5, $v0
    /* 343C4 8007FDE4 A1CC0008 */  sb         $t4, 0x8($t6)
    /* 343C8 8007FDE8 8C990060 */  lw         $t9, 0x60($a0)
    /* 343CC 8007FDEC 84AF000C */  lh         $t7, 0xC($a1)
    /* 343D0 8007FDF0 0322C021 */  addu       $t8, $t9, $v0
    /* 343D4 8007FDF4 03E00008 */  jr         $ra
    /* 343D8 8007FDF8 A70F0004 */   sh        $t7, 0x4($t8)
endlabel func_8007FDA8

nonmatching func_8007FDFC, 0x80

glabel func_8007FDFC
    /* 343DC 8007FDFC 8C8E0060 */  lw         $t6, 0x60($a0)
    /* 343E0 8007FE00 00051100 */  sll        $v0, $a1, 4
    /* 343E4 8007FE04 24080040 */  addiu      $t0, $zero, 0x40
    /* 343E8 8007FE08 01C27821 */  addu       $t7, $t6, $v0
    /* 343EC 8007FE0C A1E00006 */  sb         $zero, 0x6($t7)
    /* 343F0 8007FE10 8C980060 */  lw         $t8, 0x60($a0)
    /* 343F4 8007FE14 240B007F */  addiu      $t3, $zero, 0x7F
    /* 343F8 8007FE18 240E0005 */  addiu      $t6, $zero, 0x5
    /* 343FC 8007FE1C 0302C821 */  addu       $t9, $t8, $v0
    /* 34400 8007FE20 A320000A */  sb         $zero, 0xA($t9)
    /* 34404 8007FE24 8C890060 */  lw         $t1, 0x60($a0)
    /* 34408 8007FE28 3C013F80 */  lui        $at, (0x3F800000 >> 16)
    /* 3440C 8007FE2C 44812000 */  mtc1       $at, $ft0
    /* 34410 8007FE30 01225021 */  addu       $t2, $t1, $v0
    /* 34414 8007FE34 A1480007 */  sb         $t0, 0x7($t2)
    /* 34418 8007FE38 8C8C0060 */  lw         $t4, 0x60($a0)
    /* 3441C 8007FE3C 240800C8 */  addiu      $t0, $zero, 0xC8
    /* 34420 8007FE40 01826821 */  addu       $t5, $t4, $v0
    /* 34424 8007FE44 A1AB0009 */  sb         $t3, 0x9($t5)
    /* 34428 8007FE48 8C8F0060 */  lw         $t7, 0x60($a0)
    /* 3442C 8007FE4C 01E2C021 */  addu       $t8, $t7, $v0
    /* 34430 8007FE50 A30E0008 */  sb         $t6, 0x8($t8)
    /* 34434 8007FE54 8C990060 */  lw         $t9, 0x60($a0)
    /* 34438 8007FE58 03224821 */  addu       $t1, $t9, $v0
    /* 3443C 8007FE5C A120000B */  sb         $zero, 0xB($t1)
    /* 34440 8007FE60 8C8A0060 */  lw         $t2, 0x60($a0)
    /* 34444 8007FE64 01426021 */  addu       $t4, $t2, $v0
    /* 34448 8007FE68 A5880004 */  sh         $t0, 0x4($t4)
    /* 3444C 8007FE6C 8C8B0060 */  lw         $t3, 0x60($a0)
    /* 34450 8007FE70 01626821 */  addu       $t5, $t3, $v0
    /* 34454 8007FE74 03E00008 */  jr         $ra
    /* 34458 8007FE78 E5A4000C */   swc1      $ft0, 0xC($t5)
endlabel func_8007FDFC
