.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_8007A6D8, 0x78

glabel func_8007A6D8
    /* 2ECB8 8007A6D8 27BDFF88 */  addiu      $sp, $sp, -0x78
    /* 2ECBC 8007A6DC C7A40088 */  lwc1       $ft0, 0x88($sp)
    /* 2ECC0 8007A6E0 44866000 */  mtc1       $a2, $fa0
    /* 2ECC4 8007A6E4 44877000 */  mtc1       $a3, $fa1
    /* 2ECC8 8007A6E8 E7A40010 */  swc1       $ft0, 0x10($sp)
    /* 2ECCC 8007A6EC C7A400A0 */  lwc1       $ft0, 0xA0($sp)
    /* 2ECD0 8007A6F0 C7A6008C */  lwc1       $ft1, 0x8C($sp)
    /* 2ECD4 8007A6F4 C7A80090 */  lwc1       $ft2, 0x90($sp)
    /* 2ECD8 8007A6F8 C7AA0094 */  lwc1       $ft3, 0x94($sp)
    /* 2ECDC 8007A6FC C7B00098 */  lwc1       $ft4, 0x98($sp)
    /* 2ECE0 8007A700 C7B2009C */  lwc1       $ft5, 0x9C($sp)
    /* 2ECE4 8007A704 AFBF0034 */  sw         $ra, 0x34($sp)
    /* 2ECE8 8007A708 AFA40078 */  sw         $a0, 0x78($sp)
    /* 2ECEC 8007A70C 44066000 */  mfc1       $a2, $fa0
    /* 2ECF0 8007A710 44077000 */  mfc1       $a3, $fa1
    /* 2ECF4 8007A714 27A40038 */  addiu      $a0, $sp, 0x38
    /* 2ECF8 8007A718 E7A40028 */  swc1       $ft0, 0x28($sp)
    /* 2ECFC 8007A71C E7A60014 */  swc1       $ft1, 0x14($sp)
    /* 2ED00 8007A720 E7A80018 */  swc1       $ft2, 0x18($sp)
    /* 2ED04 8007A724 E7AA001C */  swc1       $ft3, 0x1C($sp)
    /* 2ED08 8007A728 E7B00020 */  swc1       $ft4, 0x20($sp)
    /* 2ED0C 8007A72C 0C01E8A6 */  jal        func_8007A298
    /* 2ED10 8007A730 E7B20024 */   swc1      $ft5, 0x24($sp)
    /* 2ED14 8007A734 27A40038 */  addiu      $a0, $sp, 0x38
    /* 2ED18 8007A738 0C01E9D6 */  jal        func_8007A758
    /* 2ED1C 8007A73C 8FA50078 */   lw        $a1, 0x78($sp)
    /* 2ED20 8007A740 8FBF0034 */  lw         $ra, 0x34($sp)
    /* 2ED24 8007A744 27BD0078 */  addiu      $sp, $sp, 0x78
    /* 2ED28 8007A748 03E00008 */  jr         $ra
    /* 2ED2C 8007A74C 00000000 */   nop
endlabel func_8007A6D8
    /* 2ED30 8007A750 00000000 */  nop
    /* 2ED34 8007A754 00000000 */  nop

nonmatching func_8007A758, 0x100

glabel func_8007A758
    /* 2ED38 8007A758 3C014780 */  lui        $at, (0x47800000 >> 16)
    /* 2ED3C 8007A75C 44810000 */  mtc1       $at, $fv0
    /* 2ED40 8007A760 00A01025 */  or         $v0, $a1, $zero
    /* 2ED44 8007A764 24A30020 */  addiu      $v1, $a1, 0x20
    /* 2ED48 8007A768 00003025 */  or         $a2, $zero, $zero
    /* 2ED4C 8007A76C 00803825 */  or         $a3, $a0, $zero
    /* 2ED50 8007A770 240C0004 */  addiu      $t4, $zero, 0x4
    /* 2ED54 8007A774 240B0002 */  addiu      $t3, $zero, 0x2
    /* 2ED58 8007A778 3C0AFFFF */  lui        $t2, (0xFFFF0000 >> 16)
  .L8007A77C:
    /* 2ED5C 8007A77C 00002025 */  or         $a0, $zero, $zero
    /* 2ED60 8007A780 00E04025 */  or         $t0, $a3, $zero
    /* 2ED64 8007A784 C50E0004 */  lwc1       $fa1, 0x4($t0)
    /* 2ED68 8007A788 24840001 */  addiu      $a0, $a0, 0x1
    /* 2ED6C 8007A78C C5120000 */  lwc1       $ft5, 0x0($t0)
    /* 2ED70 8007A790 46007402 */  mul.s      $ft4, $fa1, $fv0
    /* 2ED74 8007A794 108B0019 */  beq        $a0, $t3, .L8007A7FC
    /* 2ED78 8007A798 00000000 */   nop
  .L8007A79C:
    /* 2ED7C 8007A79C 46009382 */  mul.s      $fa1, $ft5, $fv0
    /* 2ED80 8007A7A0 24840001 */  addiu      $a0, $a0, 0x1
    /* 2ED84 8007A7A4 24420004 */  addiu      $v0, $v0, 0x4
    /* 2ED88 8007A7A8 24630004 */  addiu      $v1, $v1, 0x4
    /* 2ED8C 8007A7AC 25080008 */  addiu      $t0, $t0, 0x8
    /* 2ED90 8007A7B0 4600830D */  trunc.w.s  $fa0, $ft4
    /* 2ED94 8007A7B4 4600738D */  trunc.w.s  $fa1, $fa1
    /* 2ED98 8007A7B8 44096000 */  mfc1       $t1, $fa0
    /* 2ED9C 8007A7BC 44057000 */  mfc1       $a1, $fa1
    /* 2EDA0 8007A7C0 0009CC03 */  sra        $t9, $t1, 16
    /* 2EDA4 8007A7C4 332DFFFF */  andi       $t5, $t9, 0xFFFF
    /* 2EDA8 8007A7C8 00AAC024 */  and        $t8, $a1, $t2
    /* 2EDAC 8007A7CC 030D7025 */  or         $t6, $t8, $t5
    /* 2EDB0 8007A7D0 00057C00 */  sll        $t7, $a1, 16
    /* 2EDB4 8007A7D4 01EAC824 */  and        $t9, $t7, $t2
    /* 2EDB8 8007A7D8 AC4EFFFC */  sw         $t6, -0x4($v0)
    /* 2EDBC 8007A7DC 3138FFFF */  andi       $t8, $t1, 0xFFFF
    /* 2EDC0 8007A7E0 03386825 */  or         $t5, $t9, $t8
    /* 2EDC4 8007A7E4 AC6DFFFC */  sw         $t5, -0x4($v1)
    /* 2EDC8 8007A7E8 C50E0004 */  lwc1       $fa1, 0x4($t0)
    /* 2EDCC 8007A7EC C5120000 */  lwc1       $ft5, 0x0($t0)
    /* 2EDD0 8007A7F0 46007402 */  mul.s      $ft4, $fa1, $fv0
    /* 2EDD4 8007A7F4 148BFFE9 */  bne        $a0, $t3, .L8007A79C
    /* 2EDD8 8007A7F8 00000000 */   nop
  .L8007A7FC:
    /* 2EDDC 8007A7FC 46009382 */  mul.s      $fa1, $ft5, $fv0
    /* 2EDE0 8007A800 25080008 */  addiu      $t0, $t0, 0x8
    /* 2EDE4 8007A804 24420004 */  addiu      $v0, $v0, 0x4
    /* 2EDE8 8007A808 24630004 */  addiu      $v1, $v1, 0x4
    /* 2EDEC 8007A80C 4600830D */  trunc.w.s  $fa0, $ft4
    /* 2EDF0 8007A810 4600738D */  trunc.w.s  $fa1, $fa1
    /* 2EDF4 8007A814 44096000 */  mfc1       $t1, $fa0
    /* 2EDF8 8007A818 44057000 */  mfc1       $a1, $fa1
    /* 2EDFC 8007A81C 0009CC03 */  sra        $t9, $t1, 16
    /* 2EE00 8007A820 332DFFFF */  andi       $t5, $t9, 0xFFFF
    /* 2EE04 8007A824 00AAC024 */  and        $t8, $a1, $t2
    /* 2EE08 8007A828 030D7025 */  or         $t6, $t8, $t5
    /* 2EE0C 8007A82C 00057C00 */  sll        $t7, $a1, 16
    /* 2EE10 8007A830 01EAC824 */  and        $t9, $t7, $t2
    /* 2EE14 8007A834 3138FFFF */  andi       $t8, $t1, 0xFFFF
    /* 2EE18 8007A838 AC4EFFFC */  sw         $t6, -0x4($v0)
    /* 2EE1C 8007A83C 03386825 */  or         $t5, $t9, $t8
    /* 2EE20 8007A840 AC6DFFFC */  sw         $t5, -0x4($v1)
    /* 2EE24 8007A844 24C60001 */  addiu      $a2, $a2, 0x1
    /* 2EE28 8007A848 14CCFFCC */  bne        $a2, $t4, .L8007A77C
    /* 2EE2C 8007A84C 24E70010 */   addiu     $a3, $a3, 0x10
    /* 2EE30 8007A850 03E00008 */  jr         $ra
    /* 2EE34 8007A854 00000000 */   nop
endlabel func_8007A758

nonmatching func_8007A858, 0x88

glabel func_8007A858
    /* 2EE38 8007A858 3C013F80 */  lui        $at, (0x3F800000 >> 16)
    /* 2EE3C 8007A85C 00801825 */  or         $v1, $a0, $zero
    /* 2EE40 8007A860 44810000 */  mtc1       $at, $fv0
    /* 2EE44 8007A864 44801000 */  mtc1       $zero, $fv1
    /* 2EE48 8007A868 24040001 */  addiu      $a0, $zero, 0x1
    /* 2EE4C 8007A86C 00001025 */  or         $v0, $zero, $zero
    /* 2EE50 8007A870 24070004 */  addiu      $a3, $zero, 0x4
    /* 2EE54 8007A874 24060003 */  addiu      $a2, $zero, 0x3
    /* 2EE58 8007A878 24050002 */  addiu      $a1, $zero, 0x2
  .L8007A87C:
    /* 2EE5C 8007A87C 54400004 */  bnel       $v0, $zero, .L8007A890
    /* 2EE60 8007A880 E4620000 */   swc1      $fv1, 0x0($v1)
    /* 2EE64 8007A884 10000002 */  b          .L8007A890
    /* 2EE68 8007A888 E4600000 */   swc1      $fv0, 0x0($v1)
    /* 2EE6C 8007A88C E4620000 */  swc1       $fv1, 0x0($v1)
  .L8007A890:
    /* 2EE70 8007A890 54440004 */  bnel       $v0, $a0, .L8007A8A4
    /* 2EE74 8007A894 E4620004 */   swc1      $fv1, 0x4($v1)
    /* 2EE78 8007A898 10000002 */  b          .L8007A8A4
    /* 2EE7C 8007A89C E4600004 */   swc1      $fv0, 0x4($v1)
    /* 2EE80 8007A8A0 E4620004 */  swc1       $fv1, 0x4($v1)
  .L8007A8A4:
    /* 2EE84 8007A8A4 54450004 */  bnel       $v0, $a1, .L8007A8B8
    /* 2EE88 8007A8A8 E4620008 */   swc1      $fv1, 0x8($v1)
    /* 2EE8C 8007A8AC 10000002 */  b          .L8007A8B8
    /* 2EE90 8007A8B0 E4600008 */   swc1      $fv0, 0x8($v1)
    /* 2EE94 8007A8B4 E4620008 */  swc1       $fv1, 0x8($v1)
  .L8007A8B8:
    /* 2EE98 8007A8B8 54460004 */  bnel       $v0, $a2, .L8007A8CC
    /* 2EE9C 8007A8BC E462000C */   swc1      $fv1, 0xC($v1)
    /* 2EEA0 8007A8C0 10000002 */  b          .L8007A8CC
    /* 2EEA4 8007A8C4 E460000C */   swc1      $fv0, 0xC($v1)
    /* 2EEA8 8007A8C8 E462000C */  swc1       $fv1, 0xC($v1)
  .L8007A8CC:
    /* 2EEAC 8007A8CC 24420001 */  addiu      $v0, $v0, 0x1
    /* 2EEB0 8007A8D0 1447FFEA */  bne        $v0, $a3, .L8007A87C
    /* 2EEB4 8007A8D4 24630010 */   addiu     $v1, $v1, 0x10
    /* 2EEB8 8007A8D8 03E00008 */  jr         $ra
    /* 2EEBC 8007A8DC 00000000 */   nop
endlabel func_8007A858
