.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_8004EF78, 0x84

glabel func_8004EF78
    /* 3558 8004EF78 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 355C 8004EF7C AFB00010 */  sw         $s0, 0x10($sp)
    /* 3560 8004EF80 00A08021 */  addu       $s0, $a1, $zero
    /* 3564 8004EF84 10C00008 */  beqz       $a2, .L8004EFA8
    /* 3568 8004EF88 AFBF0014 */   sw        $ra, 0x14($sp)
    /* 356C 8004EF8C C48C0000 */  lwc1       $fa0, 0x0($a0)
    /* 3570 8004EF90 C48E0004 */  lwc1       $fa1, 0x4($a0)
    /* 3574 8004EF94 8C860008 */  lw         $a2, 0x8($a0)
    /* 3578 8004EF98 0C013B97 */  jal        func_8004EE5C
    /* 357C 8004EF9C 00000000 */   nop
    /* 3580 8004EFA0 08013BEB */  j          func_8004EFAC
    /* 3584 8004EFA4 00000000 */   nop
  .L8004EFA8:
    /* 3588 8004EFA8 86020004 */  lh         $v0, 0x4($s0)
  alabel func_8004EFAC
    /* 358C 8004EFAC 3C018005 */  lui        $at, %hi(D_8004BBB8)
    /* 3590 8004EFB0 C420BBB8 */  lwc1       $fv0, %lo(D_8004BBB8)($at)
    /* 3594 8004EFB4 3C018005 */  lui        $at, %hi(D_8004BBBC)
    /* 3598 8004EFB8 C422BBBC */  lwc1       $fv1, %lo(D_8004BBBC)($at)
    /* 359C 8004EFBC A6020004 */  sh         $v0, 0x4($s0)
    /* 35A0 8004EFC0 2402FFFF */  addiu      $v0, $zero, -0x1
    /* 35A4 8004EFC4 A6020006 */  sh         $v0, 0x6($s0)
    /* 35A8 8004EFC8 A6000002 */  sh         $zero, 0x2($s0)
    /* 35AC 8004EFCC AE000080 */  sw         $zero, 0x80($s0)
    /* 35B0 8004EFD0 A6020000 */  sh         $v0, 0x0($s0)
    /* 35B4 8004EFD4 AE000038 */  sw         $zero, 0x38($s0)
    /* 35B8 8004EFD8 AE00003C */  sw         $zero, 0x3C($s0)
    /* 35BC 8004EFDC AE000054 */  sw         $zero, 0x54($s0)
    /* 35C0 8004EFE0 AE000058 */  sw         $zero, 0x58($s0)
    /* 35C4 8004EFE4 E6000040 */  swc1       $fv0, 0x40($s0)
    /* 35C8 8004EFE8 E6020050 */  swc1       $fv1, 0x50($s0)
    /* 35CC 8004EFEC 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 35D0 8004EFF0 8FB00010 */  lw         $s0, 0x10($sp)
    /* 35D4 8004EFF4 03E00008 */  jr         $ra
    /* 35D8 8004EFF8 27BD0018 */   addiu     $sp, $sp, 0x18
endlabel func_8004EF78
