.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_80063A3C, 0xD0

glabel func_80063A3C
    /* 1801C 80063A3C 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 18020 80063A40 3C074C48 */  lui        $a3, (0x4C485546 >> 16)
    /* 18024 80063A44 3C028009 */  lui        $v0, %hi(D_80092D38)
    /* 18028 80063A48 8C422D38 */  lw         $v0, %lo(D_80092D38)($v0)
    /* 1802C 80063A4C 00042100 */  sll        $a0, $a0, 4
    /* 18030 80063A50 AFBF0010 */  sw         $ra, 0x10($sp)
    /* 18034 80063A54 00441821 */  addu       $v1, $v0, $a0
    /* 18038 80063A58 8C640004 */  lw         $a0, 0x4($v1)
    /* 1803C 80063A5C 34E75546 */  ori        $a3, $a3, (0x4C485546 & 0xFFFF)
    /* 18040 80063A60 10870021 */  beq        $a0, $a3, .L80063AE8
    /* 18044 80063A64 3C028005 */   lui       $v0, %hi(D_8004B658)
    /* 18048 80063A68 00E4102B */  sltu       $v0, $a3, $a0
    /* 1804C 80063A6C 14400007 */  bnez       $v0, .L80063A8C
    /* 18050 80063A70 3C024C5A */   lui       $v0, (0x4C5A5353 >> 16)
    /* 18054 80063A74 3C02434F */  lui        $v0, (0x434F5059 >> 16)
    /* 18058 80063A78 34425059 */  ori        $v0, $v0, (0x434F5059 & 0xFFFF)
    /* 1805C 80063A7C 10820008 */  beq        $a0, $v0, .L80063AA0
    /* 18060 80063A80 00001021 */   addu      $v0, $zero, $zero
    /* 18064 80063A84 08018EC0 */  j          func_80063B00
    /* 18068 80063A88 00000000 */   nop
  .L80063A8C:
    /* 1806C 80063A8C 34425353 */  ori        $v0, $v0, (0x4C5A5353 & 0xFFFF)
    /* 18070 80063A90 1082000C */  beq        $a0, $v0, .L80063AC4
    /* 18074 80063A94 00001021 */   addu      $v0, $zero, $zero
    /* 18078 80063A98 08018EC0 */  j          func_80063B00
    /* 1807C 80063A9C 00000000 */   nop
  .L80063AA0:
    /* 18080 80063AA0 00A03021 */  addu       $a2, $a1, $zero
    /* 18084 80063AA4 3C028005 */  lui        $v0, %hi(D_8004B658)
    /* 18088 80063AA8 8C42B658 */  lw         $v0, %lo(D_8004B658)($v0)
    /* 1808C 80063AAC 8C640000 */  lw         $a0, 0x0($v1)
    /* 18090 80063AB0 8C650008 */  lw         $a1, 0x8($v1)
    /* 18094 80063AB4 0C016AE0 */  jal        func_8005AB80
    /* 18098 80063AB8 00442021 */   addu      $a0, $v0, $a0
    /* 1809C 80063ABC 08018EC0 */  j          func_80063B00
    /* 180A0 80063AC0 24020001 */   addiu     $v0, $zero, 0x1
  .L80063AC4:
    /* 180A4 80063AC4 3C028005 */  lui        $v0, %hi(D_8004B658)
    /* 180A8 80063AC8 8C660008 */  lw         $a2, 0x8($v1)
    /* 180AC 80063ACC 8C42B658 */  lw         $v0, %lo(D_8004B658)($v0)
    /* 180B0 80063AD0 8C640000 */  lw         $a0, 0x0($v1)
    /* 180B4 80063AD4 8C67000C */  lw         $a3, 0xC($v1)
    /* 180B8 80063AD8 0C016B1C */  jal        func_8005AC70
    /* 180BC 80063ADC 00442021 */   addu      $a0, $v0, $a0
    /* 180C0 80063AE0 08018EC0 */  j          func_80063B00
    /* 180C4 80063AE4 24020001 */   addiu     $v0, $zero, 0x1
  .L80063AE8:
    /* 180C8 80063AE8 8C42B658 */  lw         $v0, %lo(D_8004B658)($v0)
    /* 180CC 80063AEC 8C640000 */  lw         $a0, 0x0($v1)
    /* 180D0 80063AF0 8C660008 */  lw         $a2, 0x8($v1)
    /* 180D4 80063AF4 0C016C89 */  jal        func_8005B224
    /* 180D8 80063AF8 00442021 */   addu      $a0, $v0, $a0
    /* 180DC 80063AFC 24020001 */  addiu      $v0, $zero, 0x1
  alabel func_80063B00
    /* 180E0 80063B00 8FBF0010 */  lw         $ra, 0x10($sp)
    /* 180E4 80063B04 03E00008 */  jr         $ra
    /* 180E8 80063B08 27BD0018 */   addiu     $sp, $sp, 0x18
endlabel func_80063A3C

nonmatching func_80063B0C, 0x8

glabel func_80063B0C
    /* 180EC 80063B0C 3C028018 */  lui        $v0, %hi(D_801823E0)
    /* 180F0 80063B10 8C4223E0 */  lw         $v0, %lo(D_801823E0)($v0)
endlabel func_80063B0C
