.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_8004EC54, 0x34

glabel func_8004EC54
    /* 3234 8004EC54 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 3238 8004EC58 3404FA00 */  ori        $a0, $zero, 0xFA00
    /* 323C 8004EC5C AFBF0014 */  sw         $ra, 0x14($sp)
    /* 3240 8004EC60 0C01352A */  jal        func_8004D4A8
    /* 3244 8004EC64 AFB00010 */   sw        $s0, 0x10($sp)
    /* 3248 8004EC68 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 324C 8004EC6C 3C108018 */  lui        $s0, %hi(D_8017C8A0)
    /* 3250 8004EC70 AE02C8A0 */  sw         $v0, %lo(D_8017C8A0)($s0)
    /* 3254 8004EC74 8FB00010 */  lw         $s0, 0x10($sp)
    /* 3258 8004EC78 3C038018 */  lui        $v1, %hi(D_8017C7F0)
    /* 325C 8004EC7C AC62C7F0 */  sw         $v0, %lo(D_8017C7F0)($v1)
    /* 3260 8004EC80 03E00008 */  jr         $ra
    /* 3264 8004EC84 27BD0018 */   addiu     $sp, $sp, 0x18
endlabel func_8004EC54
